Tank Controller Lib: SeeTankID Class Reference
SeeTankID Class Reference
#include <SeeTankID.h>
Public Member Functions
SeeTankID (TankControllerLib *tc)
void start ()
const char * name ()
const char * prompt ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SeeTankID.h
Display the tank ID
Definition at line 9 of file SeeTankID.h.
Constructor & Destructor Documentation
SeeTankID()
SeeTankID::SeeTankID (TankControllerLib * tc) inline
Definition at line 11 of file SeeTankID.h.
                                    : UIState(tc) {
   }
Member Function Documentation
name()
const char* SeeTankID::name () inline virtual
Implements UIState.
Definition at line 14 of file SeeTankID.h.
                      {
     return "SeeTankID";
   }
prompt()
const char* SeeTankID::prompt () inline virtual
Reimplemented from UIState.
Definition at line 17 of file SeeTankID.h.
{
     return "Tank ID:";
   };
Referenced by start().
start()
void SeeTankID::start () virtual
SeeTankID.cpp
Reimplemented from UIState.
Definition at line 10 of file SeeTankID.cpp.
                       {
   LiquidCrystal_TC::instance()->writeLine(prompt(), 0);
   char id[17];
   snprintf(id, sizeof(id), "%i", EEPROM_TC::instance()->getTankID());
   LiquidCrystal_TC::instance()->writeLine(id, 1);
 }
References EEPROM_TC::instance(), LiquidCrystal_TC::instance(), prompt(), and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SeeTankID.h
src/UIState/SeeTankID.cpp