Tank Controller Lib: SetKD Class Reference
SetKD Class Reference
#include <SetKD.h>
Public Member Functions
SetKD (TankControllerLib *tc)
const __FlashStringHelper * name ()
float getCurrentValue ()
uint16_t getCurrentValuePrecision ()
const __FlashStringHelper * prompt ()
void setValue (float value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SetKD.h
Set the KD for the PID
Definition at line 10 of file SetKD.h.
Constructor & Destructor Documentation
SetKD()
SetKD::SetKD (TankControllerLib * tc) inline
Definition at line 12 of file SetKD.h.
                                : NumCollectorState(tc) {
   }
Member Function Documentation
getCurrentValue()
float SetKD::getCurrentValue () inline virtual
Implements NumCollectorState.
Definition at line 17 of file SetKD.h.
{
     return EEPROM_TC::instance()->getKD();
   }
References EEPROM_TC::getKD(), and EEPROM_TC::instance().
getCurrentValuePrecision()
uint16_t SetKD::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 20 of file SetKD.h.
{
     return 1;
   }
name()
const __FlashStringHelper* SetKD::name () inline virtual
Implements UIState.
Definition at line 14 of file SetKD.h.
{
     return F("SetKD");
   }
prompt()
const __FlashStringHelper* SetKD::prompt () inline virtual
Reimplemented from UIState.
Definition at line 23 of file SetKD.h.
{
     return F("Set KD");
   };
setValue()
void SetKD::setValue (float value) virtual
SetKD.cpp
Implements NumCollectorState.
Definition at line 9 of file SetKD.cpp.
{
   PID_TC::instance()->setKd(value);
   char output[17];
   snprintf_P(output, sizeof(output), (PGM_P)F("New KD=%.1f"), value);
   LiquidCrystal_TC::instance()->writeLine(output, 1);
   returnToMainMenu(3000);
 }
References PID_TC::instance(), LiquidCrystal_TC::instance(), UIState::returnToMainMenu(), PID_TC::setKd(), NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SetKD.h
src/UIState/SetKD.cpp