Tank Controller Lib: SeeGoogleMins Class Reference
SeeGoogleMins Class Reference
#include <SeeGoogleMins.h>
Public Member Functions
SeeGoogleMins (TankController *tc)
void start ()
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
SeeGoogleMins.h
Display the Google Sheet Interval
Definition at line 9 of file SeeGoogleMins.h.
Constructor & Destructor Documentation
SeeGoogleMins()
SeeGoogleMins::SeeGoogleMins (TankController * tc) inline
Definition at line 11 of file SeeGoogleMins.h.
                                    : UIState(tc) {
  }
Member Function Documentation
name()
const __FlashStringHelper * SeeGoogleMins::name () inline virtual
Implements UIState.
Definition at line 14 of file SeeGoogleMins.h.
{
    return F("SeeGoogleMins");
  }
prompt()
const __FlashStringHelper * SeeGoogleMins::prompt () inline virtual
Reimplemented from UIState.
Definition at line 17 of file SeeGoogleMins.h.
{
    return F("Google Mins:");
  };
Referenced by start().
start()
void SeeGoogleMins::start () virtual
SeeGoogleMins.cpp
Reimplemented from UIState.
Definition at line 10 of file SeeGoogleMins.cpp.
{
  LiquidCrystal_TC::instance()->writeLine(prompt(), 0);
  char buffer[17];
  snprintf_P(buffer, sizeof(buffer), (PGM_P)F("%i"), EEPROM_TC::instance()->getGoogleSheetInterval());
  LiquidCrystal_TC::instance()->writeLine(buffer, 1);
}
References buffer, EEPROM_TC::instance(), LiquidCrystal_TC::instance(), prompt(), and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SeeGoogleMins.h
src/UIState/SeeGoogleMins.cpp