Tank Controller Lib: SeeFreeMemory Class Reference
SeeFreeMemory Class Reference
#include <SeeFreeMemory.h>
Public Member Functions
SeeFreeMemory (TankControllerLib *tc)
void start ()
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
Definition at line 4 of file SeeFreeMemory.h.
Constructor & Destructor Documentation
SeeFreeMemory()
SeeFreeMemory::SeeFreeMemory (TankControllerLib * tc) inline
Definition at line 6 of file SeeFreeMemory.h.
                                        : UIState(tc) {
   }
Member Function Documentation
name()
const __FlashStringHelper* SeeFreeMemory::name () inline virtual
Implements UIState.
Definition at line 9 of file SeeFreeMemory.h.
{
     return F("SeeFreeMemory");
   }
prompt()
const __FlashStringHelper* SeeFreeMemory::prompt () inline virtual
Reimplemented from UIState.
Definition at line 12 of file SeeFreeMemory.h.
{
     return F("Free Memory:");
   };
Referenced by start().
start()
void SeeFreeMemory::start () virtual
Reimplemented from UIState.
Definition at line 6 of file SeeFreeMemory.cpp.
{
   LiquidCrystal_TC::instance()->writeLine(prompt(), 0);
   char buffer[17];
   snprintf_P(buffer, sizeof(buffer), (PGM_P)F("%i bytes"), (int)TankControllerLib::instance()->freeMemory());
   LiquidCrystal_TC::instance()->writeLine(buffer, 1);
 }
References buffer, TankControllerLib::instance(), LiquidCrystal_TC::instance(), prompt(), and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SeeFreeMemory.h
src/UIState/SeeFreeMemory.cpp