Tank Controller Lib: LiquidCrystal_TC Class Reference
LiquidCrystal_TC Class Reference
#include <LiquidCrystal_TC.h>
Public Member Functions
void writeLine (const char *text, uint16_t line)
Static Public Member Functions
static LiquidCrystal_TC * instance ()
Private Member Functions
LiquidCrystal_TC ()
void splashScreen ()
Static Private Attributes
static LiquidCrystal_TC * _instance = nullptr
Detailed Description
Definition at line 10 of file LiquidCrystal_TC.h.
Constructor & Destructor Documentation
LiquidCrystal_TC()
LiquidCrystal_TC::LiquidCrystal_TC () private
Constructor sets pins, dimensions, and shows splash screen
Definition at line 29 of file LiquidCrystal_TC.cpp.
                                    : LiquidCrystal(RS, EN, D4, D5, D6, D7) {
   Serial.println("LiquidCrystal_TC");  // Serial_TC might not be ready yet
   begin(16, 2);
   splashScreen();
 }
References splashScreen().
Referenced by instance().
Member Function Documentation
instance()
LiquidCrystal_TC * LiquidCrystal_TC::instance () static
accessor for singleton
Definition at line 18 of file LiquidCrystal_TC.cpp.
{
   if (!_instance) {
     _instance = new LiquidCrystal_TC();
   }
   return _instance;
 }
References _instance, and LiquidCrystal_TC().
Referenced by SetCalibrationClear::handleKey(), MainMenu::idle(), lcd(), SeePIDConstants::loadKd(), SeePIDConstants::loadKi(), SeePIDConstants::loadKp(), SeePIDConstants::loadPID(), MainMenu::loop(), SeeDeviceUptime::loop(), SeePHSlope::loop(), NumCollectorState::printValue(), EnablePID::setValue(), PHCalibrationHigh::setValue(), PHCalibrationLow::setValue(), PHCalibrationMid::setValue(), SetChillOrHeat::setValue(), SetGoogleSheetInterval::setValue(), SetKD::setValue(), SetKI::setValue(), SetKP::setValue(), SetPHSetPoint::setValue(), SetTankID::setValue(), SetTempSetPoint::setValue(), SetTime::setValue(), TemperatureCalibration::setValue(), SeeDeviceAddress::start(), SeeGoogleMins::start(), SeeLogFile::start(), SeePHSlope::start(), SeeTankID::start(), SeeVersion::start(), UIState::start(), TankControllerLib::TankControllerLib(), and unittest().
splashScreen()
void LiquidCrystal_TC::splashScreen () private
Splash screen includes the following logo (actually, this one is float width to get it more nearly proportional): XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XX XXXX XX XXXXXXXX XXXX XXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXX XXXX XXXXXXXX XX XXXX XX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
Definition at line 55 of file LiquidCrystal_TC.cpp.
{
   uint8_t OL1[8] = {0b00000, 0b00000, 0b00001, 0b00011, 0b00011, 0b00111, 0b00111, 0b00110};
   uint8_t OL2[8] = {0b00111, 0b11111, 0b11111, 0b10011, 0b11101, 0b11110, 0b00101, 0b11011};
   uint8_t OL3[8] = {0b11100, 0b11111, 0b01111, 0b10111, 0b10110, 0b01110, 0b10101, 0b11011};
   uint8_t OL4[8] = {0b00000, 0b00000, 0b10000, 0b11000, 0b11000, 0b11100, 0b11100, 0b11100};
   uint8_t OL5[8] = {0b00111, 0b00111, 0b00111, 0b00011, 0b00011, 0b00001, 0b00000, 0b00000};
   uint8_t OL6[8] = {0b11011, 0b10101, 0b01110, 0b01101, 0b11101, 0b11110, 0b11111, 0b00111};
   uint8_t OL7[8] = {0b11011, 0b10100, 0b01111, 0b10111, 0b11001, 0b11111, 0b11111, 0b11100};
   uint8_t OL8[8] = {0b01100, 0b11100, 0b11100, 0b11000, 0b11000, 0b10000, 0b00000, 0b00000};
   createChar(0, OL1);
   createChar(1, OL2);
   createChar(2, OL3);
   createChar(3, OL4);
   createChar(4, OL5);
   createChar(5, OL6);
   createChar(6, OL7);
   createChar(7, OL8);
   clear();
   write(uint8_t(0));
   write(uint8_t(1));
   write(uint8_t(2));
   write(uint8_t(3));
   print(" ONTHANK LAB");
   setCursor(0, 1);
   write(uint8_t(4));
   write(uint8_t(5));
   write(uint8_t(6));
   write(uint8_t(7));
   print("TANK CONTROL");
 }
Referenced by LiquidCrystal_TC().
writeLine()
void LiquidCrystal_TC::writeLine (const char * text, uint16_t line)
Prints an input string to the desired line of the LCD screen Even numbers go on the bottom line, odd ones go on the top line
Definition at line 90 of file LiquidCrystal_TC.cpp.
{
   line = line % 2;
   setCursor(0, line);
   char result[17];
   bool moreText = true;
   for (size_t i = 0; i < 16; i++) {
     if (moreText && text[i] == '\0') {
       moreText = false;
     }
     if (moreText) {
       result[i] = text[i];
     } else {
       result[i] = ' ';
     }
   }
   result[16] = '\0';
   print(result);
 }
Referenced by SetCalibrationClear::handleKey(), MainMenu::idle(), SeePIDConstants::loadKd(), SeePIDConstants::loadKi(), SeePIDConstants::loadKp(), SeePIDConstants::loadPID(), MainMenu::loop(), SeeDeviceUptime::loop(), SeePHSlope::loop(), NumCollectorState::printValue(), EnablePID::setValue(), PHCalibrationHigh::setValue(), PHCalibrationLow::setValue(), PHCalibrationMid::setValue(), SetChillOrHeat::setValue(), SetGoogleSheetInterval::setValue(), SetKD::setValue(), SetKI::setValue(), SetKP::setValue(), SetPHSetPoint::setValue(), SetTankID::setValue(), SetTempSetPoint::setValue(), SetTime::setValue(), TemperatureCalibration::setValue(), SeeDeviceAddress::start(), SeeGoogleMins::start(), SeeLogFile::start(), SeePHSlope::start(), SeeTankID::start(), SeeVersion::start(), UIState::start(), and unittest().
Member Data Documentation
_instance
LiquidCrystal_TC * LiquidCrystal_TC::_instance = nullptr static private
Definition at line 17 of file LiquidCrystal_TC.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/Devices/LiquidCrystal_TC.h
src/Devices/LiquidCrystal_TC.cpp