Tank Controller Lib: SeeDeviceAddress Class Reference
SeeDeviceAddress Class Reference
#include <SeeDeviceAddress.h>
Public Member Functions
SeeDeviceAddress (TankController *tc)
void start ()
void handleKey (char key)
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
SeeDeviceAddress.h
Display the device address
Definition at line 9 of file SeeDeviceAddress.h.
Constructor & Destructor Documentation
SeeDeviceAddress()
SeeDeviceAddress::SeeDeviceAddress (TankController * tc) inline
Definition at line 11 of file SeeDeviceAddress.h.
                                       : UIState(tc) {
  }
Member Function Documentation
handleKey()
void SeeDeviceAddress::handleKey (char key) virtual
SeeDeviceAddress.cpp
Reimplemented from UIState.
Definition at line 13 of file SeeDeviceAddress.cpp.
{
  switch (key) {
    case 'B':  // Infinite loop to test Watchdog Timer
      wdt_disable();
      wdt_enable(WDTO_15MS);
      do {
      } while (true);
      break;
    case 'C':  // Reset MAC address
      Ethernet_TC::instance()->readMac(true);
      start();
      break;
    default:
      returnToMainMenu();
      break;
  };
}
References Ethernet_TC::instance(), key(), Ethernet_TC::readMac(), UIState::returnToMainMenu(), and start().
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
name()
const __FlashStringHelper * SeeDeviceAddress::name () inline virtual
Implements UIState.
Definition at line 15 of file SeeDeviceAddress.h.
{
    return F("SeeDeviceAddress");
  }
prompt()
const __FlashStringHelper * SeeDeviceAddress::prompt () inline virtual
Reimplemented from UIState.
Definition at line 18 of file SeeDeviceAddress.h.
{
    return F("Device address");
  };
start()
void SeeDeviceAddress::start () virtual
Reimplemented from UIState.
Definition at line 31 of file SeeDeviceAddress.cpp.
{
  char line[17];
  // first line
  IPAddress IP = Ethernet_TC::instance()->getIP();
  snprintf_P(line, sizeof(line), (PGM_P)F("%03d.%03d.%03d.%03d"), IP[0], IP[1], IP[2], IP[3]);
  LiquidCrystal_TC::instance()->writeLine(line, 0);
  // second line
  byte* mac = Ethernet_TC::instance()->getMac();
  snprintf_P(line, sizeof(line), (PGM_P)F("%02X%02X:%02X%02X:%02X%02X"), mac[0], mac[1], mac[2], mac[3], mac[4],
             mac[5]);
  LiquidCrystal_TC::instance()->writeLine(line, 1);
}
References Ethernet_TC::getIP(), Ethernet_TC::getMac(), Ethernet_TC::instance(), LiquidCrystal_TC::instance(), and LiquidCrystal_TC::writeLine().
Referenced by handleKey().
The documentation for this class was generated from the following files:
src/UIState/SeeDeviceAddress.h
src/UIState/SeeDeviceAddress.cpp