Tank Controller Lib: Ethernet_TC Class Reference
Ethernet_TC Class Reference
#include <Ethernet_TC.h>
Public Member Functions
IPAddress getIP ()
bool getIsUsingDHCP ()
byte * getMac ()
void readMac (bool forceReset=false)
uint16_t getNumAttemptedDHCPReleases ()
void loop ()
Static Public Member Functions
static Ethernet_TC * instance (bool reset=false)
Protected Member Functions
Ethernet_TC ()
Private Attributes
byte mac [6] = {0x90, 0xA2, 0xDA, 0x00, 0x00, 0x00}
IPAddress defaultIP = IPAddress(192, 168, 1, 10)
IPAddress time_serverIP
const int SD_SELECT_PIN = 4
IPAddress IP
bool isUsingDHCP = false
uint16_t numAttemptedDHCPReleases = 0
Static Private Attributes
static Ethernet_TC * _instance = nullptr
Detailed Description
Based off Arduino's Ethernet library Implements a wrapper for the Ethernet Class
Definition at line 11 of file Ethernet_TC.h.
Constructor & Destructor Documentation
Ethernet_TC()
Ethernet_TC::Ethernet_TC () protected
Definition at line 12 of file Ethernet_TC.cpp.
{
   pinMode(SD_SELECT_PIN, OUTPUT);
   digitalWrite(SD_SELECT_PIN, HIGH);
   readMac();
   serial(F("Attempting to connect to Ethernet"));
   wdt_disable();
   int key = Keypad_TC::instance()->getKey();
   long timeout = key == NO_KEY ? 60000 : 1;
   if (Ethernet.begin(mac, timeout)) {
     IP = Ethernet.localIP();
     serial(F("DHCP address is %i.%i.%i.%i"), IP[0], IP[1], IP[2], IP[3]);
     isUsingDHCP = true;
   } else {
     // update IP by adding tank ID to last octet
     defaultIP[3] += EEPROM_TC::instance()->getTankID();
     serial(F("DHCP failed, trying %i.%i.%i.%i"), defaultIP[0], defaultIP[1], defaultIP[2], defaultIP[3]);
     Ethernet.begin(mac, defaultIP);
     serial(F("Done with Ethernet setup"));
     IP = defaultIP;
   }
   wdt_enable(WDTO_8S);
 }
References defaultIP, Keypad_TC::getKey(), EEPROM_TC::getTankID(), EEPROM_TC::instance(), Keypad_TC::instance(), IP, isUsingDHCP, key(), mac, readMac(), SD_SELECT_PIN, and serial().
Referenced by instance().
Member Function Documentation
getIP()
IPAddress Ethernet_TC::getIP () inline
Definition at line 14 of file Ethernet_TC.h.
                     {
     return IP;
   };
References IP.
Referenced by SeeDeviceAddress::start(), and unittest().
getIsUsingDHCP()
bool Ethernet_TC::getIsUsingDHCP () inline
Definition at line 17 of file Ethernet_TC.h.
{
     return isUsingDHCP;
   }
References isUsingDHCP.
getMac()
byte* Ethernet_TC::getMac () inline
Definition at line 20 of file Ethernet_TC.h.
                  {
     return mac;
   }
References mac.
Referenced by SeeDeviceAddress::start(), and unittest().
getNumAttemptedDHCPReleases()
uint16_t Ethernet_TC::getNumAttemptedDHCPReleases () inline
Definition at line 24 of file Ethernet_TC.h.
{
     return numAttemptedDHCPReleases;
   };
References numAttemptedDHCPReleases.
Referenced by unittest().
instance()
Ethernet_TC * Ethernet_TC::instance (bool reset = false) static
Definition at line 35 of file Ethernet_TC.cpp.
{
   if (reset && _instance) {
     delete _instance;
     _instance = nullptr;
   }
   if (_instance == nullptr) {
     _instance = new Ethernet_TC;
   }
   return _instance;
 }
References _instance, Ethernet_TC(), and reset().
Referenced by SeeDeviceAddress::handleKey(), PushingBox::loop(), TankControllerLib::loop(), SeeDeviceAddress::start(), TankControllerLib::TankControllerLib(), unittest(), and unittest_setup().
loop()
void Ethernet_TC::loop ()
Definition at line 46 of file Ethernet_TC.cpp.
{
   if (isUsingDHCP) {
     // "just call it on every loop() invocation" https://www.arduino.cc/en/Reference/EthernetMaintain
     Ethernet.maintain();
   }
   numAttemptedDHCPReleases++;
 }
References isUsingDHCP, and numAttemptedDHCPReleases.
Referenced by TankControllerLib::loop(), and unittest().
readMac()
void Ethernet_TC::readMac (bool forceReset = false)
Definition at line 54 of file Ethernet_TC.cpp.
{
   uint8_t bytes[6];
   EEPROM_TC::instance()->getMac(bytes);
   if (forceReset || bytes[0] != '#') {
     randomSeed(analogRead(0) + millis());
     bytes[0] = '#';
     bytes[3] = random(256);
     bytes[4] = random(256);
     bytes[5] = random(256);
     EEPROM_TC::instance()->setMac(bytes);
   }
   mac[3] = bytes[3];
   mac[4] = bytes[4];
   mac[5] = bytes[5];
   serial(F("MAC address is %02x:%02x:%02x:%02x:%02x:%02x"), mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
 }
References EEPROM_TC::getMac(), EEPROM_TC::instance(), mac, serial(), and EEPROM_TC::setMac().
Referenced by Ethernet_TC(), SeeDeviceAddress::handleKey(), and unittest().
Member Data Documentation
_instance
Ethernet_TC * Ethernet_TC::_instance = nullptr static private
Definition at line 33 of file Ethernet_TC.h.
Referenced by instance().
defaultIP
IPAddress Ethernet_TC::defaultIP = IPAddress(192, 168, 1, 10) private
Definition at line 35 of file Ethernet_TC.h.
Referenced by Ethernet_TC().
IP
IPAddress Ethernet_TC::IP private
Definition at line 38 of file Ethernet_TC.h.
Referenced by Ethernet_TC(), and getIP().
isUsingDHCP
bool Ethernet_TC::isUsingDHCP = false private
Definition at line 39 of file Ethernet_TC.h.
Referenced by Ethernet_TC(), getIsUsingDHCP(), and loop().
mac
byte Ethernet_TC::mac[6] = {0x90, 0xA2, 0xDA, 0x00, 0x00, 0x00} private
Definition at line 34 of file Ethernet_TC.h.
Referenced by Ethernet_TC(), getMac(), and readMac().
numAttemptedDHCPReleases
uint16_t Ethernet_TC::numAttemptedDHCPReleases = 0 private
Definition at line 42 of file Ethernet_TC.h.
Referenced by getNumAttemptedDHCPReleases(), and loop().
SD_SELECT_PIN
const int Ethernet_TC::SD_SELECT_PIN = 4 private
Definition at line 37 of file Ethernet_TC.h.
Referenced by Ethernet_TC().
time_serverIP
IPAddress Ethernet_TC::time_serverIP private
Definition at line 36 of file Ethernet_TC.h.
The documentation for this class was generated from the following files:
src/Devices/Ethernet_TC.h
src/Devices/Ethernet_TC.cpp