Tank Controller Lib: SeePHSlope Class Reference
SeePHSlope Class Reference
#include <SeePHSlope.h>
Public Member Functions
SeePHSlope (TankControllerLib *tc)
void start ()
void loop ()
const char * name ()
const char * prompt ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SeePHSlope.h
Display the tank ID
Definition at line 9 of file SeePHSlope.h.
Constructor & Destructor Documentation
SeePHSlope()
SeePHSlope::SeePHSlope (TankControllerLib * tc) inline
Definition at line 11 of file SeePHSlope.h.
                                     : UIState(tc) {
   }
Member Function Documentation
loop()
void SeePHSlope::loop () virtual
SeePHSlope.cpp
Reimplemented from UIState.
Definition at line 10 of file SeePHSlope.cpp.
                       {
   LiquidCrystal_TC::instance()->writeLine(PHProbe::instance()->getSlope().c_str(), 1);
 }
References LiquidCrystal_TC::instance(), PHProbe::instance(), and LiquidCrystal_TC::writeLine().
name()
const char* SeePHSlope::name () inline virtual
Implements UIState.
Definition at line 15 of file SeePHSlope.h.
                      {
     return "SeePHSlope";
   }
prompt()
const char* SeePHSlope::prompt () inline virtual
Reimplemented from UIState.
Definition at line 18 of file SeePHSlope.h.
{
     return "PH Slope:       ";
   };
Referenced by start().
start()
void SeePHSlope::start () virtual
Reimplemented from UIState.
Definition at line 14 of file SeePHSlope.cpp.
{
   LiquidCrystal_TC::instance()->writeLine(prompt(), 0);
   LiquidCrystal_TC::instance()->writeLine("requesting slope", 1);
   PHProbe::instance()->sendSlopeRequest();
 }
References LiquidCrystal_TC::instance(), PHProbe::instance(), prompt(), PHProbe::sendSlopeRequest(), and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SeePHSlope.h
src/UIState/SeePHSlope.cpp