Tank Controller Lib: PHCalibrationMid Class Reference
PHCalibrationMid Class Reference
#include <PHCalibrationMid.h>
Public Member Functions
PHCalibrationMid (TankControllerLib *tc)
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
void setValue (float value)
Public Member Functions inherited from PHCalibration
PHCalibration (TankControllerLib *tc)
virtual bool isInCalibration ()
float getCurrentValue ()
uint16_t getCurrentValuePrecision ()
void loop ()
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isMainMenu ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
PHCalibrationMid.h
pH midpoint calibration
Definition at line 9 of file PHCalibrationMid.h.
Constructor & Destructor Documentation
PHCalibrationMid()
PHCalibrationMid::PHCalibrationMid (TankControllerLib * tc) inline
Definition at line 11 of file PHCalibrationMid.h.
                                           : PHCalibration(tc) {
   }
Member Function Documentation
name()
const __FlashStringHelper* PHCalibrationMid::name () inline virtual
Implements UIState.
Definition at line 13 of file PHCalibrationMid.h.
{
     return F("PHCalibrationMid");
   }
prompt()
const __FlashStringHelper* PHCalibrationMid::prompt () inline virtual
Reimplemented from UIState.
Definition at line 16 of file PHCalibrationMid.h.
{
     return F("pH-Midpoint");
   };
setValue()
void PHCalibrationMid::setValue (float value) virtual
PHCalibrationMid.cpp
Implements NumCollectorState.
Definition at line 12 of file PHCalibrationMid.cpp.
{
   PHProbe::instance()->setMidpointCalibration(value);
   char output[17];
   snprintf_P(output, sizeof(output), (PGM_P)F("New Mid = %5.3f"), value);  // "New Mid = 12.345"
   LiquidCrystal_TC::instance()->writeLine(output, 1);
   this->setNextState((UIState*)new Wait(tc, 3000, new PHCalibrationLow(tc)));
 }
References PHProbe::instance(), LiquidCrystal_TC::instance(), PHProbe::setMidpointCalibration(), UIState::setNextState(), UIState::tc, NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/PHCalibrationMid.h
src/UIState/PHCalibrationMid.cpp