Tank Controller Lib: TemperatureCalibration Class Reference
TemperatureCalibration Class Reference
#include <TemperatureCalibration.h>
Public Member Functions
TemperatureCalibration (TankControllerLib *tc)
bool isInCalibration ()
const char * name ()
float getCurrentValue ()
int getCurrentValuePrecision ()
const char * prompt ()
void setValue (double value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (int digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes inherited from NumCollectorState
double value = 0.0
int numDigits = 0
int factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
TemperatureCalibration.h
Calibrate the temperature
Definition at line 9 of file TemperatureCalibration.h.
Constructor & Destructor Documentation
TemperatureCalibration()
TemperatureCalibration::TemperatureCalibration (TankControllerLib * tc) inline
Definition at line 11 of file TemperatureCalibration.h.
                                                 : NumCollectorState(tc) {
   }
Member Function Documentation
getCurrentValue()
float TemperatureCalibration::getCurrentValue () inline virtual
Implements NumCollectorState.
Definition at line 19 of file TemperatureCalibration.h.
{
     return 0;
   }
getCurrentValuePrecision()
int TemperatureCalibration::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 22 of file TemperatureCalibration.h.
{
     return 2;
   }
isInCalibration()
bool TemperatureCalibration::isInCalibration () inline virtual
Reimplemented from UIState.
Definition at line 13 of file TemperatureCalibration.h.
{
     return true;
   }
name()
const char* TemperatureCalibration::name () inline virtual
Implements UIState.
Definition at line 16 of file TemperatureCalibration.h.
                      {
     return "TemperatureCalibration";
   }
prompt()
const char* TemperatureCalibration::prompt () inline virtual
Reimplemented from UIState.
Definition at line 25 of file TemperatureCalibration.h.
{
     return "Real Temperature";
   };
setValue()
void TemperatureCalibration::setValue (double value) virtual
TemperatureCalibration.cpp
Implements NumCollectorState.
Definition at line 9 of file TemperatureCalibration.cpp.
{
   TempProbe_TC *pProbe = TempProbe_TC::instance();
   double average = pProbe->getRunningAverage();
   pProbe->setCorrection(value - average);
 }
References TempProbe_TC::getRunningAverage(), TempProbe_TC::instance(), TempProbe_TC::setCorrection(), and NumCollectorState::value.
The documentation for this class was generated from the following files:
src/UIState/TemperatureCalibration.h
src/UIState/TemperatureCalibration.cpp