Tank Controller Lib: PHCalibration Class Reference
PHCalibration Class Reference
#include <PHCalibration.h>
Public Member Functions
PHCalibration (TankControllerLib *tc)
virtual bool isInCalibration ()
float getCurrentValue ()
uint16_t getCurrentValuePrecision ()
void loop ()
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void setValue (float value)=0
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isMainMenu ()
virtual const char * name ()=0
virtual const char * prompt ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
Definition at line 5 of file PHCalibration.h.
Constructor & Destructor Documentation
PHCalibration()
PHCalibration::PHCalibration (TankControllerLib * tc) inline
Definition at line 7 of file PHCalibration.h.
                                        : NumCollectorState(tc) {
   }
Member Function Documentation
getCurrentValue()
float PHCalibration::getCurrentValue () inline virtual
Implements NumCollectorState.
Definition at line 12 of file PHCalibration.h.
{
     return PHProbe::instance()->getPh();
   }
References PHProbe::getPh(), and PHProbe::instance().
getCurrentValuePrecision()
uint16_t PHCalibration::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 15 of file PHCalibration.h.
{
     return 3;
   }
isInCalibration()
virtual bool PHCalibration::isInCalibration () inline virtual
Reimplemented from UIState.
Definition at line 9 of file PHCalibration.h.
{
     return true;  // disable controls during calibration
   }
loop()
void PHCalibration::loop () inline virtual
Reimplemented from UIState.
Definition at line 18 of file PHCalibration.h.
               {
     printValue();
   }
References NumCollectorState::printValue().
The documentation for this class was generated from the following file:
src/UIState/PHCalibration.h