Tank Controller Lib: Chiller Class Reference
Chiller Class Reference
#include <TemperatureControl.h>
Public Member Functions
Chiller ()
bool isHeater ()
void updateControl (float currentTemperature)
Public Member Functions inherited from TemperatureControl
virtual ~TemperatureControl ()
float getTargetTemperature ()
float getCurrentTemperatureTarget ()
uint32_t getRampTimeStart ()
uint32_t getRampTimeEnd ()
bool isOn ()
void setTargetTemperature (float newTemperature)
void setRampDuration (float newTempRampDuration)
Private Attributes
const uint32_t TIME_INTERVAL = 30 * 1000UL
uint32_t previousMillis = 0
Additional Inherited Members
Static Public Member Functions inherited from TemperatureControl
static TemperatureControl * instance ()
static void clearInstance ()
static void enableHeater (bool flag)
Protected Member Functions inherited from TemperatureControl
TemperatureControl ()
Protected Attributes inherited from TemperatureControl
const uint16_t TEMP_CONTROL_PIN = 47
const float DELTA = 0.05
uint32_t lastSwitchMS = 0
float targetTemperature
float currentTemperatureTarget
float rampStartingTemp
uint32_t rampTimeStart
uint32_t rampTimeEnd
Detailed Description
Definition at line 61 of file TemperatureControl.h.
Constructor & Destructor Documentation
Chiller()
Chiller::Chiller () inline
Definition at line 67 of file TemperatureControl.h.
 : TemperatureControl(){};
Member Function Documentation
isHeater()
bool Chiller::isHeater () inline virtual
is heater
Reimplemented from TemperatureControl.
Definition at line 68 of file TemperatureControl.h.
                   {
     return false;
   }
updateControl()
void Chiller::updateControl (float currentTemperature) virtual
Implements TemperatureControl.
Definition at line 130 of file TemperatureControl.cpp.
{
   uint32_t currentMillis = millis();
   float currentTime = DateTime_TC::now().secondstime();
   // if ramp is being used
   if (currentTime < rampTimeEnd) {
     currentTemperatureTarget =
         rampStartingTemp +
         ((currentTime - rampTimeStart) * (targetTemperature - rampStartingTemp) / (rampTimeEnd - rampTimeStart));
   } else {
     currentTemperatureTarget = targetTemperature;
   }
   COUT("Chiller::updateControl(" << currentTemperature << ") at " << currentMillis);
   if (currentMillis < previousMillis) {
     COUT("Reset previousMillis from " << previousMillis << " to 0");
     previousMillis = 0;  // reset if clock went backwards (typical during tests)
   }
   // pause 30 seconds between switching chiller on and off to prevent damage to chiller
   if (currentMillis - previousMillis < TIME_INTERVAL) {
     COUT("Chiller update at " << currentMillis << " ignored due to update at " << previousMillis);
   } else {
     bool oldValue = digitalRead(TEMP_CONTROL_PIN);
     bool newValue;
     previousMillis = currentMillis;
     // if in calibration, turn unit off
     if (TankController::instance()->isInCalibration()) {
       newValue = TURN_SOLENOID_OFF;
       COUT("Chiller should be off");
     }
     // if the observed temperature is above the set-point range turn on the chiller
     else if (currentTemperature >= currentTemperatureTarget + DELTA) {
       newValue = TURN_SOLENOID_ON;
       COUT("Chiller should be on");
     }
     // if the observed temperature is below the set-point range turn off the chiller
     else if (currentTemperature <= currentTemperatureTarget - DELTA) {
       newValue = TURN_SOLENOID_OFF;
       COUT("Chiller should be off");
     } else {
       newValue = oldValue;
     }
     if (newValue != oldValue) {
       uint32_t currentMS = millis();
       serial(F("chiller turned %s at %lu after %lu ms"), newValue ? "off" : "on", currentMS, currentMS - lastSwitchMS);
       lastSwitchMS = currentMS;
       digitalWrite(TEMP_CONTROL_PIN, newValue);
     }
   }
 }
References COUT, TemperatureControl::currentTemperatureTarget, TemperatureControl::DELTA, TankController::instance(), TemperatureControl::lastSwitchMS, DateTime_TC::now(), previousMillis, TemperatureControl::rampStartingTemp, TemperatureControl::rampTimeEnd, TemperatureControl::rampTimeStart, serial(), TemperatureControl::targetTemperature, TemperatureControl::TEMP_CONTROL_PIN, TIME_INTERVAL, TURN_SOLENOID_OFF, and TURN_SOLENOID_ON.
Member Data Documentation
previousMillis
uint32_t Chiller::previousMillis = 0 private
Definition at line 64 of file TemperatureControl.h.
Referenced by updateControl().
TIME_INTERVAL
const uint32_t Chiller::TIME_INTERVAL = 30 * 1000UL private
Definition at line 63 of file TemperatureControl.h.
Referenced by updateControl().
The documentation for this class was generated from the following files:
src/Devices/TemperatureControl.h
src/Devices/TemperatureControl.cpp