Tank Controller Lib: SD_TC Class Reference
SD_TC Class Reference
#include <SD_TC.h>
Public Member Functions
void appendToDataLog (String header, String data)
void appendToSerialLog (String data)
String todaysDataFileName ()
void printRootDirectory ()
void visit (visitor pFunction)
Static Public Member Functions
static SD_TC * instance ()
Private Member Functions
SD_TC ()
void appendDataToPath (String data, String path)
void visit (visitor pFunction, File dir, String parentPath)
Private Attributes
const int PIN = 10
bool hasHadError = false
Static Private Attributes
static SD_TC * _instance = nullptr
Detailed Description
Definition at line 12 of file SD_TC.h.
Constructor & Destructor Documentation
SD_TC()
SD_TC::SD_TC () private
constructor
Definition at line 28 of file SD_TC.cpp.
              {
   assert(_instance == nullptr);
   pinMode(PIN, OUTPUT);
   digitalWrite(PIN, HIGH);
   begin(4);
 }
References _instance, assert, and PIN.
Referenced by instance().
Member Function Documentation
appendDataToPath()
void SD_TC::appendDataToPath (String data, String path) private
append data to a path
Definition at line 52 of file SD_TC.cpp.
{
   int i = path.indexOf('/', 1);
   while (i > 0) {
     String s = path.substring(0, i);
     if (!SD.exists(s)) {
       if (!SD.mkdir(s.c_str())) {
         if (!hasHadError) {
           hasHadError = true;
           serial("Unable to create directory: \"%s\"", s.c_str());
           COUT("Unable to create directory: \"" << s.c_str() << "\"");
         }
         return;
       }
     }
     i = path.indexOf('/', i + 2);
   }
   File file = SD_TC::instance()->open(path, FILE_WRITE);
   if (file) {
     file.write(data.c_str(), data.length());
     file.write("\n", 1);
     file.close();
   } else {
     if (!hasHadError) {
       hasHadError = true;
       serial("Unable to open file: \"%s\"", path.c_str());
       COUT("Unable to open file: \"" << path.c_str() << "\"");
       return;
     }
   }
 }
References COUT, hasHadError, instance(), and serial().
Referenced by appendToDataLog(), and appendToSerialLog().
appendToDataLog()
void SD_TC::appendToDataLog (String header, String data)
append data to a data log file
Definition at line 38 of file SD_TC.cpp.
{
   String path = todaysDataFileName();
   COUT(path);
   if (!exists(path)) {
     appendDataToPath(header, path);
     COUT(header);
   }
   appendDataToPath(data, path);
   COUT(data);
 }
References appendDataToPath(), COUT, and todaysDataFileName().
Referenced by unittest(), and TankControllerLib::writeDataToSD().
appendToSerialLog()
void SD_TC::appendToSerialLog (String data)
append data to a serial log file
Definition at line 86 of file SD_TC.cpp.
{
   DateTime_TC now = DateTime_TC::now();
   char path[30];
   snprintf(path, sizeof(path), "/log/%4i/%02i/%02i.txt", now.year(), now.month(), now.day());
   appendDataToPath(data, path);
 }
References appendDataToPath(), and DateTime_TC::now().
Referenced by unittest().
instance()
SD_TC * SD_TC::instance () static
accessor for singleton
Definition at line 15 of file SD_TC.cpp.
{
   if (!_instance) {
     _instance = new SD_TC();
     serial("SD_TC::instance() called SD_TC::SD_TC()");
   }
   return _instance;
 }
References _instance, SD_TC(), and serial().
Referenced by appendDataToPath(), sdInit(), sdNextValue(), TankControllerLib::setup(), SeeLogFile::start(), unittest(), unittest_setup(), unittest_teardown(), and TankControllerLib::writeDataToSD().
printRootDirectory()
void SD_TC::printRootDirectory ()
print the root directory and all subdirectories
Definition at line 115 of file SD_TC.cpp.
{
   serial("SD_TC::printRootDirectory() - start");
   visit(printEntry);
   serial("SD_TC::printRootDirectory() - end");
 }
References printEntry(), serial(), and visit().
Referenced by TankControllerLib::setup(), and unittest().
todaysDataFileName()
String SD_TC::todaysDataFileName ()
Definition at line 121 of file SD_TC.cpp.
{
   DateTime_TC now = DateTime_TC::now();
   char path[30];
   snprintf(path, sizeof(path), "/data/%4i/%02i/%02i.txt", now.year(), now.month(), now.day());
   COUT(path);
   return String(path);
 }
References COUT, and DateTime_TC::now().
Referenced by appendToDataLog(), and SeeLogFile::start().
visit() [1/2]
void SD_TC::visit (visitor pFunction)
Definition at line 129 of file SD_TC.cpp.
{
   File root = open("/");
   if (root) {
     visit(pFunction, root, "/");
   } else {
     serial("Unable to open root directory of SD card!");
   }
 }
References serial().
Referenced by printRootDirectory(), sdInit(), and visit().
visit() [2/2]
void SD_TC::visit (visitor pFunction, File dir, String parentPath) private
Definition at line 138 of file SD_TC.cpp.
{
   int i = 0;
   while (i++ < 100) {
     File entry = dir.openNextFile();
     if (!entry) {
       return;  // no more files
     }
     pFunction(entry, parentPath);
     if (entry.isDirectory()) {
       visit(pFunction, entry, parentPath + entry.name() + "/");
     }
     entry.close();
   }
   serial("Stopped after 100 entries");
 }
References serial(), and visit().
Member Data Documentation
_instance
SD_TC * SD_TC::_instance = nullptr static private
Definition at line 26 of file SD_TC.h.
Referenced by instance(), and SD_TC().
hasHadError
bool SD_TC::hasHadError = false private
Definition at line 30 of file SD_TC.h.
Referenced by appendDataToPath().
PIN
const int SD_TC::PIN = 10 private
Definition at line 29 of file SD_TC.h.
Referenced by SD_TC().
The documentation for this class was generated from the following files:
src/Devices/SD_TC.h
src/Devices/SD_TC.cpp