Tank Controller Lib: EnablePID Class Reference
EnablePID Class Reference
#include <EnablePID.h>
Public Member Functions
EnablePID (TankControllerLib *tc)
const char * name ()
const char * prompt ()
void setValue (double value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (int digit)
void printValue ()
virtual bool isInteger ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes inherited from NumCollectorState
double value = 0.0
int numDigits = 0
int factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
EnablePID.h
Enable PID Controller
Definition at line 9 of file EnablePID.h.
Constructor & Destructor Documentation
EnablePID()
EnablePID::EnablePID (TankControllerLib * tc) inline
Definition at line 11 of file EnablePID.h.
                                    : NumCollectorState(tc) {
   }
Member Function Documentation
name()
const char* EnablePID::name () inline virtual
Implements UIState.
Definition at line 13 of file EnablePID.h.
                      {
     return "EnablePID";
   }
prompt()
const char* EnablePID::prompt () inline virtual
Reimplemented from UIState.
Definition at line 16 of file EnablePID.h.
{
     return "PID 1:on; 9:off ";
   };
setValue()
void EnablePID::setValue (double value) virtual
EnablePID.cpp
Implements NumCollectorState.
Definition at line 10 of file EnablePID.cpp.
{
   if (!(value == 1.0 || value == 9.0)) {
     LiquidCrystal_TC::instance()->writeLine("Invalid entry!  ", 1);
   } else {
     bool flag = (int)value == 1;
     PHControl::instance()->setUsePID(flag);
     if (flag) {
       LiquidCrystal_TC::instance()->writeLine("PID enabled     ", 1);
     } else {
       LiquidCrystal_TC::instance()->writeLine("PID disabled    ", 1);
     }
   }
 }
References LiquidCrystal_TC::instance(), PHControl::instance(), PHControl::setUsePID(), NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/EnablePID.h
src/UIState/EnablePID.cpp