Tank Controller Lib: EEPROM_TC_2 Class Reference
EEPROM_TC_2 Class Reference
#include <EEPROM_TC_2.h>
Public Member Functions
double getAmplitude ()
double getCorrectedTemp ()
double getFrequency ()
int getGoogleSheetInterval ()
double getGranularity ()
bool getHeat ()
double getKD ()
double getKI ()
double getKP ()
double getMac ()
double getMaxDataAge ()
double getPH ()
double getPHDelay ()
double getPHInterval ()
double getPHSeriesPointer ()
double getPHSeriesSize ()
int getTankID ()
double getTemp ()
double getTempDelay ()
double getTempInterval ()
double getTempSeriesPointer ()
double getTempSeriesSize ()
int getVersion ()
void setAmplitude (double value)
void setCorrectedTemp (double value)
void setFrequency (double value)
void setGoogleSheetInterval (int value)
void setGranularity (double value)
void setHeat (bool value)
void setKD (double value)
void setKI (double value)
void setKP (double value)
void setMac (double value)
void setMaxDataAge (double value)
void setPH (double value)
void setPHDelay (double value)
void setPHInterval (double value)
void setPHSeriesPointer (double value)
void setPHSeriesSize (double value)
void setTankID (int value)
void setTemp (double value)
void setTempDelay (double value)
void setTempInterval (double value)
void setTempSeriesPointer (double value)
void setTempSeriesSize (double value)
void setVersion ()
Public Member Functions inherited from EEPROM_TC
virtual ~EEPROM_TC ()
double eepromReadDouble (int address)
int eepromReadInt (int address)
void eepromWriteDouble (int address, double value)
void eepromWriteInt (int address, int value)
Protected Member Functions
virtual bool isRightVersion ()
Private Attributes
const int PH_ADDRESS = 0
const int TEMP_ADDRESS = 4
const int TANK_ID_ADDRESS = 8
const int TEMP_CORR_ADDRESS = 12
const int KP_ADDRESS = 20
const int KI_ADDRESS = 28
const int KD_ADDRESS = 36
const int MAC_ADDRESS = 44
const int HEAT_ADDRESS = 52
const int AMPLITUDE_ADDRESS = 56
const int FREQUENCY_ADDRESS = 60
const int GRANULARITY_ADDRESS = 64
const int MAX_DATA_AGE_ADDRESS = 68
const int PH_SERIES_SIZE_ADDRESS = 72
const int PH_SERIES_POINTER_ADDRESS = 76
const int TEMP_SERIES_SIZE_ADDRESS = 80
const int TEMP_SERIES_POINTER_ADDRESS = 84
const int PH_INTERVAL_ADDRESS = 88
const int PH_DELAY_ADDRESS = 92
const int TEMP_INTERVAL_ADDRESS = 96
const int TEMP_DELAY_ADDRESS = 100
const int GOOGLE_INTERVAL_ADDRESS = 108
Additional Inherited Members
Static Public Member Functions inherited from EEPROM_TC
static EEPROM_TC * instance (int version=0)
Detailed Description
Definition at line 5 of file EEPROM_TC_2.h.
Member Function Documentation
getAmplitude()
double EEPROM_TC_2::getAmplitude () virtual
Implements EEPROM_TC.
Definition at line 11 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(AMPLITUDE_ADDRESS);
 }
References AMPLITUDE_ADDRESS, and EEPROM_TC::eepromReadDouble().
getCorrectedTemp()
double EEPROM_TC_2::getCorrectedTemp () virtual
Implements EEPROM_TC.
Definition at line 14 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(TEMP_CORR_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_CORR_ADDRESS.
getFrequency()
double EEPROM_TC_2::getFrequency () virtual
Implements EEPROM_TC.
Definition at line 17 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(FREQUENCY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and FREQUENCY_ADDRESS.
getGoogleSheetInterval()
int EEPROM_TC_2::getGoogleSheetInterval () virtual
Implements EEPROM_TC.
Definition at line 20 of file EEPROM_TC_2.cpp.
{
   return eepromReadInt(GOOGLE_INTERVAL_ADDRESS);
 }
References EEPROM_TC::eepromReadInt(), and GOOGLE_INTERVAL_ADDRESS.
getGranularity()
double EEPROM_TC_2::getGranularity () virtual
Implements EEPROM_TC.
Definition at line 23 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(GRANULARITY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and GRANULARITY_ADDRESS.
getHeat()
bool EEPROM_TC_2::getHeat () virtual
Implements EEPROM_TC.
Definition at line 26 of file EEPROM_TC_2.cpp.
{
   return (bool)eepromReadDouble(HEAT_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and HEAT_ADDRESS.
getKD()
double EEPROM_TC_2::getKD () virtual
Implements EEPROM_TC.
Definition at line 29 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(KD_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and KD_ADDRESS.
getKI()
double EEPROM_TC_2::getKI () virtual
Implements EEPROM_TC.
Definition at line 32 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(KI_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and KI_ADDRESS.
getKP()
double EEPROM_TC_2::getKP () virtual
Implements EEPROM_TC.
Definition at line 35 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(KP_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and KP_ADDRESS.
getMac()
double EEPROM_TC_2::getMac () virtual
Implements EEPROM_TC.
Definition at line 38 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(MAC_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and MAC_ADDRESS.
getMaxDataAge()
double EEPROM_TC_2::getMaxDataAge () virtual
Implements EEPROM_TC.
Definition at line 41 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(MAX_DATA_AGE_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and MAX_DATA_AGE_ADDRESS.
getPH()
double EEPROM_TC_2::getPH () virtual
Implements EEPROM_TC.
Definition at line 44 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(PH_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_ADDRESS.
getPHDelay()
double EEPROM_TC_2::getPHDelay () virtual
Implements EEPROM_TC.
Definition at line 47 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(PH_DELAY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_DELAY_ADDRESS.
getPHInterval()
double EEPROM_TC_2::getPHInterval () virtual
Implements EEPROM_TC.
Definition at line 50 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(PH_INTERVAL_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_INTERVAL_ADDRESS.
getPHSeriesPointer()
double EEPROM_TC_2::getPHSeriesPointer () virtual
Implements EEPROM_TC.
Definition at line 53 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(PH_SERIES_POINTER_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_SERIES_POINTER_ADDRESS.
getPHSeriesSize()
double EEPROM_TC_2::getPHSeriesSize () virtual
Implements EEPROM_TC.
Definition at line 56 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(PH_SERIES_SIZE_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_SERIES_SIZE_ADDRESS.
getTankID()
int EEPROM_TC_2::getTankID () virtual
Implements EEPROM_TC.
Definition at line 59 of file EEPROM_TC_2.cpp.
{
   return (int)eepromReadDouble(TANK_ID_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TANK_ID_ADDRESS.
getTemp()
double EEPROM_TC_2::getTemp () virtual
Implements EEPROM_TC.
Definition at line 62 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(TEMP_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_ADDRESS.
getTempDelay()
double EEPROM_TC_2::getTempDelay () virtual
Implements EEPROM_TC.
Definition at line 65 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(TEMP_DELAY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_DELAY_ADDRESS.
getTempInterval()
double EEPROM_TC_2::getTempInterval () virtual
Implements EEPROM_TC.
Definition at line 68 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(TEMP_INTERVAL_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_INTERVAL_ADDRESS.
getTempSeriesPointer()
double EEPROM_TC_2::getTempSeriesPointer () virtual
Implements EEPROM_TC.
Definition at line 71 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(TEMP_SERIES_POINTER_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_SERIES_POINTER_ADDRESS.
getTempSeriesSize()
double EEPROM_TC_2::getTempSeriesSize () virtual
Implements EEPROM_TC.
Definition at line 74 of file EEPROM_TC_2.cpp.
{
   return eepromReadDouble(TEMP_SERIES_SIZE_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_SERIES_SIZE_ADDRESS.
getVersion()
int EEPROM_TC_2::getVersion () virtual
Implements EEPROM_TC.
Definition at line 77 of file EEPROM_TC_2.cpp.
{
   return 2;  // we assume so!
 }
isRightVersion()
bool EEPROM_TC_2::isRightVersion () protected virtual
Implements EEPROM_TC.
Definition at line 6 of file EEPROM_TC_2.cpp.
{
   return true;  // we have no way of telling!
 }
setAmplitude()
void EEPROM_TC_2::setAmplitude (double value) virtual
Implements EEPROM_TC.
Definition at line 82 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(AMPLITUDE_ADDRESS, value);
 }
References AMPLITUDE_ADDRESS, EEPROM_TC::eepromWriteDouble(), and value.
setCorrectedTemp()
void EEPROM_TC_2::setCorrectedTemp (double value) virtual
Implements EEPROM_TC.
Definition at line 85 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(TEMP_CORR_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_CORR_ADDRESS, and value.
setFrequency()
void EEPROM_TC_2::setFrequency (double value) virtual
Implements EEPROM_TC.
Definition at line 88 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(FREQUENCY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), FREQUENCY_ADDRESS, and value.
setGoogleSheetInterval()
void EEPROM_TC_2::setGoogleSheetInterval (int value) virtual
Implements EEPROM_TC.
Definition at line 91 of file EEPROM_TC_2.cpp.
{
   eepromWriteInt(GOOGLE_INTERVAL_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteInt(), GOOGLE_INTERVAL_ADDRESS, and value.
setGranularity()
void EEPROM_TC_2::setGranularity (double value) virtual
Implements EEPROM_TC.
Definition at line 94 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(GRANULARITY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), GRANULARITY_ADDRESS, and value.
setHeat()
void EEPROM_TC_2::setHeat (bool value) virtual
Implements EEPROM_TC.
Definition at line 97 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(HEAT_ADDRESS, (double)value);
 }
References EEPROM_TC::eepromWriteDouble(), HEAT_ADDRESS, and value.
setKD()
void EEPROM_TC_2::setKD (double value) virtual
Implements EEPROM_TC.
Definition at line 100 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(KD_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), KD_ADDRESS, and value.
setKI()
void EEPROM_TC_2::setKI (double value) virtual
Implements EEPROM_TC.
Definition at line 103 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(KI_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), KI_ADDRESS, and value.
setKP()
void EEPROM_TC_2::setKP (double value) virtual
Implements EEPROM_TC.
Definition at line 106 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(KP_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), KP_ADDRESS, and value.
setMac()
void EEPROM_TC_2::setMac (double value) virtual
Implements EEPROM_TC.
Definition at line 109 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(MAC_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), MAC_ADDRESS, and value.
setMaxDataAge()
void EEPROM_TC_2::setMaxDataAge (double value) virtual
Implements EEPROM_TC.
Definition at line 112 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(MAX_DATA_AGE_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), MAX_DATA_AGE_ADDRESS, and value.
setPH()
void EEPROM_TC_2::setPH (double value) virtual
Implements EEPROM_TC.
Definition at line 115 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(PH_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_ADDRESS, and value.
setPHDelay()
void EEPROM_TC_2::setPHDelay (double value) virtual
Implements EEPROM_TC.
Definition at line 118 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(PH_DELAY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_DELAY_ADDRESS, and value.
setPHInterval()
void EEPROM_TC_2::setPHInterval (double value) virtual
Implements EEPROM_TC.
Definition at line 121 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(PH_INTERVAL_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_INTERVAL_ADDRESS, and value.
setPHSeriesPointer()
void EEPROM_TC_2::setPHSeriesPointer (double value) virtual
Implements EEPROM_TC.
Definition at line 124 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(PH_SERIES_POINTER_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_SERIES_POINTER_ADDRESS, and value.
setPHSeriesSize()
void EEPROM_TC_2::setPHSeriesSize (double value) virtual
Implements EEPROM_TC.
Definition at line 127 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(PH_SERIES_SIZE_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_SERIES_SIZE_ADDRESS, and value.
setTankID()
void EEPROM_TC_2::setTankID (int value) virtual
Implements EEPROM_TC.
Definition at line 130 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(TANK_ID_ADDRESS, (double)value);
 }
References EEPROM_TC::eepromWriteDouble(), TANK_ID_ADDRESS, and value.
setTemp()
void EEPROM_TC_2::setTemp (double value) virtual
Implements EEPROM_TC.
Definition at line 133 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(TEMP_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_ADDRESS, and value.
setTempDelay()
void EEPROM_TC_2::setTempDelay (double value) virtual
Implements EEPROM_TC.
Definition at line 136 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(TEMP_DELAY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_DELAY_ADDRESS, and value.
setTempInterval()
void EEPROM_TC_2::setTempInterval (double value) virtual
Implements EEPROM_TC.
Definition at line 139 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(TEMP_INTERVAL_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_INTERVAL_ADDRESS, and value.
setTempSeriesPointer()
void EEPROM_TC_2::setTempSeriesPointer (double value) virtual
Implements EEPROM_TC.
Definition at line 142 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(TEMP_SERIES_POINTER_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_SERIES_POINTER_ADDRESS, and value.
setTempSeriesSize()
void EEPROM_TC_2::setTempSeriesSize (double value) virtual
Implements EEPROM_TC.
Definition at line 145 of file EEPROM_TC_2.cpp.
{
   eepromWriteDouble(TEMP_SERIES_SIZE_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_SERIES_SIZE_ADDRESS, and value.
setVersion()
void EEPROM_TC_2::setVersion () inline virtual
Implements EEPROM_TC.
Definition at line 55 of file EEPROM_TC_2.h.
                     {  // Nothing to be done here!
   }
Member Data Documentation
AMPLITUDE_ADDRESS
const int EEPROM_TC_2::AMPLITUDE_ADDRESS = 56 private
Definition at line 76 of file EEPROM_TC_2.h.
Referenced by getAmplitude(), and setAmplitude().
FREQUENCY_ADDRESS
const int EEPROM_TC_2::FREQUENCY_ADDRESS = 60 private
Definition at line 77 of file EEPROM_TC_2.h.
Referenced by getFrequency(), and setFrequency().
GOOGLE_INTERVAL_ADDRESS
const int EEPROM_TC_2::GOOGLE_INTERVAL_ADDRESS = 108 private
Definition at line 89 of file EEPROM_TC_2.h.
Referenced by getGoogleSheetInterval(), and setGoogleSheetInterval().
GRANULARITY_ADDRESS
const int EEPROM_TC_2::GRANULARITY_ADDRESS = 64 private
Definition at line 78 of file EEPROM_TC_2.h.
Referenced by getGranularity(), and setGranularity().
HEAT_ADDRESS
const int EEPROM_TC_2::HEAT_ADDRESS = 52 private
Definition at line 74 of file EEPROM_TC_2.h.
Referenced by getHeat(), and setHeat().
KD_ADDRESS
const int EEPROM_TC_2::KD_ADDRESS = 36 private
Definition at line 72 of file EEPROM_TC_2.h.
Referenced by getKD(), and setKD().
KI_ADDRESS
const int EEPROM_TC_2::KI_ADDRESS = 28 private
Definition at line 71 of file EEPROM_TC_2.h.
Referenced by getKI(), and setKI().
KP_ADDRESS
const int EEPROM_TC_2::KP_ADDRESS = 20 private
Definition at line 70 of file EEPROM_TC_2.h.
Referenced by getKP(), and setKP().
MAC_ADDRESS
const int EEPROM_TC_2::MAC_ADDRESS = 44 private
Definition at line 73 of file EEPROM_TC_2.h.
Referenced by getMac(), and setMac().
MAX_DATA_AGE_ADDRESS
const int EEPROM_TC_2::MAX_DATA_AGE_ADDRESS = 68 private
Definition at line 79 of file EEPROM_TC_2.h.
Referenced by getMaxDataAge(), and setMaxDataAge().
PH_ADDRESS
const int EEPROM_TC_2::PH_ADDRESS = 0 private
Definition at line 66 of file EEPROM_TC_2.h.
Referenced by getPH(), and setPH().
PH_DELAY_ADDRESS
const int EEPROM_TC_2::PH_DELAY_ADDRESS = 92 private
Definition at line 85 of file EEPROM_TC_2.h.
Referenced by getPHDelay(), and setPHDelay().
PH_INTERVAL_ADDRESS
const int EEPROM_TC_2::PH_INTERVAL_ADDRESS = 88 private
Definition at line 84 of file EEPROM_TC_2.h.
Referenced by getPHInterval(), and setPHInterval().
PH_SERIES_POINTER_ADDRESS
const int EEPROM_TC_2::PH_SERIES_POINTER_ADDRESS = 76 private
Definition at line 81 of file EEPROM_TC_2.h.
Referenced by getPHSeriesPointer(), and setPHSeriesPointer().
PH_SERIES_SIZE_ADDRESS
const int EEPROM_TC_2::PH_SERIES_SIZE_ADDRESS = 72 private
Definition at line 80 of file EEPROM_TC_2.h.
Referenced by getPHSeriesSize(), and setPHSeriesSize().
TANK_ID_ADDRESS
const int EEPROM_TC_2::TANK_ID_ADDRESS = 8 private
Definition at line 68 of file EEPROM_TC_2.h.
Referenced by getTankID(), and setTankID().
TEMP_ADDRESS
const int EEPROM_TC_2::TEMP_ADDRESS = 4 private
Definition at line 67 of file EEPROM_TC_2.h.
Referenced by getTemp(), and setTemp().
TEMP_CORR_ADDRESS
const int EEPROM_TC_2::TEMP_CORR_ADDRESS = 12 private
Definition at line 69 of file EEPROM_TC_2.h.
Referenced by getCorrectedTemp(), and setCorrectedTemp().
TEMP_DELAY_ADDRESS
const int EEPROM_TC_2::TEMP_DELAY_ADDRESS = 100 private
Definition at line 87 of file EEPROM_TC_2.h.
Referenced by getTempDelay(), and setTempDelay().
TEMP_INTERVAL_ADDRESS
const int EEPROM_TC_2::TEMP_INTERVAL_ADDRESS = 96 private
Definition at line 86 of file EEPROM_TC_2.h.
Referenced by getTempInterval(), and setTempInterval().
TEMP_SERIES_POINTER_ADDRESS
const int EEPROM_TC_2::TEMP_SERIES_POINTER_ADDRESS = 84 private
Definition at line 83 of file EEPROM_TC_2.h.
Referenced by getTempSeriesPointer(), and setTempSeriesPointer().
TEMP_SERIES_SIZE_ADDRESS
const int EEPROM_TC_2::TEMP_SERIES_SIZE_ADDRESS = 80 private
Definition at line 82 of file EEPROM_TC_2.h.
Referenced by getTempSeriesSize(), and setTempSeriesSize().
The documentation for this class was generated from the following files:
src/Devices/EEPROM_TC_2.h
src/Devices/EEPROM_TC_2.cpp