Tank Controller Lib: UIState Class Reference
UIState Class Reference abstract
#include <UIState.h>
Public Member Functions
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Protected Member Functions
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes
TankControllerLib * tc = nullptr
Detailed Description
Definition at line 11 of file UIState.h.
Constructor & Destructor Documentation
UIState()
UIState::UIState (TankControllerLib * tc) inline
Definition at line 14 of file UIState.h.
{
     this->tc = tc;
   }
References tc.
~UIState()
virtual UIState::~UIState () inline virtual
Definition at line 18 of file UIState.h.
                      {
   }
Member Function Documentation
handleKey()
void UIState::handleKey (char key) virtual
Reimplemented in SetCalibrationClear, SeeDeviceAddress, ResetLCDScreen, NumCollectorState, MainMenu, and CalibrationManagement.
Definition at line 10 of file UIState.cpp.
{
   // use value just to avoid compiler warning
   (void)key;
   // default is to just return to main menu
   // this is useful for display-only actions
   this->returnToMainMenu();
 }
References key(), and returnToMainMenu().
Referenced by TankControllerLib::handleUI(), TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
isInCalibration()
virtual bool UIState::isInCalibration () inline virtual
Reimplemented in TemperatureCalibration, and PHCalibration.
Definition at line 23 of file UIState.h.
{
     return false;  // override to return true to disable controls
   }
Referenced by TankControllerLib::isInCalibration().
isMainMenu()
virtual bool UIState::isMainMenu () inline virtual
Reimplemented in MainMenu.
Definition at line 26 of file UIState.h.
{
     return false;
   }
loop()
virtual void UIState::loop () inline virtual
Reimplemented in Wait, SeePIDConstants, SeePHSlope, SeeDeviceUptime, PHCalibration, and MainMenu.
Definition at line 29 of file UIState.h.
                       {
   }
Referenced by TankControllerLib::handleUI().
name()
virtual const __FlashStringHelper* UIState::name () pure virtual
Implemented in Wait, TemperatureCalibration, SetTime, SetTempSetPoint, SetTankID, SetPHSetPoint, SetKP, SetKI, SetKD, SetGoogleSheetInterval, SetChillOrHeat, SetCalibrationClear, SeeVersion, SeeTankID, SeePIDConstants, SeePHSlope, SeeLogFile, SeeGoogleMins, SeeFreeMemory, SeeDeviceUptime, SeeDeviceAddress, ResetLCDScreen, PHCalibrationMid, PHCalibrationLow, PHCalibrationHigh, MainMenu, EnablePID, and CalibrationManagement.
Referenced by TankControllerLib::handleUI(), TankControllerLib::setNextState(), TankControllerLib::stateName(), TankControllerLib::updateState(), and Wait::Wait().
prompt()
virtual const __FlashStringHelper* UIState::prompt () inline virtual
Reimplemented in TemperatureCalibration, SetTime, SetTempSetPoint, SetTankID, SetPHSetPoint, SetKP, SetKI, SetKD, SetGoogleSheetInterval, SetChillOrHeat, SetCalibrationClear, SeeVersion, SeeTankID, SeePHSlope, SeeLogFile, SeeGoogleMins, SeeFreeMemory, SeeDeviceAddress, ResetLCDScreen, PHCalibrationMid, PHCalibrationLow, PHCalibrationHigh, MainMenu, EnablePID, and CalibrationManagement.
Definition at line 32 of file UIState.h.
{
     return F("");
   }
Referenced by start().
returnToMainMenu()
void UIState::returnToMainMenu (uint16_t msDelay = 0) protected
Definition at line 18 of file UIState.cpp.
{
   if (msDelay) {
     this->setNextState((UIState*)new Wait(tc, msDelay));
   } else {
     this->setNextState((UIState*)new MainMenu(tc));
   }
 }
References setNextState(), and tc.
Referenced by CalibrationManagement::handleKey(), NumCollectorState::handleKey(), ResetLCDScreen::handleKey(), SeeDeviceAddress::handleKey(), SetCalibrationClear::handleKey(), handleKey(), EnablePID::setValue(), PHCalibrationHigh::setValue(), SetChillOrHeat::setValue(), SetGoogleSheetInterval::setValue(), SetKD::setValue(), SetKI::setValue(), SetKP::setValue(), SetPHSetPoint::setValue(), SetTankID::setValue(), SetTempSetPoint::setValue(), SetTime::setValue(), and TemperatureCalibration::setValue().
setNextState()
void UIState::setNextState (UIState * state) protected
Definition at line 26 of file UIState.cpp.
{
   tc->setNextState(state);
 }
References TankControllerLib::setNextState(), state, and tc.
Referenced by MainMenu::handleKey(), Wait::loop(), returnToMainMenu(), MainMenu::selectSet(), MainMenu::selectView(), PHCalibrationLow::setValue(), and PHCalibrationMid::setValue().
start()
void UIState::start () virtual
Reimplemented in Wait, SeeVersion, SeeTankID, SeePIDConstants, SeePHSlope, SeeLogFile, SeeGoogleMins, SeeFreeMemory, SeeDeviceAddress, and NumCollectorState.
Definition at line 30 of file UIState.cpp.
                     {
   // default is to print the current prompt on the first line of the display
   LiquidCrystal_TC::instance()->writeLine(this->prompt(), 0);
   LiquidCrystal_TC::instance()->writeLine(F(""), 1);
 }
References LiquidCrystal_TC::instance(), prompt(), and LiquidCrystal_TC::writeLine().
Referenced by NumCollectorState::start(), and TankControllerLib::updateState().
Member Data Documentation
tc
TankControllerLib* UIState::tc = nullptr protected
Definition at line 40 of file UIState.h.
Referenced by MainMenu::handleKey(), returnToMainMenu(), MainMenu::selectSet(), MainMenu::selectView(), setNextState(), PHCalibrationLow::setValue(), PHCalibrationMid::setValue(), UIState(), and Wait::Wait().
The documentation for this class was generated from the following files:
src/UIState/UIState.h
src/UIState/UIState.cpp