Tank Controller Lib: PHCalibrationLow Class Reference
PHCalibrationLow Class Reference
#include <PHCalibrationLow.h>
Public Member Functions
PHCalibrationLow (TankControllerLib *tc)
virtual bool isInCalibration ()
const char * name ()
float getCurrentValue ()
int getCurrentValuePrecision ()
const char * prompt ()
void setValue (double value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (int digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes inherited from NumCollectorState
double value = 0.0
int numDigits = 0
int factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
PHCalibrationLow.h
pH lowpoint calibration
Definition at line 9 of file PHCalibrationLow.h.
Constructor & Destructor Documentation
PHCalibrationLow()
PHCalibrationLow::PHCalibrationLow (TankControllerLib * tc) inline
Definition at line 11 of file PHCalibrationLow.h.
                                           : NumCollectorState(tc) {
   }
Member Function Documentation
getCurrentValue()
float PHCalibrationLow::getCurrentValue () inline virtual
Implements NumCollectorState.
Definition at line 19 of file PHCalibrationLow.h.
{
     return 0.0;
   }
getCurrentValuePrecision()
int PHCalibrationLow::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 22 of file PHCalibrationLow.h.
{
     return 3;
   }
isInCalibration()
virtual bool PHCalibrationLow::isInCalibration () inline virtual
Reimplemented from UIState.
Definition at line 13 of file PHCalibrationLow.h.
{
     return true;  // disable controls during calibration
   }
name()
const char* PHCalibrationLow::name () inline virtual
Implements UIState.
Definition at line 16 of file PHCalibrationLow.h.
                      {
     return "PHCalibrationLow";
   }
prompt()
const char* PHCalibrationLow::prompt () inline virtual
Reimplemented from UIState.
Definition at line 25 of file PHCalibrationLow.h.
{
     return "pH-Lowpoint     ";
   };
setValue()
void PHCalibrationLow::setValue (double value) virtual
PHCalibrationLow.cpp
Implements NumCollectorState.
Definition at line 12 of file PHCalibrationLow.cpp.
{
   PHProbe::instance()->setLowpointCalibration(value);
   char output[17];
   snprintf(output, sizeof(output), "New Low = %2.3f", value);  // "New Low = 12.345"
   LiquidCrystal_TC::instance()->writeLine(output, 1);
   this->setNextState((UIState*)new Wait(tc, 1000, new PHCalibrationHigh(tc)));
 }
References LiquidCrystal_TC::instance(), PHProbe::instance(), PHProbe::setLowpointCalibration(), UIState::setNextState(), UIState::tc, NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/PHCalibrationLow.h
src/UIState/PHCalibrationLow.cpp