Tank Controller Lib: SetCalibrationClear Class Reference
SetCalibrationClear Class Reference
#include <SetCalibrationClear.h>
Public Member Functions
SetCalibrationClear (TankController *tc)
void handleKey (char key)
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
SetCalibrationClear.h
Clear pH Calibration
Definition at line 9 of file SetCalibrationClear.h.
Constructor & Destructor Documentation
SetCalibrationClear()
SetCalibrationClear::SetCalibrationClear (TankController * tc) inline
Definition at line 11 of file SetCalibrationClear.h.
                                          : UIState(tc) {
  }
Member Function Documentation
handleKey()
void SetCalibrationClear::handleKey (char key) virtual
SetCalibrationClear.cpp
Reimplemented from UIState.
Definition at line 9 of file SetCalibrationClear.cpp.
{
  switch (key) {
    case 'A':  // Save (clear calibration)
      PHProbe::instance()->clearCalibration();
      LiquidCrystal_TC::instance()->writeLine(F("Cleared pH Calib"), 1);
      returnToMainMenu(3000);
      break;
    case 'D':  // Don't save (cancel)
      returnToMainMenu();
      break;
    default:
      break;
  };
}
References PHProbe::clearCalibration(), PHProbe::instance(), LiquidCrystal_TC::instance(), key(), UIState::returnToMainMenu(), and LiquidCrystal_TC::writeLine().
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
name()
const __FlashStringHelper * SetCalibrationClear::name () inline virtual
Implements UIState.
Definition at line 14 of file SetCalibrationClear.h.
{
    return F("SetCalibrationClear");
  }
prompt()
const __FlashStringHelper * SetCalibrationClear::prompt () inline virtual
Reimplemented from UIState.
Definition at line 17 of file SetCalibrationClear.h.
{
    return F("A: Clear pH Cali");
  };
The documentation for this class was generated from the following files:
src/UIState/SetCalibrationClear.h
src/UIState/SetCalibrationClear.cpp