Tank Controller Lib: EEPROM_TC Class Reference
EEPROM_TC Class Reference
#include <EEPROM_TC.h>
Public Member Functions
float eepromReadFloat (uint16_t address)
int32_t eepromReadInt (uint16_t address)
void eepromWriteFloat (uint16_t address, float value)
void eepromWriteInt (uint16_t address, int32_t value)
float getAmplitude ()
float getCorrectedTemp ()
float getFrequency ()
uint16_t getGoogleSheetInterval ()
float getGranularity ()
bool getHeat ()
float getKD ()
float getKI ()
float getKP ()
void getMac (uint8_t *bytes)
float getMaxDataAge ()
float getPh ()
uint32_t getPhRampTimeStart ()
uint32_t getPhRampTimeEnd ()
float getRampStartingPh ()
uint32_t getPhSineStartTime ()
uint32_t getPhSinePeriod ()
float getPhSineAmplitude ()
uint32_t getRampTimeStartTemp ()
uint32_t getRampTimeEndTemp ()
float getRampStartingTemp ()
float getPhDelay ()
float getPhInterval ()
float getPhSeriesPointer ()
float getPhSeriesSize ()
uint16_t getPhSetType ()
uint16_t getTankID ()
float getTemp ()
float getTempDelay ()
float getTempInterval ()
float getTempSeriesPointer ()
float getTempSeriesSize ()
void setAmplitude (float value)
void setCorrectedTemp (float value)
void setFrequency (float value)
void setGoogleSheetInterval (uint16_t value)
void setGranularity (float value)
void setHeat (bool value)
void setKD (float value)
void setKI (float value)
void setKP (float value)
void setMac (uint8_t *bytes)
void setMaxDataAge (float value)
void setPh (float value)
void setPhRampTimeStart (uint32_t value)
void setPhRampTimeEnd (uint32_t value)
void setRampStartingPh (float value)
void setPhSineStartTime (uint32_t value)
void setPhSinePeriod (uint32_t value)
void setPhSineAmplitude (float value)
void setRampTimeStartTemp (uint32_t value)
void setRampTimeEndTemp (uint32_t value)
void setRampStartingTemp (float value)
void setPhDelay (float value)
void setPhInterval (float value)
void setPhSeriesPointer (float value)
void setPhSeriesSize (float value)
void setPhSetType (uint16_t value)
void setTankID (uint16_t value)
void setTemp (float value)
void setTempDelay (float value)
void setTempInterval (float value)
void setTempSeriesPointer (float value)
void setTempSeriesSize (float value)
void setVersion ()
Static Public Member Functions
static EEPROM_TC * instance ()
Private Attributes
const uint16_t PH_ADDRESS = 0
const uint16_t TEMP_ADDRESS = 4
const uint16_t TANK_ID_ADDRESS = 8
const uint16_t TEMP_CORR_ADDRESS = 12
const uint16_t KP_ADDRESS = 20
const uint16_t KI_ADDRESS = 28
const uint16_t KD_ADDRESS = 36
const uint16_t MAC_ADDRESS = 44
const uint16_t HEAT_ADDRESS = 52
const uint16_t AMPLITUDE_ADDRESS = 56
const uint16_t FREQUENCY_ADDRESS = 60
const uint16_t GRANULARITY_ADDRESS = 64
const uint16_t MAX_DATA_AGE_ADDRESS = 68
const uint16_t PH_SERIES_SIZE_ADDRESS = 72
const uint16_t PH_SERIES_POINTER_ADDRESS = 76
const uint16_t TEMP_SERIES_SIZE_ADDRESS = 80
const uint16_t TEMP_SERIES_POINTER_ADDRESS = 84
const uint16_t PH_INTERVAL_ADDRESS = 88
const uint16_t PH_DELAY_ADDRESS = 92
const uint16_t TEMP_INTERVAL_ADDRESS = 96
const uint16_t TEMP_DELAY_ADDRESS = 100
const uint16_t GOOGLE_INTERVAL_ADDRESS = 108
const uint16_t RAMP_STARTING_PH_ADDRESS = 112
const uint16_t RAMP_TIME_START_PH_ADDRESS = 116
const uint16_t RAMP_TIME_END_PH_ADDRESS = 120
const uint16_t PH_SINE_AMPLITUDE_ADDRESS = 112
const uint16_t PH_SINE_START_TIME_ADDRESS = 116
const uint16_t PH_SINE_PERIOD_ADDRESS = 120
const uint16_t RAMP_STARTING_TEMP_ADDRESS = 124
const uint16_t RAMP_TIME_START_TEMP_ADDRESS = 128
const uint16_t RAMP_TIME_END_TEMP_ADDRESS = 132
const uint16_t PH_SET_TYPE_ADDRESS = 136
Static Private Attributes
static EEPROM_TC * _instance = nullptr
Detailed Description
Definition at line 6 of file EEPROM_TC.h.
Member Function Documentation
eepromReadFloat()
float EEPROM_TC::eepromReadFloat (uint16_t address)
Definition at line 24 of file EEPROM_TC.cpp.
{
   assert(address >= 0);
   float value = 0.0;
   byte* p = (byte*)(void*)&value;
   for (size_t i = 0; i < sizeof(value); i++) {
     *p++ = EEPROM.read(address++);
   }
   return value;
 }
References assert, and value.
Referenced by getAmplitude(), getCorrectedTemp(), getFrequency(), getGranularity(), getHeat(), getKD(), getKI(), getKP(), getMaxDataAge(), getPh(), getPhDelay(), getPhInterval(), getPhSeriesPointer(), getPhSeriesSize(), getPhSetType(), getPhSineAmplitude(), getRampStartingPh(), getRampStartingTemp(), getTankID(), getTemp(), getTempDelay(), getTempInterval(), getTempSeriesPointer(), and getTempSeriesSize().
eepromReadInt()
int32_t EEPROM_TC::eepromReadInt (uint16_t address)
Definition at line 42 of file EEPROM_TC.cpp.
{
   assert(address >= 0);
   int32_t value = 0;
   byte* p = (byte*)(void*)&value;
   for (size_t i = 0; i < sizeof(value); i++) {
     *p++ = EEPROM.read(address++);
   }
   return value;
 }
References assert, and value.
Referenced by getGoogleSheetInterval(), getPhRampTimeEnd(), getPhRampTimeStart(), getPhSinePeriod(), getPhSineStartTime(), getRampTimeEndTemp(), and getRampTimeStartTemp().
eepromWriteFloat()
void EEPROM_TC::eepromWriteFloat (uint16_t address, float value)
Definition at line 34 of file EEPROM_TC.cpp.
{
   assert(address >= 0);
   byte* p = (byte*)(void*)&value;
   for (size_t i = 0; i < sizeof(value); i++) {
     EEPROM.update(address++, *p++);
   }
 }
References assert, and value.
Referenced by setAmplitude(), setCorrectedTemp(), setFrequency(), setGranularity(), setHeat(), setKD(), setKI(), setKP(), setMaxDataAge(), setPh(), setPhDelay(), setPhInterval(), setPhSeriesPointer(), setPhSeriesSize(), setPhSetType(), setPhSineAmplitude(), setRampStartingPh(), setRampStartingTemp(), setTankID(), setTemp(), setTempDelay(), setTempInterval(), setTempSeriesPointer(), and setTempSeriesSize().
eepromWriteInt()
void EEPROM_TC::eepromWriteInt (uint16_t address, int32_t value)
Definition at line 52 of file EEPROM_TC.cpp.
{
   assert(address >= 0);
   byte* p = (byte*)(void*)&value;
   for (size_t i = 0; i < sizeof(value); i++) {
     EEPROM.update(address++, *p++);
   }
 }
References assert, and value.
Referenced by setGoogleSheetInterval(), setPhRampTimeEnd(), setPhRampTimeStart(), setPhSinePeriod(), setPhSineStartTime(), setRampTimeEndTemp(), and setRampTimeStartTemp().
getAmplitude()
float EEPROM_TC::getAmplitude ()
Definition at line 61 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(AMPLITUDE_ADDRESS);
 }
References AMPLITUDE_ADDRESS, and eepromReadFloat().
Referenced by eeprom(), and unittest().
getCorrectedTemp()
float EEPROM_TC::getCorrectedTemp ()
Definition at line 64 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(TEMP_CORR_ADDRESS);
 }
References eepromReadFloat(), and TEMP_CORR_ADDRESS.
Referenced by eeprom(), TempProbe_TC::TempProbe_TC(), and unittest().
getFrequency()
float EEPROM_TC::getFrequency ()
Definition at line 67 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(FREQUENCY_ADDRESS);
 }
References eepromReadFloat(), and FREQUENCY_ADDRESS.
Referenced by eeprom(), and unittest().
getGoogleSheetInterval()
uint16_t EEPROM_TC::getGoogleSheetInterval ()
Definition at line 70 of file EEPROM_TC.cpp.
{
   return eepromReadInt(GOOGLE_INTERVAL_ADDRESS);
 }
References eepromReadInt(), and GOOGLE_INTERVAL_ADDRESS.
Referenced by eeprom(), SetGoogleSheetInterval::getCurrentValue(), PushingBox::loop(), and unittest().
getGranularity()
float EEPROM_TC::getGranularity ()
Definition at line 73 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(GRANULARITY_ADDRESS);
 }
References eepromReadFloat(), and GRANULARITY_ADDRESS.
Referenced by eeprom(), and unittest().
getHeat()
bool EEPROM_TC::getHeat ()
Definition at line 76 of file EEPROM_TC.cpp.
{
   return (bool)eepromReadFloat(HEAT_ADDRESS);
 }
References eepromReadFloat(), and HEAT_ADDRESS.
Referenced by eeprom(), SetChillOrHeat::getCurrentValue(), and unittest().
getKD()
float EEPROM_TC::getKD ()
Definition at line 79 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(KD_ADDRESS);
 }
References eepromReadFloat(), and KD_ADDRESS.
Referenced by eeprom(), SetKD::getCurrentValue(), and unittest().
getKI()
float EEPROM_TC::getKI ()
Definition at line 82 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(KI_ADDRESS);
 }
References eepromReadFloat(), and KI_ADDRESS.
Referenced by eeprom(), SetKI::getCurrentValue(), and unittest().
getKP()
float EEPROM_TC::getKP ()
Definition at line 85 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(KP_ADDRESS);
 }
References eepromReadFloat(), and KP_ADDRESS.
Referenced by eeprom(), SetKP::getCurrentValue(), and unittest().
getMac()
void EEPROM_TC::getMac (uint8_t * bytes)
Definition at line 88 of file EEPROM_TC.cpp.
{
   for (int i = 0; i < 6; ++i) {
     bytes[i] = EEPROM.read(MAC_ADDRESS + i);  // Flawfinder: ignore
   }
 }
References MAC_ADDRESS.
Referenced by Ethernet_TC::readMac(), and unittest().
getMaxDataAge()
float EEPROM_TC::getMaxDataAge ()
Definition at line 93 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(MAX_DATA_AGE_ADDRESS);
 }
References eepromReadFloat(), and MAX_DATA_AGE_ADDRESS.
Referenced by eeprom(), and unittest().
getPh()
float EEPROM_TC::getPh ()
Definition at line 96 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(PH_ADDRESS);
 }
References eepromReadFloat(), and PH_ADDRESS.
Referenced by eeprom(), PHControl::PHControl(), and unittest().
getPhDelay()
float EEPROM_TC::getPhDelay ()
Definition at line 99 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(PH_DELAY_ADDRESS);
 }
References eepromReadFloat(), and PH_DELAY_ADDRESS.
Referenced by eeprom(), and unittest().
getPhInterval()
float EEPROM_TC::getPhInterval ()
Definition at line 102 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(PH_INTERVAL_ADDRESS);
 }
References eepromReadFloat(), and PH_INTERVAL_ADDRESS.
Referenced by eeprom(), and unittest().
getPhRampTimeEnd()
uint32_t EEPROM_TC::getPhRampTimeEnd ()
Definition at line 114 of file EEPROM_TC.cpp.
{
   return eepromReadInt(RAMP_TIME_END_PH_ADDRESS);
 }
References eepromReadInt(), and RAMP_TIME_END_PH_ADDRESS.
Referenced by PHControl::PHControl(), and unittest().
getPhRampTimeStart()
uint32_t EEPROM_TC::getPhRampTimeStart ()
Definition at line 111 of file EEPROM_TC.cpp.
{
   return eepromReadInt(RAMP_TIME_START_PH_ADDRESS);
 }
References eepromReadInt(), and RAMP_TIME_START_PH_ADDRESS.
Referenced by PHControl::PHControl(), and unittest().
getPhSeriesPointer()
float EEPROM_TC::getPhSeriesPointer ()
Definition at line 105 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(PH_SERIES_POINTER_ADDRESS);
 }
References eepromReadFloat(), and PH_SERIES_POINTER_ADDRESS.
Referenced by eeprom(), and unittest().
getPhSeriesSize()
float EEPROM_TC::getPhSeriesSize ()
Definition at line 108 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(PH_SERIES_SIZE_ADDRESS);
 }
References eepromReadFloat(), and PH_SERIES_SIZE_ADDRESS.
Referenced by eeprom(), and unittest().
getPhSetType()
uint16_t EEPROM_TC::getPhSetType ()
Definition at line 138 of file EEPROM_TC.cpp.
{
   return static_cast<uint16_t>(eepromReadFloat(PH_SET_TYPE_ADDRESS));
 }
References eepromReadFloat(), and PH_SET_TYPE_ADDRESS.
Referenced by PHControl::PHControl(), and unittest().
getPhSineAmplitude()
float EEPROM_TC::getPhSineAmplitude ()
Definition at line 126 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(PH_SINE_PERIOD_ADDRESS);
 }
References eepromReadFloat(), and PH_SINE_PERIOD_ADDRESS.
Referenced by PHControl::PHControl(), and unittest().
getPhSinePeriod()
uint32_t EEPROM_TC::getPhSinePeriod ()
Definition at line 123 of file EEPROM_TC.cpp.
{
   return eepromReadInt(PH_SINE_AMPLITUDE_ADDRESS);
 }
References eepromReadInt(), and PH_SINE_AMPLITUDE_ADDRESS.
Referenced by PHControl::PHControl(), and unittest().
getPhSineStartTime()
uint32_t EEPROM_TC::getPhSineStartTime ()
Definition at line 120 of file EEPROM_TC.cpp.
{
   return eepromReadInt(PH_SINE_START_TIME_ADDRESS);
 }
References eepromReadInt(), and PH_SINE_START_TIME_ADDRESS.
Referenced by PHControl::PHControl(), and unittest().
getRampStartingPh()
float EEPROM_TC::getRampStartingPh ()
Definition at line 117 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(RAMP_STARTING_PH_ADDRESS);
 }
References eepromReadFloat(), and RAMP_STARTING_PH_ADDRESS.
Referenced by PHControl::PHControl(), and unittest().
getRampStartingTemp()
float EEPROM_TC::getRampStartingTemp ()
Definition at line 135 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(RAMP_STARTING_TEMP_ADDRESS);
 }
References eepromReadFloat(), and RAMP_STARTING_TEMP_ADDRESS.
Referenced by TemperatureControl::TemperatureControl(), and unittest().
getRampTimeEndTemp()
uint32_t EEPROM_TC::getRampTimeEndTemp ()
Definition at line 132 of file EEPROM_TC.cpp.
{
   return eepromReadInt(RAMP_TIME_END_TEMP_ADDRESS);
 }
References eepromReadInt(), and RAMP_TIME_END_TEMP_ADDRESS.
Referenced by TemperatureControl::TemperatureControl(), and unittest().
getRampTimeStartTemp()
uint32_t EEPROM_TC::getRampTimeStartTemp ()
Definition at line 129 of file EEPROM_TC.cpp.
{
   return eepromReadInt(RAMP_TIME_START_TEMP_ADDRESS);
 }
References eepromReadInt(), and RAMP_TIME_START_TEMP_ADDRESS.
Referenced by TemperatureControl::TemperatureControl(), and unittest().
getTankID()
uint16_t EEPROM_TC::getTankID ()
Definition at line 141 of file EEPROM_TC.cpp.
{
   return static_cast<uint16_t>(eepromReadFloat(TANK_ID_ADDRESS));
 }
References eepromReadFloat(), and TANK_ID_ADDRESS.
Referenced by eeprom(), Ethernet_TC::Ethernet_TC(), SetTankID::getCurrentValue(), PushingBox::sendData(), unittest(), and TankController::writeDataToSD().
getTemp()
float EEPROM_TC::getTemp ()
Definition at line 144 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(TEMP_ADDRESS);
 }
References eepromReadFloat(), and TEMP_ADDRESS.
Referenced by eeprom(), TemperatureControl::TemperatureControl(), and unittest().
getTempDelay()
float EEPROM_TC::getTempDelay ()
Definition at line 147 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(TEMP_DELAY_ADDRESS);
 }
References eepromReadFloat(), and TEMP_DELAY_ADDRESS.
Referenced by eeprom(), and unittest().
getTempInterval()
float EEPROM_TC::getTempInterval ()
Definition at line 150 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(TEMP_INTERVAL_ADDRESS);
 }
References eepromReadFloat(), and TEMP_INTERVAL_ADDRESS.
Referenced by eeprom(), and unittest().
getTempSeriesPointer()
float EEPROM_TC::getTempSeriesPointer ()
Definition at line 153 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(TEMP_SERIES_POINTER_ADDRESS);
 }
References eepromReadFloat(), and TEMP_SERIES_POINTER_ADDRESS.
Referenced by eeprom(), and unittest().
getTempSeriesSize()
float EEPROM_TC::getTempSeriesSize ()
Definition at line 156 of file EEPROM_TC.cpp.
{
   return eepromReadFloat(TEMP_SERIES_SIZE_ADDRESS);
 }
References eepromReadFloat(), and TEMP_SERIES_SIZE_ADDRESS.
Referenced by eeprom(), and unittest().
instance()
EEPROM_TC * EEPROM_TC::instance () static
accessor for singleton
Definition at line 14 of file EEPROM_TC.cpp.
{
   if (_instance) {
     return _instance;
   }
   _instance = new EEPROM_TC();
   Serial.println(F("EEPROM_TC"));  // Serial_TC might not be ready yet
   return _instance;
 }
References _instance.
Referenced by eeprom(), TemperatureControl::enableHeater(), Ethernet_TC::Ethernet_TC(), SetChillOrHeat::getCurrentValue(), SetGoogleSheetInterval::getCurrentValue(), SetKD::getCurrentValue(), SetKI::getCurrentValue(), SetKP::getCurrentValue(), SetTankID::getCurrentValue(), TemperatureControl::instance(), PushingBox::loop(), PHControl::PHControl(), PID_TC::PID_TC(), Ethernet_TC::readMac(), PushingBox::sendData(), TempProbe_TC::setCorrection(), PID_TC::setKd(), PID_TC::setKi(), PID_TC::setKp(), PHControl::setRampDuration(), TemperatureControl::setRampDuration(), PHControl::setSine(), PHControl::setTargetPh(), TemperatureControl::setTargetTemperature(), SetGoogleSheetInterval::setValue(), SetTankID::setValue(), SeeGoogleMins::start(), SeeTankID::start(), TankController::TankController(), TemperatureControl::TemperatureControl(), TempProbe_TC::TempProbe_TC(), unittest(), unittest_setup(), PHControl::updateControl(), and TankController::writeDataToSD().
setAmplitude()
void EEPROM_TC::setAmplitude (float value)
Definition at line 160 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(AMPLITUDE_ADDRESS, value);
 }
References AMPLITUDE_ADDRESS, eepromWriteFloat(), and value.
Referenced by unittest().
setCorrectedTemp()
void EEPROM_TC::setCorrectedTemp (float value)
Definition at line 163 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(TEMP_CORR_ADDRESS, value);
 }
References eepromWriteFloat(), TEMP_CORR_ADDRESS, and value.
Referenced by TempProbe_TC::setCorrection(), TempProbe_TC::TempProbe_TC(), and unittest().
setFrequency()
void EEPROM_TC::setFrequency (float value)
Definition at line 166 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(FREQUENCY_ADDRESS, value);
 }
References eepromWriteFloat(), FREQUENCY_ADDRESS, and value.
Referenced by unittest().
setGoogleSheetInterval()
void EEPROM_TC::setGoogleSheetInterval (uint16_t value)
Definition at line 169 of file EEPROM_TC.cpp.
{
   eepromWriteInt(GOOGLE_INTERVAL_ADDRESS, value);
 }
References eepromWriteInt(), GOOGLE_INTERVAL_ADDRESS, and value.
Referenced by SetGoogleSheetInterval::setValue(), and unittest().
setGranularity()
void EEPROM_TC::setGranularity (float value)
Definition at line 172 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(GRANULARITY_ADDRESS, value);
 }
References eepromWriteFloat(), GRANULARITY_ADDRESS, and value.
Referenced by unittest().
setHeat()
void EEPROM_TC::setHeat (bool value)
Definition at line 175 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(HEAT_ADDRESS, (float)value);
 }
References eepromWriteFloat(), HEAT_ADDRESS, and value.
Referenced by TemperatureControl::enableHeater(), and unittest().
setKD()
void EEPROM_TC::setKD (float value)
Definition at line 178 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(KD_ADDRESS, value);
 }
References eepromWriteFloat(), KD_ADDRESS, and value.
Referenced by PID_TC::setKd(), unittest(), and unittest_setup().
setKI()
void EEPROM_TC::setKI (float value)
Definition at line 181 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(KI_ADDRESS, value);
 }
References eepromWriteFloat(), KI_ADDRESS, and value.
Referenced by PID_TC::setKi(), unittest(), and unittest_setup().
setKP()
void EEPROM_TC::setKP (float value)
Definition at line 184 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(KP_ADDRESS, value);
 }
References eepromWriteFloat(), KP_ADDRESS, and value.
Referenced by PID_TC::setKp(), unittest(), and unittest_setup().
setMac()
void EEPROM_TC::setMac (uint8_t * bytes)
Definition at line 187 of file EEPROM_TC.cpp.
{
   for (int i = 0; i < 6; ++i) {
     EEPROM.update(MAC_ADDRESS + i, bytes[i]);
   }
 }
References MAC_ADDRESS.
Referenced by Ethernet_TC::readMac(), and unittest().
setMaxDataAge()
void EEPROM_TC::setMaxDataAge (float value)
Definition at line 192 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(MAX_DATA_AGE_ADDRESS, value);
 }
References eepromWriteFloat(), MAX_DATA_AGE_ADDRESS, and value.
Referenced by unittest().
setPh()
void EEPROM_TC::setPh (float value)
Definition at line 195 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(PH_ADDRESS, value);
 }
References eepromWriteFloat(), PH_ADDRESS, and value.
Referenced by PHControl::PHControl(), PHControl::setTargetPh(), unittest(), and unittest_setup().
setPhDelay()
void EEPROM_TC::setPhDelay (float value)
Definition at line 198 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(PH_DELAY_ADDRESS, value);
 }
References eepromWriteFloat(), PH_DELAY_ADDRESS, and value.
Referenced by unittest().
setPhInterval()
void EEPROM_TC::setPhInterval (float value)
Definition at line 201 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(PH_INTERVAL_ADDRESS, value);
 }
References eepromWriteFloat(), PH_INTERVAL_ADDRESS, and value.
Referenced by unittest().
setPhRampTimeEnd()
void EEPROM_TC::setPhRampTimeEnd (uint32_t value)
Definition at line 213 of file EEPROM_TC.cpp.
{
   eepromWriteInt(RAMP_TIME_END_PH_ADDRESS, value);
 }
References eepromWriteInt(), RAMP_TIME_END_PH_ADDRESS, and value.
Referenced by PHControl::PHControl(), PHControl::setRampDuration(), and unittest().
setPhRampTimeStart()
void EEPROM_TC::setPhRampTimeStart (uint32_t value)
Definition at line 210 of file EEPROM_TC.cpp.
{
   eepromWriteInt(RAMP_TIME_START_PH_ADDRESS, value);
 }
References eepromWriteInt(), RAMP_TIME_START_PH_ADDRESS, and value.
Referenced by PHControl::PHControl(), PHControl::setRampDuration(), and unittest().
setPhSeriesPointer()
void EEPROM_TC::setPhSeriesPointer (float value)
Definition at line 204 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(PH_SERIES_POINTER_ADDRESS, value);
 }
References eepromWriteFloat(), PH_SERIES_POINTER_ADDRESS, and value.
Referenced by unittest().
setPhSeriesSize()
void EEPROM_TC::setPhSeriesSize (float value)
Definition at line 207 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(PH_SERIES_SIZE_ADDRESS, value);
 }
References eepromWriteFloat(), PH_SERIES_SIZE_ADDRESS, and value.
Referenced by unittest().
setPhSetType()
void EEPROM_TC::setPhSetType (uint16_t value)
Definition at line 237 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(PH_SET_TYPE_ADDRESS, (float)value);
 }
References eepromWriteFloat(), PH_SET_TYPE_ADDRESS, and value.
Referenced by PHControl::PHControl(), PHControl::setRampDuration(), PHControl::setSine(), and unittest().
setPhSineAmplitude()
void EEPROM_TC::setPhSineAmplitude (float value)
Definition at line 225 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(PH_SINE_PERIOD_ADDRESS, value);
 }
References eepromWriteFloat(), PH_SINE_PERIOD_ADDRESS, and value.
Referenced by PHControl::setSine(), and unittest().
setPhSinePeriod()
void EEPROM_TC::setPhSinePeriod (uint32_t value)
Definition at line 222 of file EEPROM_TC.cpp.
{
   eepromWriteInt(PH_SINE_AMPLITUDE_ADDRESS, value);
 }
References eepromWriteInt(), PH_SINE_AMPLITUDE_ADDRESS, and value.
Referenced by PHControl::setSine(), and unittest().
setPhSineStartTime()
void EEPROM_TC::setPhSineStartTime (uint32_t value)
Definition at line 219 of file EEPROM_TC.cpp.
{
   eepromWriteInt(PH_SINE_START_TIME_ADDRESS, value);
 }
References eepromWriteInt(), PH_SINE_START_TIME_ADDRESS, and value.
Referenced by PHControl::setSine(), unittest(), and PHControl::updateControl().
setRampStartingPh()
void EEPROM_TC::setRampStartingPh (float value)
Definition at line 216 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(RAMP_STARTING_PH_ADDRESS, value);
 }
References eepromWriteFloat(), RAMP_STARTING_PH_ADDRESS, and value.
Referenced by PHControl::setRampDuration(), and unittest().
setRampStartingTemp()
void EEPROM_TC::setRampStartingTemp (float value)
Definition at line 234 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(RAMP_STARTING_TEMP_ADDRESS, value);
 }
References eepromWriteFloat(), RAMP_STARTING_TEMP_ADDRESS, and value.
Referenced by TemperatureControl::setRampDuration(), and unittest().
setRampTimeEndTemp()
void EEPROM_TC::setRampTimeEndTemp (uint32_t value)
Definition at line 231 of file EEPROM_TC.cpp.
{
   eepromWriteInt(RAMP_TIME_END_TEMP_ADDRESS, value);
 }
References eepromWriteInt(), RAMP_TIME_END_TEMP_ADDRESS, and value.
Referenced by TemperatureControl::setRampDuration(), TemperatureControl::TemperatureControl(), and unittest().
setRampTimeStartTemp()
void EEPROM_TC::setRampTimeStartTemp (uint32_t value)
Definition at line 228 of file EEPROM_TC.cpp.
{
   eepromWriteInt(RAMP_TIME_START_TEMP_ADDRESS, value);
 }
References eepromWriteInt(), RAMP_TIME_START_TEMP_ADDRESS, and value.
Referenced by TemperatureControl::setRampDuration(), TemperatureControl::TemperatureControl(), and unittest().
setTankID()
void EEPROM_TC::setTankID (uint16_t value)
Definition at line 240 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(TANK_ID_ADDRESS, (float)value);
 }
References eepromWriteFloat(), TANK_ID_ADDRESS, and value.
Referenced by SetTankID::setValue(), unittest(), and unittest_setup().
setTemp()
void EEPROM_TC::setTemp (float value)
Definition at line 243 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(TEMP_ADDRESS, value);
 }
References eepromWriteFloat(), TEMP_ADDRESS, and value.
Referenced by TemperatureControl::setTargetTemperature(), TemperatureControl::TemperatureControl(), and unittest().
setTempDelay()
void EEPROM_TC::setTempDelay (float value)
Definition at line 246 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(TEMP_DELAY_ADDRESS, value);
 }
References eepromWriteFloat(), TEMP_DELAY_ADDRESS, and value.
Referenced by unittest().
setTempInterval()
void EEPROM_TC::setTempInterval (float value)
Definition at line 249 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(TEMP_INTERVAL_ADDRESS, value);
 }
References eepromWriteFloat(), TEMP_INTERVAL_ADDRESS, and value.
Referenced by unittest().
setTempSeriesPointer()
void EEPROM_TC::setTempSeriesPointer (float value)
Definition at line 252 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(TEMP_SERIES_POINTER_ADDRESS, value);
 }
References eepromWriteFloat(), TEMP_SERIES_POINTER_ADDRESS, and value.
Referenced by unittest().
setTempSeriesSize()
void EEPROM_TC::setTempSeriesSize (float value)
Definition at line 255 of file EEPROM_TC.cpp.
{
   eepromWriteFloat(TEMP_SERIES_SIZE_ADDRESS, value);
 }
References eepromWriteFloat(), TEMP_SERIES_SIZE_ADDRESS, and value.
Referenced by unittest().
setVersion()
void EEPROM_TC::setVersion () inline
Definition at line 83 of file EEPROM_TC.h.
                     {  // Nothing to be done here!
   }
Member Data Documentation
_instance
EEPROM_TC * EEPROM_TC::_instance = nullptr static private
Definition at line 124 of file EEPROM_TC.h.
Referenced by instance().
AMPLITUDE_ADDRESS
const uint16_t EEPROM_TC::AMPLITUDE_ADDRESS = 56 private
Definition at line 98 of file EEPROM_TC.h.
Referenced by getAmplitude(), and setAmplitude().
FREQUENCY_ADDRESS
const uint16_t EEPROM_TC::FREQUENCY_ADDRESS = 60 private
Definition at line 99 of file EEPROM_TC.h.
Referenced by getFrequency(), and setFrequency().
GOOGLE_INTERVAL_ADDRESS
const uint16_t EEPROM_TC::GOOGLE_INTERVAL_ADDRESS = 108 private
Definition at line 111 of file EEPROM_TC.h.
Referenced by getGoogleSheetInterval(), and setGoogleSheetInterval().
GRANULARITY_ADDRESS
const uint16_t EEPROM_TC::GRANULARITY_ADDRESS = 64 private
Definition at line 100 of file EEPROM_TC.h.
Referenced by getGranularity(), and setGranularity().
HEAT_ADDRESS
const uint16_t EEPROM_TC::HEAT_ADDRESS = 52 private
Definition at line 96 of file EEPROM_TC.h.
Referenced by getHeat(), and setHeat().
KD_ADDRESS
const uint16_t EEPROM_TC::KD_ADDRESS = 36 private
Definition at line 94 of file EEPROM_TC.h.
Referenced by getKD(), and setKD().
KI_ADDRESS
const uint16_t EEPROM_TC::KI_ADDRESS = 28 private
Definition at line 93 of file EEPROM_TC.h.
Referenced by getKI(), and setKI().
KP_ADDRESS
const uint16_t EEPROM_TC::KP_ADDRESS = 20 private
Definition at line 92 of file EEPROM_TC.h.
Referenced by getKP(), and setKP().
MAC_ADDRESS
const uint16_t EEPROM_TC::MAC_ADDRESS = 44 private
Definition at line 95 of file EEPROM_TC.h.
Referenced by getMac(), and setMac().
MAX_DATA_AGE_ADDRESS
const uint16_t EEPROM_TC::MAX_DATA_AGE_ADDRESS = 68 private
Definition at line 101 of file EEPROM_TC.h.
Referenced by getMaxDataAge(), and setMaxDataAge().
PH_ADDRESS
const uint16_t EEPROM_TC::PH_ADDRESS = 0 private
Definition at line 88 of file EEPROM_TC.h.
Referenced by getPh(), and setPh().
PH_DELAY_ADDRESS
const uint16_t EEPROM_TC::PH_DELAY_ADDRESS = 92 private
Definition at line 107 of file EEPROM_TC.h.
Referenced by getPhDelay(), and setPhDelay().
PH_INTERVAL_ADDRESS
const uint16_t EEPROM_TC::PH_INTERVAL_ADDRESS = 88 private
Definition at line 106 of file EEPROM_TC.h.
Referenced by getPhInterval(), and setPhInterval().
PH_SERIES_POINTER_ADDRESS
const uint16_t EEPROM_TC::PH_SERIES_POINTER_ADDRESS = 76 private
Definition at line 103 of file EEPROM_TC.h.
Referenced by getPhSeriesPointer(), and setPhSeriesPointer().
PH_SERIES_SIZE_ADDRESS
const uint16_t EEPROM_TC::PH_SERIES_SIZE_ADDRESS = 72 private
Definition at line 102 of file EEPROM_TC.h.
Referenced by getPhSeriesSize(), and setPhSeriesSize().
PH_SET_TYPE_ADDRESS
const uint16_t EEPROM_TC::PH_SET_TYPE_ADDRESS = 136 private
Definition at line 121 of file EEPROM_TC.h.
Referenced by getPhSetType(), and setPhSetType().
PH_SINE_AMPLITUDE_ADDRESS
const uint16_t EEPROM_TC::PH_SINE_AMPLITUDE_ADDRESS = 112 private
Definition at line 115 of file EEPROM_TC.h.
Referenced by getPhSinePeriod(), and setPhSinePeriod().
PH_SINE_PERIOD_ADDRESS
const uint16_t EEPROM_TC::PH_SINE_PERIOD_ADDRESS = 120 private
Definition at line 117 of file EEPROM_TC.h.
Referenced by getPhSineAmplitude(), and setPhSineAmplitude().
PH_SINE_START_TIME_ADDRESS
const uint16_t EEPROM_TC::PH_SINE_START_TIME_ADDRESS = 116 private
Definition at line 116 of file EEPROM_TC.h.
Referenced by getPhSineStartTime(), and setPhSineStartTime().
RAMP_STARTING_PH_ADDRESS
const uint16_t EEPROM_TC::RAMP_STARTING_PH_ADDRESS = 112 private
Definition at line 112 of file EEPROM_TC.h.
Referenced by getRampStartingPh(), and setRampStartingPh().
RAMP_STARTING_TEMP_ADDRESS
const uint16_t EEPROM_TC::RAMP_STARTING_TEMP_ADDRESS = 124 private
Definition at line 118 of file EEPROM_TC.h.
Referenced by getRampStartingTemp(), and setRampStartingTemp().
RAMP_TIME_END_PH_ADDRESS
const uint16_t EEPROM_TC::RAMP_TIME_END_PH_ADDRESS = 120 private
Definition at line 114 of file EEPROM_TC.h.
Referenced by getPhRampTimeEnd(), and setPhRampTimeEnd().
RAMP_TIME_END_TEMP_ADDRESS
const uint16_t EEPROM_TC::RAMP_TIME_END_TEMP_ADDRESS = 132 private
Definition at line 120 of file EEPROM_TC.h.
Referenced by getRampTimeEndTemp(), and setRampTimeEndTemp().
RAMP_TIME_START_PH_ADDRESS
const uint16_t EEPROM_TC::RAMP_TIME_START_PH_ADDRESS = 116 private
Definition at line 113 of file EEPROM_TC.h.
Referenced by getPhRampTimeStart(), and setPhRampTimeStart().
RAMP_TIME_START_TEMP_ADDRESS
const uint16_t EEPROM_TC::RAMP_TIME_START_TEMP_ADDRESS = 128 private
Definition at line 119 of file EEPROM_TC.h.
Referenced by getRampTimeStartTemp(), and setRampTimeStartTemp().
TANK_ID_ADDRESS
const uint16_t EEPROM_TC::TANK_ID_ADDRESS = 8 private
Definition at line 90 of file EEPROM_TC.h.
Referenced by getTankID(), and setTankID().
TEMP_ADDRESS
const uint16_t EEPROM_TC::TEMP_ADDRESS = 4 private
Definition at line 89 of file EEPROM_TC.h.
Referenced by getTemp(), and setTemp().
TEMP_CORR_ADDRESS
const uint16_t EEPROM_TC::TEMP_CORR_ADDRESS = 12 private
Definition at line 91 of file EEPROM_TC.h.
Referenced by getCorrectedTemp(), and setCorrectedTemp().
TEMP_DELAY_ADDRESS
const uint16_t EEPROM_TC::TEMP_DELAY_ADDRESS = 100 private
Definition at line 109 of file EEPROM_TC.h.
Referenced by getTempDelay(), and setTempDelay().
TEMP_INTERVAL_ADDRESS
const uint16_t EEPROM_TC::TEMP_INTERVAL_ADDRESS = 96 private
Definition at line 108 of file EEPROM_TC.h.
Referenced by getTempInterval(), and setTempInterval().
TEMP_SERIES_POINTER_ADDRESS
const uint16_t EEPROM_TC::TEMP_SERIES_POINTER_ADDRESS = 84 private
Definition at line 105 of file EEPROM_TC.h.
Referenced by getTempSeriesPointer(), and setTempSeriesPointer().
TEMP_SERIES_SIZE_ADDRESS
const uint16_t EEPROM_TC::TEMP_SERIES_SIZE_ADDRESS = 80 private
Definition at line 104 of file EEPROM_TC.h.
Referenced by getTempSeriesSize(), and setTempSeriesSize().
The documentation for this class was generated from the following files:
src/Devices/EEPROM_TC.h
src/Devices/EEPROM_TC.cpp