Tank Controller Lib: DateTime_TC Class Reference
DateTime_TC Class Reference
#include <DateTime_TC.h>
Public Member Functions
DateTime_TC (uint16_t year, uint8_t month, uint8_t day, uint8_t hour=0, uint8_t min=0, uint8_t sec=0)
char * as16CharacterString ()
void printToSerial ()
void yearMonthAsPath (char *buffer, size_t size)
void setAsCurrent ()
Static Public Member Functions
static DateTime_TC now ()
static RTC_PCF8523 * rtc ()
Static Private Attributes
static RTC_PCF8523 * _rtc = nullptr
Detailed Description
year range: 2000 - 2099
Definition at line 11 of file DateTime_TC.h.
Constructor & Destructor Documentation
DateTime_TC()
DateTime_TC::DateTime_TC (uint16_t year, uint8_t month, uint8_t day, uint8_t hour = 0, uint8_t min = 0, uint8_t sec = 0)
Constructor
Definition at line 40 of file DateTime_TC.cpp.
    : DateTime(year, month, day, hour, min, sec) {
}
Referenced by now().
Member Function Documentation
as16CharacterString()
char * DateTime_TC::as16CharacterString ()
Definition at line 49 of file DateTime_TC.cpp.
{
  strncpy_P(buffer, (PGM_P)F("YYYY-MM-DD hh:mm"), sizeof(buffer));
  this->toString(buffer);
  return buffer;
}
References buffer.
Referenced by dateTime(), and SetTime::setValue().
now()
DateTime_TC DateTime_TC::now () static
Definition at line 31 of file DateTime_TC.cpp.
{
  DateTime now = rtc()->now();
  return DateTime_TC(now.year(), now.month(), now.day(), now.hour(), now.minute(), now.second());
}
References DateTime_TC(), now(), and rtc().
Referenced by SD_TC::appendToLog(), dateTime(), SetTime::getCurrentValue(), SeeDeviceUptime::loop(), now(), printToSerial(), PHControl::setRampDuration(), TemperatureControl::setRampDuration(), PHControl::setSine(), SetTime::setValue(), SD_TC::todaysDataFileName(), unittest(), Heater::updateControl(), Chiller::updateControl(), PHControl::updateControl(), TankController::writeDataToSD(), and TankController::writeDataToSerial().
printToSerial()
void DateTime_TC::printToSerial ()
Definition at line 55 of file DateTime_TC.cpp.
{
  char buffer[20];
  strncpy_P(buffer, (PGM_P)F("YYYY-MM-DD hh:mm:ss"), sizeof(buffer));
  DateTime_TC now = DateTime_TC::now();
  now.toString(buffer);
  serial(F("%s"), buffer);
}
References buffer, now(), and serial().
Referenced by unittest().
rtc()
RTC_PCF8523 * DateTime_TC::rtc () static
Definition at line 11 of file DateTime_TC.cpp.
{
  if (_rtc == nullptr) {
    _rtc = new RTC_PCF8523;
    // look for Real Time Clock
    if (!_rtc->begin()) {
      serial(F("Couldn't find RTC!"));
      while (true)
        ;  // infinite loop; hang forever
    }
    // has the time been set?
    if (!_rtc->initialized()) {
      serial(F("RTC has not been initialized! Date and time is wrong!"));
      // set the RTC to the date & time this file was compiled
      _rtc->adjust(DateTime(__DATE__, __TIME__));
    }
  }
  return _rtc;
}
References _rtc, and serial().
Referenced by now(), setAsCurrent(), TankController::TankController(), and unittest().
setAsCurrent()
void DateTime_TC::setAsCurrent ()
Definition at line 81 of file DateTime_TC.cpp.
{
  DateTime newDT(yOff + 2000, m, d, hh, mm, ss);
  rtc()->adjust(newDT);
}
References rtc().
Referenced by reset(), setTime(), SetTime::setValue(), unittest(), and unittest_setup().
yearMonthAsPath()
void DateTime_TC::yearMonthAsPath (char * buffer, size_t sizeOfBuffer)
populate a buffer with dateTime as a path: "/2020/09"
Definition at line 66 of file DateTime_TC.cpp.
{
  memset(buffer, 0, sizeOfBuffer);
  if (sizeOfBuffer < 9) {  // is there enough room?
    return;
  }
  buffer[0] = '/';
  itoa(year(), buffer + 1, 10);
  buffer[5] = '/';
  uint16_t i = 6;
  if (month() < 10) {
    buffer[i++] = '0';
  }
  itoa(month(), buffer + i, 10);
}
References buffer.
Referenced by unittest().
Member Data Documentation
_rtc
RTC_PCF8523 * DateTime_TC::_rtc = nullptr static private
Definition at line 27 of file DateTime_TC.h.
Referenced by rtc().
The documentation for this class was generated from the following files:
src/Devices/DateTime_TC.h
src/Devices/DateTime_TC.cpp