Tank Controller Lib: MainMenu Class Reference
MainMenu Class Reference
#include <MainMenu.h>
Public Types
enum ViewCommands {
VIEW_TIME , VIEW_PID , VIEW_PH_SLOPE , VIEW_TANK_ID ,
VIEW_LOG_FILE , VIEW_GOOGLE_MINS , VIEW_ADDRESS , VIEW_VERSION ,
VIEW_FREE_MEMORY , VIEW_COMMAND_COUNT
}
enum SetCommands {
SET_PH , SET_TEMPERATURE , SET_CALIBRATION , SET_CALIBRATION_CLEAR ,
SET_TEMP_CALIBRATION , SET_KP , SET_KI , SET_KD ,
SET_PID_ON_OFF , SET_CHILL_OR_HEAT , SET_GOOGLE_MINS , SET_TIME ,
SET_TANK_ID , SET_PH_WITH_SINE , SET_COMMAND_COUNT
}
Public Member Functions
MainMenu (TankController *tc)
void handleKey (char key)
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
bool isMainMenu ()
void loop ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Private Member Functions
void left ()
void right ()
void up ()
void down ()
void selectView ()
void selectSet ()
void idle ()
Private Attributes
int16_t level1 = 0
int16_t level2 = -1
const __FlashStringHelper * viewMenus [VIEW_COMMAND_COUNT]
const __FlashStringHelper * setMenus [SET_COMMAND_COUNT]
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
Definition at line 13 of file MainMenu.h.
Member Enumeration Documentation
SetCommands
enum MainMenu::SetCommands
Enumerator
SET_PH
SET_TEMPERATURE
SET_CALIBRATION
SET_CALIBRATION_CLEAR
SET_TEMP_CALIBRATION
SET_KP
SET_KI
SET_KD
SET_PID_ON_OFF
SET_CHILL_OR_HEAT
SET_GOOGLE_MINS
SET_TIME
SET_TANK_ID
SET_PH_WITH_SINE
SET_COMMAND_COUNT
Definition at line 27 of file MainMenu.h.
                   {  // this order affects tests
    SET_PH,
    SET_TEMPERATURE,
    SET_CALIBRATION,
    SET_CALIBRATION_CLEAR,
    SET_TEMP_CALIBRATION,
    SET_KP,
    SET_KI,
    SET_KD,
    SET_PID_ON_OFF,
    SET_CHILL_OR_HEAT,
    SET_GOOGLE_MINS,
    SET_TIME,
    SET_TANK_ID,
    SET_PH_WITH_SINE,
    SET_COMMAND_COUNT  // always last
  };
ViewCommands
enum MainMenu::ViewCommands
Enumerator
VIEW_TIME
VIEW_PID
VIEW_PH_SLOPE
VIEW_TANK_ID
VIEW_LOG_FILE
VIEW_GOOGLE_MINS
VIEW_ADDRESS
VIEW_VERSION
VIEW_FREE_MEMORY
VIEW_COMMAND_COUNT
Definition at line 15 of file MainMenu.h.
                    {  // this order affects tests
    VIEW_TIME,
    VIEW_PID,
    VIEW_PH_SLOPE,
    VIEW_TANK_ID,
    VIEW_LOG_FILE,
    VIEW_GOOGLE_MINS,
    VIEW_ADDRESS,
    VIEW_VERSION,
    VIEW_FREE_MEMORY,
    VIEW_COMMAND_COUNT  // always last
  };
Constructor & Destructor Documentation
MainMenu()
MainMenu::MainMenu (TankController * tc)
Definition at line 33 of file MainMenu.cpp.
                                     : UIState(tc) {
  viewMenus[VIEW_GOOGLE_MINS] = F("View Google mins");
  viewMenus[VIEW_ADDRESS] = F("View IP and MAC");
  viewMenus[VIEW_FREE_MEMORY] = F("View free memory");
  viewMenus[VIEW_LOG_FILE] = F("View log file");
  viewMenus[VIEW_PID] = F("View PID");
  viewMenus[VIEW_PH_SLOPE] = F("View pH slope");
  viewMenus[VIEW_TANK_ID] = F("View tank ID");
  viewMenus[VIEW_TIME] = F("View time");
  viewMenus[VIEW_VERSION] = F("View version");
  setMenus[SET_CALIBRATION] = F("pH calibration");
  setMenus[SET_CALIBRATION_CLEAR] = F("Clear pH calibra");
  setMenus[SET_CHILL_OR_HEAT] = F("Set chill/heat");
  setMenus[SET_GOOGLE_MINS] = F("Set Google mins");
  setMenus[SET_PH] = F("Set pH target");
  setMenus[SET_KD] = F("Set KD");
  setMenus[SET_KI] = F("Set KI");
  setMenus[SET_KP] = F("Set KP");
  setMenus[SET_PID_ON_OFF] = F("PID on/off");
  setMenus[SET_TANK_ID] = F("Set Tank ID");
  setMenus[SET_TEMP_CALIBRATION] = F("Temp calibration");
  setMenus[SET_TEMPERATURE] = F("Set temperature");
  setMenus[SET_TIME] = F("Set date/time");
  setMenus[SET_PH_WITH_SINE] = F("Set pH w sine");
}
References SET_CALIBRATION, SET_CALIBRATION_CLEAR, SET_CHILL_OR_HEAT, SET_GOOGLE_MINS, SET_KD, SET_KI, SET_KP, SET_PH, SET_PH_WITH_SINE, SET_PID_ON_OFF, SET_TANK_ID, SET_TEMP_CALIBRATION, SET_TEMPERATURE, SET_TIME, setMenus, VIEW_ADDRESS, VIEW_FREE_MEMORY, VIEW_GOOGLE_MINS, VIEW_LOG_FILE, VIEW_PH_SLOPE, VIEW_PID, VIEW_TANK_ID, VIEW_TIME, VIEW_VERSION, and viewMenus.
Member Function Documentation
down()
void MainMenu::down () private
Definition at line 126 of file MainMenu.cpp.
                    {
  if (level2 == -1) {
    level1 = (level1 + 1) % 3;
  } else {
    if (level1 == 1) {
      level2 = (level2 + 1) % VIEW_COMMAND_COUNT;
    } else {
      level2 = (level2 + 1) % SET_COMMAND_COUNT;
    }
  }
}
References level1, level2, SET_COMMAND_COUNT, and VIEW_COMMAND_COUNT.
Referenced by handleKey().
handleKey()
void MainMenu::handleKey (char key) virtual
Branch to other states to handle various menu options
Reimplemented from UIState.
Definition at line 63 of file MainMenu.cpp.
{
  switch (key) {
    case 'A':  // Set pH set_point
      this->setNextState(static_cast<UIState *>(new SetPHSetPoint(tc)));
      break;
    case 'B':  // Set Temperature set_point
      this->setNextState(static_cast<UIState *>(new SetTempSetPoint(tc)));
      break;
    case 'D':  // Reset
      level1 = 0;
      level2 = -1;
      break;
    case '2':  // up
      up();
      break;
    case '4':  // left
      left();
      break;
    case '6':  // right
      right();
      break;
    case '8':  // down
      down();
      break;
    default:
      // ignore invalid keys
      break;
  }
}
References down(), key(), left(), level1, level2, right(), UIState::setNextState(), UIState::tc, and up().
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
idle()
void MainMenu::idle () private
Definition at line 223 of file MainMenu.cpp.
                    {
  PHControl *phControl = PHControl::instance();
  char output[17];
  output[0] = 'p';
  output[1] = 'H';
  output[2] = millis() / 1000 % 2 ? '=' : ' ';
  dtostrf(PHProbe::instance()->getPh(), 5, 3, output + 3);
  output[8] = ' ';
  output[9] = phControl->isOn() ? 'B' : ' ';
  output[10] = ' ';
  dtostrf(PHControl::instance()->getTargetPh(), 5, 3, output + 11);
  LiquidCrystal_TC::instance()->writeLine(output, 0);
  TemperatureControl *tempControl = TemperatureControl::instance();
  TempProbe_TC *tempProbe = TempProbe_TC::instance();
  float temp = tempProbe->getRunningAverage();
  if (temp < 0.0) {
    temp = 0.0;
  } else if (99.99 < temp) {
    temp = 99.99;
  }
  char status = tempControl->isHeater() ? 'h' : 'c';
  if (tempControl->isOn()) {
    status = toupper(status);
  }
  output[0] = 'T';
  output[1] = millis() / 1000 % 2 ? '=' : ' ';
  dtostrf(temp, 5, 2, output + 2);
  output[7] = ' ';
  output[8] = status;
  output[9] = ' ';
  dtostrf(tempControl->getTargetTemperature(), 5, 2, output + 10);
  LiquidCrystal_TC::instance()->writeLine(output, 1);
}
References TempProbe_TC::getRunningAverage(), TemperatureControl::getTargetTemperature(), PHControl::instance(), PHProbe::instance(), TemperatureControl::instance(), TempProbe_TC::instance(), LiquidCrystal_TC::instance(), TemperatureControl::isHeater(), PHControl::isOn(), TemperatureControl::isOn(), tempControl, tempProbe, and LiquidCrystal_TC::writeLine().
Referenced by loop().
isMainMenu()
bool MainMenu::isMainMenu () inline virtual
Reimplemented from UIState.
Definition at line 52 of file MainMenu.h.
                    {
    return true;
  }
left()
void MainMenu::left () private
Definition at line 93 of file MainMenu.cpp.
                    {
  if (level2 == -1) {
    level1 = 0;
  } else {
    level2 = -1;
  }
}
References level1, and level2.
Referenced by handleKey().
loop()
void MainMenu::loop () virtual
Reimplemented from UIState.
Definition at line 257 of file MainMenu.cpp.
                    {
  if (level1 == 0) {
    idle();
  } else {
    if (level1 == 1) {
      if (level2 == -1) {
        LiquidCrystal_TC::instance()->writeLine(F("View settings"), 0);
      } else {
        LiquidCrystal_TC::instance()->writeLine(viewMenus[level2], 0);
      }
    } else {
      if (level2 == -1) {
        LiquidCrystal_TC::instance()->writeLine(F("Change settings"), 0);
      } else {
        LiquidCrystal_TC::instance()->writeLine(setMenus[level2], 0);
      }
    }
    LiquidCrystal_TC::instance()->writeLine(F("<4   ^2  8v   6>"), 1);
  }
}
References idle(), LiquidCrystal_TC::instance(), level1, level2, setMenus, viewMenus, and LiquidCrystal_TC::writeLine().
name()
const __FlashStringHelper * MainMenu::name () inline virtual
Implements UIState.
Definition at line 46 of file MainMenu.h.
{
    return F("MainMenu");
  }
prompt()
const __FlashStringHelper * MainMenu::prompt () inline virtual
Reimplemented from UIState.
Definition at line 49 of file MainMenu.h.
{
    return F("Main Menu");
  };
right()
void MainMenu::right () private
Definition at line 101 of file MainMenu.cpp.
                     {
  if (level1 == 0) {
    level1 = 1;
    level2 = -1;
  } else if (level2 == -1) {
    level2 = 0;
  } else if (level1 == 1) {
    selectView();
  } else {
    selectSet();
  }
}
References level1, level2, selectSet(), and selectView().
Referenced by handleKey().
selectSet()
void MainMenu::selectSet () private
Definition at line 172 of file MainMenu.cpp.
{
  switch (level2) {
    case SET_CALIBRATION:
      this->setNextState(static_cast<UIState *>(new PHCalibrationMid(tc)));
      break;
    case SET_CALIBRATION_CLEAR:
      this->setNextState(static_cast<UIState *>(new SetCalibrationClear(tc)));
      break;
    case SET_CHILL_OR_HEAT:
      this->setNextState(static_cast<UIState *>(new SetChillOrHeat(tc)));
      break;
    case SET_GOOGLE_MINS:
      this->setNextState(static_cast<UIState *>(new SetGoogleSheetInterval(tc)));
      break;
    case SET_PH:
      this->setNextState(static_cast<UIState *>(new SetPHSetPoint(tc)));
      break;
    case SET_KD:
      this->setNextState(static_cast<UIState *>(new SetKD(tc)));
      break;
    case SET_KI:
      this->setNextState(static_cast<UIState *>(new SetKI(tc)));
      break;
    case SET_KP:
      this->setNextState(static_cast<UIState *>(new SetKP(tc)));
      break;
    case SET_PID_ON_OFF:
      this->setNextState(static_cast<UIState *>(new EnablePID(tc)));
      break;
    case SET_TANK_ID:
      this->setNextState(static_cast<UIState *>(new SetTankID(tc)));
      break;
    case SET_TEMP_CALIBRATION:
      this->setNextState(static_cast<UIState *>(new TemperatureCalibration(tc)));
      break;
    case SET_TEMPERATURE:
      this->setNextState(static_cast<UIState *>(new SetTempSetPoint(tc)));
      break;
    case SET_PH_WITH_SINE:
      this->setNextState(static_cast<UIState *>(new SetPHWithSine(tc)));
      break;
    case SET_TIME:
      this->setNextState(static_cast<UIState *>(new SetTime(tc)));
      break;
    default:
      break;
  }
}
References level2, SET_CALIBRATION, SET_CALIBRATION_CLEAR, SET_CHILL_OR_HEAT, SET_GOOGLE_MINS, SET_KD, SET_KI, SET_KP, SET_PH, SET_PH_WITH_SINE, SET_PID_ON_OFF, SET_TANK_ID, SET_TEMP_CALIBRATION, SET_TEMPERATURE, SET_TIME, UIState::setNextState(), and UIState::tc.
Referenced by right().
selectView()
void MainMenu::selectView () private
Definition at line 138 of file MainMenu.cpp.
{
  switch (level2) {
    case VIEW_GOOGLE_MINS:
      this->setNextState(static_cast<UIState *>(new SeeGoogleMins(tc)));
      break;
    case VIEW_ADDRESS:
      this->setNextState(static_cast<UIState *>(new SeeDeviceAddress(tc)));
      break;
    case VIEW_FREE_MEMORY:
      this->setNextState(static_cast<UIState *>(new SeeFreeMemory(tc)));
      break;
    case VIEW_LOG_FILE:
      this->setNextState(static_cast<UIState *>(new SeeLogFile(tc)));
      break;
    case VIEW_PID:
      this->setNextState(static_cast<UIState *>(new SeePIDConstants(tc)));
      break;
    case VIEW_PH_SLOPE:
      this->setNextState(static_cast<UIState *>(new SeePHSlope(tc)));
      break;
    case VIEW_TANK_ID:
      this->setNextState(static_cast<UIState *>(new SeeTankID(tc)));
      break;
    case VIEW_TIME:
      this->setNextState(static_cast<UIState *>(new SeeDeviceUptime(tc)));
      break;
    case VIEW_VERSION:
      this->setNextState(static_cast<UIState *>(new SeeVersion(tc)));
      break;
    default:
      break;
  }
}
References level2, UIState::setNextState(), UIState::tc, VIEW_ADDRESS, VIEW_FREE_MEMORY, VIEW_GOOGLE_MINS, VIEW_LOG_FILE, VIEW_PH_SLOPE, VIEW_PID, VIEW_TANK_ID, VIEW_TIME, and VIEW_VERSION.
Referenced by right().
up()
void MainMenu::up () private
Definition at line 114 of file MainMenu.cpp.
                  {
  if (level2 == -1) {
    level1 = (level1 + 2) % 3;
  } else {
    if (level1 == 1) {
      level2 = (level2 + VIEW_COMMAND_COUNT - 1) % VIEW_COMMAND_COUNT;
    } else {
      level2 = (level2 + SET_COMMAND_COUNT - 1) % SET_COMMAND_COUNT;
    }
  }
}
References level1, level2, SET_COMMAND_COUNT, and VIEW_COMMAND_COUNT.
Referenced by handleKey().
Member Data Documentation
level1
int16_t MainMenu::level1 = 0 private
Definition at line 58 of file MainMenu.h.
Referenced by down(), handleKey(), left(), loop(), right(), and up().
level2
int16_t MainMenu::level2 = -1 private
Definition at line 59 of file MainMenu.h.
Referenced by down(), handleKey(), left(), loop(), right(), selectSet(), selectView(), and up().
setMenus
const __FlashStringHelper* MainMenu::setMenus[SET_COMMAND_COUNT] private
Definition at line 61 of file MainMenu.h.
Referenced by loop(), and MainMenu().
viewMenus
const __FlashStringHelper* MainMenu::viewMenus[VIEW_COMMAND_COUNT] private
Definition at line 60 of file MainMenu.h.
Referenced by loop(), and MainMenu().
The documentation for this class was generated from the following files:
src/UIState/MainMenu.h
src/UIState/MainMenu.cpp