Tank Controller Lib: TankControllerLib Class Reference
TankControllerLib Class Reference
#include <TankControllerLib.h>
Public Member Functions
bool isInCalibration ()
int freeMemory ()
void loop ()
void serialEvent ()
void serialEvent1 ()
void setNextState (UIState *newState, bool update=false)
void setup ()
const __FlashStringHelper * stateName ()
const char * version ()
Static Public Member Functions
static TankControllerLib * instance (const char *pushingBoxID=nullptr)
Private Member Functions
TankControllerLib ()
~TankControllerLib ()
void blink ()
void handleUI ()
void updateControls ()
void updateState ()
void writeDataToSD ()
void writeDataToSerial ()
Private Attributes
UIState * state = nullptr
UIState * nextState = nullptr
uint32_t lastKeypadTime = 0
Static Private Attributes
static TankControllerLib * _instance = nullptr
static const uint32_t IDLE_TIMEOUT = 60L * 1000L
Detailed Description
Definition at line 12 of file TankControllerLib.h.
Constructor & Destructor Documentation
TankControllerLib()
TankControllerLib::TankControllerLib () private
Constructor
Definition at line 46 of file TankControllerLib.cpp.
{
   serial(F("\r\n#################\r\nTankControllerLib::TankControllerLib() - version %s"), TANK_CONTROLLER_VERSION);
   assert(!_instance);
   // ensure we have instances
   SD_TC::instance();
   EEPROM_TC::instance();
   Keypad_TC::instance();
   LiquidCrystal_TC::instance(TANK_CONTROLLER_VERSION);
   DateTime_TC::rtc();
   Ethernet_TC::instance();
   TempProbe_TC::instance();
   TemperatureControl::instance();
   PHProbe::instance();
   PHControl::instance();
   state = new MainMenu(this);
   pinMode(LED_BUILTIN, OUTPUT);
 }
References _instance, assert, EEPROM_TC::instance(), Keypad_TC::instance(), PHControl::instance(), PHProbe::instance(), SD_TC::instance(), TemperatureControl::instance(), TempProbe_TC::instance(), Ethernet_TC::instance(), LiquidCrystal_TC::instance(), DateTime_TC::rtc(), serial(), state, and TANK_CONTROLLER_VERSION.
Referenced by instance().
~TankControllerLib()
TankControllerLib::~TankControllerLib () private
Destructor
Definition at line 67 of file TankControllerLib.cpp.
{
   if (state) {
     delete state;
     state = nullptr;
   }
   if (nextState) {
     delete nextState;
     nextState = nullptr;
   }
 }
References nextState, and state.
Member Function Documentation
blink()
void TankControllerLib::blink () private
Blink the on-board LED to let us know that loop() is being called
Definition at line 82 of file TankControllerLib.cpp.
{
   if (millis() / 1000 % 2) {
     digitalWrite(LED_BUILTIN, LOW);  // turn the LED off by making the voltage LOW
   } else {
     digitalWrite(LED_BUILTIN, HIGH);  // turn the LED on (HIGH is the voltage level)
   }
 }
Referenced by loop().
freeMemory()
int TankControllerLib::freeMemory ()
Definition at line 91 of file TankControllerLib.cpp.
{
 #ifdef MOCK_PINS_COUNT
   int *__brkval = 0;
   int __bss_end = 0;
 #else
   extern char *__brkval;
   extern char __bss_end;
 #endif
   int topOfStack;
   if ((size_t)__brkval == 0) {
     return ((size_t)&topOfStack) - ((size_t)&__bss_end);
   }
   return (int)((size_t)&topOfStack) - ((size_t)__brkval);
 }
Referenced by setup().
handleUI()
void TankControllerLib::handleUI () private
Private member function called by loop Handles keypresses
Definition at line 119 of file TankControllerLib.cpp.
{
   COUT("TankControllerLib::handleUI() - " << state->name());
   char key = Keypad_TC::instance()->getKey();
   if (key == NO_KEY) {
     if (!lastKeypadTime) {
       // we have already reached an idle state, so don't do other checks
     } else if (isInCalibration()) {
       // we are in calibration, so don't return to main menu
     } else if (nextState) {
       // we already have a next state teed-up, do don't try to return to main menu
     } else if (millis() - lastKeypadTime > IDLE_TIMEOUT) {
       // time since last keypress exceeds the idle timeout, so return to main menu
       setNextState((UIState *)new MainMenu(this));
       lastKeypadTime = 0;  // so we don't do this until another keypress!
     }
   } else {
     serial(F("Keypad input: %c"), key);
     COUT("TankControllerLib::handleUI() - " << state->name() << "::handleKey(" << key << ")");
     state->handleKey(key);
     lastKeypadTime = millis();
   }
   updateState();
   COUT("TankControllerLib::handleUI() - " << state->name() << "::loop()");
   state->loop();
 }
References COUT, Keypad_TC::getKey(), UIState::handleKey(), IDLE_TIMEOUT, Keypad_TC::instance(), isInCalibration(), key(), lastKeypadTime, UIState::loop(), UIState::name(), nextState, serial(), setNextState(), state, and updateState().
Referenced by loop().
instance()
TankControllerLib * TankControllerLib::instance (const char * pushingBoxID = nullptr) static
static function to return singleton
Definition at line 34 of file TankControllerLib.cpp.
{
   if (!_instance) {
     _instance = new TankControllerLib;
     PushingBox::instance(pushingBoxID);
   }
   return _instance;
 }
References _instance, PushingBox::instance(), and TankControllerLib().
Referenced by PID_TC::computeOutput(), EthernetServer_TC::file(), loop(), PushingBox::sendData(), setup(), SeeFreeMemory::start(), SeeVersion::start(), unittest(), unittest_setup(), Heater::updateControl(), Chiller::updateControl(), PHControl::updateControl(), version(), and writeSerial1().
isInCalibration()
bool TankControllerLib::isInCalibration ()
Is the current UIState one that should disable controls? We don't want to turn on the heat/chill if the temperature probe is out of the tank!
Definition at line 111 of file TankControllerLib.cpp.
{
   return state->isInCalibration();
 }
References UIState::isInCalibration(), and state.
Referenced by handleUI(), unittest(), and writeDataToSD().
loop()
void TankControllerLib::loop ()
This is one of two public instance functions. It is called repeatedly while the board is on. (It appears to be called about once every 15 ms.)
Definition at line 150 of file TankControllerLib.cpp.
{
   wdt_reset();
   blink();                                // blink the on-board LED to show that we are running
   handleUI();                             // look at keypad, update LCD
   updateControls();                       // turn CO2 and temperature controls on or off
   writeDataToSD();                        // record current state to data log
   writeDataToSerial();                    // record current pH and temperature to serial
   PushingBox::instance()->loop();         // write data to Google Sheets
   Ethernet_TC::instance()->loop();        // renew DHCP lease
   EthernetServer_TC::instance()->loop();  // handle any HTTP requests
 }
References blink(), handleUI(), EthernetServer_TC::instance(), Ethernet_TC::instance(), PushingBox::instance(), Ethernet_TC::loop(), EthernetServer_TC::loop(), PushingBox::loop(), updateControls(), writeDataToSD(), and writeDataToSerial().
Referenced by enterKey(), loop(), setPhMeasurementTo(), unittest(), and unittest_setup().
serialEvent()
void TankControllerLib::serialEvent ()
This public instance function is called when there is data on the serial port(0).
Definition at line 165 of file TankControllerLib.cpp.
{
 }
serialEvent1()
void TankControllerLib::serialEvent1 ()
This public instance function is called when there is data on the serial port(1). This the Atlas EZO pH circuit probe.
Definition at line 172 of file TankControllerLib.cpp.
{
   PHProbe::instance()->serialEvent1();
 }
References PHProbe::instance(), and PHProbe::serialEvent1().
Referenced by setPhMeasurementTo(), unittest(), unittest_setup(), and writeSerial1().
setNextState()
void TankControllerLib::setNextState (UIState * newState, bool update = false)
Set the next state
Definition at line 179 of file TankControllerLib.cpp.
{
   COUT("TankControllerLib::setNextState() from " << (nextState ? nextState->name() : "nullptr") << " to "
                                                  << newState->name());
   assert(nextState == nullptr);
   nextState = newState;
   if (update) {
     this->updateState();
   }
 }
References assert, COUT, UIState::name(), nextState, and updateState().
Referenced by handleUI(), reset(), UIState::setNextState(), unittest(), unittest_setup(), and unittest_teardown().
setup()
void TankControllerLib::setup ()
This is one of two public instance functions. Here we do any one-time startup initialization.
Definition at line 193 of file TankControllerLib.cpp.
{
   wdt_enable(WDTO_8S);
   serial(F("TankControllerLib::setup()"));
   SD_TC::instance()->printRootDirectory();
   serial(F("Free memory = %i"), freeMemory());
 }
References freeMemory(), SD_TC::instance(), SD_TC::printRootDirectory(), and serial().
Referenced by setup(), and unittest().
stateName()
const __FlashStringHelper * TankControllerLib::stateName ()
Public member function used to get the current state name. This is primarily used by testing.
Definition at line 204 of file TankControllerLib.cpp.
{
   return state->name();
 }
References UIState::name(), and state.
Referenced by unittest().
updateControls()
void TankControllerLib::updateControls () private
Private member function called by loop to update solonoids
Definition at line 211 of file TankControllerLib.cpp.
{
   // update TemperatureControl
   TemperatureControl::instance()->updateControl(TempProbe_TC::instance()->getRunningAverage());
   // update PHControl
   PHControl::instance()->updateControl(PHProbe::instance()->getPh());
 }
References PHControl::instance(), PHProbe::instance(), TemperatureControl::instance(), TempProbe_TC::instance(), TemperatureControl::updateControl(), and PHControl::updateControl().
Referenced by loop().
updateState()
void TankControllerLib::updateState () private
Private member function called by UIState subclasses Only updates if a new state is available to switch to
Definition at line 222 of file TankControllerLib.cpp.
{
   if (nextState) {
     COUT("TankControllerLib::updateState() to " << nextState->name());
     assert(state != nextState);
     delete state;
     state = nextState;
     nextState = nullptr;
     state->start();
   }
 }
References assert, COUT, UIState::name(), nextState, UIState::start(), and state.
Referenced by handleUI(), and setNextState().
version()
const char * TankControllerLib::version ()
What is the current version?
Definition at line 236 of file TankControllerLib.cpp.
{
   serial(F("TankControllerLib::version() = %s"), TANK_CONTROLLER_VERSION);
   return TANK_CONTROLLER_VERSION;
 }
References serial(), and TANK_CONTROLLER_VERSION.
Referenced by SeeVersion::start(), and version().
writeDataToSD()
void TankControllerLib::writeDataToSD () private
once per second write the current data to the SD card
Definition at line 244 of file TankControllerLib.cpp.
{
   static uint32_t nextWriteTime = 0;
   uint32_t msNow = millis();
   COUT("nextWriteTime: " << nextWriteTime << "; now = " << msNow);
   if (nextWriteTime > msNow) {
     return;
   }
   char currentTemp[10];
   char currentPh[10];
   if (isInCalibration()) {
     snprintf_P(currentTemp, sizeof(currentTemp), (PGM_P)F("C"));
     snprintf_P(currentPh, sizeof(currentPh), (PGM_P)F("C"));
   } else {
     snprintf_P(currentTemp, sizeof(currentTemp), (PGM_P)F("%4.2f"),
                (float)TempProbe_TC::instance()->getRunningAverage());
     snprintf_P(currentPh, sizeof(currentPh), (PGM_P)F("%5.3f"), (float)PHProbe::instance()->getPh());
   }
   static const char header[] = "time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd";
   static const char format[] PROGMEM =
       "%02i/%02i/%4i %02i:%02i:%02i, %3i, %s, %4.2f, %s, %5.3f, %4lu, %8.1f, %8.1f, %8.1f";
   char buffer[128];
   DateTime_TC dtNow = DateTime_TC::now();
   PID_TC *pPID = PID_TC::instance();
   uint16_t tankId = EEPROM_TC::instance()->getTankID();
   snprintf_P(buffer, sizeof(buffer), (PGM_P)format, (uint16_t)dtNow.month(), (uint16_t)dtNow.day(),
              (uint16_t)dtNow.year(), (uint16_t)dtNow.hour(), (uint16_t)dtNow.minute(), (uint16_t)dtNow.second(),
              (uint16_t)tankId, currentTemp, (float)TemperatureControl::instance()->getTargetTemperature(), currentPh,
              (float)PHControl::instance()->getTargetPh(), (unsigned long)(millis() / 1000), (float)pPID->getKp(),
              (float)pPID->getKi(), (float)pPID->getKd());
   SD_TC::instance()->appendData(header, buffer);
   nextWriteTime = msNow / 1000 * 1000 + 1000;  // round up to next second
   COUT(buffer);
 }
References SD_TC::appendData(), buffer, COUT, PID_TC::getKd(), PID_TC::getKi(), PID_TC::getKp(), EEPROM_TC::getTankID(), PHControl::getTargetPh(), TemperatureControl::getTargetTemperature(), EEPROM_TC::instance(), PHControl::instance(), PHProbe::instance(), PID_TC::instance(), SD_TC::instance(), TemperatureControl::instance(), TempProbe_TC::instance(), isInCalibration(), and DateTime_TC::now().
Referenced by loop().
writeDataToSerial()
void TankControllerLib::writeDataToSerial () private
once per minute write the current data to the serial port
Definition at line 281 of file TankControllerLib.cpp.
{
   static uint32_t nextWriteTime = 0;
   uint32_t msNow = millis();
   if (nextWriteTime <= msNow) {
     DateTime_TC dtNow = DateTime_TC::now();
     serial(F("%02d:%02d pH=%5.3f temp=%5.2f"), (uint16_t)dtNow.hour(), (uint16_t)dtNow.minute(),
            (float)PHProbe::instance()->getPh(), (float)TempProbe_TC::instance()->getRunningAverage());
     nextWriteTime = msNow / 60000 * 60000 + 60000;  // round up to next minute
     COUT(buffer);
   }
 }
References buffer, COUT, PHProbe::getPh(), TempProbe_TC::getRunningAverage(), PHProbe::instance(), TempProbe_TC::instance(), DateTime_TC::now(), and serial().
Referenced by loop().
Member Data Documentation
_instance
TankControllerLib * TankControllerLib::_instance = nullptr static private
static variable to hold singleton
Definition at line 30 of file TankControllerLib.h.
Referenced by instance(), and TankControllerLib().
IDLE_TIMEOUT
const uint32_t TankControllerLib::IDLE_TIMEOUT = 60L * 1000L static private
Definition at line 31 of file TankControllerLib.h.
Referenced by handleUI().
lastKeypadTime
uint32_t TankControllerLib::lastKeypadTime = 0 private
Definition at line 36 of file TankControllerLib.h.
Referenced by handleUI().
nextState
UIState* TankControllerLib::nextState = nullptr private
Definition at line 35 of file TankControllerLib.h.
Referenced by handleUI(), setNextState(), updateState(), and ~TankControllerLib().
state
UIState* TankControllerLib::state = nullptr private
Definition at line 34 of file TankControllerLib.h.
Referenced by handleUI(), isInCalibration(), stateName(), TankControllerLib(), updateState(), and ~TankControllerLib().
The documentation for this class was generated from the following files:
src/TankControllerLib.h
src/TankControllerLib.cpp