Tank Controller Lib: CalibrationManagement Class Reference
CalibrationManagement Class Reference
#include <CalibrationManagement.h>
Public Member Functions
CalibrationManagement (TankController *tc)
void handleKey (char key)
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
CalibrationManagement.h
Calibration Management
Definition at line 9 of file CalibrationManagement.h.
Constructor & Destructor Documentation
CalibrationManagement()
CalibrationManagement::CalibrationManagement (TankController * tc) inline
Definition at line 11 of file CalibrationManagement.h.
                                            : UIState(tc) {
  }
Member Function Documentation
handleKey()
void CalibrationManagement::handleKey (char key) virtual
CalibrationManagement.cpp
Reimplemented from UIState.
Definition at line 7 of file CalibrationManagement.cpp.
{
  switch (key) {
    case 'D':  // Don't save (cancel)
      returnToMainMenu();
      break;
    default:
      break;
  };
}
References key(), and UIState::returnToMainMenu().
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
name()
const __FlashStringHelper * CalibrationManagement::name () inline virtual
Implements UIState.
Definition at line 14 of file CalibrationManagement.h.
{
    return F("CalibrationManagement");
  }
prompt()
const __FlashStringHelper * CalibrationManagement::prompt () inline virtual
Reimplemented from UIState.
Definition at line 17 of file CalibrationManagement.h.
{
    return F("Cal Management");
  };
The documentation for this class was generated from the following files:
src/UIState/CalibrationManagement.h
src/UIState/CalibrationManagement.cpp