Tank Controller Lib: PIDTuningMenu Class Reference
PIDTuningMenu Class Reference
#include <PIDTuningMenu.h>
Public Member Functions
PIDTuningMenu (TankControllerLib *tc)
void handleKey (char key)
const char * name ()
const char * prompt ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
PIDTuningMenu.h
PID Tuning
Definition at line 9 of file PIDTuningMenu.h.
Constructor & Destructor Documentation
PIDTuningMenu()
PIDTuningMenu::PIDTuningMenu (TankControllerLib * tc) inline
Definition at line 11 of file PIDTuningMenu.h.
                                        : UIState(tc) {
   }
Member Function Documentation
handleKey()
void PIDTuningMenu::handleKey (char key) virtual
PIDTuningMenu.cpp
Reimplemented from UIState.
Definition at line 7 of file PIDTuningMenu.cpp.
{
   switch (key) {
     case 'D':  // Don't save (cancel)
       returnToMainMenu();
       break;
     default:
       break;
   };
 }
References key(), and UIState::returnToMainMenu().
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
name()
const char* PIDTuningMenu::name () inline virtual
Implements UIState.
Definition at line 14 of file PIDTuningMenu.h.
                      {
     return "PIDTuningMenu";
   }
prompt()
const char* PIDTuningMenu::prompt () inline virtual
Reimplemented from UIState.
Definition at line 17 of file PIDTuningMenu.h.
{
     return "PID TUNING      ";
   };
The documentation for this class was generated from the following files:
src/UIState/PIDTuningMenu.h
src/UIState/PIDTuningMenu.cpp