Tank Controller Lib: PHControl Class Reference
PHControl Class Reference
#include <PHControl.h>
Public Types
enum phSetTypeTypes { FLAT_TYPE , RAMP_TYPE , SINE_TYPE }
Public Member Functions
float getTargetPh ()
float getCurrentPhTarget ()
int getPhSetType ()
float getAmplitude ()
uint32_t getPhRampTimeStart ()
uint32_t getPhRampTimeEnd ()
uint32_t getPeriod ()
bool getUsePID ()
bool isOn ()
void setTargetPh (float newPh)
void setRampDuration (float newPhRampDuration)
void setSine (float sineAmplitude, float sinePeriodInHours)
void enablePID (bool flag)
void updateControl (float pH)
Static Public Member Functions
static PHControl * instance ()
static void clearInstance ()
Private Member Functions
PHControl ()
Private Attributes
uint32_t lastSwitchMS = 0
uint32_t lastWarnMS = 0
const uint16_t PH_CONTROL_PIN = 49
const uint16_t SOLENOID_OPENING_TIME = 100
float targetPh
float currentPHTarget
float rampStartingPh
uint32_t rampTimeStart
uint32_t rampTimeEnd
float amplitude
uint32_t period
uint32_t sineStartTime
const uint16_t WINDOW_SIZE = 10000
bool usePID = true
int pHSetType = FLAT_TYPE
Static Private Attributes
static PHControl * _instance = nullptr
Detailed Description
Definition at line 5 of file PHControl.h.
Member Enumeration Documentation
phSetTypeTypes
enum PHControl::phSetTypeTypes
Enumerator
FLAT_TYPE
RAMP_TYPE
SINE_TYPE
Definition at line 28 of file PHControl.h.
                       {
     FLAT_TYPE,
     RAMP_TYPE,
     SINE_TYPE,
   };
Constructor & Destructor Documentation
PHControl()
PHControl::PHControl () private
Definition at line 39 of file PHControl.cpp.
                      {
   pinMode(PH_CONTROL_PIN, OUTPUT);
   digitalWrite(PH_CONTROL_PIN, TURN_SOLENOID_OFF);
   targetPh = EEPROM_TC::instance()->getPh();
   if (isnan(targetPh)) {
     targetPh = DEFAULT_PH;
     EEPROM_TC::instance()->setPh(targetPh);
   }
   pHSetType = EEPROM_TC::instance()->getPhSetType();
   if (pHSetType == 0xFFFFFFFF) {
     pHSetType = FLAT_TYPE;
     EEPROM_TC::instance()->setPhSetType(pHSetType);
   }
   switch (pHSetType) {
     case RAMP_TYPE:
       rampTimeEnd = EEPROM_TC::instance()->getPhRampTimeEnd();
       if (rampTimeEnd == 0xFFFFFFFF || rampTimeEnd == 0) {
         rampTimeEnd = 0;
         EEPROM_TC::instance()->setPhRampTimeEnd(rampTimeEnd);
         rampTimeStart = 0;
         EEPROM_TC::instance()->setPhRampTimeStart(rampTimeStart);
       } else {
         rampTimeStart = EEPROM_TC::instance()->getPhRampTimeStart();
         rampStartingPh = EEPROM_TC::instance()->getRampStartingPh();
       }
       break;
     case SINE_TYPE:
       period = EEPROM_TC::instance()->getPhSinePeriod();
       amplitude = EEPROM_TC::instance()->getPhSineAmplitude();
       sineStartTime = EEPROM_TC::instance()->getPhSineStartTime();
       break;
     default:
       break;
   }
   char buffer[40];
   strncpy_P(buffer, (PGM_P)F("PHControl with target pH = "), sizeof(buffer));
   dtostrf(targetPh, 5, 3, buffer + strnlen(buffer, sizeof(buffer)));
   serial(buffer);
 }
References amplitude, buffer, DEFAULT_PH, FLAT_TYPE, EEPROM_TC::getPh(), EEPROM_TC::getPhRampTimeEnd(), EEPROM_TC::getPhRampTimeStart(), EEPROM_TC::getPhSetType(), EEPROM_TC::getPhSineAmplitude(), EEPROM_TC::getPhSinePeriod(), EEPROM_TC::getPhSineStartTime(), EEPROM_TC::getRampStartingPh(), EEPROM_TC::instance(), period, PH_CONTROL_PIN, pHSetType, RAMP_TYPE, rampStartingPh, rampTimeEnd, rampTimeStart, serial(), EEPROM_TC::setPh(), EEPROM_TC::setPhRampTimeEnd(), EEPROM_TC::setPhRampTimeStart(), EEPROM_TC::setPhSetType(), SINE_TYPE, sineStartTime, targetPh, and TURN_SOLENOID_OFF.
Referenced by instance().
Member Function Documentation
clearInstance()
void PHControl::clearInstance () static
Definition at line 32 of file PHControl.cpp.
{
   if (_instance) {
     delete _instance;
     _instance = nullptr;
   }
 }
References _instance.
Referenced by unittest().
enablePID()
void PHControl::enablePID (bool flag)
Definition at line 129 of file PHControl.cpp.
{
   usePID = flag;
   // save to EEPROM?
   serial(flag ? F("enable PID") : F("disable PID"));
 }
References serial(), and usePID.
Referenced by reset(), EnablePID::setValue(), unittest(), and unittest_setup().
getAmplitude()
float PHControl::getAmplitude () inline
Definition at line 44 of file PHControl.h.
{
     return amplitude;
   }
References amplitude.
Referenced by SetPHWithSine::getCurrentValue().
getCurrentPhTarget()
float PHControl::getCurrentPhTarget () inline
Definition at line 38 of file PHControl.h.
{
     return currentPHTarget;
   }
References currentPHTarget.
Referenced by unittest().
getPeriod()
uint32_t PHControl::getPeriod () inline
Definition at line 53 of file PHControl.h.
{
     return period;
   }
References period.
Referenced by SetPHWithSine::getCurrentValue().
getPhRampTimeEnd()
uint32_t PHControl::getPhRampTimeEnd () inline
Definition at line 50 of file PHControl.h.
{
     return rampTimeEnd;
   }
References rampTimeEnd.
Referenced by SetPHSetPoint::getCurrentValue().
getPhRampTimeStart()
uint32_t PHControl::getPhRampTimeStart () inline
Definition at line 47 of file PHControl.h.
{
     return rampTimeStart;
   }
References rampTimeStart.
Referenced by SetPHSetPoint::getCurrentValue().
getPhSetType()
int PHControl::getPhSetType () inline
Definition at line 41 of file PHControl.h.
                      {
     return pHSetType;
   }
References pHSetType.
Referenced by unittest().
getTargetPh()
float PHControl::getTargetPh () inline
Definition at line 35 of file PHControl.h.
                       {
     return targetPh;
   }
References targetPh.
Referenced by SetPHSetPoint::getCurrentValue(), and SetPHWithSine::getCurrentValue().
getUsePID()
bool PHControl::getUsePID () inline
Definition at line 56 of file PHControl.h.
                    {
     return usePID;
   }
References usePID.
Referenced by EnablePID::getCurrentValue().
instance()
PHControl * PHControl::instance () static
static member function to return singleton
Definition at line 25 of file PHControl.cpp.
{
   if (!_instance) {
     _instance = new PHControl();
   }
   return _instance;
 }
References _instance, and PHControl().
Referenced by EnablePID::getCurrentValue(), SetPHSetPoint::getCurrentValue(), SetPHWithSine::getCurrentValue(), MainMenu::idle(), SeePIDConstants::loadPID(), EnablePID::setValue(), SetPHSetPoint::setValue(), SetPHWithSine::setValue(), TankController::TankController(), unittest(), unittest_setup(), TankController::updateControls(), and TankController::writeDataToSD().
isOn()
bool PHControl::isOn ()
Definition at line 135 of file PHControl.cpp.
                      {
   return digitalRead(PH_CONTROL_PIN) == TURN_SOLENOID_ON;
 }
References PH_CONTROL_PIN, and TURN_SOLENOID_ON.
Referenced by MainMenu::idle(), and unittest().
setRampDuration()
void PHControl::setRampDuration (float newPhRampDuration)
Definition at line 92 of file PHControl.cpp.
{
   if (newPhRampDuration > 0) {
     char buffer[40];
     float currentRampTime = rampTimeEnd - rampTimeStart;
     strncpy_P(buffer, (PGM_P)F("change ramp time from "), sizeof(buffer));
     dtostrf(currentRampTime, 5, 3, buffer + strnlen(buffer, sizeof(buffer)));
     strcpy_P(buffer + strnlen(buffer, sizeof(buffer)), (PGM_P)F(" to "));
     dtostrf(newPhRampDuration, 5, 3, buffer + strnlen(buffer, sizeof(buffer)));
     serial(buffer);
     rampTimeStart = DateTime_TC::now().secondstime();
     rampTimeEnd = rampTimeStart + (newPhRampDuration * 3600);
     rampStartingPh = PHProbe::instance()->getPh();
     pHSetType = phSetTypeTypes::RAMP_TYPE;
     EEPROM_TC::instance()->setPhSetType(pHSetType);
     EEPROM_TC::instance()->setPhRampTimeStart(rampTimeStart);
     EEPROM_TC::instance()->setPhRampTimeEnd(rampTimeEnd);
     EEPROM_TC::instance()->setRampStartingPh(rampStartingPh);
   } else {
     rampTimeEnd = 0;
     pHSetType = phSetTypeTypes::FLAT_TYPE;
     EEPROM_TC::instance()->setPhSetType(pHSetType);
     EEPROM_TC::instance()->setPhRampTimeEnd(rampTimeEnd);
     serial("set ramp time to 0");
   }
 }
References buffer, PHProbe::getPh(), EEPROM_TC::instance(), PHProbe::instance(), DateTime_TC::now(), pHSetType, rampStartingPh, rampTimeEnd, rampTimeStart, serial(), EEPROM_TC::setPhRampTimeEnd(), EEPROM_TC::setPhRampTimeStart(), EEPROM_TC::setPhSetType(), and EEPROM_TC::setRampStartingPh().
Referenced by SetPHSetPoint::setValue(), and unittest().
setSine()
void PHControl::setSine (float sineAmplitude, float sinePeriodInHours)
Definition at line 118 of file PHControl.cpp.
{
   period = (sinePeriodInHours * 3600);
   amplitude = sineAmplitude;
   pHSetType = phSetTypeTypes::SINE_TYPE;
   sineStartTime = DateTime_TC::now().secondstime();
   EEPROM_TC::instance()->setPhSetType(pHSetType);
   EEPROM_TC::instance()->setPhSinePeriod(period);
   EEPROM_TC::instance()->setPhSineAmplitude(amplitude);
   EEPROM_TC::instance()->setPhSineStartTime(sineStartTime);
 }
References amplitude, EEPROM_TC::instance(), DateTime_TC::now(), period, pHSetType, EEPROM_TC::setPhSetType(), EEPROM_TC::setPhSineAmplitude(), EEPROM_TC::setPhSinePeriod(), EEPROM_TC::setPhSineStartTime(), and sineStartTime.
Referenced by SetPHWithSine::setValue(), and unittest().
setTargetPh()
void PHControl::setTargetPh (float newPh)
Definition at line 79 of file PHControl.cpp.
{
   if (targetPh != newPh) {
     char buffer[40];
     strncpy_P(buffer, (PGM_P)F("change target pH from "), sizeof(buffer));
     dtostrf(targetPh, 5, 3, buffer + strnlen(buffer, sizeof(buffer)));
     strcpy_P(buffer + strnlen(buffer, sizeof(buffer)), (PGM_P)F(" to "));
     dtostrf(newPh, 5, 3, buffer + strnlen(buffer, sizeof(buffer)));
     serial(buffer);
     targetPh = newPh;
     EEPROM_TC::instance()->setPh(newPh);
   }
 }
References buffer, EEPROM_TC::instance(), serial(), EEPROM_TC::setPh(), and targetPh.
Referenced by reset(), SetPHSetPoint::setValue(), SetPHWithSine::setValue(), unittest(), and unittest_setup().
updateControl()
void PHControl::updateControl (float pH)
Definition at line 139 of file PHControl.cpp.
{
   int msToBeOn;
   int nowModWindow = millis() % WINDOW_SIZE;
   uint32_t currentTime = DateTime_TC::now().secondstime();
   switch (pHSetType) {
     case FLAT_TYPE: {
       currentPHTarget = targetPh;
       break;
     }
     case RAMP_TYPE: {
       if (currentTime < rampTimeEnd) {
         currentPHTarget = rampStartingPh +
                           ((currentTime - rampTimeStart) * (targetPh - rampStartingPh) / (rampTimeEnd - rampTimeStart));
       } else {
         currentPHTarget = targetPh;
       }
       break;
     }
     case SINE_TYPE: {
       uint32_t sineEndTime = sineStartTime + period;
       if (currentTime >= sineEndTime) {
         sineStartTime = DateTime_TC::now().secondstime();
         sineEndTime = sineStartTime + period;
         EEPROM_TC::instance()->setPhSineStartTime(sineStartTime);
       }
       float timeLeftTillPeriodEnd = sineEndTime - currentTime;
       float percentNOTThroughPeriod = timeLeftTillPeriodEnd / period;
       float percentThroughPeriod = 1 - percentNOTThroughPeriod;
       float x = percentThroughPeriod * (2 * PI);        // the x position for our sine wave
       currentPHTarget = amplitude * sin(x) + targetPh;  // y position in our sine wave
       break;
     }
     default:
       break;
   }
   COUT("PHControl::updateControl(" << pH << ") at " << millis());
   if (usePID) {
     msToBeOn = PID_TC::instance()->computeOutput(currentPHTarget, pH);
     if (msToBeOn > 9000) {
       if (msToBeOn > 10000 && lastWarnMS + 60000 < millis()) {
         serial(F("WARNING: PID asked for an on time of %i which has been capped at 9000"), msToBeOn);
         lastWarnMS = millis();
       }
       msToBeOn = 9000;
     }
   } else {
     msToBeOn = pH > currentPHTarget ? 9000 : 0;
   }
   COUT("target: " << currentPHTarget << "; current: " << pH << "; nowModWindow = " << nowModWindow
                   << "; msToBeOn = " << msToBeOn);
   bool newValue;
   if (TankController::instance()->isInCalibration()) {
     COUT("pH control should be off since in calibration");
     newValue = TURN_SOLENOID_OFF;  // turn off CO2 while in calibration
   } else if (SOLENOID_OPENING_TIME < msToBeOn && nowModWindow < msToBeOn) {
     COUT("pH control should be on");
     newValue = TURN_SOLENOID_ON;  // open CO2 solenoid
   } else {
     COUT("pH control should be off");
     newValue = TURN_SOLENOID_OFF;  // close CO2 solenoid
   }
   if (newValue != digitalRead(PH_CONTROL_PIN)) {
     digitalWrite(PH_CONTROL_PIN, newValue);
     uint32_t currentMS = millis();
     serial(F("CO2 bubbler turned %s after %lu ms"), newValue ? "off" : "on", currentMS - lastSwitchMS);
     lastSwitchMS = currentMS;
   }
 }
References amplitude, PID_TC::computeOutput(), COUT, currentPHTarget, FLAT_TYPE, EEPROM_TC::instance(), PID_TC::instance(), TankController::instance(), lastSwitchMS, lastWarnMS, DateTime_TC::now(), period, PH_CONTROL_PIN, pHSetType, RAMP_TYPE, rampStartingPh, rampTimeEnd, rampTimeStart, serial(), EEPROM_TC::setPhSineStartTime(), SINE_TYPE, sineStartTime, SOLENOID_OPENING_TIME, targetPh, TURN_SOLENOID_OFF, TURN_SOLENOID_ON, usePID, and WINDOW_SIZE.
Referenced by TankController::updateControls().
Member Data Documentation
_instance
PHControl * PHControl::_instance = nullptr static private
static variable for singleton
Definition at line 8 of file PHControl.h.
Referenced by clearInstance(), and instance().
amplitude
float PHControl::amplitude private
Definition at line 19 of file PHControl.h.
Referenced by getAmplitude(), PHControl(), setSine(), and updateControl().
currentPHTarget
float PHControl::currentPHTarget private
Definition at line 15 of file PHControl.h.
Referenced by getCurrentPhTarget(), and updateControl().
lastSwitchMS
uint32_t PHControl::lastSwitchMS = 0 private
Definition at line 10 of file PHControl.h.
Referenced by updateControl().
lastWarnMS
uint32_t PHControl::lastWarnMS = 0 private
Definition at line 11 of file PHControl.h.
Referenced by updateControl().
period
uint32_t PHControl::period private
Definition at line 20 of file PHControl.h.
Referenced by getPeriod(), PHControl(), setSine(), and updateControl().
PH_CONTROL_PIN
const uint16_t PHControl::PH_CONTROL_PIN = 49 private
Definition at line 12 of file PHControl.h.
Referenced by isOn(), PHControl(), and updateControl().
pHSetType
int PHControl::pHSetType = FLAT_TYPE private
Definition at line 24 of file PHControl.h.
Referenced by getPhSetType(), PHControl(), setRampDuration(), setSine(), and updateControl().
rampStartingPh
float PHControl::rampStartingPh private
Definition at line 16 of file PHControl.h.
Referenced by PHControl(), setRampDuration(), and updateControl().
rampTimeEnd
uint32_t PHControl::rampTimeEnd private
Definition at line 18 of file PHControl.h.
Referenced by getPhRampTimeEnd(), PHControl(), setRampDuration(), and updateControl().
rampTimeStart
uint32_t PHControl::rampTimeStart private
Definition at line 17 of file PHControl.h.
Referenced by getPhRampTimeStart(), PHControl(), setRampDuration(), and updateControl().
sineStartTime
uint32_t PHControl::sineStartTime private
Definition at line 21 of file PHControl.h.
Referenced by PHControl(), setSine(), and updateControl().
SOLENOID_OPENING_TIME
const uint16_t PHControl::SOLENOID_OPENING_TIME = 100 private
Definition at line 13 of file PHControl.h.
Referenced by updateControl().
targetPh
float PHControl::targetPh private
Definition at line 14 of file PHControl.h.
Referenced by getTargetPh(), PHControl(), setTargetPh(), and updateControl().
usePID
bool PHControl::usePID = true private
Definition at line 23 of file PHControl.h.
Referenced by enablePID(), getUsePID(), and updateControl().
WINDOW_SIZE
const uint16_t PHControl::WINDOW_SIZE = 10000 private
Definition at line 22 of file PHControl.h.
Referenced by updateControl().
The documentation for this class was generated from the following files:
src/Devices/PHControl.h
src/Devices/PHControl.cpp