Tank Controller Lib: SeePIDConstants Class Reference
SeePIDConstants Class Reference
#include <SeePIDConstants.h>
Public Member Functions
SeePIDConstants (TankControllerLib *tc)
void loop ()
const char * name ()
void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual const char * prompt ()
Private Member Functions
void loadKp (uint16_t line)
void loadKi (uint16_t line)
void loadKd (uint16_t line)
void loadPID (uint16_t line)
Private Attributes
uint32_t startTime
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SeePIDConstants.h
See PID Constants
Definition at line 10 of file SeePIDConstants.h.
Constructor & Destructor Documentation
SeePIDConstants()
SeePIDConstants::SeePIDConstants (TankControllerLib * tc) inline
Definition at line 12 of file SeePIDConstants.h.
                                          : UIState(tc) {
   }
Member Function Documentation
loadKd()
void SeePIDConstants::loadKd (uint16_t line) private
Definition at line 39 of file SeePIDConstants.cpp.
{
   char buffer[17];
   snprintf(buffer, sizeof(buffer), "Kd: %.1f", PID_TC::instance()->getKd());
   LiquidCrystal_TC::instance()->writeLine(buffer, line);
 }
References buffer, PID_TC::instance(), LiquidCrystal_TC::instance(), and LiquidCrystal_TC::writeLine().
Referenced by loop().
loadKi()
void SeePIDConstants::loadKi (uint16_t line) private
Definition at line 33 of file SeePIDConstants.cpp.
{
   char buffer[17];
   snprintf(buffer, sizeof(buffer), "Ki: %.1f", PID_TC::instance()->getKi());
   LiquidCrystal_TC::instance()->writeLine(buffer, line);
 }
References buffer, PID_TC::instance(), LiquidCrystal_TC::instance(), and LiquidCrystal_TC::writeLine().
Referenced by loop().
loadKp()
void SeePIDConstants::loadKp (uint16_t line) private
Definition at line 27 of file SeePIDConstants.cpp.
{
   char buffer[17];
   snprintf(buffer, sizeof(buffer), "Kp: %.1f", PID_TC::instance()->getKp());
   LiquidCrystal_TC::instance()->writeLine(buffer, line);
 }
References buffer, PID_TC::instance(), LiquidCrystal_TC::instance(), and LiquidCrystal_TC::writeLine().
Referenced by loop().
loadPID()
void SeePIDConstants::loadPID (uint16_t line) private
Definition at line 45 of file SeePIDConstants.cpp.
{
   bool flag = PHControl::instance()->getUsePID();
   if (flag) {
     LiquidCrystal_TC::instance()->writeLine("PID: ON         ", line);
   } else {
     LiquidCrystal_TC::instance()->writeLine("PID: OFF        ", line);
   }
 }
References PHControl::getUsePID(), PHControl::instance(), LiquidCrystal_TC::instance(), and LiquidCrystal_TC::writeLine().
Referenced by loop().
loop()
void SeePIDConstants::loop () virtual
SeePIDConstants.cpp
Reimplemented from UIState.
Definition at line 13 of file SeePIDConstants.cpp.
{
   int32_t elapsedSeconds = ((millis() - startTime) / 3000) % 2;
   switch (elapsedSeconds) {
     case 0:
       loadKp(0);
       loadKi(1);
       break;
     case 1:
       loadKd(0);
       loadPID(1);
       break;
   }
 }
References loadKd(), loadKi(), loadKp(), loadPID(), and startTime.
name()
const char* SeePIDConstants::name () inline virtual
Implements UIState.
Definition at line 15 of file SeePIDConstants.h.
                      {
     return "SeePIDConstants";
   }
start()
void SeePIDConstants::start () inline virtual
Reimplemented from UIState.
Definition at line 18 of file SeePIDConstants.h.
                {
     startTime = millis();
   }
References startTime.
Member Data Documentation
startTime
uint32_t SeePIDConstants::startTime private
Definition at line 28 of file SeePIDConstants.h.
Referenced by loop(), and start().
The documentation for this class was generated from the following files:
src/UIState/SeePIDConstants.h
src/UIState/SeePIDConstants.cpp