Tank Controller Lib: SetTempSetPoint Class Reference
SetTempSetPoint Class Reference
#include <SetTempSetPoint.h>
Public Member Functions
SetTempSetPoint (TankController *tc)
const __FlashStringHelper * name ()
float getCurrentValue ()
uint16_t getCurrentValuePrecision ()
const __FlashStringHelper * prompt ()
void setValue (float value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankController *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Private Attributes
uint16_t subState = 0
float values [NUM_VALUES] = {0, 0}
const uint16_t precision [NUM_VALUES] = {2, 1}
const __FlashStringHelper * prompts [NUM_VALUES]
Static Private Attributes
static const uint16_t NUM_VALUES = 2
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
SetTempSetPoint.h
Set the target Temperature
Definition at line 10 of file SetTempSetPoint.h.
Constructor & Destructor Documentation
SetTempSetPoint()
SetTempSetPoint::SetTempSetPoint (TankController * tc)
SetTemperatureSetPoint.cpp
Definition at line 9 of file SetTempSetPoint.cpp.
                                                    : NumCollectorState(tc) {
   prompts[0] = F("Set Temperature");
   prompts[1] = F("Set ramp hours:");
 }
References prompts.
Member Function Documentation
getCurrentValue()
float SetTempSetPoint::getCurrentValue () virtual
Implements NumCollectorState.
Definition at line 14 of file SetTempSetPoint.cpp.
{
   if (subState == 0) {
     return TemperatureControl::instance()->getTargetTemperature();
   } else {
     uint32_t rampTimeStart = TemperatureControl::instance()->getRampTimeStart();
     uint32_t rampTimeEnd = TemperatureControl::instance()->getRampTimeEnd();
     return (rampTimeEnd - rampTimeStart) / 3600;
   }
 }
References TemperatureControl::getRampTimeEnd(), TemperatureControl::getRampTimeStart(), TemperatureControl::getTargetTemperature(), TemperatureControl::instance(), and subState.
getCurrentValuePrecision()
uint16_t SetTempSetPoint::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 17 of file SetTempSetPoint.h.
{
     return precision[subState];
   }
References precision, and subState.
name()
const __FlashStringHelper* SetTempSetPoint::name () inline virtual
Implements UIState.
Definition at line 13 of file SetTempSetPoint.h.
{
     return F("SetTempSetPoint");
   }
prompt()
const __FlashStringHelper* SetTempSetPoint::prompt () inline virtual
Reimplemented from UIState.
Definition at line 20 of file SetTempSetPoint.h.
{
     return prompts[subState];
   };
References prompts, and subState.
setValue()
void SetTempSetPoint::setValue (float value) virtual
Implements NumCollectorState.
Definition at line 24 of file SetTempSetPoint.cpp.
{
   values[subState++] = value;
   if (subState < NUM_VALUES) {
     clear();
     start();
   } else {
     TemperatureControl::instance()->setTargetTemperature(values[0]);
     TemperatureControl::instance()->setRampDuration(values[1]);
     char output0[17];
     char output1[17];
     snprintf_P(output0, sizeof(output0), (PGM_P)F("New Temp=%i.%i"), (int)values[0],
                (int)(values[0] * 1000 + 0.5) % 1000);
     snprintf_P(output1, sizeof(output1), (PGM_P)F("New ramp=%i.%i"), (int)values[1], (int)(values[1] * 1000) % 1000);
     LiquidCrystal_TC::instance()->writeLine(output0, 0);
     LiquidCrystal_TC::instance()->writeLine(output1, 1);
     returnToMainMenu(3000);  // after 3-second delay
   }
 }
References NumCollectorState::clear(), TemperatureControl::instance(), LiquidCrystal_TC::instance(), NUM_VALUES, UIState::returnToMainMenu(), TemperatureControl::setRampDuration(), TemperatureControl::setTargetTemperature(), NumCollectorState::start(), subState, NumCollectorState::value, values, and LiquidCrystal_TC::writeLine().
Member Data Documentation
NUM_VALUES
const uint16_t SetTempSetPoint::NUM_VALUES = 2 static private
Definition at line 26 of file SetTempSetPoint.h.
Referenced by setValue().
precision
const uint16_t SetTempSetPoint::precision[NUM_VALUES] = {2, 1} private
Definition at line 29 of file SetTempSetPoint.h.
Referenced by getCurrentValuePrecision().
prompts
const __FlashStringHelper* SetTempSetPoint::prompts[NUM_VALUES] private
Definition at line 30 of file SetTempSetPoint.h.
Referenced by prompt(), and SetTempSetPoint().
subState
uint16_t SetTempSetPoint::subState = 0 private
Definition at line 27 of file SetTempSetPoint.h.
Referenced by getCurrentValue(), getCurrentValuePrecision(), prompt(), and setValue().
values
float SetTempSetPoint::values[NUM_VALUES] = {0, 0} private
Definition at line 28 of file SetTempSetPoint.h.
Referenced by setValue().
The documentation for this class was generated from the following files:
src/UIState/SetTempSetPoint.h
src/UIState/SetTempSetPoint.cpp