Tank Controller Lib: PHProbe Class Reference
PHProbe Class Reference
#include <PHProbe.h>
Public Member Functions
float getPh ()
const char * getSlopeResponse () const
void clearCalibration ()
void getSlope (char *buffer, int size)
void sendSlopeRequest ()
void serialEvent1 ()
void setHighpointCalibration (float highpoint)
void setLowpointCalibration (float lowpoint)
void setMidpointCalibration (float midpoint)
void setTemperatureCompensation (float temperature)
Static Public Member Functions
static PHProbe * instance ()
Private Member Functions
PHProbe ()
Private Attributes
float value = 0
char slopeResponse [32] = ""
Static Private Attributes
static PHProbe * _instance = nullptr
Detailed Description
wrapper class for EZO pH Circuit | Atlas Scientific
https://www.atlas-scientific.com/files/pH_EZO_Datasheet.pdf
Issuing the "Cal,mid,n\r" command will clear the other calibration points.
While the data sheet uses "Slope" the actual string is "SLOPE"
Definition at line 16 of file PHProbe.h.
Constructor & Destructor Documentation
PHProbe()
PHProbe::PHProbe () private
constructor (private so clients use the singleton)
Definition at line 29 of file PHProbe.cpp.
                 {
  Serial1.begin(9600);
  // wait for Serial Monitor to connect. Needed for native USB port boards only:
  while (!Serial1)
    ;
  Serial1.print(F("*OK,0\r"));  // Turn off the returning of OK after command to EZO pH
  Serial1.print(F("C,1\r"));    // Reset pH stamp to continuous measurement: once per second
}
Referenced by instance().
Member Function Documentation
clearCalibration()
void PHProbe::clearCalibration ()
Definition at line 38 of file PHProbe.cpp.
{
  Serial1.print(F("Cal,clear\r"));  // send that string to the Atlas Scientific product
}
Referenced by SetCalibrationClear::handleKey(), and unittest().
getPh()
float PHProbe::getPh () inline
Definition at line 19 of file PHProbe.h.
                {
    return value;
  }
References value.
Referenced by PHCalibration::getCurrentValue(), readPh(), PushingBox::sendData(), PHControl::setRampDuration(), and unittest().
getSlope()
void PHProbe::getSlope (char * buffer, int size)
Definition at line 48 of file PHProbe.cpp.
{
  // for example "?SLOPE,99.7,100.3, -0.89"
  if (strlen(slopeResponse) > 10) {            // Flawfinder: ignore
    strncpy(buffer, slopeResponse + 7, size);  // Flawfinder: ignore
  } else {
    buffer[0] = '\0';
  }
}
References buffer, and slopeResponse.
Referenced by SeePHSlope::loop(), and unittest().
getSlopeResponse()
const char * PHProbe::getSlopeResponse () const inline
Definition at line 22 of file PHProbe.h.
{
    return slopeResponse;
  }
References slopeResponse.
Referenced by unittest().
instance()
PHProbe * PHProbe::instance () static
static member function to return singleton
Definition at line 18 of file PHProbe.cpp.
{
  if (!_instance) {
    _instance = new PHProbe();
  }
  return _instance;
}
References _instance, and PHProbe().
Referenced by PHCalibration::getCurrentValue(), SetCalibrationClear::handleKey(), MainMenu::idle(), SeePHSlope::loop(), readPh(), PushingBox::sendData(), TankController::serialEvent1(), PHControl::setRampDuration(), PHCalibrationHigh::setValue(), PHCalibrationLow::setValue(), PHCalibrationMid::setValue(), SeePHSlope::start(), TankController::TankController(), unittest(), TankController::updateControls(), TankController::writeDataToSD(), and TankController::writeDataToSerial().
sendSlopeRequest()
void PHProbe::sendSlopeRequest ()
Definition at line 42 of file PHProbe.cpp.
{
  // Sending request for Calibration Slope
  Serial1.print(F("SLOPE,?\r"));
  strncpy_P(slopeResponse, (PGM_P)F("       Slope requested!"), sizeof(slopeResponse));  // Flawfinder: ignore
}
References slopeResponse.
Referenced by SeePHSlope::start(), and unittest().
serialEvent1()
void PHProbe::serialEvent1 ()
interrupt handler for data arriving from probe
Definition at line 60 of file PHProbe.cpp.
{
  // if we see that the Atlas Scientific product has sent a character
  while (Serial1.available() > 0) {
    String string = Serial1.readStringUntil('\r');  // read the string until we see a <CR>
    if (string.length() > 0 && string[string.length() - 1] == '\r') {
      // We should not see the CR (https://github.com/Arduino-CI/arduino_ci/pull/302)
      string.remove(string.length() - 1);
    }
    if (string.length() > 0) {
      if (isdigit(string[0])) {  // if the first character in the string is a digit
        // convert the string to a floating point number so it can be evaluated by the Arduino
        value = string.toFloat();
        // we have seen situations where the CO2 bubbler stays on and drives the pH down
        if (value && value < 7.0) {  // hang so as to trigger the watchdog timer reset
                                     // treat 0 as valid since probe might not be connected
          wdt_disable();
          wdt_enable(WDTO_120MS);  // allow enough time to print message
          char buffer[50];
          strncpy_P(buffer, (PGM_P)F("Triggering a reset because pH dropped to "), sizeof(buffer));
          dtostrf(value, 5, 3, buffer + strnlen(buffer, sizeof(buffer)));
          serial(buffer);
          while (true) {
          }
        }
      } else if (string[0] == '?') {  // answer to a previous query
        serial(F("PHProbe serialEvent1: \"%s\""), string.c_str());
        if (string.length() > 7 && string.substring(0, 7) == "?SLOPE,") {
          // for example "?SLOPE,16.1,100.0"
          strncpy(slopeResponse, string.c_str(), sizeof(slopeResponse));  // Flawfinder: ignore
        }
      }
    }
  }
}
References buffer, serial(), slopeResponse, and value.
Referenced by TankController::serialEvent1().
setHighpointCalibration()
void PHProbe::setHighpointCalibration (float highpoint)
Definition at line 109 of file PHProbe.cpp.
{
  char buffer[17];
  snprintf_P(buffer, sizeof(buffer), (PGM_P)F("Cal,High,%i.%i\r"), (int)highpoint,
             (int)(highpoint * 1000 + 0.5) % 1000);
  Serial1.print(buffer);  // send that string to the Atlas Scientific product
  serial(F("PHProbe::setHighpointCalibration(%i.%i)"), (int)highpoint, (int)(highpoint * 1000) % 1000);
}
References buffer, and serial().
Referenced by PHCalibrationHigh::setValue(), and unittest().
setLowpointCalibration()
void PHProbe::setLowpointCalibration (float lowpoint)
Definition at line 117 of file PHProbe.cpp.
{
  char buffer[16];
  snprintf_P(buffer, sizeof(buffer), (PGM_P)F("Cal,low,%i.%i\r"), (int)lowpoint, (int)(lowpoint * 1000 + 0.5) % 1000);
  Serial1.print(buffer);  // send that string to the Atlas Scientific product
  serial(F("PHProbe::setLowpointCalibration(%i.%i)"), (int)lowpoint, (int)(lowpoint * 1000) % 1000);
}
References buffer, and serial().
Referenced by PHCalibrationLow::setValue(), and unittest().
setMidpointCalibration()
void PHProbe::setMidpointCalibration (float midpoint)
Definition at line 124 of file PHProbe.cpp.
{
  char buffer[16];
  snprintf_P(buffer, sizeof(buffer), (PGM_P)F("Cal,mid,%i.%i\r"), (int)midpoint, (int)(midpoint * 1000 + 0.5) % 1000);
  Serial1.print(buffer);  // send that string to the Atlas Scientific product
  serial(F("PHProbe::setMidpointCalibration(%i.%i)"), (int)midpoint, (int)(midpoint * 1000) % 1000);
}
References buffer, and serial().
Referenced by PHCalibrationMid::setValue(), and unittest().
setTemperatureCompensation()
void PHProbe::setTemperatureCompensation (float temperature)
Definition at line 98 of file PHProbe.cpp.
{
  char buffer[10];
  if (temperature > 0 && temperature < 100) {
    snprintf_P(buffer, sizeof(buffer), (PGM_P)F("T,%i.%i\r"), (int)temperature, (int)(temperature * 100 + 0.5) % 100);
  } else {
    snprintf_P(buffer, sizeof(buffer), (PGM_P)F("T,20\r"));
  }
  serial(F("PHProbe::setTemperatureCompensation() - %s"), buffer);
  Serial1.print(buffer);  // send that string to the Atlas Scientific product
}
References buffer, and serial().
Referenced by unittest().
Member Data Documentation
_instance
PHProbe * PHProbe::_instance = nullptr static private
static variable for singleton
Definition at line 36 of file PHProbe.h.
Referenced by instance().
slopeResponse
char PHProbe::slopeResponse[32] = "" private
Definition at line 39 of file PHProbe.h.
Referenced by getSlope(), getSlopeResponse(), sendSlopeRequest(), and serialEvent1().
value
float PHProbe::value = 0 private
Definition at line 38 of file PHProbe.h.
Referenced by getPh(), and serialEvent1().
The documentation for this class was generated from the following files:
src/Devices/PHProbe.h
src/Devices/PHProbe.cpp