Tank Controller Lib: SeeDeviceUptime Class Reference
SeeDeviceUptime Class Reference
#include <SeeDeviceUptime.h>
Public Member Functions
SeeDeviceUptime (TankControllerLib *tc)
void loop ()
const char * name ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual const char * prompt ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SeeDeviceUptime.h
Display the device uptime & Current time
Definition at line 9 of file SeeDeviceUptime.h.
Constructor & Destructor Documentation
SeeDeviceUptime()
SeeDeviceUptime::SeeDeviceUptime (TankControllerLib * tc) inline
Definition at line 11 of file SeeDeviceUptime.h.
                                          : UIState(tc) {
   }
Member Function Documentation
loop()
void SeeDeviceUptime::loop () virtual
SeeDeviceUptime.cpp
Reimplemented from UIState.
Definition at line 11 of file SeeDeviceUptime.cpp.
{
   uint32_t ms = millis();
   COUT("SeeDeviceUptime::loop() at " << ms);
   uint16_t days = ms / 86400000;
   uint16_t hours = (ms - (days * 86400000)) / 3600000;
   uint16_t minutes = (ms - (days * 86400000) - (hours * 3600000)) / 60000;
   uint16_t seconds = (ms - (days * 86400000) - (hours * 3600000) - (minutes * 60000)) / 1000;
   char buffer[17];
   COUT("days: " << days << "; hours: " << hours << "; mins: " << minutes << "; secs: " << seconds);
   snprintf(buffer, sizeof(buffer), "Up d:%02i %02i:%02i:%02i", days, hours, minutes, seconds);
   LiquidCrystal_TC::instance()->writeLine(DateTime_TC::now().as16CharacterString(), 0);
   LiquidCrystal_TC::instance()->writeLine(buffer, 1);
   COUT(buffer);
 }
References buffer, COUT, LiquidCrystal_TC::instance(), DateTime_TC::now(), and LiquidCrystal_TC::writeLine().
name()
const char* SeeDeviceUptime::name () inline virtual
Implements UIState.
Definition at line 14 of file SeeDeviceUptime.h.
                      {
     return "SeeDeviceUptime";
   }
The documentation for this class was generated from the following files:
src/UIState/SeeDeviceUptime.h
src/UIState/SeeDeviceUptime.cpp