Tank Controller Lib: SetChillOrHeat Class Reference
SetChillOrHeat Class Reference
#include <SetChillOrHeat.h>
Public Member Functions
SetChillOrHeat (TankControllerLib *tc)
virtual bool isInteger ()
const char * name ()
float getCurrentValue ()
const char * prompt ()
void setValue (float value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
void printValue ()
virtual uint16_t getCurrentValuePrecision ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SetChillOrHeat.h
Set if the chiller or heater is used
Definition at line 9 of file SetChillOrHeat.h.
Constructor & Destructor Documentation
SetChillOrHeat()
SetChillOrHeat::SetChillOrHeat (TankControllerLib * tc) inline
Definition at line 11 of file SetChillOrHeat.h.
                                         : NumCollectorState(tc) {
   }
Member Function Documentation
getCurrentValue()
float SetChillOrHeat::getCurrentValue () virtual
SetChillOrHeat.cpp
Implements NumCollectorState.
Definition at line 11 of file SetChillOrHeat.cpp.
{
   return EEPROM_TC::instance()->getHeat() ? 9 : 1;
 }
References EEPROM_TC::getHeat(), and EEPROM_TC::instance().
isInteger()
virtual bool SetChillOrHeat::isInteger () inline virtual
Reimplemented from NumCollectorState.
Definition at line 13 of file SetChillOrHeat.h.
{
     return true;
   }
name()
const char* SetChillOrHeat::name () inline virtual
Implements UIState.
Definition at line 16 of file SetChillOrHeat.h.
                      {
     return "SetChillOrHeat";
   }
prompt()
const char* SetChillOrHeat::prompt () inline virtual
Reimplemented from UIState.
Definition at line 20 of file SetChillOrHeat.h.
{
     return "1:Chill; 9:Heat";
   };
setValue()
void SetChillOrHeat::setValue (float value) virtual
Implements NumCollectorState.
Definition at line 15 of file SetChillOrHeat.cpp.
{
   if (!(value == 1.0 || value == 9.0)) {
     LiquidCrystal_TC::instance()->writeLine("Invalid entry!  ", 1);
   } else {
     bool isHeat = (uint16_t)value == 9;
     TemperatureControl::instance()->enableHeater(isHeat);
     if (isHeat) {
       LiquidCrystal_TC::instance()->writeLine("Use heater      ", 1);
     } else {
       LiquidCrystal_TC::instance()->writeLine("Use chiller     ", 1);
     }
   }
   returnToMainMenu(3000);  // after 1-second delay
 }
References TemperatureControl::enableHeater(), TemperatureControl::instance(), LiquidCrystal_TC::instance(), UIState::returnToMainMenu(), NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SetChillOrHeat.h
src/UIState/SetChillOrHeat.cpp