Tank Controller Lib: NumCollectorState Class Reference
NumCollectorState Class Reference abstract
#include <NumberCollectorState.h>
Public Member Functions
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void setValue (float value)=0
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
Protected Member Functions
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
virtual float getCurrentValue ()=0
virtual uint16_t getCurrentValuePrecision ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
Abstract superclass for the NumberCollector UI states
Definition at line 8 of file NumberCollectorState.h.
Constructor & Destructor Documentation
NumCollectorState()
NumCollectorState::NumCollectorState (TankControllerLib * tc) inline
Definition at line 10 of file NumberCollectorState.h.
                                            : UIState(tc) {
   }
Member Function Documentation
backSpace()
void NumCollectorState::backSpace () protected
Definition at line 45 of file NumberCollectorState.cpp.
{
   if (hasDecimal && factor == 10) {
     hasDecimal = false;
   } else if (hasDecimal) {
     numDigits--;
     factor = factor / 10;
     // we use factor/10 because factor is set to the next decimal not the current entered one
     value = floor(value * factor / 10) / (factor / 10);
   } else {
     numDigits--;
     value = floor(value / 10);
   }
 }
References factor, hasDecimal, numDigits, and value.
Referenced by handleKey().
clear()
void NumCollectorState::clear () protected
Definition at line 11 of file NumberCollectorState.cpp.
{
   hasDecimal = false;
   numDigits = 0;
   value = 0;
 }
References hasDecimal, numDigits, and value.
Referenced by handleKey(), and SetTime::setValue().
getCurrentValue()
virtual float NumCollectorState::getCurrentValue () protected pure virtual
Implemented in TemperatureCalibration, SetTime, SetTempSetPoint, SetTankID, SetPHSetPoint, SetKP, SetKI, SetKD, SetGoogleSheetInterval, SetChillOrHeat, PHCalibration, and EnablePID.
Referenced by printValue().
getCurrentValuePrecision()
virtual uint16_t NumCollectorState::getCurrentValuePrecision () inline protected virtual
Reimplemented in TemperatureCalibration, SetTempSetPoint, SetPHSetPoint, SetKP, SetKI, SetKD, and PHCalibration.
Definition at line 26 of file NumberCollectorState.h.
{
     return 0;
   };
Referenced by printValue().
handleDigit()
void NumCollectorState::handleDigit (uint16_t digit) protected
Definition at line 36 of file NumberCollectorState.cpp.
{
   if (hasDecimal) {
     value = value + (float)digit / factor;
     factor = factor * 10;
   } else {
     value = value * 10 + digit;
   }
 }
References factor, hasDecimal, and value.
Referenced by handleKey().
handleKey()
void NumCollectorState::handleKey (char key) virtual
Reimplemented from UIState.
Definition at line 17 of file NumberCollectorState.cpp.
{
   if (key >= '0' && key <= '9') {  // a digit
     numDigits++;
     handleDigit(key - '0');
   } else if (key == '*') {  // Decimal place (if we already have a decimal nothing happens)
     hasDecimal = !isInteger();
   } else if (key == 'A') {  // Accept
     setValue(value);
     return;                 // don't print the value again
   } else if (key == 'B') {  // Backspace
     backSpace();
   } else if (key == 'C') {  // Clear
     clear();
   } else if (key == 'D') {  // Disregard (escape/cancel)
     returnToMainMenu();
   }
   printValue();
 }
References backSpace(), clear(), handleDigit(), hasDecimal, isInteger(), key(), numDigits, printValue(), UIState::returnToMainMenu(), setValue(), and value.
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
isInteger()
virtual bool NumCollectorState::isInteger () inline protected virtual
Reimplemented in SetTime, SetTankID, SetGoogleSheetInterval, SetChillOrHeat, and EnablePID.
Definition at line 21 of file NumberCollectorState.h.
{
     return false;
   }
Referenced by handleKey().
printValue()
void NumCollectorState::printValue () protected
Definition at line 59 of file NumberCollectorState.cpp.
{
   char format[20], strValue[20];
   // The Arduino does not support variable widths, so we construct the format string at runtime!
   snprintf_P(format, sizeof(format), (PGM_P)F("%%7.%if->"), getCurrentValuePrecision());
   snprintf(strValue, sizeof(strValue), format, getCurrentValue());
   if (!hasDecimal) {
     // show user entry as an integer (no decimal yet)
     snprintf_P(format, sizeof(format), (PGM_P)F("%s%%6i"), strValue);
     snprintf(strValue, sizeof(strValue), format, (uint32_t)value);
   } else if (factor == 10) {
     // show user entry with a decimal but nothing beyond
     snprintf_P(format, sizeof(format), (PGM_P)F("%s%%6i."), strValue);
     snprintf(strValue, sizeof(strValue), format, (uint32_t)value);
   } else {
     // show user entry with appropriate precision (based on digits user has entered)
     uint16_t precision = log10(factor / 10);
     snprintf_P(format, sizeof(format), (PGM_P)F("%s%%7.%if"), strValue, precision);
     snprintf(strValue, sizeof(strValue), format, value);
   }
   LiquidCrystal_TC::instance()->writeLine(strValue, 1);
 }
References factor, getCurrentValue(), getCurrentValuePrecision(), hasDecimal, LiquidCrystal_TC::instance(), value, and LiquidCrystal_TC::writeLine().
Referenced by handleKey(), PHCalibration::loop(), and start().
setValue()
virtual void NumCollectorState::setValue (float value) pure virtual
Implemented in TemperatureCalibration, SetTime, SetTempSetPoint, SetTankID, SetPHSetPoint, SetKP, SetKI, SetKD, SetGoogleSheetInterval, SetChillOrHeat, PHCalibrationMid, PHCalibrationLow, PHCalibrationHigh, and EnablePID.
Referenced by handleKey().
start()
void NumCollectorState::start () virtual
Reimplemented from UIState.
Definition at line 82 of file NumberCollectorState.cpp.
{
   UIState::start();
   printValue();
 }
References printValue(), and UIState::start().
Referenced by SetTime::setValue().
Member Data Documentation
factor
uint16_t NumCollectorState::factor = 10 protected
Definition at line 32 of file NumberCollectorState.h.
Referenced by backSpace(), handleDigit(), and printValue().
hasDecimal
bool NumCollectorState::hasDecimal = false protected
Definition at line 33 of file NumberCollectorState.h.
Referenced by backSpace(), clear(), handleDigit(), handleKey(), and printValue().
numDigits
uint16_t NumCollectorState::numDigits = 0 protected
Definition at line 31 of file NumberCollectorState.h.
Referenced by backSpace(), clear(), and handleKey().
value
float NumCollectorState::value = 0.0 protected
Definition at line 30 of file NumberCollectorState.h.
Referenced by backSpace(), clear(), handleDigit(), handleKey(), printValue(), EnablePID::setValue(), PHCalibrationHigh::setValue(), PHCalibrationLow::setValue(), PHCalibrationMid::setValue(), SetChillOrHeat::setValue(), SetGoogleSheetInterval::setValue(), SetKD::setValue(), SetKI::setValue(), SetKP::setValue(), SetPHSetPoint::setValue(), SetTankID::setValue(), SetTempSetPoint::setValue(), SetTime::setValue(), and TemperatureCalibration::setValue().
The documentation for this class was generated from the following files:
src/UIState/NumberCollectorState.h
src/UIState/NumberCollectorState.cpp