Tank Controller Lib: Heater Class Reference
Heater Class Reference
#include <TemperatureControl.h>
Public Member Functions
Heater ()
bool isHeater ()
void updateControl (float currentTemperature)
Public Member Functions inherited from TemperatureControl
virtual ~TemperatureControl ()
float getTargetTemperature ()
float getCurrentTemperatureTarget ()
uint32_t getPhRampTimeStart ()
uint32_t getPhRampTimeEnd ()
bool isOn ()
void setTargetTemperature (float newTemperature)
void setRampDuration (float newTempRampDuration)
Additional Inherited Members
Static Public Member Functions inherited from TemperatureControl
static TemperatureControl * instance ()
static void clearInstance ()
static void enableHeater (bool flag)
Protected Member Functions inherited from TemperatureControl
TemperatureControl ()
Protected Attributes inherited from TemperatureControl
const uint16_t TEMP_CONTROL_PIN = 47
const float DELTA = 0.05
uint32_t lastSwitchMS = 0
float targetTemperature
float currentTemperatureTarget
float rampStartingTemp
uint32_t rampTimeStart
uint32_t rampTimeEnd
Detailed Description
Definition at line 52 of file TemperatureControl.h.
Constructor & Destructor Documentation
Heater()
Heater::Heater () inline
Definition at line 54 of file TemperatureControl.h.
 : TemperatureControl(){};
Member Function Documentation
isHeater()
bool Heater::isHeater () inline virtual
is heater
Reimplemented from TemperatureControl.
Definition at line 55 of file TemperatureControl.h.
                   {
     return true;
   }
updateControl()
void Heater::updateControl (float currentTemperature) virtual
Implements TemperatureControl.
Definition at line 179 of file TemperatureControl.cpp.
{
   float currentTime = DateTime_TC::now().secondstime();
   // if ramp is being used
   if (currentTime < rampTimeEnd) {
     currentTemperatureTarget =
         rampStartingTemp +
         ((currentTime - rampTimeStart) * (targetTemperature - rampStartingTemp) / (rampTimeEnd - rampTimeStart));
   } else {
     currentTemperatureTarget = targetTemperature;
   }
   COUT("Heater::updateControl(" << currentTemperature);
   bool oldValue = digitalRead(TEMP_CONTROL_PIN);
   bool newValue;
   // if in calibration, turn unit off
   if (TankController::instance()->isInCalibration()) {
     newValue = TURN_SOLENOID_OFF;
   }
   // if the observed temperature is below the temperature set-point range turn on the heater
   else if (currentTemperature <= currentTemperatureTarget - DELTA) {
     newValue = TURN_SOLENOID_ON;
   }
   // if the observed temperature is above the temperature set-point range turn off the heater
   else if (currentTemperature >= currentTemperatureTarget + DELTA) {
     newValue = TURN_SOLENOID_OFF;
   } else {
     newValue = oldValue;
     COUT("Heater update at " << millis() << " ignored due to recent change in state");
   }
   if (newValue != oldValue) {
     uint32_t currentMS = millis();
     serial(F("heater turned %s at %lu after %lu ms"), newValue ? "off" : "on", currentMS, currentMS - lastSwitchMS);
     lastSwitchMS = currentMS;
     digitalWrite(TEMP_CONTROL_PIN, newValue);
   }
 }
References COUT, TemperatureControl::currentTemperatureTarget, TemperatureControl::DELTA, TankController::instance(), TemperatureControl::lastSwitchMS, DateTime_TC::now(), TemperatureControl::rampStartingTemp, TemperatureControl::rampTimeEnd, TemperatureControl::rampTimeStart, serial(), TemperatureControl::targetTemperature, TemperatureControl::TEMP_CONTROL_PIN, TURN_SOLENOID_OFF, and TURN_SOLENOID_ON.
The documentation for this class was generated from the following files:
src/Devices/TemperatureControl.h
src/Devices/TemperatureControl.cpp