Tank Controller Lib: SetKP Class Reference
SetKP Class Reference
#include <SetKP.h>
Public Member Functions
SetKP (TankController *tc)
const __FlashStringHelper * name ()
float getCurrentValue ()
uint16_t getCurrentValuePrecision ()
const __FlashStringHelper * prompt ()
void setValue (float value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankController *tc)
void handleKey (char key)
virtual void setValue (float value)=0
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
virtual float getCurrentValue ()=0
virtual uint16_t getCurrentValuePrecision ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
SetKP.h
Set the KP for the PID
Definition at line 10 of file SetKP.h.
Constructor & Destructor Documentation
SetKP()
SetKP::SetKP (TankController * tc) inline
Definition at line 12 of file SetKP.h.
                            : NumCollectorState(tc) {
  }
Member Function Documentation
getCurrentValue()
float SetKP::getCurrentValue () inline virtual
Implements NumCollectorState.
Definition at line 17 of file SetKP.h.
{
    return EEPROM_TC::instance()->getKP();
  }
References EEPROM_TC::getKP(), and EEPROM_TC::instance().
getCurrentValuePrecision()
uint16_t SetKP::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 20 of file SetKP.h.
{
    return 1;
  }
name()
const __FlashStringHelper * SetKP::name () inline virtual
Implements UIState.
Definition at line 14 of file SetKP.h.
{
    return F("SetKP");
  }
prompt()
const __FlashStringHelper * SetKP::prompt () inline virtual
Reimplemented from UIState.
Definition at line 23 of file SetKP.h.
{
    return F("Set KP");
  };
setValue()
void SetKP::setValue (float value) virtual
SetKP.cpp
Implements NumCollectorState.
Definition at line 9 of file SetKP.cpp.
{
  PID_TC::instance()->setKp(value);
  char output[17];
  snprintf_P(output, sizeof(output), (PGM_P)F("New KP=%i.%i"), (int)value, (int)(value * 10 + 0.5) % 10);
  LiquidCrystal_TC::instance()->writeLine(output, 1);
  returnToMainMenu(3000);
}
References PID_TC::instance(), LiquidCrystal_TC::instance(), UIState::returnToMainMenu(), PID_TC::setKp(), NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SetKP.h
src/UIState/SetKP.cpp