Tank Controller Lib: SetTime Class Reference
SetTime Class Reference
#include <SetTime.h>
Public Member Functions
SetTime (TankControllerLib *tc)
virtual bool isInteger ()
const __FlashStringHelper * name ()
float getCurrentValue ()
const __FlashStringHelper * prompt ()
void setValue (float value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Private Attributes
uint16_t subState = 0
uint16_t values [NUM_VALUES] = {0, 0, 0, 0, 0}
float current [NUM_VALUES] = {0.0, 0.0, 0.0, 0.0, 0.0}
const __FlashStringHelper * prompts [NUM_VALUES]
Static Private Attributes
static const uint16_t NUM_VALUES = 5
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
void printValue ()
virtual uint16_t getCurrentValuePrecision ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SetTime.h
Manually set the Arduino date and time
Definition at line 9 of file SetTime.h.
Constructor & Destructor Documentation
SetTime()
SetTime::SetTime (TankControllerLib * tc)
SetTime.cpp
Definition at line 12 of file SetTime.cpp.
                                       : NumCollectorState(tc) {
   prompts[0] = F("Set Year (YYYY):");
   prompts[1] = F("Month (1-12):");
   prompts[2] = F("Day (1-31):");
   prompts[3] = F("Hour (0-23):    ");
   prompts[4] = F("Minute (0-59):  ");
 }
References prompts.
Member Function Documentation
getCurrentValue()
float SetTime::getCurrentValue () virtual
Implements NumCollectorState.
Definition at line 20 of file SetTime.cpp.
{
   if (subState == 0) {
     // initialize current values with current date time
     DateTime_TC now = DateTime_TC::now();
     current[0] = now.year();
     current[1] = now.month();
     current[2] = now.day();
     current[3] = now.hour();
     current[4] = now.minute();
   }
   return current[subState];
 }
References current, DateTime_TC::now(), and subState.
isInteger()
virtual bool SetTime::isInteger () inline virtual
Reimplemented from NumCollectorState.
Definition at line 12 of file SetTime.h.
{
     return true;
   }
name()
const __FlashStringHelper* SetTime::name () inline virtual
Implements UIState.
Definition at line 15 of file SetTime.h.
{
     return F("SetTime");
   }
prompt()
const __FlashStringHelper* SetTime::prompt () inline virtual
Reimplemented from UIState.
Definition at line 20 of file SetTime.h.
{
     return prompts[subState];
   }
References prompts, and subState.
setValue()
void SetTime::setValue (float value) virtual
Implements NumCollectorState.
Definition at line 33 of file SetTime.cpp.
{
   values[subState++] = value;
   if (subState < NUM_VALUES) {
     clear();
     start();
   } else {
     DateTime_TC dt(values[0], values[1], values[2], values[3], values[4]);
     dt.setAsCurrent();
     char* buffer = DateTime_TC::now().as16CharacterString();
     serial(F("Set time to %s"), buffer);
     LiquidCrystal_TC::instance()->writeLine(F("New Date/Time:"), 0);
     LiquidCrystal_TC::instance()->writeLine(buffer, 1);
     returnToMainMenu(3000);  // after 3-second delay
   }
 }
References DateTime_TC::as16CharacterString(), buffer, NumCollectorState::clear(), LiquidCrystal_TC::instance(), DateTime_TC::now(), NUM_VALUES, UIState::returnToMainMenu(), serial(), DateTime_TC::setAsCurrent(), NumCollectorState::start(), subState, NumCollectorState::value, values, and LiquidCrystal_TC::writeLine().
Member Data Documentation
current
float SetTime::current[NUM_VALUES] = {0.0, 0.0, 0.0, 0.0, 0.0} private
Definition at line 29 of file SetTime.h.
Referenced by getCurrentValue().
NUM_VALUES
const uint16_t SetTime::NUM_VALUES = 5 static private
Definition at line 26 of file SetTime.h.
Referenced by setValue().
prompts
const __FlashStringHelper* SetTime::prompts[NUM_VALUES] private
Definition at line 30 of file SetTime.h.
Referenced by prompt(), and SetTime().
subState
uint16_t SetTime::subState = 0 private
Definition at line 27 of file SetTime.h.
Referenced by getCurrentValue(), prompt(), and setValue().
values
uint16_t SetTime::values[NUM_VALUES] = {0, 0, 0, 0, 0} private
Definition at line 28 of file SetTime.h.
Referenced by setValue().
The documentation for this class was generated from the following files:
src/UIState/SetTime.h
src/UIState/SetTime.cpp