Tank Controller Lib: TemperatureControl Class Reference
TemperatureControl Class Reference abstract
#include <TemperatureControl.h>
Public Member Functions
virtual ~TemperatureControl ()
float getTargetTemperature ()
virtual bool isHeater ()
bool isOn ()
void setTargetTemperature (float newTemperature)
virtual void updateControl (float currentTemperature)=0
Static Public Member Functions
static TemperatureControl * instance ()
static void enableHeater (bool flag)
Protected Member Functions
TemperatureControl ()
Protected Attributes
const uint16_t TEMP_CONTROL_PIN = 47
const float DELTA = 0.05
uint32_t lastSwitchMS = 0
float targetTemperature
Static Private Attributes
static TemperatureControl * _instance = nullptr
Detailed Description
Temperature Control Controlling the tank temperature is done by external devices that are controlled by setting designated pins on the Arduino.
Definition at line 12 of file TemperatureControl.h.
Constructor & Destructor Documentation
TemperatureControl()
TemperatureControl::TemperatureControl () protected
protected constructor
Definition at line 44 of file TemperatureControl.cpp.
{
   COUT("TemperatureControl()");
   targetTemperature = EEPROM_TC::instance()->getTemp();
   if (isnan(targetTemperature)) {
     targetTemperature = DEFAULT_TEMPERATURE;
     EEPROM_TC::instance()->setTemp(targetTemperature);
   }
   pinMode(TEMP_CONTROL_PIN, OUTPUT);
   digitalWrite(TEMP_CONTROL_PIN, TURN_SOLENOID_OFF);
   serial("%s starts with solenoid off with target temperature of %5.2f C", this->isHeater() ? "Heater" : "Chiller",
          targetTemperature);
 }
References COUT, DEFAULT_TEMPERATURE, EEPROM_TC::getTemp(), EEPROM_TC::instance(), isHeater(), serial(), EEPROM_TC::setTemp(), targetTemperature, TEMP_CONTROL_PIN, and TURN_SOLENOID_OFF.
~TemperatureControl()
virtual TemperatureControl::~TemperatureControl () inline virtual
Definition at line 24 of file TemperatureControl.h.
{
   }
Member Function Documentation
enableHeater()
void TemperatureControl::enableHeater (bool flag) static
Definition at line 31 of file TemperatureControl.cpp.
{
   EEPROM_TC::instance()->setHeat(flag);
   if (_instance && (_instance->isHeater() != flag)) {
     delete _instance;
     _instance = nullptr;
     serial("TemperatureControl::enableHeater(%s)", flag ? "true" : "false");
     instance();
   }
 }
References _instance, EEPROM_TC::instance(), instance(), isHeater(), serial(), and EEPROM_TC::setHeat().
Referenced by SetChillOrHeat::setValue(), unittest(), and unittest_setup().
getTargetTemperature()
float TemperatureControl::getTargetTemperature () inline
Definition at line 28 of file TemperatureControl.h.
{
     return targetTemperature;
   }
References targetTemperature.
Referenced by MainMenu::idle(), and TankControllerLib::writeDataToSD().
instance()
TemperatureControl * TemperatureControl::instance () static
static member function to return singleton
Definition at line 20 of file TemperatureControl.cpp.
{
   if (!_instance) {
     if (EEPROM_TC::instance()->getHeat()) {
       _instance = new Heater();
     } else {
       _instance = new Chiller();
     }
   }
   return _instance;
 }
References _instance, and EEPROM_TC::instance().
Referenced by enableHeater(), MainMenu::idle(), SetChillOrHeat::setValue(), SetTempSetPoint::setValue(), TankControllerLib::TankControllerLib(), unittest(), unittest_setup(), TankControllerLib::updateControls(), and TankControllerLib::writeDataToSD().
isHeater()
bool TemperatureControl::isHeater () virtual
is heater
Reimplemented in Chiller, and Heater.
Definition at line 60 of file TemperatureControl.cpp.
{
   return true;
 }
Referenced by enableHeater(), MainMenu::idle(), and TemperatureControl().
isOn()
bool TemperatureControl::isOn ()
Definition at line 64 of file TemperatureControl.cpp.
{
   return digitalRead(TEMP_CONTROL_PIN) == TURN_SOLENOID_ON;
 }
References TEMP_CONTROL_PIN, and TURN_SOLENOID_ON.
Referenced by MainMenu::idle(), and unittest().
setTargetTemperature()
void TemperatureControl::setTargetTemperature (float newTemperature)
set target temperature and save in EEPROM
Definition at line 71 of file TemperatureControl.cpp.
{
   if (targetTemperature != newTemperature) {
     serial("Change target temperature from %5.2f to %5.2f", targetTemperature, newTemperature);
     EEPROM_TC::instance()->setTemp(newTemperature);
     targetTemperature = newTemperature;
   }
 }
References EEPROM_TC::instance(), serial(), EEPROM_TC::setTemp(), and targetTemperature.
Referenced by SetTempSetPoint::setValue(), unittest(), and unittest_setup().
updateControl()
virtual void TemperatureControl::updateControl (float currentTemperature) pure virtual
Implemented in Chiller, and Heater.
Referenced by unittest(), and TankControllerLib::updateControls().
Member Data Documentation
_instance
TemperatureControl * TemperatureControl::_instance = nullptr static private
static variable for singleton
Definition at line 14 of file TemperatureControl.h.
Referenced by enableHeater(), and instance().
DELTA
const float TemperatureControl::DELTA = 0.05 protected
Definition at line 18 of file TemperatureControl.h.
Referenced by Heater::updateControl(), and Chiller::updateControl().
lastSwitchMS
uint32_t TemperatureControl::lastSwitchMS = 0 protected
Definition at line 19 of file TemperatureControl.h.
Referenced by Heater::updateControl(), and Chiller::updateControl().
targetTemperature
float TemperatureControl::targetTemperature protected
Definition at line 20 of file TemperatureControl.h.
Referenced by getTargetTemperature(), setTargetTemperature(), TemperatureControl(), Heater::updateControl(), and Chiller::updateControl().
TEMP_CONTROL_PIN
const uint16_t TemperatureControl::TEMP_CONTROL_PIN = 47 protected
Definition at line 17 of file TemperatureControl.h.
Referenced by isOn(), TemperatureControl(), Heater::updateControl(), and Chiller::updateControl().
The documentation for this class was generated from the following files:
src/Devices/TemperatureControl.h
src/Devices/TemperatureControl.cpp