Tank Controller Lib: PID_TC Class Reference
PID_TC Class Reference
#include <PID_TC.h>
Public Member Functions
float computeOutput (float target, float current)
float getKd ()
float getKi ()
float getKp ()
uint16_t getMode ()
void logToSerial ()
void setKd (float Kd)
void setKi (float Ki)
void setKp (float Kp)
void setTunings (float Kp, float Ki, float Kd)
Static Public Member Functions
static PID_TC * instance ()
static void reset ()
Private Member Functions
PID_TC ()
~PID_TC ()
Private Attributes
double input = 0.0
double output = 0.0
double set_point = 0.0
const uint16_t WINDOW_SIZE = 10000
PID * pPID
Static Private Attributes
static PID_TC * _instance = nullptr
Detailed Description
Definition at line 4 of file PID_TC.h.
Constructor & Destructor Documentation
PID_TC()
PID_TC::PID_TC () private
Definition at line 27 of file PID_TC.cpp.
                {
   float Kp, Ki, Kd;
   EEPROM_TC *eeprom = EEPROM_TC::instance();
   Kp = eeprom->getKP();
   Ki = eeprom->getKI();
   Kd = eeprom->getKD();
   if (isnan(Kp)) {
     Kp = 100000;
     eeprom->setKP(Kp);
   }
   if (isnan(Ki)) {
     Ki = 0;
     eeprom->setKI(Ki);
   }
   if (isnan(Kd)) {
     Kd = 0;
     eeprom->setKD(Kd);
   }
   pPID = new PID(&input, &output, &set_point, Kp, Ki, Kd,
                  REVERSE);  // Starting the PID, Specify the links and initial
                             // tuning parameters
   pPID->SetMode(AUTOMATIC);
   pPID->SetSampleTime(1000);
   pPID->SetOutputLimits(0, WINDOW_SIZE);
 }
References eeprom(), input, EEPROM_TC::instance(), output, pPID, set_point, and WINDOW_SIZE.
Referenced by instance().
~PID_TC()
PID_TC::~PID_TC () private
Definition at line 54 of file PID_TC.cpp.
                 {
   if (pPID) {
     delete pPID;
     pPID = nullptr;
   }
 }
References pPID.
Member Function Documentation
computeOutput()
float PID_TC::computeOutput (float target, float current)
Definition at line 62 of file PID_TC.cpp.
{
   if (TankControllerLib::instance()->isInCalibration()) {
     // current value will likely be wrong during calibration, so don't make any changes
     return static_cast<float>(output);
   }
   set_point = static_cast<float>(target);
   input = static_cast<double>(current);
   pPID->Compute();
   return static_cast<float>(static_cast<float>(output));
 }
References input, TankControllerLib::instance(), output, pPID, and set_point.
Referenced by unittest(), and PHControl::updateControl().
getKd()
float PID_TC::getKd () inline
Definition at line 11 of file PID_TC.h.
                 {
     return pPID->GetKd();
   }
References pPID.
Referenced by setKi(), setKp(), unittest(), and TankControllerLib::writeDataToSD().
getKi()
float PID_TC::getKi () inline
Definition at line 14 of file PID_TC.h.
                 {
     return pPID->GetKi();
   }
References pPID.
Referenced by setKd(), setKp(), unittest(), and TankControllerLib::writeDataToSD().
getKp()
float PID_TC::getKp () inline
Definition at line 17 of file PID_TC.h.
                 {
     return pPID->GetKp();
   }
References pPID.
Referenced by setKd(), setKi(), unittest(), and TankControllerLib::writeDataToSD().
getMode()
uint16_t PID_TC::getMode () inline
Definition at line 20 of file PID_TC.h.
                      {
     return pPID->GetMode();
   }
References pPID.
Referenced by unittest().
instance()
PID_TC * PID_TC::instance () static
Definition at line 12 of file PID_TC.cpp.
{
   if (!_instance) {
     _instance = new PID_TC();
   }
   return _instance;
 }
References _instance, and PID_TC().
Referenced by SeePIDConstants::loadKd(), SeePIDConstants::loadKi(), SeePIDConstants::loadKp(), SetKD::setValue(), SetKI::setValue(), SetKP::setValue(), unittest(), PHControl::updateControl(), and TankControllerLib::writeDataToSD().
logToSerial()
void PID_TC::logToSerial ()
Definition at line 73 of file PID_TC.cpp.
{
   serial(F("Kp: %6.1f Ki: %6.1f Kd: %6.1f\r\nPID output (s):%4.1f"), pPID->GetKp(), pPID->GetKi(), pPID->GetKd(),
          static_cast<float>(output) / 1000);
 }
References output, pPID, and serial().
Referenced by unittest().
reset()
void PID_TC::reset () static
Definition at line 19 of file PID_TC.cpp.
                    {
   if (_instance) {
     delete _instance;
     _instance = nullptr;
   }
 }
References _instance.
Referenced by unittest_setup().
setKd()
void PID_TC::setKd (float Kd)
Definition at line 78 of file PID_TC.cpp.
{
   pPID->SetTunings(getKp(), getKi(), Kd);
   EEPROM_TC::instance()->setKD(Kd);
 }
References getKi(), getKp(), EEPROM_TC::instance(), pPID, and EEPROM_TC::setKD().
Referenced by SetKD::setValue(), and unittest().
setKi()
void PID_TC::setKi (float Ki)
Definition at line 83 of file PID_TC.cpp.
{
   pPID->SetTunings(getKp(), Ki, getKd());
   EEPROM_TC::instance()->setKI(Ki);
 }
References getKd(), getKp(), EEPROM_TC::instance(), pPID, and EEPROM_TC::setKI().
Referenced by SetKI::setValue(), and unittest().
setKp()
void PID_TC::setKp (float Kp)
Definition at line 88 of file PID_TC.cpp.
{
   pPID->SetTunings(Kp, getKi(), getKd());
   EEPROM_TC::instance()->setKP(Kp);
 }
References getKd(), getKi(), EEPROM_TC::instance(), pPID, and EEPROM_TC::setKP().
Referenced by SetKP::setValue(), and unittest().
setTunings()
void PID_TC::setTunings (float Kp, float Ki, float Kd)
Definition at line 93 of file PID_TC.cpp.
{
   pPID->SetTunings(Kp, Ki, Kd);
 }
References pPID.
Referenced by unittest().
Member Data Documentation
_instance
PID_TC * PID_TC::_instance = nullptr static private
Definition at line 31 of file PID_TC.h.
Referenced by instance(), and reset().
input
double PID_TC::input = 0.0 private
Definition at line 37 of file PID_TC.h.
Referenced by computeOutput(), and PID_TC().
output
double PID_TC::output = 0.0 private
Definition at line 38 of file PID_TC.h.
Referenced by computeOutput(), logToSerial(), and PID_TC().
pPID
PID* PID_TC::pPID private
Definition at line 41 of file PID_TC.h.
Referenced by computeOutput(), getKd(), getKi(), getKp(), getMode(), logToSerial(), PID_TC(), setKd(), setKi(), setKp(), setTunings(), and ~PID_TC().
set_point
double PID_TC::set_point = 0.0 private
Definition at line 39 of file PID_TC.h.
Referenced by computeOutput(), and PID_TC().
WINDOW_SIZE
const uint16_t PID_TC::WINDOW_SIZE = 10000 private
Definition at line 40 of file PID_TC.h.
Referenced by PID_TC().
The documentation for this class was generated from the following files:
src/Devices/PID_TC.h
src/Devices/PID_TC.cpp