Tank Controller Lib: EEPROM_TC_3 Class Reference
EEPROM_TC_3 Class Reference
#include <EEPROM_TC_3.h>
Public Member Functions
double getAmplitude ()
double getCorrectedTemp ()
double getFrequency ()
int getGoogleSheetInterval ()
double getGranularity ()
bool getHeat ()
double getKD ()
double getKI ()
double getKP ()
double getMac ()
double getMaxDataAge ()
double getPH ()
double getPHDelay ()
double getPHInterval ()
double getPHSeriesPointer ()
double getPHSeriesSize ()
int getTankID ()
double getTemp ()
double getTempDelay ()
double getTempInterval ()
double getTempSeriesPointer ()
double getTempSeriesSize ()
int getVersion ()
void setAmplitude (double value)
void setCorrectedTemp (double value)
void setFrequency (double value)
void setGoogleSheetInterval (int value)
void setGranularity (double value)
void setHeat (bool value)
void setKD (double value)
void setKI (double value)
void setKP (double value)
void setMac (double value)
void setMaxDataAge (double value)
void setPH (double value)
void setPHDelay (double value)
void setPHInterval (double value)
void setPHSeriesPointer (double value)
void setPHSeriesSize (double value)
void setTankID (int value)
void setTemp (double value)
void setTempDelay (double value)
void setTempInterval (double value)
void setTempSeriesPointer (double value)
void setTempSeriesSize (double value)
void setVersion ()
Public Member Functions inherited from EEPROM_TC
virtual ~EEPROM_TC ()
double eepromReadDouble (int address)
int eepromReadInt (int address)
void eepromWriteDouble (int address, double value)
void eepromWriteInt (int address, int value)
Protected Member Functions
virtual bool isRightVersion ()
Private Attributes
const int VERSION_ADDRESS = 0
const int TANK_ID_ADDRESS = VERSION_ADDRESS + 4
const int HEAT_ADDRESS = TANK_ID_ADDRESS + 4
const int PH_ADDRESS = HEAT_ADDRESS + 4
const int TEMP_ADDRESS = PH_ADDRESS + 8
const int TEMP_CORR_ADDRESS = TEMP_ADDRESS + 8
const int KP_ADDRESS = TEMP_CORR_ADDRESS + 8
const int KI_ADDRESS = KP_ADDRESS + 8
const int KD_ADDRESS = KI_ADDRESS + 8
const int MAC_ADDRESS = KD_ADDRESS + 8
const int AMPLITUDE_ADDRESS = MAC_ADDRESS + 8
const int FREQUENCY_ADDRESS = AMPLITUDE_ADDRESS + 8
const int GRANULARITY_ADDRESS = FREQUENCY_ADDRESS + 8
const int MAX_DATA_AGE_ADDRESS = GRANULARITY_ADDRESS + 8
const int PH_SERIES_SIZE_ADDRESS = MAX_DATA_AGE_ADDRESS + 8
const int PH_SERIES_POINTER_ADDRESS = PH_SERIES_SIZE_ADDRESS + 8
const int TEMP_SERIES_SIZE_ADDRESS = PH_SERIES_POINTER_ADDRESS + 8
const int TEMP_SERIES_POINTER_ADDRESS = TEMP_SERIES_SIZE_ADDRESS + 8
const int PH_INTERVAL_ADDRESS = TEMP_SERIES_POINTER_ADDRESS + 8
const int PH_DELAY_ADDRESS = PH_INTERVAL_ADDRESS + 8
const int TEMP_INTERVAL_ADDRESS = PH_DELAY_ADDRESS + 8
const int TEMP_DELAY_ADDRESS = TEMP_INTERVAL_ADDRESS + 8
const int GOOGLE_INTERVAL_ADDRESS = TEMP_DELAY_ADDRESS + 8
Additional Inherited Members
Static Public Member Functions inherited from EEPROM_TC
static EEPROM_TC * instance (int version=0)
Detailed Description
Definition at line 5 of file EEPROM_TC_3.h.
Member Function Documentation
getAmplitude()
double EEPROM_TC_3::getAmplitude () virtual
Implements EEPROM_TC.
Definition at line 13 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(AMPLITUDE_ADDRESS);
 }
References AMPLITUDE_ADDRESS, and EEPROM_TC::eepromReadDouble().
getCorrectedTemp()
double EEPROM_TC_3::getCorrectedTemp () virtual
Implements EEPROM_TC.
Definition at line 16 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(TEMP_CORR_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_CORR_ADDRESS.
getFrequency()
double EEPROM_TC_3::getFrequency () virtual
Implements EEPROM_TC.
Definition at line 19 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(FREQUENCY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and FREQUENCY_ADDRESS.
getGoogleSheetInterval()
int EEPROM_TC_3::getGoogleSheetInterval () virtual
Implements EEPROM_TC.
Definition at line 22 of file EEPROM_TC_3.cpp.
{
   return eepromReadInt(GOOGLE_INTERVAL_ADDRESS);
 }
References EEPROM_TC::eepromReadInt(), and GOOGLE_INTERVAL_ADDRESS.
getGranularity()
double EEPROM_TC_3::getGranularity () virtual
Implements EEPROM_TC.
Definition at line 25 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(GRANULARITY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and GRANULARITY_ADDRESS.
getHeat()
bool EEPROM_TC_3::getHeat () virtual
Implements EEPROM_TC.
Definition at line 28 of file EEPROM_TC_3.cpp.
{
   return (bool)eepromReadInt(HEAT_ADDRESS);
 }
References EEPROM_TC::eepromReadInt(), and HEAT_ADDRESS.
getKD()
double EEPROM_TC_3::getKD () virtual
Implements EEPROM_TC.
Definition at line 31 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(KD_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and KD_ADDRESS.
getKI()
double EEPROM_TC_3::getKI () virtual
Implements EEPROM_TC.
Definition at line 34 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(KI_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and KI_ADDRESS.
getKP()
double EEPROM_TC_3::getKP () virtual
Implements EEPROM_TC.
Definition at line 37 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(KP_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and KP_ADDRESS.
getMac()
double EEPROM_TC_3::getMac () virtual
Implements EEPROM_TC.
Definition at line 40 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(MAC_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and MAC_ADDRESS.
getMaxDataAge()
double EEPROM_TC_3::getMaxDataAge () virtual
Implements EEPROM_TC.
Definition at line 43 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(MAX_DATA_AGE_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and MAX_DATA_AGE_ADDRESS.
getPH()
double EEPROM_TC_3::getPH () virtual
Implements EEPROM_TC.
Definition at line 46 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(PH_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_ADDRESS.
getPHDelay()
double EEPROM_TC_3::getPHDelay () virtual
Implements EEPROM_TC.
Definition at line 49 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(PH_DELAY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_DELAY_ADDRESS.
getPHInterval()
double EEPROM_TC_3::getPHInterval () virtual
Implements EEPROM_TC.
Definition at line 52 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(PH_INTERVAL_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_INTERVAL_ADDRESS.
getPHSeriesPointer()
double EEPROM_TC_3::getPHSeriesPointer () virtual
Implements EEPROM_TC.
Definition at line 55 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(PH_SERIES_POINTER_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_SERIES_POINTER_ADDRESS.
getPHSeriesSize()
double EEPROM_TC_3::getPHSeriesSize () virtual
Implements EEPROM_TC.
Definition at line 58 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(PH_SERIES_SIZE_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and PH_SERIES_SIZE_ADDRESS.
getTankID()
int EEPROM_TC_3::getTankID () virtual
Implements EEPROM_TC.
Definition at line 61 of file EEPROM_TC_3.cpp.
{
   return eepromReadInt(TANK_ID_ADDRESS);
 }
References EEPROM_TC::eepromReadInt(), and TANK_ID_ADDRESS.
getTemp()
double EEPROM_TC_3::getTemp () virtual
Implements EEPROM_TC.
Definition at line 64 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(TEMP_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_ADDRESS.
getTempDelay()
double EEPROM_TC_3::getTempDelay () virtual
Implements EEPROM_TC.
Definition at line 67 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(TEMP_DELAY_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_DELAY_ADDRESS.
getTempInterval()
double EEPROM_TC_3::getTempInterval () virtual
Implements EEPROM_TC.
Definition at line 70 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(TEMP_INTERVAL_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_INTERVAL_ADDRESS.
getTempSeriesPointer()
double EEPROM_TC_3::getTempSeriesPointer () virtual
Implements EEPROM_TC.
Definition at line 73 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(TEMP_SERIES_POINTER_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_SERIES_POINTER_ADDRESS.
getTempSeriesSize()
double EEPROM_TC_3::getTempSeriesSize () virtual
Implements EEPROM_TC.
Definition at line 76 of file EEPROM_TC_3.cpp.
{
   return eepromReadDouble(TEMP_SERIES_SIZE_ADDRESS);
 }
References EEPROM_TC::eepromReadDouble(), and TEMP_SERIES_SIZE_ADDRESS.
getVersion()
int EEPROM_TC_3::getVersion () virtual
Implements EEPROM_TC.
Definition at line 79 of file EEPROM_TC_3.cpp.
{
   int result = eepromReadInt(VERSION_ADDRESS);
   if (result == -1) {
     // the initial value in EEPROM is -1, so we are starting clean
     setVersion();
     result = eepromReadInt(VERSION_ADDRESS);
   }
   return result;
 }
References EEPROM_TC::eepromReadInt(), setVersion(), and VERSION_ADDRESS.
Referenced by isRightVersion().
isRightVersion()
bool EEPROM_TC_3::isRightVersion () protected virtual
Implements EEPROM_TC.
Definition at line 6 of file EEPROM_TC_3.cpp.
{
   int version = getVersion();
   // the initial value in EEPROM is -1, so we are starting clean
   return version == -1 || version == 3;
 }
References getVersion(), and version().
setAmplitude()
void EEPROM_TC_3::setAmplitude (double value) virtual
Implements EEPROM_TC.
Definition at line 90 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(AMPLITUDE_ADDRESS, value);
 }
References AMPLITUDE_ADDRESS, EEPROM_TC::eepromWriteDouble(), and value.
setCorrectedTemp()
void EEPROM_TC_3::setCorrectedTemp (double value) virtual
Implements EEPROM_TC.
Definition at line 93 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(TEMP_CORR_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_CORR_ADDRESS, and value.
setFrequency()
void EEPROM_TC_3::setFrequency (double value) virtual
Implements EEPROM_TC.
Definition at line 96 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(FREQUENCY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), FREQUENCY_ADDRESS, and value.
setGoogleSheetInterval()
void EEPROM_TC_3::setGoogleSheetInterval (int value) virtual
Implements EEPROM_TC.
Definition at line 99 of file EEPROM_TC_3.cpp.
{
   eepromWriteInt(GOOGLE_INTERVAL_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteInt(), GOOGLE_INTERVAL_ADDRESS, and value.
setGranularity()
void EEPROM_TC_3::setGranularity (double value) virtual
Implements EEPROM_TC.
Definition at line 102 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(GRANULARITY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), GRANULARITY_ADDRESS, and value.
setHeat()
void EEPROM_TC_3::setHeat (bool value) virtual
Implements EEPROM_TC.
Definition at line 105 of file EEPROM_TC_3.cpp.
{
   eepromWriteInt(HEAT_ADDRESS, (int)value);
 }
References EEPROM_TC::eepromWriteInt(), HEAT_ADDRESS, and value.
setKD()
void EEPROM_TC_3::setKD (double value) virtual
Implements EEPROM_TC.
Definition at line 108 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(KD_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), KD_ADDRESS, and value.
setKI()
void EEPROM_TC_3::setKI (double value) virtual
Implements EEPROM_TC.
Definition at line 111 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(KI_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), KI_ADDRESS, and value.
setKP()
void EEPROM_TC_3::setKP (double value) virtual
Implements EEPROM_TC.
Definition at line 114 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(KP_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), KP_ADDRESS, and value.
setMac()
void EEPROM_TC_3::setMac (double value) virtual
Implements EEPROM_TC.
Definition at line 117 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(MAC_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), MAC_ADDRESS, and value.
setMaxDataAge()
void EEPROM_TC_3::setMaxDataAge (double value) virtual
Implements EEPROM_TC.
Definition at line 120 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(MAX_DATA_AGE_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), MAX_DATA_AGE_ADDRESS, and value.
setPH()
void EEPROM_TC_3::setPH (double value) virtual
Implements EEPROM_TC.
Definition at line 123 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(PH_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_ADDRESS, and value.
setPHDelay()
void EEPROM_TC_3::setPHDelay (double value) virtual
Implements EEPROM_TC.
Definition at line 126 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(PH_DELAY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_DELAY_ADDRESS, and value.
setPHInterval()
void EEPROM_TC_3::setPHInterval (double value) virtual
Implements EEPROM_TC.
Definition at line 129 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(PH_INTERVAL_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_INTERVAL_ADDRESS, and value.
setPHSeriesPointer()
void EEPROM_TC_3::setPHSeriesPointer (double value) virtual
Implements EEPROM_TC.
Definition at line 132 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(PH_SERIES_POINTER_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_SERIES_POINTER_ADDRESS, and value.
setPHSeriesSize()
void EEPROM_TC_3::setPHSeriesSize (double value) virtual
Implements EEPROM_TC.
Definition at line 135 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(PH_SERIES_SIZE_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), PH_SERIES_SIZE_ADDRESS, and value.
setTankID()
void EEPROM_TC_3::setTankID (int value) virtual
Implements EEPROM_TC.
Definition at line 138 of file EEPROM_TC_3.cpp.
{
   eepromWriteInt(TANK_ID_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteInt(), TANK_ID_ADDRESS, and value.
setTemp()
void EEPROM_TC_3::setTemp (double value) virtual
Implements EEPROM_TC.
Definition at line 141 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(TEMP_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_ADDRESS, and value.
setTempDelay()
void EEPROM_TC_3::setTempDelay (double value) virtual
Implements EEPROM_TC.
Definition at line 144 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(TEMP_DELAY_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_DELAY_ADDRESS, and value.
setTempInterval()
void EEPROM_TC_3::setTempInterval (double value) virtual
Implements EEPROM_TC.
Definition at line 147 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(TEMP_INTERVAL_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_INTERVAL_ADDRESS, and value.
setTempSeriesPointer()
void EEPROM_TC_3::setTempSeriesPointer (double value) virtual
Implements EEPROM_TC.
Definition at line 150 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(TEMP_SERIES_POINTER_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_SERIES_POINTER_ADDRESS, and value.
setTempSeriesSize()
void EEPROM_TC_3::setTempSeriesSize (double value) virtual
Implements EEPROM_TC.
Definition at line 153 of file EEPROM_TC_3.cpp.
{
   eepromWriteDouble(TEMP_SERIES_SIZE_ADDRESS, value);
 }
References EEPROM_TC::eepromWriteDouble(), TEMP_SERIES_SIZE_ADDRESS, and value.
setVersion()
void EEPROM_TC_3::setVersion () virtual
Implements EEPROM_TC.
Definition at line 156 of file EEPROM_TC_3.cpp.
{
   eepromWriteInt(VERSION_ADDRESS, 3);
 }
References EEPROM_TC::eepromWriteInt(), and VERSION_ADDRESS.
Referenced by getVersion().
Member Data Documentation
AMPLITUDE_ADDRESS
const int EEPROM_TC_3::AMPLITUDE_ADDRESS = MAC_ADDRESS + 8 private
Definition at line 75 of file EEPROM_TC_3.h.
Referenced by getAmplitude(), and setAmplitude().
FREQUENCY_ADDRESS
const int EEPROM_TC_3::FREQUENCY_ADDRESS = AMPLITUDE_ADDRESS + 8 private
Definition at line 76 of file EEPROM_TC_3.h.
Referenced by getFrequency(), and setFrequency().
GOOGLE_INTERVAL_ADDRESS
const int EEPROM_TC_3::GOOGLE_INTERVAL_ADDRESS = TEMP_DELAY_ADDRESS + 8 private
Definition at line 88 of file EEPROM_TC_3.h.
Referenced by getGoogleSheetInterval(), and setGoogleSheetInterval().
GRANULARITY_ADDRESS
const int EEPROM_TC_3::GRANULARITY_ADDRESS = FREQUENCY_ADDRESS + 8 private
Definition at line 77 of file EEPROM_TC_3.h.
Referenced by getGranularity(), and setGranularity().
HEAT_ADDRESS
const int EEPROM_TC_3::HEAT_ADDRESS = TANK_ID_ADDRESS + 4 private
Definition at line 66 of file EEPROM_TC_3.h.
Referenced by getHeat(), and setHeat().
KD_ADDRESS
const int EEPROM_TC_3::KD_ADDRESS = KI_ADDRESS + 8 private
Definition at line 72 of file EEPROM_TC_3.h.
Referenced by getKD(), and setKD().
KI_ADDRESS
const int EEPROM_TC_3::KI_ADDRESS = KP_ADDRESS + 8 private
Definition at line 71 of file EEPROM_TC_3.h.
Referenced by getKI(), and setKI().
KP_ADDRESS
const int EEPROM_TC_3::KP_ADDRESS = TEMP_CORR_ADDRESS + 8 private
Definition at line 70 of file EEPROM_TC_3.h.
Referenced by getKP(), and setKP().
MAC_ADDRESS
const int EEPROM_TC_3::MAC_ADDRESS = KD_ADDRESS + 8 private
Definition at line 73 of file EEPROM_TC_3.h.
Referenced by getMac(), and setMac().
MAX_DATA_AGE_ADDRESS
const int EEPROM_TC_3::MAX_DATA_AGE_ADDRESS = GRANULARITY_ADDRESS + 8 private
Definition at line 78 of file EEPROM_TC_3.h.
Referenced by getMaxDataAge(), and setMaxDataAge().
PH_ADDRESS
const int EEPROM_TC_3::PH_ADDRESS = HEAT_ADDRESS + 4 private
Definition at line 67 of file EEPROM_TC_3.h.
Referenced by getPH(), and setPH().
PH_DELAY_ADDRESS
const int EEPROM_TC_3::PH_DELAY_ADDRESS = PH_INTERVAL_ADDRESS + 8 private
Definition at line 84 of file EEPROM_TC_3.h.
Referenced by getPHDelay(), and setPHDelay().
PH_INTERVAL_ADDRESS
const int EEPROM_TC_3::PH_INTERVAL_ADDRESS = TEMP_SERIES_POINTER_ADDRESS + 8 private
Definition at line 83 of file EEPROM_TC_3.h.
Referenced by getPHInterval(), and setPHInterval().
PH_SERIES_POINTER_ADDRESS
const int EEPROM_TC_3::PH_SERIES_POINTER_ADDRESS = PH_SERIES_SIZE_ADDRESS + 8 private
Definition at line 80 of file EEPROM_TC_3.h.
Referenced by getPHSeriesPointer(), and setPHSeriesPointer().
PH_SERIES_SIZE_ADDRESS
const int EEPROM_TC_3::PH_SERIES_SIZE_ADDRESS = MAX_DATA_AGE_ADDRESS + 8 private
Definition at line 79 of file EEPROM_TC_3.h.
Referenced by getPHSeriesSize(), and setPHSeriesSize().
TANK_ID_ADDRESS
const int EEPROM_TC_3::TANK_ID_ADDRESS = VERSION_ADDRESS + 4 private
Definition at line 65 of file EEPROM_TC_3.h.
Referenced by getTankID(), and setTankID().
TEMP_ADDRESS
const int EEPROM_TC_3::TEMP_ADDRESS = PH_ADDRESS + 8 private
Definition at line 68 of file EEPROM_TC_3.h.
Referenced by getTemp(), and setTemp().
TEMP_CORR_ADDRESS
const int EEPROM_TC_3::TEMP_CORR_ADDRESS = TEMP_ADDRESS + 8 private
Definition at line 69 of file EEPROM_TC_3.h.
Referenced by getCorrectedTemp(), and setCorrectedTemp().
TEMP_DELAY_ADDRESS
const int EEPROM_TC_3::TEMP_DELAY_ADDRESS = TEMP_INTERVAL_ADDRESS + 8 private
Definition at line 86 of file EEPROM_TC_3.h.
Referenced by getTempDelay(), and setTempDelay().
TEMP_INTERVAL_ADDRESS
const int EEPROM_TC_3::TEMP_INTERVAL_ADDRESS = PH_DELAY_ADDRESS + 8 private
Definition at line 85 of file EEPROM_TC_3.h.
Referenced by getTempInterval(), and setTempInterval().
TEMP_SERIES_POINTER_ADDRESS
const int EEPROM_TC_3::TEMP_SERIES_POINTER_ADDRESS = TEMP_SERIES_SIZE_ADDRESS + 8 private
Definition at line 82 of file EEPROM_TC_3.h.
Referenced by getTempSeriesPointer(), and setTempSeriesPointer().
TEMP_SERIES_SIZE_ADDRESS
const int EEPROM_TC_3::TEMP_SERIES_SIZE_ADDRESS = PH_SERIES_POINTER_ADDRESS + 8 private
Definition at line 81 of file EEPROM_TC_3.h.
Referenced by getTempSeriesSize(), and setTempSeriesSize().
VERSION_ADDRESS
const int EEPROM_TC_3::VERSION_ADDRESS = 0 private
Definition at line 62 of file EEPROM_TC_3.h.
Referenced by getVersion(), and setVersion().
The documentation for this class was generated from the following files:
src/Devices/EEPROM_TC_3.h
src/Devices/EEPROM_TC_3.cpp