Tank Controller Lib: TempProbe_TC Class Reference
TempProbe_TC Class Reference
#include <TempProbe_TC.h>
Public Member Functions
uint16_t getResistance ()
float getRawTemperature ()
float getRunningAverage ()
float getUncorrectedRunningAverage ()
uint8_t readFault ()
void clearFault ()
void setCorrection (float value)
Static Public Member Functions
static TempProbe_TC * instance ()
static void reset ()
Private Member Functions
TempProbe_TC ()
Private Attributes
Adafruit_MAX31865 thermo = Adafruit_MAX31865(45, 43, 41, 39)
bool firstTime = true
float history [HISTORY_SIZE]
uint16_t historyIndex = 0
float correction = 0.0
uint32_t lastTime = 0
Static Private Attributes
static TempProbe_TC * _instance = nullptr
static const uint16_t RTDnominal = 100
static const uint16_t refResistor = 430
static const uint16_t HISTORY_SIZE = 10
Detailed Description
Adafruit MAX31865 The Adafruit MAX31865 is an external device that connects to a thermocouple (temperature sensor), and has pins that can be used to read a resistance, temperature, or fault. The associated library has a simple API as described below.
Device I/O: This device has 5 pins: Vin (3V or 5V power supply, the same as the microcontroler), GND (Ground), CLK (Clock), SDO (MOSI: Master Out Slave In), SDI (MISO: Master In Slave Out), and CS (Slave Select).
Connection with the thermocouple: The Adafruit MAX31865 can connect to three different types of thermocouples, two wire, three wire, or four wire. You'll need to look at the sensor's documentation to find the wiring requirements. The board has four pins used for connection with the thermocouple, they are labeled on the board: RTD+ (Resistance Positive), RTD- (Resistance Negative), F+ (Fault Plus), and F- (Fault Negative).
Using Adafruit MAX31865 There are 5 functions needed to use Adafruit MAX31865: the constructor, begin(), readRTD() (Read Resistance), temperature(), readFault(), and clearFault().
Here is a description of those functions:
Constructor: To use the constructor you will have to set which pins you want to use, the functions are labeled below. Adafruit_MAX31865 thermo = Adafruit_MAX31865(CS (Slave Select), DI (MOSI), DO (MISO), CLK (Clock));
Begin: Call this after calling the constructor and before anything else. Returns true if successful. Default is a 2 wire thermocouple but you can specify 2,3, and 4 wire by passing in MAX31865_2WIRE, MAX31865_3WIRE, and MAX31865_4WIRE. bool successful = thermo.begin(max31865_numwires_t x = MAX31865_2WIRE);
Read Resistance: Returns the resistance of the device. uint16_t rtd = thermo.readRTD();
Get Temperature: To get the temperature you will need to know the Nominal Resistance, and the Resistor Reference of your temperature sensor. This must be set according to your thermocouple. Read your thermocouple manual to find these values. float temp = thermo.temperature(float RTDnominal, float refResistor)
Read Fault: Returns a fault number in hex. You can compare with returned fault with the default fault values given below uint8_t fault = thermo.readFault();
Faults: MAX31865_FAULT_HIGHTHRESH (RTD High Threshold) MAX31865_FAULT_LOWTHRESH (RTD Low Threshold) MAX31865_FAULT_REFINLOW (REFIN- > 0.85 x Bias) MAX31865_FAULT_REFINHIGH (REFIN- < 0.85 x Bias - FORCE- open) MAX31865_FAULT_RTDINLOW (RTDIN- < 0.85 x Bias - FORCE- open) MAX31865_FAULT_OVUV (Under/Over Voltage)
Clear Fault: Once Fault is read clear fault so that it returns to its default state of 0 which is no fault. thermo.clearFault();
How to use the Device: To use the device you must call the constructor, call begin, and then you can either call readRTD(), or temperature(). Once you have read either, or both you can check for a fault, use the data accordingly, and then clear the fault before reading again.
How to use this TempProbe_TC class: Call the constructor TempProbe_TC tempProbe = TempProbe_TC(); Since this class is build for Tank Controller class, it will automatically set the device to a three wire thermocouple, set the pins that the tank controller has delegated for it, and it has values for RTDnominal, and the refResistor. This class is pretty straightforward and you can the functions and how to call them below.
Definition at line 89 of file TempProbe_TC.h.
Constructor & Destructor Documentation
TempProbe_TC()
TempProbe_TC::TempProbe_TC () private
constructor (private so clients use the singleton)
Definition at line 36 of file TempProbe_TC.cpp.
{
   // Start pt100 temperature probe with 3 wire configuration
   thermo.begin(MAX31865_3WIRE);
   // load offset from EEPROM
   correction = EEPROM_TC::instance()->getCorrectedTemp();
   if (isnan(correction)) {
     correction = 0;
     EEPROM_TC::instance()->setCorrectedTemp(correction);
   }
   serial("Temperature probe with correction of %6.3f", correction);
 }
References correction, EEPROM_TC::getCorrectedTemp(), EEPROM_TC::instance(), serial(), EEPROM_TC::setCorrectedTemp(), and thermo.
Referenced by instance().
Member Function Documentation
clearFault()
void TempProbe_TC::clearFault () inline
Definition at line 112 of file TempProbe_TC.h.
                     {
     thermo.clearFault();
   }
References thermo.
Referenced by unittest().
getRawTemperature()
float TempProbe_TC::getRawTemperature () inline
Definition at line 98 of file TempProbe_TC.h.
{
     return thermo.temperature(RTDnominal, refResistor);
   }
References refResistor, RTDnominal, and thermo.
Referenced by getUncorrectedRunningAverage(), and unittest().
getResistance()
uint16_t TempProbe_TC::getResistance () inline
Definition at line 94 of file TempProbe_TC.h.
{
     return thermo.readRTD();
   }
References thermo.
Referenced by unittest().
getRunningAverage()
float TempProbe_TC::getRunningAverage () inline
Definition at line 102 of file TempProbe_TC.h.
{
     return getUncorrectedRunningAverage() + correction;
   }
References correction, and getUncorrectedRunningAverage().
Referenced by getTemperature(), MainMenu::idle(), PushingBox::sendData(), unittest(), unittest_setup(), and TankControllerLib::writeDataToSerial().
getUncorrectedRunningAverage()
float TempProbe_TC::getUncorrectedRunningAverage ()
getUncorrectedRunningAverage()
Read the current temperature and return a running average. Do this only once per second since device is unreliable beyond that.
Definition at line 55 of file TempProbe_TC.cpp.
{
   uint32_t currentTime = millis();
   if (firstTime || lastTime + 1000 <= currentTime) {
     float temp = this->getRawTemperature();
     if (firstTime) {
       for (size_t i = 0; i < HISTORY_SIZE; ++i) {
         history[i] = temp;
       }
       firstTime = false;
     }
     historyIndex = (historyIndex + 1) % HISTORY_SIZE;
     history[historyIndex] = temp;
     lastTime = currentTime;
   }
   float sum = 0.0;
   for (size_t i = 0; i < HISTORY_SIZE; ++i) {
     sum += history[i];
   }
   return sum / HISTORY_SIZE;
 }
References firstTime, getRawTemperature(), history, HISTORY_SIZE, historyIndex, and lastTime.
Referenced by getRunningAverage(), and TemperatureCalibration::setValue().
instance()
TempProbe_TC * TempProbe_TC::instance () static
static member function to return singleton
Definition at line 18 of file TempProbe_TC.cpp.
{
   if (!_instance) {
     _instance = new TempProbe_TC();
   }
   return _instance;
 }
References _instance, and TempProbe_TC().
Referenced by getTemperature(), MainMenu::idle(), PushingBox::sendData(), setTemperature(), TemperatureCalibration::setValue(), TankControllerLib::TankControllerLib(), unittest(), unittest_setup(), TankControllerLib::updateControls(), TankControllerLib::writeDataToSD(), and TankControllerLib::writeDataToSerial().
readFault()
uint8_t TempProbe_TC::readFault () inline
Definition at line 108 of file TempProbe_TC.h.
                       {
     return thermo.readFault();
   }
References thermo.
Referenced by unittest().
reset()
void TempProbe_TC::reset () static
Definition at line 25 of file TempProbe_TC.cpp.
{
   if (_instance) {
     delete _instance;
     _instance = nullptr;
   }
 }
References _instance.
Referenced by unittest_setup().
setCorrection()
void TempProbe_TC::setCorrection (float value)
setCorrection(float value)
Set a new value for the correction offset
Definition at line 81 of file TempProbe_TC.cpp.
{
   COUT("old = " << correction << "; new = " << value);
   if (value != correction) {
     correction = value;
     EEPROM_TC::instance()->setCorrectedTemp(correction);
     DateTime_TC::now().printToSerial();
     serial("Set temperature correction to %f", correction);
   }
 }
References correction, COUT, EEPROM_TC::instance(), DateTime_TC::now(), DateTime_TC::printToSerial(), serial(), EEPROM_TC::setCorrectedTemp(), and value.
Referenced by TemperatureCalibration::setValue(), unittest(), and unittest_setup().
Member Data Documentation
_instance
TempProbe_TC * TempProbe_TC::_instance = nullptr static private
static variable for singleton
Definition at line 127 of file TempProbe_TC.h.
Referenced by instance(), and reset().
correction
float TempProbe_TC::correction = 0.0 private
Definition at line 137 of file TempProbe_TC.h.
Referenced by getRunningAverage(), setCorrection(), and TempProbe_TC().
firstTime
bool TempProbe_TC::firstTime = true private
Definition at line 133 of file TempProbe_TC.h.
Referenced by getUncorrectedRunningAverage().
history
float TempProbe_TC::history[HISTORY_SIZE] private
Definition at line 135 of file TempProbe_TC.h.
Referenced by getUncorrectedRunningAverage().
HISTORY_SIZE
const uint16_t TempProbe_TC::HISTORY_SIZE = 10 static private
Definition at line 134 of file TempProbe_TC.h.
Referenced by getUncorrectedRunningAverage().
historyIndex
uint16_t TempProbe_TC::historyIndex = 0 private
Definition at line 136 of file TempProbe_TC.h.
Referenced by getUncorrectedRunningAverage().
lastTime
uint32_t TempProbe_TC::lastTime = 0 private
Definition at line 138 of file TempProbe_TC.h.
Referenced by getUncorrectedRunningAverage().
refResistor
const uint16_t TempProbe_TC::refResistor = 430 static private
Definition at line 131 of file TempProbe_TC.h.
Referenced by getRawTemperature().
RTDnominal
const uint16_t TempProbe_TC::RTDnominal = 100 static private
Definition at line 130 of file TempProbe_TC.h.
Referenced by getRawTemperature().
thermo
Adafruit_MAX31865 TempProbe_TC::thermo = Adafruit_MAX31865(45, 43, 41, 39) private
Definition at line 132 of file TempProbe_TC.h.
Referenced by clearFault(), getRawTemperature(), getResistance(), readFault(), and TempProbe_TC().
The documentation for this class was generated from the following files:
src/Devices/TempProbe_TC.h
src/Devices/TempProbe_TC.cpp