Tank Controller Lib: SeeVersion Class Reference
SeeVersion Class Reference
#include <SeeVersion.h>
Public Member Functions
SeeVersion (TankController *tc)
void start ()
const __FlashStringHelper * name ()
const __FlashStringHelper * prompt ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
virtual const __FlashStringHelper * name ()=0
virtual const __FlashStringHelper * prompt ()
virtual void start ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
SeeVersion.h
Display the tankController Version
Definition at line 9 of file SeeVersion.h.
Constructor & Destructor Documentation
SeeVersion()
SeeVersion::SeeVersion (TankController * tc) inline
Definition at line 11 of file SeeVersion.h.
                                 : UIState(tc) {
  }
Member Function Documentation
name()
const __FlashStringHelper * SeeVersion::name () inline virtual
Implements UIState.
Definition at line 14 of file SeeVersion.h.
{
    return F("SeeVersion");
  }
prompt()
const __FlashStringHelper * SeeVersion::prompt () inline virtual
Reimplemented from UIState.
Definition at line 17 of file SeeVersion.h.
{
    return F("Software Version");
  };
Referenced by start().
start()
void SeeVersion::start () virtual
SeeVersion.cpp
Reimplemented from UIState.
Definition at line 10 of file SeeVersion.cpp.
                       {
  LiquidCrystal_TC::instance()->writeLine(prompt(), 0);
  const char* version = TankController::instance()->version();
  LiquidCrystal_TC::instance()->writeLine(version, 1);
}
References TankController::instance(), LiquidCrystal_TC::instance(), prompt(), version(), TankController::version(), and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SeeVersion.h
src/UIState/SeeVersion.cpp