Tank Controller Lib: SetPHWithSine Class Reference
SetPHWithSine Class Reference
#include <SetPHWithSine.h>
Public Member Functions
SetPHWithSine (TankController *tc)
const __FlashStringHelper * name ()
float getCurrentValue ()
uint16_t getCurrentValuePrecision ()
const __FlashStringHelper * prompt ()
void setValue (float value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankController *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankController *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Private Attributes
uint16_t subState = 0
float values [NUM_VALUES] = {0, 0}
const uint16_t precision [NUM_VALUES] = {3, 1}
const __FlashStringHelper * prompts [NUM_VALUES]
Static Private Attributes
static const uint16_t NUM_VALUES = 3
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankController * tc = nullptr
Detailed Description
SetPHWithSine.h
Set the target pH
Definition at line 9 of file SetPHWithSine.h.
Constructor & Destructor Documentation
SetPHWithSine()
SetPHWithSine::SetPHWithSine (TankController * tc)
SetPHWithSine.cpp
Definition at line 10 of file SetPHWithSine.cpp.
                                                : NumCollectorState(tc) {
   prompts[0] = F("Set pH Set Point");
   prompts[1] = F("Set Amplitude:");
   prompts[2] = F("Set Period hrs:");
 }
References prompts.
Member Function Documentation
getCurrentValue()
float SetPHWithSine::getCurrentValue () virtual
Implements NumCollectorState.
Definition at line 16 of file SetPHWithSine.cpp.
{
   if (subState == 0) {
     return PHControl::instance()->getTargetPh();
   } else if (subState == 1) {
     if (PHControl::instance()->getPhSetType() == PHControl::instance()->phSetTypeTypes::SINE_TYPE) {
       return PHControl::instance()->getAmplitude();
     } else {
       return 0.000;
     }
   } else {
     if (PHControl::instance()->getPhSetType() == PHControl::instance()->phSetTypeTypes::SINE_TYPE) {
       return PHControl::instance()->getPeriod() / 3600;
     } else {
       return 0.0;
     }
   }
 }
References PHControl::getAmplitude(), PHControl::getPeriod(), PHControl::getTargetPh(), PHControl::instance(), and subState.
getCurrentValuePrecision()
uint16_t SetPHWithSine::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 16 of file SetPHWithSine.h.
{
     return precision[subState];
   }
References precision, and subState.
name()
const __FlashStringHelper* SetPHWithSine::name () inline virtual
Implements UIState.
Definition at line 12 of file SetPHWithSine.h.
{
     return F("SetPHWithSine");
   }
prompt()
const __FlashStringHelper* SetPHWithSine::prompt () inline virtual
Reimplemented from UIState.
Definition at line 19 of file SetPHWithSine.h.
{
     return prompts[subState];
   };
References prompts, and subState.
setValue()
void SetPHWithSine::setValue (float value) virtual
Implements NumCollectorState.
Definition at line 34 of file SetPHWithSine.cpp.
{
   values[subState++] = value;
   if (subState < NUM_VALUES) {
     clear();
     start();
   } else {
     PHControl::instance()->setTargetPh(values[0]);
     PHControl::instance()->setSine(values[1], values[2]);
     char output0[17];
     char temp1[8];
     char temp2[9];
     char output1[17];
     snprintf_P(output0, sizeof(output0), (PGM_P)F("New pH=%i.%i"), (int)values[0],
                (int)(values[0] * 1000 + 0.5) % 1000);
     snprintf_P(temp1, sizeof(temp1), (PGM_P)F("A=%i.%i"), (int)values[1], (int)(values[1] * 1000) % 1000);
     snprintf_P(temp2, sizeof(temp2), (PGM_P)F(" P=%i.%i"), (int)values[2], (int)(values[2] * 1000) % 1000);
     snprintf_P(output1, sizeof(output1), (PGM_P)F("%s%s"), (const char*)temp1, (const char*)temp2);
     LiquidCrystal_TC::instance()->writeLine(output0, 0);
     LiquidCrystal_TC::instance()->writeLine(output1, 1);
     returnToMainMenu(3000);  // after 3-second delay
   }
 }
References NumCollectorState::clear(), PHControl::instance(), LiquidCrystal_TC::instance(), NUM_VALUES, UIState::returnToMainMenu(), PHControl::setSine(), PHControl::setTargetPh(), NumCollectorState::start(), subState, NumCollectorState::value, values, and LiquidCrystal_TC::writeLine().
Member Data Documentation
NUM_VALUES
const uint16_t SetPHWithSine::NUM_VALUES = 3 static private
Definition at line 25 of file SetPHWithSine.h.
Referenced by setValue().
precision
const uint16_t SetPHWithSine::precision[NUM_VALUES] = {3, 1} private
Definition at line 28 of file SetPHWithSine.h.
Referenced by getCurrentValuePrecision().
prompts
const __FlashStringHelper* SetPHWithSine::prompts[NUM_VALUES] private
Definition at line 29 of file SetPHWithSine.h.
Referenced by prompt(), and SetPHWithSine().
subState
uint16_t SetPHWithSine::subState = 0 private
Definition at line 26 of file SetPHWithSine.h.
Referenced by getCurrentValue(), getCurrentValuePrecision(), prompt(), and setValue().
values
float SetPHWithSine::values[NUM_VALUES] = {0, 0} private
Definition at line 27 of file SetPHWithSine.h.
Referenced by setValue().
The documentation for this class was generated from the following files:
src/UIState/SetPHWithSine.h
src/UIState/SetPHWithSine.cpp