Tank Controller Lib: SetKI Class Reference
SetKI Class Reference
#include <SetKI.h>
Public Member Functions
SetKI (TankControllerLib *tc)
const char * name ()
const char * prompt ()
void setValue (double value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (int digit)
void printValue ()
virtual bool isInteger ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes inherited from NumCollectorState
double value = 0.0
int numDigits = 0
int factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SetKI.h
Set the KI for the PID
Definition at line 9 of file SetKI.h.
Constructor & Destructor Documentation
SetKI()
SetKI::SetKI (TankControllerLib * tc) inline
Definition at line 11 of file SetKI.h.
                                : NumCollectorState(tc) {
   }
Member Function Documentation
name()
const char* SetKI::name () inline virtual
Implements UIState.
Definition at line 13 of file SetKI.h.
                      {
     return "SetKI";
   }
prompt()
const char* SetKI::prompt () inline virtual
Reimplemented from UIState.
Definition at line 16 of file SetKI.h.
{
     return "Set KI          ";
   };
setValue()
void SetKI::setValue (double value) virtual
SetKI.cpp
Implements NumCollectorState.
Definition at line 9 of file SetKI.cpp.
{
   PID_TC::instance()->setKi(value);
   char output[17];
   snprintf(output, sizeof(output), "New KI=%.1f", value);  // "New KI=12345.5"
   LiquidCrystal_TC::instance()->writeLine(output, 1);
 }
References LiquidCrystal_TC::instance(), PID_TC::instance(), PID_TC::setKi(), NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SetKI.h
src/UIState/SetKI.cpp