Tank Controller Lib: SetPHSetPoint Class Reference
SetPHSetPoint Class Reference
#include <SetPHSetPoint.h>
Public Member Functions
SetPHSetPoint (TankControllerLib *tc)
const char * name ()
float getCurrentValue ()
uint16_t getCurrentValuePrecision ()
const char * prompt ()
void setValue (float value)
Public Member Functions inherited from NumCollectorState
NumCollectorState (TankControllerLib *tc)
void handleKey (char key)
virtual void start ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isInCalibration ()
virtual bool isMainMenu ()
virtual void loop ()
Additional Inherited Members
Protected Member Functions inherited from NumCollectorState
void backSpace ()
void clear ()
void handleDigit (uint16_t digit)
virtual bool isInteger ()
void printValue ()
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (uint16_t msDelay=0)
Protected Attributes inherited from NumCollectorState
float value = 0.0
uint16_t numDigits = 0
uint16_t factor = 10
bool hasDecimal = false
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
SetPHSetPoint.h
Set the target pH
Definition at line 9 of file SetPHSetPoint.h.
Constructor & Destructor Documentation
SetPHSetPoint()
SetPHSetPoint::SetPHSetPoint (TankControllerLib * tc) inline
Definition at line 11 of file SetPHSetPoint.h.
                                        : NumCollectorState(tc) {
   }
Member Function Documentation
getCurrentValue()
float SetPHSetPoint::getCurrentValue () virtual
SetPHSetPoint.cpp
Implements NumCollectorState.
Definition at line 10 of file SetPHSetPoint.cpp.
{
   return PHControl::instance()->getTargetPh();
 }
References PHControl::getTargetPh(), and PHControl::instance().
getCurrentValuePrecision()
uint16_t SetPHSetPoint::getCurrentValuePrecision () inline virtual
Reimplemented from NumCollectorState.
Definition at line 17 of file SetPHSetPoint.h.
{
     return 3;
   }
name()
const char* SetPHSetPoint::name () inline virtual
Implements UIState.
Definition at line 13 of file SetPHSetPoint.h.
                      {
     return "SetPHSetPoint";
   }
prompt()
const char* SetPHSetPoint::prompt () inline virtual
Reimplemented from UIState.
Definition at line 20 of file SetPHSetPoint.h.
{
     return "Set pH Set Point";
   };
setValue()
void SetPHSetPoint::setValue (float value) virtual
Implements NumCollectorState.
Definition at line 14 of file SetPHSetPoint.cpp.
{
   PHControl::instance()->setTargetPh(value);
   char output[17];
   snprintf(output, sizeof(output), "New pH=%.3f", value);
   LiquidCrystal_TC::instance()->writeLine(output, 1);
   returnToMainMenu(3000);  // after 3-second delay
 }
References PHControl::instance(), LiquidCrystal_TC::instance(), UIState::returnToMainMenu(), PHControl::setTargetPh(), NumCollectorState::value, and LiquidCrystal_TC::writeLine().
The documentation for this class was generated from the following files:
src/UIState/SetPHSetPoint.h
src/UIState/SetPHSetPoint.cpp