Tank Controller Lib: PushingBox Class Reference
PushingBox Class Reference
#include <PushingBox.h>
Public Member Functions
EthernetClient * getClient ()
const char * getServer ()
void loop ()
Static Public Member Functions
static PushingBox * instance ()
Private Member Functions
void sendData ()
Private Attributes
EthernetClient client
const char * DevID = "v172D35C152EDA6C"
unsigned long nextSendTime = 70000
const char * server = "api.pushingbox.com"
Static Private Attributes
static PushingBox * _instance = nullptr
Detailed Description
Definition at line 6 of file PushingBox.h.
Member Function Documentation
getClient()
EthernetClient* PushingBox::getClient () inline
Definition at line 12 of file PushingBox.h.
{
     return &client;
   }
References client.
Referenced by unittest().
getServer()
const char* PushingBox::getServer () inline
Definition at line 15 of file PushingBox.h.
{
     return server;
   }
References server.
Referenced by unittest().
instance()
PushingBox * PushingBox::instance () static
accessor for singleton
Definition at line 17 of file PushingBox.cpp.
{
   if (!_instance) {
     _instance = new PushingBox();
   }
   return _instance;
 }
References _instance.
Referenced by TankControllerLib::loop(), and unittest().
loop()
void PushingBox::loop ()
Definition at line 24 of file PushingBox.cpp.
                       {
   // is it time to send ?
   unsigned long now = millis();
   if (now >= nextSendTime) {
     sendData();
     unsigned long minutes = EEPROM_TC::instance()->getGoogleSheetInterval();
     if (minutes == 0xffff) {
       minutes = 20;
     }
     unsigned long interval = minutes * 60l * 1000l;
     // jump to the next multiple of interval
     nextSendTime = (now / interval + 1) * interval;
   }
   // are we still connected?
   if (client.connected()) {
     // if so, read response
     int next;
     while ((next = client.read()) != -1) {  // Flawfinder: ignore
       Serial.print((char)next);             // print response if any to serial
     }
   } else {
     // will this close every 15 ms?
     client.stop();
   }
 }
References client, EEPROM_TC::getGoogleSheetInterval(), EEPROM_TC::instance(), nextSendTime, and sendData().
Referenced by TankControllerLib::loop().
sendData()
void PushingBox::sendData () private
Definition at line 50 of file PushingBox.cpp.
{
   int tankID = EEPROM_TC::instance()->getTankID();
   if (!tankID) {
     serial("Set Tank ID in order to send data to PushingBox");
     return;
   }
   char format[] =
       "GET /pushingbox?devid=%s&tankid=%i&tempData=%.2f&pHdata=%.3f HTTP/1.1\r\n"
       "Host: api.pushingbox.com\r\n"
       "Connection: close\r\n"
       "\r\n";
   char buffer[200];
   // look up tankid, temperature, ph
   float temperature = TempProbe_TC::instance()->getRunningAverage();
   float pH = PHProbe::instance()->getPh();
   snprintf(buffer, sizeof(buffer), format, DevID, tankID, temperature, pH);
   serial(buffer);
   serial("attempting to connect to PushingBox...");
   if (client.connected() || client.connect(server, 80)) {
     serial("connected");
     client.write(buffer, strnlen(buffer, sizeof(buffer)));
   } else {
     serial("connection failed");
   }
 }
References buffer, client, DevID, PHProbe::getPh(), TempProbe_TC::getRunningAverage(), EEPROM_TC::getTankID(), EEPROM_TC::instance(), PHProbe::instance(), TempProbe_TC::instance(), serial(), and server.
Referenced by loop().
Member Data Documentation
_instance
PushingBox * PushingBox::_instance = nullptr static private
Definition at line 22 of file PushingBox.h.
Referenced by instance().
client
EthernetClient PushingBox::client private
Definition at line 25 of file PushingBox.h.
Referenced by getClient(), loop(), and sendData().
DevID
const char* PushingBox::DevID = "v172D35C152EDA6C" private
Definition at line 26 of file PushingBox.h.
Referenced by sendData().
nextSendTime
unsigned long PushingBox::nextSendTime = 70000 private
Definition at line 28 of file PushingBox.h.
Referenced by loop().
server
const char* PushingBox::server = "api.pushingbox.com" private
Definition at line 29 of file PushingBox.h.
Referenced by getServer(), and sendData().
The documentation for this class was generated from the following files:
src/Devices/PushingBox.h
src/Devices/PushingBox.cpp