Tank Controller Lib: test/DateTimeTest.cpp File Reference
DateTimeTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/DateTime_TC.h"
#include <chrono>
#include <thread>
#include "UIState/UIState.h"
Functions
unittest (singleton)
unittest (constructor)
unittest (now)
unittest (as16CharacterString)
unittest (yearMonthAsPath)
unittest (setAsCurrent)
unittest (printToSerial)
unittest (myDelay)
Function Documentation
unittest() [1/8]
unittest (as16CharacterString)
Definition at line 40 of file DateTimeTest.cpp.
{
   DateTime_TC dateTime = DateTime_TC(2021, 03, 19, 15, 50);
   assertEqual("2021-03-19 15:50", dateTime.as16CharacterString());
 }
References dateTime().
unittest() [2/8]
unittest (constructor)
Definition at line 20 of file DateTimeTest.cpp.
                       {
   DateTime_TC dt(2021, 2, 15, 1, 48, 24);
   assertEqual(2021, dt.year());
   assertEqual(2, dt.month());
   assertEqual(15, dt.day());
   assertEqual(1, dt.hour());
   assertEqual(48, dt.minute());
   assertEqual(24, dt.second());
 }
unittest() [3/8]
unittest (myDelay)
Definition at line 82 of file DateTimeTest.cpp.
                   {
   uint32_t t1 = DateTime_TC::now().unixtime();
   auto start = std::chrono::high_resolution_clock::now();
   std::this_thread::sleep_for(std::chrono::milliseconds(1));
   delay(10000);  // this should be seen by arduino_ci, but not the underlying system
   auto end = std::chrono::high_resolution_clock::now();
   std::chrono::duration<float, std::milli> elapsed = end - start;
   // actual delay should a few milliseconds
   assertTrue(1 <= elapsed.count() && elapsed.count() <= 5);
   uint32_t t2 = DateTime_TC::now().unixtime();
   // simulated delay should be 10 seconds
   assertTrue(t1 + 10 <= t2 && t2 <= t1 + 11);
 }
References DateTime_TC::now().
unittest() [4/8]
unittest (now)
Definition at line 30 of file DateTimeTest.cpp.
               {
   DateTime_TC now = DateTime_TC::now();
   assertTrue(now.year() >= 2020);
   assertTrue(now.month() >= 1);
   assertTrue(now.day() >= 1);
   assertTrue(now.hour() >= 0);
   assertTrue(now.minute() >= 0);
   assertTrue(now.second() >= 0);
 }
References DateTime_TC::now().
unittest() [5/8]
unittest (printToSerial)
Definition at line 66 of file DateTimeTest.cpp.
{
   GodmodeState *state = GODMODE();
   DateTime_TC january(2021, 1, 15, 1, 48, 24);
   january.setAsCurrent();
   state->serialPort[0].dataOut = "";  // the history of data written
   DateTime_TC::now().printToSerial();
   assertEqual("2021-01-15 01:48:24\r\n", state->serialPort[0].dataOut);
 }
References DateTime_TC::now(), DateTime_TC::printToSerial(), DateTime_TC::setAsCurrent(), and state.
unittest() [6/8]
unittest (setAsCurrent)
Definition at line 53 of file DateTimeTest.cpp.
{
   DateTime_TC january(2021, 1, 15, 1, 48, 24);
   january.setAsCurrent();
   DateTime_TC now1 = DateTime_TC::now();
   assertEqual(2021, now1.year());
   assertEqual(1, now1.month());
   assertEqual(15, now1.day());
   assertEqual(1, now1.hour());
   assertEqual(48, now1.minute());
   assertEqual(24, now1.second());
 }
References DateTime_TC::now(), and DateTime_TC::setAsCurrent().
unittest() [7/8]
unittest (singleton)
year has to be range: 2000-2099 following command only runs this test bundle exec arduino_ci.rb –skip-examples-compilation –testfile-select=DateTime.cpp
Definition at line 13 of file DateTimeTest.cpp.
                     {
   DateTime_TC dt(2021, 2, 15, 1, 48, 24);
   RTC_PCF8523 *rtc1 = dt.rtc();
   RTC_PCF8523 *rtc2 = dt.rtc();
   assertEqual(rtc1, rtc2);
 }
References DateTime_TC::rtc().
unittest() [8/8]
unittest (yearMonthAsPath)
Definition at line 46 of file DateTimeTest.cpp.
{
   DateTime_TC date = DateTime_TC(2020, 9, 26);
   char buffer[9];
   date.yearMonthAsPath(buffer, sizeof(buffer));
   assertEqual("/2020/09", buffer);
 }
References buffer, and DateTime_TC::yearMonthAsPath().