Tank Controller Lib: test/EEPROMTest.cpp File Reference
EEPROMTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "EEPROM_TC.h"
Functions
unittest_setup ()
unittest (singleton)
unittest (eeprom_Read_and_Write_Double)
unittest (Ph)
unittest (RampStartingPh)
unittest (RampTimeStart)
unittest (RampTimeEnd)
unittest (Temp)
unittest (RampStartingTemp)
unittest (RampTimeStartTemp)
unittest (RampTimeEndTemp)
unittest (PhSetType)
unittest (PhSineAmplitude)
unittest (PhSineStartTime)
unittest (PhSinePeriod)
unittest (TankID)
unittest (CorrectedTemp)
unittest (KP)
unittest (KI)
unittest (KD)
unittest (Mac)
unittest (Heat)
unittest (Amplitude)
unittest (Frequency)
unittest (Granularity)
unittest (MaxDataAge)
unittest (PhSeriesSize)
unittest (PhSeriesPointer)
unittest (TempSeriesSize)
unittest (TempSeriesPointer)
unittest (PhInterval)
unittest (PhDelay)
unittest (TempInterval)
unittest (TempDelay)
unittest (GoogleSheetIntervalMinutes)
Function Documentation
unittest() [1/34]
unittest (Amplitude)
Definition at line 178 of file EEPROMTest.cpp.
                    {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getAmplitude());
  singleton->setAmplitude(12);
  assertEqual(12, singleton->getAmplitude());
}
References EEPROM_TC::getAmplitude(), EEPROM_TC::instance(), and EEPROM_TC::setAmplitude().
unittest() [2/34]
unittest (CorrectedTemp)
Definition at line 121 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getCorrectedTemp());
  singleton->setCorrectedTemp(6);
  assertEqual(6, singleton->getCorrectedTemp());
}
References EEPROM_TC::getCorrectedTemp(), EEPROM_TC::instance(), and EEPROM_TC::setCorrectedTemp().
unittest() [3/34]
unittest (eeprom_Read_and_Write_Double)
Definition at line 21 of file EEPROMTest.cpp.
{
  EEPROM_TC* test = EEPROM_TC::instance();
  const uint16_t TEST_ADDRESS = 4000;  // beyond the end of our use
  // integer
  test->eepromWriteFloat(TEST_ADDRESS, 10);
  assertEqual(10, test->eepromReadFloat(TEST_ADDRESS));
  // float
  test->eepromWriteFloat(TEST_ADDRESS, 12.25);
  assertEqual(12.25, test->eepromReadFloat(TEST_ADDRESS));
}
References EEPROM_TC::instance().
unittest() [4/34]
unittest (Frequency)
Definition at line 185 of file EEPROMTest.cpp.
                    {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getFrequency());
  singleton->setFrequency(13);
  assertEqual(13, singleton->getFrequency());
}
References EEPROM_TC::getFrequency(), EEPROM_TC::instance(), and EEPROM_TC::setFrequency().
unittest() [5/34]
unittest (GoogleSheetIntervalMinutes)
Definition at line 262 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(65535, singleton->getGoogleSheetInterval());
  singleton->setGoogleSheetInterval(20);
  assertEqual(20, singleton->getGoogleSheetInterval());
}
References EEPROM_TC::getGoogleSheetInterval(), EEPROM_TC::instance(), and EEPROM_TC::setGoogleSheetInterval().
unittest() [6/34]
unittest (Granularity)
Definition at line 192 of file EEPROMTest.cpp.
                      {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getGranularity());
  singleton->setGranularity(14);
  assertEqual(14, singleton->getGranularity());
}
References EEPROM_TC::getGranularity(), EEPROM_TC::instance(), and EEPROM_TC::setGranularity().
unittest() [7/34]
unittest (Heat)
Definition at line 169 of file EEPROMTest.cpp.
               {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertTrue(singleton->getHeat());  // (bool)(-1)
  singleton->setHeat(false);
  assertFalse(singleton->getHeat());
  singleton->setHeat(true);
  assertTrue(singleton->getHeat());
}
References EEPROM_TC::getHeat(), EEPROM_TC::instance(), and EEPROM_TC::setHeat().
unittest() [8/34]
unittest (KD)
Definition at line 142 of file EEPROMTest.cpp.
             {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getKD());
  singleton->setKD(9);
  assertEqual(9, singleton->getKD());
}
References EEPROM_TC::getKD(), EEPROM_TC::instance(), and EEPROM_TC::setKD().
unittest() [9/34]
unittest (KI)
Definition at line 135 of file EEPROMTest.cpp.
             {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getKI());
  singleton->setKI(8);
  assertEqual(8, singleton->getKI());
}
References EEPROM_TC::getKI(), EEPROM_TC::instance(), and EEPROM_TC::setKI().
unittest() [10/34]
unittest (KP)
Definition at line 128 of file EEPROMTest.cpp.
             {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getKP());
  singleton->setKP(7);
  assertEqual(7, singleton->getKP());
}
References EEPROM_TC::getKP(), EEPROM_TC::instance(), and EEPROM_TC::setKP().
unittest() [11/34]
unittest (Mac)
Definition at line 149 of file EEPROMTest.cpp.
              {
  uint8_t bytes[6];
  EEPROM_TC* singleton = EEPROM_TC::instance();
  singleton->getMac(bytes);
  for (int i = 0; i < 6; ++i) {
    assertEqual(255, bytes[i]);
  }
  for (int i = 0; i < 6; ++i) {
    bytes[i] = i + 10;
  }
  singleton->setMac(bytes);
  for (int i = 0; i < 6; ++i) {
    bytes[i] = 0;
  }
  singleton->getMac(bytes);
  for (int i = 0; i < 6; ++i) {
    assertEqual(i + 10, bytes[i]);
  }
}
References EEPROM_TC::getMac(), EEPROM_TC::instance(), and EEPROM_TC::setMac().
unittest() [12/34]
unittest (MaxDataAge)
Definition at line 199 of file EEPROMTest.cpp.
                     {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getMaxDataAge());
  singleton->setMaxDataAge(15);
  assertEqual(15, singleton->getMaxDataAge());
}
References EEPROM_TC::getMaxDataAge(), EEPROM_TC::instance(), and EEPROM_TC::setMaxDataAge().
unittest() [13/34]
unittest (Ph)
Definition at line 34 of file EEPROMTest.cpp.
             {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getPh());
  singleton->setPh(3.125);
  assertEqual(3.125, singleton->getPh());
}
References EEPROM_TC::getPh(), EEPROM_TC::instance(), and EEPROM_TC::setPh().
unittest() [14/34]
unittest (PhDelay)
Definition at line 241 of file EEPROMTest.cpp.
                  {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getPhDelay());
  singleton->setPhDelay(21);
  assertEqual(21, singleton->getPhDelay());
}
References EEPROM_TC::getPhDelay(), EEPROM_TC::instance(), and EEPROM_TC::setPhDelay().
unittest() [15/34]
unittest (PhInterval)
Definition at line 234 of file EEPROMTest.cpp.
                     {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getPhInterval());
  singleton->setPhInterval(20);
  assertEqual(20, singleton->getPhInterval());
}
References EEPROM_TC::getPhInterval(), EEPROM_TC::instance(), and EEPROM_TC::setPhInterval().
unittest() [16/34]
unittest (PhSeriesPointer)
Definition at line 213 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getPhSeriesPointer());
  singleton->setPhSeriesPointer(17);
  assertEqual(17, singleton->getPhSeriesPointer());
}
References EEPROM_TC::getPhSeriesPointer(), EEPROM_TC::instance(), and EEPROM_TC::setPhSeriesPointer().
unittest() [17/34]
unittest (PhSeriesSize)
Definition at line 206 of file EEPROMTest.cpp.
                       {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getPhSeriesSize());
  singleton->setPhSeriesSize(16);
  assertEqual(16, singleton->getPhSeriesSize());
}
References EEPROM_TC::getPhSeriesSize(), EEPROM_TC::instance(), and EEPROM_TC::setPhSeriesSize().
unittest() [18/34]
unittest (PhSetType)
Definition at line 89 of file EEPROMTest.cpp.
                    {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0, singleton->getPhSetType());
  singleton->setPhSetType(5);
  assertEqual(5, singleton->getPhSetType());
}
References EEPROM_TC::getPhSetType(), EEPROM_TC::instance(), and EEPROM_TC::setPhSetType().
unittest() [19/34]
unittest (PhSineAmplitude)
Definition at line 95 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getPhSineAmplitude());
  singleton->setPhSineAmplitude(4);
  assertEqual(4, singleton->getPhSineAmplitude());
}
References EEPROM_TC::getPhSineAmplitude(), EEPROM_TC::instance(), and EEPROM_TC::setPhSineAmplitude().
unittest() [20/34]
unittest (PhSinePeriod)
Definition at line 108 of file EEPROMTest.cpp.
                       {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0xFFFFFFFF, singleton->getPhSinePeriod());
  singleton->setPhSinePeriod(987654321);
  assertEqual(987654321, singleton->getPhSinePeriod());
}
References EEPROM_TC::getPhSinePeriod(), EEPROM_TC::instance(), and EEPROM_TC::setPhSinePeriod().
unittest() [21/34]
unittest (PhSineStartTime)
Definition at line 101 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0xFFFFFFFF, singleton->getPhSineStartTime());
  singleton->setPhSineStartTime(123456789);
  assertEqual(123456789, singleton->getPhSineStartTime());
}
References EEPROM_TC::getPhSineStartTime(), EEPROM_TC::instance(), and EEPROM_TC::setPhSineStartTime().
unittest() [22/34]
unittest (RampStartingPh)
Definition at line 41 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getRampStartingPh());
  singleton->setRampStartingPh(4.125);
  assertEqual(4.125, singleton->getRampStartingPh());
}
References EEPROM_TC::getRampStartingPh(), EEPROM_TC::instance(), and EEPROM_TC::setRampStartingPh().
unittest() [23/34]
unittest (RampStartingTemp)
Definition at line 69 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getRampStartingTemp());
  singleton->setRampStartingTemp(4.125);
  assertEqual(4.125, singleton->getRampStartingTemp());
}
References EEPROM_TC::getRampStartingTemp(), EEPROM_TC::instance(), and EEPROM_TC::setRampStartingTemp().
unittest() [24/34]
unittest (RampTimeEnd)
Definition at line 55 of file EEPROMTest.cpp.
                      {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0xFFFFFFFF, singleton->getPhRampTimeEnd());
  singleton->setPhRampTimeEnd(987654321);
  assertEqual(987654321, singleton->getPhRampTimeEnd());
}
References EEPROM_TC::getPhRampTimeEnd(), EEPROM_TC::instance(), and EEPROM_TC::setPhRampTimeEnd().
unittest() [25/34]
unittest (RampTimeEndTemp)
Definition at line 83 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0xFFFFFFFF, singleton->getRampTimeEndTemp());
  singleton->setRampTimeEndTemp(987654321);
  assertEqual(987654321, singleton->getRampTimeEndTemp());
}
References EEPROM_TC::getRampTimeEndTemp(), EEPROM_TC::instance(), and EEPROM_TC::setRampTimeEndTemp().
unittest() [26/34]
unittest (RampTimeStart)
Definition at line 48 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0xFFFFFFFF, singleton->getPhRampTimeStart());
  singleton->setPhRampTimeStart(123456789);
  assertEqual(123456789, singleton->getPhRampTimeStart());
}
References EEPROM_TC::getPhRampTimeStart(), EEPROM_TC::instance(), and EEPROM_TC::setPhRampTimeStart().
unittest() [27/34]
unittest (RampTimeStartTemp)
Definition at line 76 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0xFFFFFFFF, singleton->getRampTimeStartTemp());
  singleton->setRampTimeStartTemp(123456789);
  assertEqual(123456789, singleton->getRampTimeStartTemp());
}
References EEPROM_TC::getRampTimeStartTemp(), EEPROM_TC::instance(), and EEPROM_TC::setRampTimeStartTemp().
unittest() [28/34]
unittest (singleton)
Definition at line 10 of file EEPROMTest.cpp.
                    {
  // Test singleton
  EEPROM_TC* singleton1 = nullptr;
  singleton1 = EEPROM_TC::instance();
  assertNotNull(singleton1);
  EEPROM_TC* singleton2 = nullptr;
  singleton2 = EEPROM_TC::instance();
  assertNotNull(singleton2);
  assertEqual(singleton1, singleton2);
}
References EEPROM_TC::instance().
unittest() [29/34]
unittest (TankID)
Definition at line 114 of file EEPROMTest.cpp.
                 {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertEqual(0, singleton->getTankID());
  singleton->setTankID(5);
  assertEqual(5, singleton->getTankID());
}
References EEPROM_TC::getTankID(), EEPROM_TC::instance(), and EEPROM_TC::setTankID().
unittest() [30/34]
unittest (Temp)
Definition at line 62 of file EEPROMTest.cpp.
               {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getTemp());
  singleton->setTemp(4);
  assertEqual(4, singleton->getTemp());
}
References EEPROM_TC::getTemp(), EEPROM_TC::instance(), and EEPROM_TC::setTemp().
unittest() [31/34]
unittest (TempDelay)
Definition at line 255 of file EEPROMTest.cpp.
                    {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getTempDelay());
  singleton->setTempDelay(23);
  assertEqual(23, singleton->getTempDelay());
}
References EEPROM_TC::getTempDelay(), EEPROM_TC::instance(), and EEPROM_TC::setTempDelay().
unittest() [32/34]
unittest (TempInterval)
Definition at line 248 of file EEPROMTest.cpp.
                       {
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getTempInterval());
  singleton->setTempInterval(22);
  assertEqual(22, singleton->getTempInterval());
}
References EEPROM_TC::getTempInterval(), EEPROM_TC::instance(), and EEPROM_TC::setTempInterval().
unittest() [33/34]
unittest (TempSeriesPointer)
Definition at line 227 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getTempSeriesPointer());
  singleton->setTempSeriesPointer(19);
  assertEqual(19, singleton->getTempSeriesPointer());
}
References EEPROM_TC::getTempSeriesPointer(), EEPROM_TC::instance(), and EEPROM_TC::setTempSeriesPointer().
unittest() [34/34]
unittest (TempSeriesSize)
Definition at line 220 of file EEPROMTest.cpp.
{
  EEPROM_TC* singleton = EEPROM_TC::instance();
  assertNAN(singleton->getTempSeriesSize());
  singleton->setTempSeriesSize(18);
  assertEqual(18, singleton->getTempSeriesSize());
}
References EEPROM_TC::getTempSeriesSize(), EEPROM_TC::instance(), and EEPROM_TC::setTempSeriesSize().
unittest_setup()
unittest_setup ()
Definition at line 6 of file EEPROMTest.cpp.
                 {
  GODMODE()->resetEEPROM();
}