Tank Controller Lib: test/EnablePIDTest.cpp File Reference
EnablePIDTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "Devices/PHControl.h"
#include "EnablePID.h"
#include "TankControllerLib.h"
Functions
unittest (IgnoreInvalidCharacter)
unittest (DisablePID)
unittest (EnablePID)
Function Documentation
unittest() [1/3]
unittest (DisablePID)
Definition at line 20 of file EnablePIDTest.cpp.
                      {
   TankControllerLib* tc = TankControllerLib::instance();
   EnablePID* test = new EnablePID(tc);
   tc->setNextState(test, true);
   assertEqual("EnablePID", tc->stateName());
   test->setValue(9.0);
   assertFalse(PHControl::instance()->getUsePID());
   assertEqual("EnablePID", tc->stateName());
   tc->loop();  // transition to Wait
   assertEqual("Wait", tc->stateName());
   delay(3000);
   tc->loop();  // after the delay, Wait will call setNextState
   tc->loop();  // now transition back to main
   assertEqual("MainMenu", tc->stateName());
 }
References PHControl::instance(), TankControllerLib::instance(), TankControllerLib::loop(), TankControllerLib::setNextState(), TankControllerLib::stateName(), and tc.
unittest() [2/3]
unittest (EnablePID)
Definition at line 36 of file EnablePIDTest.cpp.
                     {
   TankControllerLib* tc = TankControllerLib::instance();
   EnablePID* test = new EnablePID(tc);
   tc->setNextState(test, true);
   assertEqual("EnablePID", tc->stateName());
   test->setValue(1.0);
   assertTrue(PHControl::instance()->getUsePID());
   assertEqual("EnablePID", tc->stateName());
   tc->loop();  // transition to Wait
   assertEqual("Wait", tc->stateName());
   delay(3000);
   tc->loop();  // after the delay, Wait will call setNextState
   tc->loop();  // now transition back to main
   assertEqual("MainMenu", tc->stateName());
 }
References PHControl::instance(), TankControllerLib::instance(), TankControllerLib::loop(), TankControllerLib::setNextState(), TankControllerLib::stateName(), and tc.
unittest() [3/3]
unittest (IgnoreInvalidCharacter)
Definition at line 9 of file EnablePIDTest.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   EnablePID* test = new EnablePID(tc);
   tc->setNextState(test, true);
   assertEqual("EnablePID", tc->stateName());
   assertTrue(PHControl::instance()->getUsePID());
   test->setValue(2.0);
   assertEqual("EnablePID", tc->stateName());
   assertTrue(PHControl::instance()->getUsePID());
 }
References PHControl::instance(), TankControllerLib::instance(), TankControllerLib::setNextState(), TankControllerLib::stateName(), and tc.