Tank Controller Lib: GUI/libTC.cpp File Reference
libTC.cpp File Reference
#include <sys/time.h>
#include <cassert>
#include <chrono>
#include <ctime>
#include <limits>
#include <queue>
#include <string>
#include <thread>
#include <vector>
#include "Arduino.h"
#include "DateTime_TC.h"
#include "EEPROM_TC.h"
#include "Keypad_TC.h"
#include "LiquidCrystal_TC.h"
#include "PHProbe.h"
#include "SD_TC.h"
#include "Serial_TC.h"
#include "TC_util.h"
#include "TankControllerLib.h"
#include "TempProbe_TC.h"
#include "UIState.h"
#include "pybind11/pybind11.h"
Macros
#define NUM_SERIAL_PORTS 2
#define EEPROM_SIZE 4096
#define LED_PIN 13
Functions
void loop ()
uint32_t millisecondsSinceEpoch ()
char * dateTime ()
float eeprom (uint8_t index)
void key (char key)
const char * lcd (uint16_t index)
float getTemperature ()
float readPH ()
bool readPin (uint16_t pin)
string readSerial (uint16_t port)
string readSerial0 ()
string readSerial1 ()
void addPath (File *entry, String parentPath)
void sdInit ()
string sdNextKey ()
string sdNextValue ()
void setTemperature (float value)
void setTime ()
void setup ()
const char * version ()
void writeSerial1 (const char *data)
PYBIND11_MODULE (libTC, m)
Variables
char lcdLine [17]
uint32_t msOffset = 0
std::queue< string > paths
Macro Definition Documentation
EEPROM_SIZE
#define EEPROM_SIZE 4096
Definition at line 4 of file libTC.cpp.
LED_PIN
#define LED_PIN 13
Definition at line 34 of file libTC.cpp.
NUM_SERIAL_PORTS
#define NUM_SERIAL_PORTS 2
Definition at line 3 of file libTC.cpp.
Function Documentation
addPath()
void addPath (File * entry, String parentPath)
Definition at line 159 of file libTC.cpp.
{
   if (!entry->isDirectory()) {
     paths.push(parentPath + entry->name());
   }
 }
References paths.
Referenced by sdInit().
dateTime()
char* dateTime ()
Definition at line 45 of file libTC.cpp.
                  {
   return DateTime_TC::now().as16CharacterString();
 }
References DateTime_TC::as16CharacterString(), and DateTime_TC::now().
Referenced by PYBIND11_MODULE(), and unittest().
eeprom()
float eeprom (uint8_t index)
Definition at line 49 of file libTC.cpp.
{
   switch (index) {
     case 0:
       return EEPROM_TC::instance()->getPH();
     case 1:
       return EEPROM_TC::instance()->getTemp();
     case 2:
       return EEPROM_TC::instance()->getTankID();
     case 3:
       return EEPROM_TC::instance()->getCorrectedTemp();
     case 4:
       return EEPROM_TC::instance()->getKP();
     case 5:
       return EEPROM_TC::instance()->getKI();
     case 6:
       return EEPROM_TC::instance()->getKD();
     case 7:
       return -1.0;  // not really a float!
     case 8:
       return EEPROM_TC::instance()->getHeat();
     case 9:
       return EEPROM_TC::instance()->getAmplitude();
     case 10:
       return EEPROM_TC::instance()->getFrequency();
     case 11:
       return EEPROM_TC::instance()->getGranularity();
     case 12:
       return EEPROM_TC::instance()->getMaxDataAge();
     case 13:
       return EEPROM_TC::instance()->getPHSeriesSize();
     case 14:
       return EEPROM_TC::instance()->getPHSeriesPointer();
     case 15:
       return EEPROM_TC::instance()->getTempSeriesSize();
     case 16:
       return EEPROM_TC::instance()->getTempSeriesPointer();
     case 17:
       return EEPROM_TC::instance()->getPHInterval();
     case 18:
       return EEPROM_TC::instance()->getPHDelay();
     case 19:
       return EEPROM_TC::instance()->getTempInterval();
     case 20:
       return EEPROM_TC::instance()->getTempDelay();
     case 21:
       return EEPROM_TC::instance()->getGoogleSheetInterval();
     default:
       return std::numeric_limits<float>::quiet_NaN();
   }
 }
References EEPROM_TC::getAmplitude(), EEPROM_TC::getCorrectedTemp(), EEPROM_TC::getFrequency(), EEPROM_TC::getGoogleSheetInterval(), EEPROM_TC::getGranularity(), EEPROM_TC::getHeat(), EEPROM_TC::getKD(), EEPROM_TC::getKI(), EEPROM_TC::getKP(), EEPROM_TC::getMaxDataAge(), EEPROM_TC::getPH(), EEPROM_TC::getPHDelay(), EEPROM_TC::getPHInterval(), EEPROM_TC::getPHSeriesPointer(), EEPROM_TC::getPHSeriesSize(), EEPROM_TC::getTankID(), EEPROM_TC::getTemp(), EEPROM_TC::getTempDelay(), EEPROM_TC::getTempInterval(), EEPROM_TC::getTempSeriesPointer(), EEPROM_TC::getTempSeriesSize(), and EEPROM_TC::instance().
Referenced by PID_TC::PID_TC(), and PYBIND11_MODULE().
getTemperature()
float getTemperature ()
Definition at line 119 of file libTC.cpp.
{
   TempProbe_TC *tempProbe = TempProbe_TC::instance();
   return tempProbe->getRunningAverage();
 }
References TempProbe_TC::getRunningAverage(), TempProbe_TC::instance(), and tempProbe.
key()
void key (char key)
Definition at line 100 of file libTC.cpp.
                    {
   Keypad_TC::instance()->_getPuppet()->push_back(key);
 }
References Keypad_TC::_getPuppet(), and Keypad_TC::instance().
Referenced by enterKey(), Ethernet_TC::Ethernet_TC(), CalibrationManagement::handleKey(), MainMenu::handleKey(), NumCollectorState::handleKey(), ResetLCDScreen::handleKey(), SeeDeviceAddress::handleKey(), SetCalibrationClear::handleKey(), UIState::handleKey(), TankControllerLib::handleUI(), and PYBIND11_MODULE().
lcd()
const char* lcd (uint16_t index)
Definition at line 104 of file libTC.cpp.
{
   std::vector<String> lines = LiquidCrystal_TC::instance()->getLines();
   String line = lines.at(index);
   uint16_t size = line.size();
   assert(size <= 16);
   for (size_t i = 0; i < size; ++i) {
     if (line.at(i) < 32) {
       line.at(i) = '?';
     }
   }
   strncpy(lcdLine, line.c_str(), size);
   assert(lcdLine[size] == 0);
   return lcdLine;
 }
References assert, LiquidCrystal_TC::instance(), and lcdLine.
Referenced by PYBIND11_MODULE(), and unittest().
loop()
void loop ()
Definition at line 124 of file libTC.cpp.
             {
   int32_t msBehind = millisecondsSinceEpoch() - millis() - msOffset;
   if (msBehind) {
     delay(msBehind);
   }
   TankControllerLib::instance()->loop();
 }
References TankControllerLib::instance(), TankControllerLib::loop(), millisecondsSinceEpoch(), and msOffset.
Referenced by PYBIND11_MODULE().
millisecondsSinceEpoch()
uint32_t millisecondsSinceEpoch ()
Definition at line 132 of file libTC.cpp.
{
   return std::chrono::system_clock::now().time_since_epoch() / std::chrono::milliseconds(1);
 }
Referenced by loop(), and setTime().
PYBIND11_MODULE()
PYBIND11_MODULE (libTC , m)
Definition at line 222 of file libTC.cpp.
{
   m.doc() = "pybind11 example plugin";  // optional module docstring
   m.def("dateTime", &dateTime, "TankController DateTime");
   m.def("eeprom", &eeprom, "TankController EEPROM");
   m.def("key", &key, "TankController key");
   m.def("lcd", &lcd, "TankController LiquidCrystal");
   m.def("loop", &loop, "TankController loop");
   m.def("readPin", &readPin, "TankController read pin value");
   m.def("readSerial0", &readSerial0, "From TankController on serial port 0");
   m.def("readSerial1", &readSerial1, "From TankController on serial port 1");
   m.def("sdInit", &sdInit, "Reset the file system scan");
   m.def("sdNextKey", &sdNextKey, "Get the next file's full path");
   m.def("sdNextValue", &sdNextValue, "Get the next file's contents");
   m.def("setTemperature", &setTemperature, "TankController set actual tank temperature");
   m.def("setup", &setup, "TankController setup");
   m.def("version", &version, "TankController version");
   m.def("writeSerial1", &writeSerial1, "To TankController on serial port 1");
 }
References dateTime(), eeprom(), key(), lcd(), loop(), readPin(), readSerial0(), readSerial1(), sdInit(), sdNextKey(), sdNextValue(), setTemperature(), setup(), version(), and writeSerial1().
readPH()
float readPH ()
Definition at line 136 of file libTC.cpp.
                {
   return PHProbe::instance()->getPh();
 }
References PHProbe::getPh(), and PHProbe::instance().
readPin()
bool readPin (uint16_t pin)
Definition at line 140 of file libTC.cpp.
{
   return digitalRead(pin);
 }
Referenced by PYBIND11_MODULE().
readSerial()
string readSerial (uint16_t port)
Definition at line 144 of file libTC.cpp.
{
   GodmodeState *state = GODMODE();
   string result = string(state->serialPort[port].dataOut);
   state->serialPort[port].dataOut = "";
   return result;
 }
References state.
Referenced by readSerial0(), and readSerial1().
readSerial0()
string readSerial0 ()
Definition at line 151 of file libTC.cpp.
                      {
   return readSerial(0);
 }
References readSerial().
Referenced by PYBIND11_MODULE().
readSerial1()
string readSerial1 ()
Definition at line 155 of file libTC.cpp.
                      {
   return readSerial(1);
 }
References readSerial().
Referenced by PYBIND11_MODULE().
sdInit()
void sdInit ()
Definition at line 165 of file libTC.cpp.
               {
   std::queue<string> empty;
   std::swap(paths, empty);
   SD_TC::instance()->visit(addPath);
 }
References addPath(), SD_TC::instance(), and paths.
Referenced by PYBIND11_MODULE().
sdNextKey()
string sdNextKey ()
Definition at line 171 of file libTC.cpp.
                    {
   if (paths.empty()) {
     return string("");
   }
   return paths.front();
 }
References paths.
Referenced by PYBIND11_MODULE().
sdNextValue()
string sdNextValue ()
Definition at line 178 of file libTC.cpp.
                      {
   char buffer[4096];
   File entry = SD_TC::instance()->open(String(paths.front().c_str()));
   size_t size = entry.size();
   if (sizeof(buffer) - 1 < size) {
     size = sizeof(buffer) - 1;
   }
   entry.read(buffer, size);
   buffer[size] = '\0';
   string result = string(buffer);
   paths.pop();
   return result;
 }
References buffer, SD_TC::instance(), SD_TC::open(), and paths.
Referenced by PYBIND11_MODULE().
setTemperature()
void setTemperature (float value)
Definition at line 192 of file libTC.cpp.
{
   TempProbe_TC *tempProbe = TempProbe_TC::instance();
   tempProbe->setTemperature(value);
 }
References TempProbe_TC::instance(), tempProbe, and value.
Referenced by PYBIND11_MODULE().
setTime()
void setTime ()
Definition at line 197 of file libTC.cpp.
                {
   time_t rawtime;
   struct tm *timeinfo;
   time(&rawtime);
   timeinfo = localtime(&rawtime);
   DateTime_TC now(timeinfo->tm_year + 1900, timeinfo->tm_mon + 1, timeinfo->tm_mday, timeinfo->tm_hour,
                   timeinfo->tm_min, timeinfo->tm_sec);
   msOffset = millisecondsSinceEpoch() - millis();
   now.setAsCurrent();
 }
References millisecondsSinceEpoch(), msOffset, DateTime_TC::setAsCurrent(), and time.
Referenced by setup().
setup()
void setup ()
Definition at line 208 of file libTC.cpp.
              {
   setTime();
   TankControllerLib::instance()->setup();
 }
References TankControllerLib::instance(), setTime(), and TankControllerLib::setup().
Referenced by PYBIND11_MODULE().
version()
const char* version ()
Definition at line 213 of file libTC.cpp.
                       {
   return TankControllerLib::instance()->version();
 }
References TankControllerLib::instance(), and TankControllerLib::version().
Referenced by LiquidCrystal_TC::instance(), LiquidCrystal_TC::LiquidCrystal_TC(), PYBIND11_MODULE(), LiquidCrystal_TC::splashScreen(), and SeeVersion::start().
writeSerial1()
void writeSerial1 (const char * data)
Definition at line 217 of file libTC.cpp.
{
   GODMODE()->serialPort[1].dataIn = data;         // the queue of data waiting to be read
   TankControllerLib::instance()->serialEvent1();  // fake interrupt
 }
References TankControllerLib::instance(), and TankControllerLib::serialEvent1().
Referenced by PYBIND11_MODULE().
Variable Documentation
lcdLine
char lcdLine[17]
Definition at line 37 of file libTC.cpp.
Referenced by lcd().
msOffset
uint32_t msOffset = 0
Definition at line 38 of file libTC.cpp.
Referenced by loop(), and setTime().
paths
std::queue<string> paths
Definition at line 39 of file libTC.cpp.
Referenced by addPath(), sdInit(), sdNextKey(), and sdNextValue().