Tank Controller Lib: test/LiquidCrystalTest.cpp File Reference
LiquidCrystalTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <vector>
#include "Devices/LiquidCrystal_TC.h"
#include "TankControllerLib.h"
Functions
unittest (loop)
unittest (writeLine)
Function Documentation
unittest() [1/2]
unittest (loop)
Definition at line 9 of file LiquidCrystalTest.cpp.
                {
   TankControllerLib* tank = TankControllerLib::instance();
   LiquidCrystal_TC* lcd = LiquidCrystal_TC::instance();
   assertTrue(tank != nullptr);
   assertTrue(lcd != nullptr);
   assertEqual("LiquidCrystal_CI", lcd->className());
   // get currently displayed lines
   std::vector<String> lines = lcd->getLines();
   // verify that display contains the splash screen
   assertEqual(2, lines.size());
   assertEqual(16, lines.at(0).length());
   assertEqual(16, lines.at(1).length());
   assertEqual("Tank Controller ", lines.at(0));
   assertEqual(
       "v"
       "21.08.1 loading",  // this allows a word-search to find the number
       lines.at(1));
 }
References TankControllerLib::instance(), LiquidCrystal_TC::instance(), and lcd().
unittest() [2/2]
unittest (writeLine)
Definition at line 28 of file LiquidCrystalTest.cpp.
                     {
   LiquidCrystal_TC* testLcd = LiquidCrystal_TC::instance();
   testLcd->writeLine("Hello", 0);
   testLcd->writeLine("World", 1);
   std::vector<String> lines = testLcd->getLines();
   assertEqual("Hello           ", lines.at(0));
   assertEqual("World           ", lines.at(1));
   testLcd->writeLine("Wrong line num", 6);
   testLcd->writeLine("this won't break", 3);
   lines = testLcd->getLines();
   assertEqual("Wrong line num  ", lines.at(0));
   assertEqual("this won't break", lines.at(1));
 }
References LiquidCrystal_TC::instance(), and LiquidCrystal_TC::writeLine().