Tank Controller Lib: test/MenuTest.cpp File Reference
MenuTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "DateTime_TC.h"
#include "Devices/EEPROM_TC.h"
#include "Devices/PHControl.h"
#include "Devices/TemperatureControl.h"
#include "Keypad_TC.h"
#include "LiquidCrystal_TC.h"
#include "MainMenu.h"
#include "PHCalibrationHigh.h"
#include "TankControllerLib.h"
#include "TempProbe_TC.h"
Functions
void enterKey (char key)
unittest_setup ()
unittest_teardown ()
unittest (MainMenu)
unittest (ChangeSettings)
unittest (ViewSettings)
unittest (SetPHSetPoint)
unittest (ViewTime)
unittest (DisableTimeout)
Variables
TankControllerLib * tc = TankControllerLib::instance()
LiquidCrystal_TC * lc = LiquidCrystal_TC::instance()
Keypad * keypad = Keypad_TC::instance()->_getPuppet()
Function Documentation
enterKey()
void enterKey (char key)
Definition at line 21 of file MenuTest.cpp.
{
   keypad->push_back(key);
   tc->loop();  // recognize and apply the key entry
 }
References key(), keypad, TankControllerLib::loop(), and tc.
Referenced by unittest(), unittest_setup(), and unittest_teardown().
unittest() [1/6]
unittest (ChangeSettings)
Definition at line 53 of file MenuTest.cpp.
{
   enterKey('2');
   assertEqual("Change settings ", lc->getLines().at(0));
   assertEqual("<4   ^2  8v   6>", lc->getLines().at(1));
   enterKey('D');
   assertEqual("pH=0.000   8.100", lc->getLines().at(0));
   assertEqual("T=12.23 H 15.75 ", lc->getLines().at(1));
   enterKey('8');
   enterKey('8');
   assertEqual("Change settings ", lc->getLines().at(0));
   assertEqual("<4   ^2  8v   6>", lc->getLines().at(1));
   enterKey('4');
   assertEqual("pH=0.000   8.100", lc->getLines().at(0));
   assertEqual("T=12.23 H 15.75 ", lc->getLines().at(1));
 }
References enterKey(), and lc.
unittest() [2/6]
unittest (DisableTimeout)
Definition at line 117 of file MenuTest.cpp.
{
   enterKey('8');
   enterKey('8');
   enterKey('6');
   enterKey('8');
   enterKey('8');
   enterKey('6');
   assertEqual("PHCalibrationMid", tc->stateName());
   delay(65000);  // wait for over 60 seconds to verify that it does not return to main menu
   tc->loop();
   tc->loop();
   assertEqual("PHCalibrationMid", tc->stateName());
 }
References enterKey(), TankControllerLib::loop(), TankControllerLib::stateName(), and tc.
unittest() [3/6]
unittest (MainMenu)
Definition at line 40 of file MenuTest.cpp.
                    {
   assertEqual("pH=0.000   8.100", lc->getLines().at(0));
   assertEqual("T=12.23 h 15.75 ", lc->getLines().at(1));
   delay(1000);
   tc->loop();
   assertEqual("pH 0.000   8.100", lc->getLines().at(0));
   assertEqual("T 12.23 H 15.75 ", lc->getLines().at(1));
   delay(1000);
   tc->loop();
   assertEqual("pH=0.000   8.100", lc->getLines().at(0));
   assertEqual("T=12.23 H 15.75 ", lc->getLines().at(1));
 }
References lc, TankControllerLib::loop(), and tc.
unittest() [4/6]
unittest (SetPHSetPoint)
Definition at line 85 of file MenuTest.cpp.
{
   enterKey('A');
   assertEqual("Set pH Set Point", lc->getLines().at(0));
   enterKey('D');
   assertEqual("MainMenu", tc->stateName());
   enterKey('2');
   enterKey('6');
   assertEqual("Set pH target   ", lc->getLines().at(0));
   assertEqual("<4   ^2  8v   6>", lc->getLines().at(1));
   enterKey('6');
   assertEqual("Set pH Set Point", lc->getLines().at(0));
   enterKey('D');
   assertEqual("MainMenu", tc->stateName());
 }
References enterKey(), lc, TankControllerLib::stateName(), and tc.
unittest() [5/6]
unittest (ViewSettings)
Definition at line 69 of file MenuTest.cpp.
{
   enterKey('8');
   assertEqual("View settings   ", lc->getLines().at(0));
   assertEqual("<4   ^2  8v   6>", lc->getLines().at(1));
   enterKey('D');
   assertEqual("pH=0.000   8.100", lc->getLines().at(0));
   assertEqual("T=12.23 H 15.75 ", lc->getLines().at(1));
   enterKey('2');
   enterKey('2');
   assertEqual("View settings   ", lc->getLines().at(0));
   assertEqual("<4   ^2  8v   6>", lc->getLines().at(1));
   enterKey('D');
   assertEqual("pH=0.000   8.100", lc->getLines().at(0));
   assertEqual("T=12.23 H 15.75 ", lc->getLines().at(1));
 }
References enterKey(), and lc.
unittest() [6/6]
unittest (ViewTime)
Definition at line 100 of file MenuTest.cpp.
                    {
   enterKey('8');
   enterKey('6');
   assertEqual("View time       ", lc->getLines().at(0));
   assertEqual("<4   ^2  8v   6>", lc->getLines().at(1));
   enterKey('6');
   assertEqual(DateTime_TC::now().as16CharacterString(), lc->getLines().at(0).c_str());
   delay(6000);
   tc->loop();
   tc->loop();
   assertEqual("SeeDeviceUptime", tc->stateName());
   delay(55000);  // idle timeout should return to main menu
   tc->loop();
   tc->loop();
   assertEqual("MainMenu", tc->stateName());
 }
References enterKey(), lc, TankControllerLib::loop(), DateTime_TC::now(), TankControllerLib::stateName(), and tc.
unittest_setup()
unittest_setup ()
Definition at line 26 of file MenuTest.cpp.
                  {
   EEPROM_TC::instance()->setPH(8.100);
   PHControl::instance()->setTargetPh(8.100);
   tc->setNextState(new MainMenu(tc), true);
   TempProbe_TC::instance()->setTemperature(12.25);
   TemperatureControl::enableHeater(true);
   TemperatureControl::instance()->setTargetTemperature(15.75);
   enterKey('D');
 }
References TemperatureControl::enableHeater(), enterKey(), EEPROM_TC::instance(), PHControl::instance(), TemperatureControl::instance(), TempProbe_TC::instance(), TankControllerLib::setNextState(), EEPROM_TC::setPH(), PHControl::setTargetPh(), TemperatureControl::setTargetTemperature(), and tc.
unittest_teardown()
unittest_teardown ()
Definition at line 36 of file MenuTest.cpp.
                     {
   enterKey('D');
 }
References enterKey().
Variable Documentation
keypad
Keypad* keypad = Keypad_TC::instance()->_getPuppet()
Definition at line 18 of file MenuTest.cpp.
Referenced by enterKey().
lc
LiquidCrystal_TC* lc = LiquidCrystal_TC::instance()
Definition at line 17 of file MenuTest.cpp.
Referenced by unittest().
tc
TankControllerLib* tc = TankControllerLib::instance()
Definition at line 16 of file MenuTest.cpp.
Referenced by enterKey(), unittest(), and unittest_setup().