Tank Controller Lib: test/PHCalibrationHighTest.cpp File Reference
PHCalibrationHighTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "Keypad_TC.h"
#include "PHCalibrationHigh.h"
#include "TankController.h"
Functions
unittest (test)
Function Documentation
unittest()
unittest (test)
Definition at line 9 of file PHCalibrationHighTest.cpp.
                {
   TankController* tc = TankController::instance();
   PHCalibrationHigh* test = new PHCalibrationHigh(tc);
   tc->setNextState(test, true);
   assertTrue(tc->isInCalibration());
   // setValue
   test->setValue(12.345);
   // during the delay we showed the new value
   std::vector<String> lines = LiquidCrystal_TC::instance()->getLines();
   assertEqual("New High=12.345 ", lines[1]);
   assertEqual("PHCalibrationHigh", tc->stateName());
   tc->loop();  // transition to Wait
   assertEqual("Wait", tc->stateName());
   delay(3000);
   tc->loop();  // after the delay, Wait will call setNextState to prepare to go to PHCalibrationLow
   tc->loop();  // updateState to PHCalibrationLow
   assertEqual("MainMenu", tc->stateName());
 }
References TankController::instance(), LiquidCrystal_TC::instance(), TankController::isInCalibration(), TankController::loop(), TankController::setNextState(), TankController::stateName(), and tc.