Tank Controller Lib: test/PHControlTest.cpp File Reference
PHControlTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <ci/ObservableDataStream.h>
#include "Devices/DateTime_TC.h"
#include "LiquidCrystal_TC.h"
#include "MainMenu.h"
#include "PHCalibrationMid.h"
#include "PHControl.h"
#include "TankController.h"
Functions
void setPhMeasurementTo (float value)
void reset ()
unittest_setup ()
unittest_teardown ()
unittest (bubblerTurnsOnAndOff)
unittest (afterTenSecondsButPhStillHigher)
unittest (afterTenSecondsAndPhIsLower)
unittest (beforeTenSecondsButPhIsLower)
unittest (PhEvenWithTarget)
unittest (disableDuringCalibration)
unittest (RampGreaterThanZero)
unittest (ChangeRampToZero)
unittest (sineTest)
Variables
const uint16_t PH_CONTROL_PIN = 49
GodmodeState * state = GODMODE()
TankController * tc = TankController::instance()
PHControl * controlSolenoid = PHControl::instance()
LiquidCrystal_TC * lc = LiquidCrystal_TC::instance()
Function Documentation
reset()
void reset ()
cycle the control through to a point of being off
Definition at line 30 of file PHControlTest.cpp.
             {
  tc->setNextState(new MainMenu(tc), true);
  state->resetClock();
  DateTime_TC january(2021, 1, 15, 1, 48, 24);
  january.setAsCurrent();
  controlSolenoid->enablePID(false);
  controlSolenoid->setTargetPh(7.50);
  setPhMeasurementTo(7.50);
  state->serialPort[0].dataOut = "";  // the history of data written
}
References controlSolenoid, PHControl::enablePID(), DateTime_TC::setAsCurrent(), TankController::setNextState(), setPhMeasurementTo(), PHControl::setTargetPh(), state, and tc.
Referenced by Ethernet_TC::instance(), unittest_setup(), and unittest_teardown().
setPhMeasurementTo()
void setPhMeasurementTo (float value)
Definition at line 19 of file PHControlTest.cpp.
{
  char buffer[10];
  snprintf_P(buffer, sizeof(buffer), (PGM_P)F("%i.%i\r"), (int)value, (int)(value * 1000 + 0.5) % 1000);
  state->serialPort[1].dataIn = buffer;  // the queue of data waiting to be read
  tc->serialEvent1();                    // fake interrupt to update the current pH reading
  tc->loop();                            // update the controls based on the current readings
}
References buffer, TankController::loop(), TankController::serialEvent1(), state, tc, and value.
Referenced by reset(), and unittest().
unittest() [1/9]
unittest (afterTenSecondsAndPhIsLower)
Definition at line 99 of file PHControlTest.cpp.
{
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  assertEqual("pH 7.500   7.500", lc->getLines().at(0));
  controlSolenoid->setTargetPh(7.50);
  setPhMeasurementTo(8.50);
  assertEqual(TURN_SOLENOID_ON, state->digitalPin[PH_CONTROL_PIN]);
  assertTrue(controlSolenoid->isOn());
  assertEqual("CO2 bubbler turned on after 7 ms\r\n", state->serialPort[0].dataOut);
  tc->loop();
  assertEqual("pH 8.500 B 7.500", lc->getLines().at(0));
  delay(8000);
  tc->loop();
  assertEqual(TURN_SOLENOID_ON, state->digitalPin[PH_CONTROL_PIN]);
  assertTrue(controlSolenoid->isOn());
  state->serialPort[0].dataOut = "";  // the history of data written
  delay(1000);
  tc->loop();
  assertEqual("CO2 bubbler turned off after 9021 ms\r\n", state->serialPort[0].dataOut);  // after 10 seconds
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  delay(1000);
  setPhMeasurementTo(7.25);
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
}
References controlSolenoid, PHControl::isOn(), lc, TankController::loop(), PH_CONTROL_PIN, setPhMeasurementTo(), PHControl::setTargetPh(), state, tc, TURN_SOLENOID_OFF, and TURN_SOLENOID_ON.
unittest() [2/9]
unittest (afterTenSecondsButPhStillHigher)
Definition at line 82 of file PHControlTest.cpp.
{
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  controlSolenoid->setTargetPh(7.50);
  setPhMeasurementTo(8.50);
  assertEqual(TURN_SOLENOID_ON, state->digitalPin[PH_CONTROL_PIN]);
  assertTrue(controlSolenoid->isOn());
  delay(8000);
  setPhMeasurementTo(8.50);
  assertEqual(TURN_SOLENOID_ON, state->digitalPin[PH_CONTROL_PIN]);
  assertTrue(controlSolenoid->isOn());
  delay(2000);
  setPhMeasurementTo(7.75);
  assertEqual(TURN_SOLENOID_ON, state->digitalPin[PH_CONTROL_PIN]);
  assertTrue(controlSolenoid->isOn());
}
References controlSolenoid, PHControl::isOn(), PH_CONTROL_PIN, setPhMeasurementTo(), PHControl::setTargetPh(), state, TURN_SOLENOID_OFF, and TURN_SOLENOID_ON.
unittest() [3/9]
unittest (beforeTenSecondsButPhIsLower)
Test that CO2 bubbler is turned on when needed
See also
unittest(disableDuringCalibration)
Definition at line 130 of file PHControlTest.cpp.
{
  // device is initially off but turns on when needed
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  delay(1000);
  controlSolenoid->setTargetPh(7.50);
  setPhMeasurementTo(8.50);
  assertEqual(TURN_SOLENOID_ON, state->digitalPin[PH_CONTROL_PIN]);
  assertTrue(controlSolenoid->isOn());
  delay(7500);
  setPhMeasurementTo(7.25);
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
}
References controlSolenoid, PHControl::isOn(), PH_CONTROL_PIN, setPhMeasurementTo(), PHControl::setTargetPh(), state, TURN_SOLENOID_OFF, and TURN_SOLENOID_ON.
unittest() [4/9]
unittest (bubblerTurnsOnAndOff)
Definition at line 50 of file PHControlTest.cpp.
{
  assertEqual(6, millis());
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  state->serialPort[1].dataIn = "8.00\r";  // the queue of data waiting to be read
  tc->serialEvent1();                      // fake interrupt to update the current pH reading
  tc->loop();                              // update the controls based on the current readings
  assertEqual(13, millis());
  assertEqual(TURN_SOLENOID_ON, state->digitalPin[PH_CONTROL_PIN]);
  assertTrue(controlSolenoid->isOn());
  String serialOutput = state->serialPort[0].dataOut;
  String line;
  int i = 0, j = 0;
  do {
    j = serialOutput.indexOf('\r', i);
    if (j == -1) {
      assertTrue(false);  // we came to the end without finding the expected line
      break;
    }
    assertEqual('\r', serialOutput.charAt(j));
    line = serialOutput.substr(i, j);
    i = j + 2;
  } while (line.charAt(0) != 'C');
  assertEqual((int)'C', line.charAt(0));
  assertEqual("CO2 bubbler turned on after 13 ms", line);
  assertEqual(13, millis());
  delay(9500);
  tc->loop();  // solenoid should turn off briefly at end of window
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
}
References controlSolenoid, PHControl::isOn(), TankController::loop(), PH_CONTROL_PIN, TankController::serialEvent1(), state, tc, TURN_SOLENOID_OFF, and TURN_SOLENOID_ON.
unittest() [5/9]
unittest (ChangeRampToZero)
Definition at line 201 of file PHControlTest.cpp.
{
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  setPhMeasurementTo(8.50);
  controlSolenoid->setTargetPh(7.00);
  controlSolenoid->setRampDuration(1.5);
  assertEqual(controlSolenoid->phSetTypeTypes::RAMP_TYPE, controlSolenoid->getPhSetType());
  tc->loop();
  assertEqual(8.5, controlSolenoid->getCurrentPhTarget());
  controlSolenoid->setRampDuration(0);
  assertEqual(controlSolenoid->phSetTypeTypes::FLAT_TYPE, controlSolenoid->getPhSetType());
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
}
References controlSolenoid, PHControl::getCurrentPhTarget(), PHControl::getPhSetType(), PHControl::isOn(), TankController::loop(), PH_CONTROL_PIN, setPhMeasurementTo(), PHControl::setRampDuration(), PHControl::setTargetPh(), state, tc, and TURN_SOLENOID_OFF.
unittest() [6/9]
unittest (disableDuringCalibration)
Test that CO2 bubbler is turned on when needed
See also
unittest(beforeTenSecondsButPhIsLower)
Definition at line 158 of file PHControlTest.cpp.
{
  assertFalse(tc->isInCalibration());
  PHCalibrationMid* test = new PHCalibrationMid(tc);
  tc->setNextState(test, true);
  assertTrue(tc->isInCalibration());
  // device is initially off and stays off due to calibration
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  controlSolenoid->setTargetPh(7.50);
  setPhMeasurementTo(8.50);
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
}
References controlSolenoid, TankController::isInCalibration(), PHControl::isOn(), PH_CONTROL_PIN, TankController::setNextState(), setPhMeasurementTo(), PHControl::setTargetPh(), state, tc, and TURN_SOLENOID_OFF.
unittest() [7/9]
unittest (PhEvenWithTarget)
Definition at line 145 of file PHControlTest.cpp.
{
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  controlSolenoid->setTargetPh(7.50);
  setPhMeasurementTo(7.50);
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
}
References controlSolenoid, PHControl::isOn(), PH_CONTROL_PIN, setPhMeasurementTo(), PHControl::setTargetPh(), state, and TURN_SOLENOID_OFF.
unittest() [8/9]
unittest (RampGreaterThanZero)
Definition at line 172 of file PHControlTest.cpp.
{
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  setPhMeasurementTo(8.50);
  controlSolenoid->setTargetPh(7.00);
  controlSolenoid->setRampDuration(1.5);
  assertEqual(controlSolenoid->phSetTypeTypes::RAMP_TYPE, controlSolenoid->getPhSetType());
  tc->loop();
  assertEqual(8.5, controlSolenoid->getCurrentPhTarget());
  // mock arduino restarting
  PHControl::clearInstance();
  controlSolenoid = PHControl::instance();
  // takes 1.5 hours to get to pH of 7
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertTrue(8.0 <= controlSolenoid->getCurrentPhTarget() && controlSolenoid->getCurrentPhTarget() <= 8.01);
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertTrue(7.5 <= controlSolenoid->getCurrentPhTarget() && controlSolenoid->getCurrentPhTarget() <= 7.51);
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
  // ramp time no longer used after it ends
  delay(1800000);  // delay 30 minutes
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
}
References PHControl::clearInstance(), controlSolenoid, PHControl::getCurrentPhTarget(), PHControl::getPhSetType(), PHControl::instance(), PHControl::isOn(), TankController::loop(), PH_CONTROL_PIN, setPhMeasurementTo(), PHControl::setRampDuration(), PHControl::setTargetPh(), state, tc, and TURN_SOLENOID_OFF.
unittest() [9/9]
unittest (sineTest)
Definition at line 216 of file PHControlTest.cpp.
                   {
  assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PH_CONTROL_PIN]);
  assertFalse(controlSolenoid->isOn());
  setPhMeasurementTo(7.00);
  controlSolenoid->setTargetPh(7.00);
  controlSolenoid->setSine(1.5, 2);
  assertEqual(controlSolenoid->phSetTypeTypes::SINE_TYPE, controlSolenoid->getPhSetType());
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
  // mock arduino restarting
  PHControl::clearInstance();
  controlSolenoid = PHControl::instance();
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(8.5, controlSolenoid->getCurrentPhTarget());
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(5.5, controlSolenoid->getCurrentPhTarget());
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
  // make sure sine wave continues
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(8.5, controlSolenoid->getCurrentPhTarget());
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(5.5, controlSolenoid->getCurrentPhTarget());
  delay(1800000);  // delay 30 minutes
  tc->loop();
  assertEqual(7, controlSolenoid->getCurrentPhTarget());
}
References PHControl::clearInstance(), controlSolenoid, PHControl::getCurrentPhTarget(), PHControl::getPhSetType(), PHControl::instance(), PHControl::isOn(), TankController::loop(), PH_CONTROL_PIN, setPhMeasurementTo(), PHControl::setSine(), PHControl::setTargetPh(), state, tc, and TURN_SOLENOID_OFF.
unittest_setup()
unittest_setup ()
Definition at line 41 of file PHControlTest.cpp.
                 {
  reset();
}
References reset().
unittest_teardown()
unittest_teardown ()
Definition at line 45 of file PHControlTest.cpp.
                    {
  reset();
}
References reset().
Variable Documentation
controlSolenoid
PHControl* controlSolenoid = PHControl::instance()
Definition at line 16 of file PHControlTest.cpp.
Referenced by reset(), and unittest().
lc
LiquidCrystal_TC* lc = LiquidCrystal_TC::instance()
Definition at line 17 of file PHControlTest.cpp.
Referenced by unittest().
PH_CONTROL_PIN
const uint16_t PH_CONTROL_PIN = 49
Definition at line 12 of file PHControlTest.cpp.
Referenced by unittest().
state
GodmodeState* state = GODMODE()
Definition at line 14 of file PHControlTest.cpp.
Referenced by reset(), setPhMeasurementTo(), and unittest().
tc
TankController* tc = TankController::instance()
Definition at line 15 of file PHControlTest.cpp.
Referenced by reset(), setPhMeasurementTo(), and unittest().