Tank Controller Lib: test/SD.cpp File Reference
SD.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "DateTime_TC.h"
#include "SD_TC.h"
#include "TC_util.h"
Functions
unittest_setup ()
unittest_teardown ()
unittest (singleton)
unittest (appendToDataLog)
unittest (appendToSerialLog)
unittest (printRootDirectory)
Function Documentation
unittest() [1/4]
unittest (appendToDataLog)
Definition at line 23 of file SD.cpp.
{
   char data[80];
   DateTime_TC d1(2021, 4, 15), d2(2021, 4, 16);
   SD_TC* sd = SD_TC::instance();
   assertFalse(sd->exists("/data/2021/04/15.txt"));
   assertFalse(sd->exists("/data/2021/04/16.txt"));
   // write data for day 15
   d1.setAsCurrent();
   sd->appendToDataLog("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd", "line 1");
   sd->appendToDataLog("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd", "line 2");
   assertTrue(sd->exists("/data/2021/04/15.txt"));
   assertFalse(sd->exists("/data/2021/04/16.txt"));
   // write data for day 16
   d2.setAsCurrent();
   sd->appendToDataLog("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd", "line 3");
   assertTrue(sd->exists("/data/2021/04/15.txt"));
   assertTrue(sd->exists("/data/2021/04/16.txt"));
   // verify contents of 15.txt
   File file = sd->open("/data/2021/04/15.txt");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd\nline 1\nline 2\n", data);
   file.close();
   // verify contents of 16.txt
   file = sd->open("/data/2021/04/16.txt");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd\nline 3\n", data);
   file.close();
 }
References SD_TC::appendToDataLog(), SD_TC::instance(), sd, and DateTime_TC::setAsCurrent().
unittest() [2/4]
unittest (appendToSerialLog)
Definition at line 59 of file SD.cpp.
{
   char data[80];
   DateTime_TC d1(2021, 4, 15), d2(2021, 4, 16);
   SD_TC* sd = SD_TC::instance();
   assertFalse(sd->exists("/log/2021/04/15.txt"));
   assertFalse(sd->exists("/log/2021/04/16.txt"));
   // write data for day 15
   d1.setAsCurrent();
   sd->appendToSerialLog("line 1");
   sd->appendToSerialLog("line 2");
   assertTrue(sd->exists("/log/2021/04/15.txt"));
   assertFalse(sd->exists("/log/2021/04/16.txt"));
   // write data for day 16
   d2.setAsCurrent();
   sd->appendToSerialLog("line 3");
   assertTrue(sd->exists("/log/2021/04/15.txt"));
   assertTrue(sd->exists("/log/2021/04/16.txt"));
   // verify contents of 15.txt
   File file = sd->open("/log/2021/04/15.txt");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("line 1\nline 2\n", data);
   file.close();
   // verify contents of 16.txt
   file = sd->open("/log/2021/04/16.txt");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("line 3\n", data);
   file.close();
 }
References SD_TC::appendToSerialLog(), SD_TC::instance(), sd, and DateTime_TC::setAsCurrent().
unittest() [3/4]
unittest (printRootDirectory)
Definition at line 95 of file SD.cpp.
{
   GodmodeState* state = GODMODE();
   SD_TC* sd = SD_TC::instance();
   state->serialPort[0].dataOut = "";
   sd->printRootDirectory();
   assertEqual("", state->serialPort[0].dataOut);
   sd->open("c", FILE_WRITE).close();
   sd->open("e", FILE_WRITE).close();
   sd->mkdir("d");
   sd->open("d/d1", FILE_WRITE).close();
   sd->open("d/d2", FILE_WRITE).close();
   state->serialPort[0].dataOut = "";
   sd->printRootDirectory();
   String expect = String("c>>0\r\nd/\r\n>d1>>0\r\n>d2>>0\r\ne>>0\r\n");
   String output = String(state->serialPort[0].dataOut);
   std::replace(output.begin(), output.end(), '\t', '>');
   // output to serial creates additional files here and we want to ignore them!
   output = output.substr(0, expect.length());
   assertEqual(expect, output);
 }
References SD_TC::instance(), SD_TC::printRootDirectory(), sd, and state.
unittest() [4/4]
unittest (singleton)
Definition at line 16 of file SD.cpp.
                     {
   SD_TC* thing1 = SD_TC::instance();
   SD_TC* thing2 = SD_TC::instance();
   assertTrue(thing1 != nullptr);
   assertEqual(thing1, thing2);
 }
References SD_TC::instance().
unittest_setup()
unittest_setup ()
Definition at line 8 of file SD.cpp.
                  {
   SD_TC::instance()->removeAll();
 }
References SD_TC::instance().
unittest_teardown()
unittest_teardown ()
Definition at line 12 of file SD.cpp.
                     {
   SD_TC::instance()->removeAll();
 }
References SD_TC::instance().