Tank Controller Lib: src/Devices/SD_TC.cpp File Reference
SD_TC.cpp File Reference
#include "Devices/SD_TC.h"
#include "DateTime_TC.h"
#include "Serial_TC.h"
#include "TC_util.h"
Functions
void printEntry (File entry, String parentPath)
Function Documentation
printEntry()
void printEntry (File entry, String parentPath)
Definition at line 60 of file SD_TC.cpp.
{
   int depth = 0;
   for (int i = 1; i < parentPath.length(); ++i) {
     if (parentPath[i] == '/') {
       ++depth;
     }
   }
   char tabs[] = "\t\t\t\t\t\t\t\t";
   if (depth < strlen(tabs)) {
     tabs[depth] = '\0';
   }
   if (entry.isDirectory()) {
     Serial_TC::instance()->printf((const char*)F("%s%s/"), tabs, entry.name());
   } else {
     // files have sizes, directories do not
     Serial_TC::instance()->printf((const char*)F("%s%s\t\t%i"), tabs, entry.name(), entry.size());
   }
 }
References Serial_TC::instance(), and Serial_TC::printf().
Referenced by SD_TC::printRootDirectory().