Tank Controller Lib: test/SeeDeviceUptimeTest.cpp File Reference
SeeDeviceUptimeTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/DateTime_TC.h"
#include "LiquidCrystal_TC.h"
#include "SeeDeviceUptime.h"
#include "TankController.h"
#include "UIState/UIState.h"
Functions
unittest (testWaitState)
Function Documentation
unittest()
unittest (testWaitState)
Definition at line 10 of file SeeDeviceUptimeTest.cpp.
{
  TankController* tc = TankController::instance();
  LiquidCrystal_TC* display = LiquidCrystal_TC::instance();
  assertEqual("MainMenu", tc->stateName());
  GODMODE()->resetClock();
  delay(((((1 * 24 + 2) * 60) + 3) * 60 + 4) * 1000);  // 1 day, 2 hours, 3 minutes, 4 seconds
  SeeDeviceUptime* test = new SeeDeviceUptime(tc);
  tc->setNextState(test, true);  // MainMenu -> SeeDeviceUptime nextState: Wait
  tc->loop();
  assertEqual("SeeDeviceUptime", tc->stateName());
  // during the delay we showed the expected two lines
  assertEqual(DateTime_TC::now().as16CharacterString(), display->getLines().at(0).c_str());
  assertEqual("Up d:01 02:03:04", display->getLines().at(1));
  delay(1000);
  tc->loop();
  assertEqual(DateTime_TC::now().as16CharacterString(), display->getLines().at(0).c_str());
  assertEqual("Up d:01 02:03:05", display->getLines().at(1));
  delay(1000);
  tc->loop();
  assertEqual("Up d:01 02:03:06", display->getLines().at(1));
  delay(1000);
  tc->loop();
  assertEqual("Up d:01 02:03:07", display->getLines().at(1));
  delay(1000);
  tc->loop();
  assertEqual("Up d:01 02:03:08", display->getLines().at(1));
  delay(1000);
  tc->loop();
  assertEqual("Up d:01 02:03:09", display->getLines().at(1));
  delay(1000);
  tc->loop();
  assertEqual("Up d:01 02:03:10", display->getLines().at(1));
}
References TankController::instance(), LiquidCrystal_TC::instance(), TankController::loop(), DateTime_TC::now(), TankController::setNextState(), TankController::stateName(), and tc.