Tank Controller Lib: test/SeeVersionTest.cpp File Reference
SeeVersionTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Keypad_TC.h"
#include "LiquidCrystal_TC.h"
#include "SeeVersion.h"
#include "TankControllerLib.h"
Functions
unittest (testOutput)
Function Documentation
unittest()
unittest (testOutput)
Definition at line 9 of file SeeVersionTest.cpp.
                      {
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* display = LiquidCrystal_TC::instance();
   assertEqual("MainMenu", tc->stateName());
   SeeVersion* test = new SeeVersion(tc);
   tc->setNextState(test, true);
   assertEqual("SeeVersion", tc->stateName());
   // Test the output
   tc->loop();
   assertEqual("Software Version", display->getLines().at(0));
   assertEqual("21.06.1         ", display->getLines().at(1));
   // Return to mainMenu
   Keypad_TC::instance()->_getPuppet()->push_back('D');
   tc->loop();
   assertEqual("MainMenu", tc->stateName());
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), TankControllerLib::loop(), TankControllerLib::setNextState(), TankControllerLib::stateName(), and tc.