Tank Controller Lib: src/Devices/Serial_TC.cpp File Reference
Serial_TC.cpp File Reference
#include "Devices/Serial_TC.h"
#include "DateTime_TC.h"
#include "SD_TC.h"
#include "TC_util.h"
Functions
void serial (const char *format...)
void serial (const __FlashStringHelper *format...)
void serialWithTime (const char *format...)
void serialWithTime (const __FlashStringHelper *format...)
Function Documentation
serial() [1/2]
void serial (const __FlashStringHelper * format...)
Definition at line 16 of file Serial_TC.cpp.
{
   va_list args;
   va_start(args, format);
   Serial_TC::instance()->vprintf((const char *)format, args);
   va_end(args);
 }
References Serial_TC::instance(), and Serial_TC::vprintf().
serial() [2/2]
void serial (const char * format...)
global serial() functions
Definition at line 10 of file Serial_TC.cpp.
{
   va_list args;
   va_start(args, format);
   Serial_TC::instance()->vprintf(format, args);
   va_end(args);
 }
References Serial_TC::instance(), and Serial_TC::vprintf().
Referenced by SD_TC::appendDataToPath(), Ethernet_TC::Ethernet_TC(), EthernetServer_TC::EthernetServer_TC(), PHProbe::getSlope(), EthernetServer_TC::handleRequest(), TankControllerLib::handleUI(), SD_TC::instance(), LiquidCrystal_TC::LiquidCrystal_TC(), PID_TC::logToSerial(), printEntry(), SD_TC::printRootDirectory(), DateTime_TC::rtc(), PHProbe::serialEvent1(), serialWithTime(), PHProbe::setTemperatureCompensation(), TankControllerLib::setup(), SetTime::setValue(), TankControllerLib::TankControllerLib(), unittest(), TankControllerLib::version(), and SD_TC::visit().
serialWithTime() [1/2]
void serialWithTime (const __FlashStringHelper * format...)
Definition at line 34 of file Serial_TC.cpp.
{
   char buffer[100];
   unsigned long ms = millis();
   DateTime_TC now = DateTime_TC::now();
   snprintf(buffer, sizeof(buffer), "Timestamp of next line: YYYY/MM/DD hh:mm:ss.%03i", (int)ms % 1000);
   now.toString(buffer);
   serial(buffer);
   va_list args;
   va_start(args, format);
   Serial_TC::instance()->vprintf((const char *)format, args);
   va_end(args);
 }
References buffer, Serial_TC::instance(), DateTime_TC::now(), serial(), and Serial_TC::vprintf().
serialWithTime() [2/2]
void serialWithTime (const char * format...)
Definition at line 22 of file Serial_TC.cpp.
{
   char buffer[100];
   unsigned long ms = millis();
   DateTime_TC now = DateTime_TC::now();
   snprintf(buffer, sizeof(buffer), "Timestamp of next line: YYYY/MM/DD hh:mm:ss.%03i", (int)ms % 1000);
   now.toString(buffer);
   serial(buffer);
   va_list args;
   va_start(args, format);
   Serial_TC::instance()->vprintf(format, args);
   va_end(args);
 }
References buffer, Serial_TC::instance(), DateTime_TC::now(), serial(), and Serial_TC::vprintf().
Referenced by TempProbe_TC::setCorrection(), PHControl::setTargetPh(), PHControl::setUsePID(), unittest(), Heater::updateControl(), Chiller::updateControl(), and PHControl::updateControl().