Tank Controller Lib: src/Devices/Serial_TC.h File Reference
Serial_TC.h File Reference
#include <Arduino.h>
Classes
class Serial_TC
Functions
void serial (const char *format...)
void serialWithTime (const char *format...)
Function Documentation
serial()
void serial (const char * format...)
This class is a wrapper for Arduino's Serial interface. The only function it supports is printf() and Serial::println() will add a CRLF to the end of each line.
global serial() functions
Definition at line 10 of file Serial_TC.cpp.
{
   va_list args;
   va_start(args, format);
   Serial_TC::instance()->vprintf(format, args);
   va_end(args);
 }
References Serial_TC::instance(), and Serial_TC::vprintf().
Referenced by SD_TC::appendDataToPath(), TemperatureControl::enableHeater(), Ethernet_TC::Ethernet_TC(), EthernetServer_TC::EthernetServer_TC(), PHProbe::getSlope(), EthernetServer_TC::handleRequest(), TankControllerLib::handleUI(), Keypad_TC::instance(), SD_TC::instance(), EEPROM_TC::instance(), LiquidCrystal_TC::LiquidCrystal_TC(), PID_TC::logToSerial(), PHControl::PHControl(), printEntry(), SD_TC::printRootDirectory(), DateTime_TC::rtc(), PHProbe::serialEvent1(), serialWithTime(), TemperatureControl::setTargetTemperature(), PHProbe::setTemperatureCompensation(), TankControllerLib::setup(), SetTime::setValue(), TankControllerLib::TankControllerLib(), TemperatureControl::TemperatureControl(), TempProbe_TC::TempProbe_TC(), unittest(), TankControllerLib::version(), and SD_TC::visit().
serialWithTime()
void serialWithTime (const char * format...)
Definition at line 17 of file Serial_TC.cpp.
{
   char buffer[100];
   unsigned long ms = millis();
   DateTime_TC now = DateTime_TC::now();
   snprintf(buffer, sizeof(buffer), "Timestamp of next line: YYYY/MM/DD hh:mm:ss.%03lu", ms % 1000);
   now.toString(buffer);
   serial(buffer);
   va_list args;
   va_start(args, format);
   Serial_TC::instance()->vprintf(format, args);
   va_end(args);
 }
References buffer, Serial_TC::instance(), DateTime_TC::now(), serial(), and Serial_TC::vprintf().
Referenced by PHControl::enablePID(), TempProbe_TC::setCorrection(), PHControl::setTargetPh(), unittest(), Heater::updateControl(), Chiller::updateControl(), and PHControl::updateControl().