Tank Controller Lib: test/Serial.cpp File Reference
Serial.cpp File Reference
#include <RTClib.h>
#include <Serial_TC.h>
#include "ArduinoUnitTests.h"
#include "Devices/DateTime_TC.h"
#include "TC_util.h"
Functions
unittest (SerialTest)
Function Documentation
unittest()
unittest (SerialTest)
Definition at line 9 of file Serial.cpp.
                      {
   GodmodeState* state = GODMODE();
   DateTime_TC::now();                 // this puts stuff on the serial port that we want to ignore
   state->serialPort[0].dataIn = "";   // the queue of data waiting to be read
   state->serialPort[0].dataOut = "";  // the history of data written
   // basic serial output
   Serial_TC* mySerial = Serial_TC::instance();
   mySerial->printf("abc %s %i %.4f", "XYZ", 42, 1.375);
   assertEqual("", state->serialPort[0].dataIn);
   assertEqual("abc XYZ 42 1.3750\r\n", state->serialPort[0].dataOut);
   // serial output with timestamp
   state->serialPort[0].dataOut = "";  // the history of data written
   mySerial->ts_printf("foo");
   assertEqual("Timestamp of next line: 202", state->serialPort[0].dataOut.substr(0, 27));
   assertEqual(".000\r\nfoo\r\n", state->serialPort[0].dataOut.substr(27 + 16));
 }
References Serial_TC::instance(), DateTime_TC::now(), Serial_TC::printf(), state, and Serial_TC::ts_printf().