Tank Controller Lib: test/SetChillOrHeatTest.cpp File Reference
SetChillOrHeatTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "EEPROM_TC.h"
#include "SetChillOrHeat.h"
#include "TankController.h"
Functions
unittest (ignoreInvalidValues)
unittest (switchToHeat)
unittest (switchToChill)
Function Documentation
unittest() [1/3]
unittest (ignoreInvalidValues)
Definition at line 9 of file SetChillOrHeatTest.cpp.
{
  TankController* tc = TankController::instance();
  SetChillOrHeat* test = new SetChillOrHeat(tc);
  tc->setNextState(test, true);
  assertTrue(EEPROM_TC::instance()->getHeat());
  test->setValue(2.0);
  assertTrue(EEPROM_TC::instance()->getHeat());
  tc->loop();  // transition to Wait
  delay(3000);
  tc->loop();  // queue MainMenu to be next
  tc->loop();  // transition to MainMenu
  // now we should be back to the main menu
  assertEqual("MainMenu", tc->stateName());
}
References EEPROM_TC::instance(), TankController::instance(), TankController::loop(), TankController::setNextState(), TankController::stateName(), and tc.
unittest() [2/3]
unittest (switchToChill)
Definition at line 40 of file SetChillOrHeatTest.cpp.
{
  TankController* tc = TankController::instance();
  SetChillOrHeat* test = new SetChillOrHeat(tc);
  tc->setNextState(test, true);
  EEPROM_TC::instance()->setHeat(true);
  assertEqual(9, test->getCurrentValue());
  test->setValue(1.0);
  assertFalse(EEPROM_TC::instance()->getHeat());
  // during the delay we showed the new value
  std::vector<String> lines = LiquidCrystal_TC::instance()->getLines();
  assertEqual("Use chiller     ", lines[1]);
  assertEqual("SetChillOrHeat", tc->stateName());
  tc->loop();  // transition to Wait
  assertEqual("Wait", tc->stateName());
  delay(3000);
  tc->loop();  // queue MainMenu to be next
  tc->loop();  // transition to MainMenu
  // now we should be back to the main menu
  assertEqual("MainMenu", tc->stateName());
}
References EEPROM_TC::instance(), TankController::instance(), LiquidCrystal_TC::instance(), TankController::loop(), EEPROM_TC::setHeat(), TankController::setNextState(), TankController::stateName(), and tc.
unittest() [3/3]
unittest (switchToHeat)
Definition at line 24 of file SetChillOrHeatTest.cpp.
                       {
  TankController* tc = TankController::instance();
  SetChillOrHeat* test = new SetChillOrHeat(tc);
  tc->setNextState(test, true);
  EEPROM_TC::instance()->setHeat(false);
  assertEqual(1, test->getCurrentValue());
  test->setValue(9.0);
  assertTrue(EEPROM_TC::instance()->getHeat());
  tc->loop();  // transition to Wait
  delay(3000);
  tc->loop();  // queue MainMenu to be next
  tc->loop();  // transition to MainMenu
  // now we should be back to the main menu
  assertEqual("MainMenu", tc->stateName());
}
References EEPROM_TC::instance(), TankController::instance(), TankController::loop(), EEPROM_TC::setHeat(), TankController::setNextState(), TankController::stateName(), and tc.