Tank Controller Lib: test/SetCalibrationClearTest.cpp File Reference
SetCalibrationClearTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "Keypad_TC.h"
#include "SetCalibrationClear.h"
#include "TankControllerLib.h"
Functions
void enterKey (char key)
unittest (test)
Variables
TankControllerLib * tc = TankControllerLib::instance()
LiquidCrystal_TC * lc = LiquidCrystal_TC::instance()
Keypad * keypad = Keypad_TC::instance()->_getPuppet()
Function Documentation
enterKey()
void enterKey (char key)
Definition at line 15 of file SetCalibrationClearTest.cpp.
{
   keypad->push_back(key);
   tc->loop();  // recognize and apply the key entry
 }
References key(), keypad, TankControllerLib::loop(), and tc.
Referenced by unittest().
unittest()
unittest (test)
Definition at line 20 of file SetCalibrationClearTest.cpp.
                {
   SetCalibrationClear* test = new SetCalibrationClear(tc);
   tc->setNextState(test, true);
   enterKey('A');
   std::vector<String> lines2 = lc->getLines();
   assertEqual("Cleared pH Calib", lines2[1]);
   assertEqual("Wait", tc->stateName());
   delay(3000);
   tc->loop();  // queue MainMenu to be next
   tc->loop();  // transition to MainMenu
   assertEqual("MainMenu", tc->stateName());
 }
References enterKey(), lc, TankControllerLib::loop(), TankControllerLib::setNextState(), TankControllerLib::stateName(), and tc.
Variable Documentation
keypad
Keypad* keypad = Keypad_TC::instance()->_getPuppet()
Definition at line 12 of file SetCalibrationClearTest.cpp.
Referenced by enterKey().
lc
LiquidCrystal_TC* lc = LiquidCrystal_TC::instance()
Definition at line 11 of file SetCalibrationClearTest.cpp.
Referenced by unittest().
tc
TankControllerLib* tc = TankControllerLib::instance()
Definition at line 10 of file SetCalibrationClearTest.cpp.
Referenced by enterKey(), and unittest().