Tank Controller Lib: test/SetPHSetPointTest.cpp File Reference
SetPHSetPointTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "Devices/PHControl.h"
#include "EEPROM_TC.h"
#include "SetPHSetPoint.h"
#include "TC_util.h"
#include "TankController.h"
Functions
unittest_setup ()
unittest (test)
Function Documentation
unittest()
unittest (test)
Definition at line 15 of file SetPHSetPointTest.cpp.
                {
   LiquidCrystal_TC* lcd = LiquidCrystal_TC::instance();
   EEPROM_TC::instance()->setPh(8.125);
   EEPROM_TC::instance()->setPhRampTimeEnd(0);
   EEPROM_TC::instance()->setPhRampTimeStart(0);
   TankController* tc = TankController::instance();  // instantiate after setting eeprom stuff
   assertEqual(8.125, EEPROM_TC::instance()->getPh());
   assertEqual(0, 8.125 - EEPROM_TC::instance()->getPh());
   assertEqual(8.125, PHControl::instance()->getTargetPh());
   assertEqual(0, EEPROM_TC::instance()->getPhRampTimeEnd());
   assertEqual(0, EEPROM_TC::instance()->getPhRampTimeStart());
   SetPHSetPoint* test = new SetPHSetPoint(tc);
   tc->setNextState(test, true);
   // get currently displayed lines
   std::vector<String> lines = lcd->getLines();
   assertEqual(16, lines.at(0).length());
   assertEqual(16, lines.at(1).length());
   assertEqual("Set pH Set Point", lines.at(0));
   assertEqual("  8.125->     0 ", lines.at(1));
   assertEqual(8.125, test->getCurrentValue());
   // setValue
   test->setValue(7.125);
   lines = lcd->getLines();
   assertEqual("Set ramp hours: ", lines.at(0));
   assertEqual("    0.0->     0 ", lines.at(1));
   assertEqual(0, test->getCurrentValue());
   test->setValue(4.125);
   // during the delay we showed the new value
   lines = lcd->getLines();
   assertEqual(7.125, PHControl::instance()->getTargetPh());
   assertEqual(7.125, EEPROM_TC::instance()->getPh());
   assertEqual(PHControl::instance()->phSetTypeTypes::RAMP_TYPE, EEPROM_TC::instance()->getPhSetType());
   assertEqual("New pH=7.125    ", lines[0]);
   assertEqual("New ramp=4.125  ", lines[1]);
   assertEqual("SetPHSetPoint", tc->stateName());
   tc->loop();  // transition to Wait
   assertEqual("Wait", tc->stateName());
   delay(3000);
   tc->loop();  // queue MainMenu to be next
   tc->loop();  // transition to MainMenu
   // now we should be back to the main menu
   assertEqual("MainMenu", tc->stateName());
 }
References EEPROM_TC::instance(), PHControl::instance(), TankController::instance(), LiquidCrystal_TC::instance(), lcd(), TankController::loop(), TankController::setNextState(), EEPROM_TC::setPh(), EEPROM_TC::setPhRampTimeEnd(), EEPROM_TC::setPhRampTimeStart(), TankController::stateName(), and tc.
unittest_setup()
unittest_setup ()
Definition at line 11 of file SetPHSetPointTest.cpp.
                  {
   GODMODE()->resetEEPROM();
 }