Tank Controller Lib: test/TemperatureControlTest.cpp File Reference
TemperatureControlTest.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <ci/ObservableDataStream.h>
#include "Devices/DateTime_TC.h"
#include "MainMenu.h"
#include "PHCalibrationMid.h"
#include "Serial_TC.h"
#include "TankControllerLib.h"
#include "TemperatureControl.h"
Functions
unittest_setup ()
unittest_teardown ()
unittest (BeforeIntervalAndWithinDelta)
unittest (BeforeIntervalAndOutsideDelta)
unittest (AfterIntervalAndWithinDelta)
unittest (AfterIntervalAndOutsideDelta)
unittest (disableChillerDuringCalibration)
unittest (WithinDelta)
unittest (OutsideDelta)
unittest (disableHeaterDuringCalibration)
Variables
const uint16_t PIN = 47
Function Documentation
unittest() [1/8]
unittest (AfterIntervalAndOutsideDelta)
Test that is turned on when needed
See also
unittest(disableChillerDuringCalibration)
Definition at line 68 of file TemperatureControlTest.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   DateTime_TC january(2021, 1, 15, 1, 48, 24);
   january.setAsCurrent();
   state->serialPort[0].dataOut = "";  // the history of data written
   // chiller is initially off and goes on when needed
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   delay(31000);
   chiller.updateControl(20.05);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   assertEqual("2021-01-15 01:48:55\r\nchiller turned on after 31000 ms\r\n", state->serialPort[0].dataOut);
   state->serialPort[0].dataOut = "";  // the history of data written
   delay(31000);
   chiller.updateControl(19.95);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   assertEqual("2021-01-15 01:49:26\r\nchiller turned off after 31000 ms\r\n", state->serialPort[0].dataOut);
 }
References PIN, DateTime_TC::setAsCurrent(), TemperatureControl::setTargetTemperature(), state, TURN_SOLENOID_OFF, TURN_SOLENOID_ON, and Chiller::updateControl().
unittest() [2/8]
unittest (AfterIntervalAndWithinDelta)
Definition at line 53 of file TemperatureControlTest.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   delay(31000);
   chiller.updateControl(20.04);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, TURN_SOLENOID_OFF, and Chiller::updateControl().
unittest() [3/8]
unittest (BeforeIntervalAndOutsideDelta)
Definition at line 42 of file TemperatureControlTest.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   chiller.updateControl(20.05);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, TURN_SOLENOID_OFF, and Chiller::updateControl().
unittest() [4/8]
unittest (BeforeIntervalAndWithinDelta)
Definition at line 31 of file TemperatureControlTest.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   chiller.updateControl(20.04);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, TURN_SOLENOID_OFF, and Chiller::updateControl().
unittest() [5/8]
unittest (disableChillerDuringCalibration)
Test that chiller is not turned on during calibration
See also
unittest(AfterIntervalAndOutsideDelta)
Definition at line 93 of file TemperatureControlTest.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   assertFalse(tc->isInCalibration());
   PHCalibrationMid* test = new PHCalibrationMid(tc);
   tc->setNextState(test, true);
   assertTrue(tc->isInCalibration());
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   // chiller is initially off and stays off during calibration
   // (test is same as above)
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   delay(31000);
   chiller.updateControl(20.05);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References TankControllerLib::instance(), TankControllerLib::isInCalibration(), PIN, TankControllerLib::setNextState(), TemperatureControl::setTargetTemperature(), state, tc, TURN_SOLENOID_OFF, and Chiller::updateControl().
unittest() [6/8]
unittest (disableHeaterDuringCalibration)
Test that heater is not turned on during calibration
See also
unittest(OutsideDelta)
Definition at line 147 of file TemperatureControlTest.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   assertFalse(tc->isInCalibration());
   PHCalibrationMid* test = new PHCalibrationMid(tc);
   tc->setNextState(test, true);
   assertTrue(tc->isInCalibration());
   GodmodeState* state = GODMODE();
   state->reset();
   Heater heater;
   // heater is initially off, and stays off due to calibration
   // (test is same as above)
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   heater.setTargetTemperature(20);
   heater.updateControl(19.95);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References TankControllerLib::instance(), TankControllerLib::isInCalibration(), PIN, TankControllerLib::setNextState(), TemperatureControl::setTargetTemperature(), state, tc, TURN_SOLENOID_OFF, and Heater::updateControl().
unittest() [7/8]
unittest (OutsideDelta)
Test that heater is turned on when needed
See also
unittest(disableHeaterDuringCalibration)
Definition at line 126 of file TemperatureControlTest.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Heater heater;
   state->serialPort[0].dataOut = "";  // the history of data written
   // heater is initially off, then turns on
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   heater.setTargetTemperature(20);
   heater.updateControl(19.95);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   assertEqual("2021-01-15 01:48:24\r\nheater turned on after 0 ms\r\n", state->serialPort[0].dataOut);
   state->serialPort[0].dataOut = "";  // the history of data written
   delay(300);
   heater.updateControl(20.05);
   assertEqual("2021-01-15 01:48:24\r\nheater turned off after 300 ms\r\n", state->serialPort[0].dataOut);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, TURN_SOLENOID_OFF, TURN_SOLENOID_ON, and Heater::updateControl().
unittest() [8/8]
unittest (WithinDelta)
Definition at line 112 of file TemperatureControlTest.cpp.
                       {
   GodmodeState* state = GODMODE();
   state->reset();
   Heater heater;
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   heater.setTargetTemperature(20);
   heater.updateControl(19.96);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, TURN_SOLENOID_OFF, and Heater::updateControl().
unittest_setup()
unittest_setup ()
Definition at line 20 of file TemperatureControlTest.cpp.
                  {
   TankControllerLib* tc = TankControllerLib::instance();
   tc->setNextState(new MainMenu(tc), true);
 }
References TankControllerLib::instance(), TankControllerLib::setNextState(), and tc.
unittest_teardown()
unittest_teardown ()
Definition at line 25 of file TemperatureControlTest.cpp.
                     {
   TankControllerLib* tc = TankControllerLib::instance();
   tc->setNextState(new MainMenu(tc), true);
 }
References TankControllerLib::instance(), TankControllerLib::setNextState(), and tc.
Variable Documentation
PIN
const uint16_t PIN = 47
These tests test the UpdateControl virtual function for the heater and chiller subclass and checks to see whether the heater or chiller should be in an on state or an off state. The following command lets you skip all the other tests and only run these tests bundle exec arduino_ci.rb –skip-examples-compilation –testfile-select=TemperatureControlTest.cpp
Definition at line 18 of file TemperatureControlTest.cpp.
Referenced by unittest().