Tank Controller Lib: test/TestTCLib.cpp File Reference
TestTCLib.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "DateTime_TC.h"
#include "PHControl.h"
#include "PHProbe.h"
#include "SD_TC.h"
#include "TC_util.h"
#include "TankControllerLib.h"
#include "TempProbe_TC.h"
#include "TemperatureControl.h"
Functions
unittest_setup ()
unittest_teardown ()
unittest (basicOperation)
unittest (storeDataToSD)
Variables
const int TEMP_PIN = 47
const int PH_PIN = 49
GodmodeState * state = GODMODE()
TankControllerLib * pTC = TankControllerLib::instance()
TempProbe_TC * tempProbe = TempProbe_TC::instance()
TemperatureControl * tempControl = TemperatureControl::instance()
PHProbe * pPHProbe = PHProbe::instance()
PHControl * pPHControl = PHControl::instance()
SD_TC * sd = SD_TC::instance()
Function Documentation
unittest() [1/2]
unittest (basicOperation)
Definition at line 51 of file TestTCLib.cpp.
{
   // verify startup state, including that solonoids are off
   assertEqual(20, (int)tempProbe->getRunningAverage());
   assertEqual(7.5, pPHProbe->getPh());
   pTC->loop();
   assertEqual(HIGH, state->digitalPin[TEMP_PIN]);
   assertEqual(HIGH, state->digitalPin[PH_PIN]);
   // change targets
   tempControl->setTargetTemperature(21.0);
   pPHControl->setTargetPh(7.4);
   // verify that solonoids are on
   pTC->loop();
   delay(10);
   pTC->loop();
   assertEqual(LOW, state->digitalPin[TEMP_PIN]);
   assertEqual(LOW, state->digitalPin[PH_PIN]);
   // reset targets
   tempControl->setTargetTemperature(19.0);
   pPHControl->setTargetPh(7.6);
   // verify that solonoids are off
   pTC->loop();
   delay(10);
   pTC->loop();
   assertEqual(HIGH, state->digitalPin[TEMP_PIN]);
   assertEqual(HIGH, state->digitalPin[PH_PIN]);
 }
References PHProbe::getPh(), TempProbe_TC::getRunningAverage(), TankControllerLib::loop(), PH_PIN, pPHControl, pPHProbe, pTC, PHControl::setTargetPh(), TemperatureControl::setTargetTemperature(), state, TEMP_PIN, tempControl, and tempProbe.
unittest() [2/2]
unittest (storeDataToSD)
Definition at line 82 of file TestTCLib.cpp.
{
   // set date/time (so we can confirm data)
   DateTime_TC dt(2021, 4, 27, 14, 24, 50);
   dt.setAsCurrent();
   for (int i = 0; i < 4; ++i) {
     delay(500);
     pTC->loop();
   }
   /*
   time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd
   04/27/2021 14:24:51,   0, 20.021, 20.000, 7.5000, 7.5000,    0,   0.0,   0.0,   0.0
   04/27/2021 14:24:52,   0, 20.021, 20.000, 7.5000, 7.5000,    0,   0.0,   0.0,   0.0
   */
   File file = sd->open("/data/2021/04/27.txt");
   char data[4096];
   file.read(data, file.size());
   data[file.size()] = '\0';
   COUT(data);
   String contents(data), line;
   int i = contents.indexOf('\n');
   line = contents.substring(0, i);
   assertEqual("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd", line.c_str());
   contents = contents.substring(i + 1);
   i = contents.indexOf('\n');
   line = contents.substring(0, i);
   String expected("04/27/2021 14:24:51,   0, 20.021, 20.000, 7.5000, 7.5000,    0, 100000.0,   0.0,   0.0");
   COUT("expectedSize = " << expected.length() << "; actualSize = " << line.length());
   assertEqual(expected, line);
   contents = contents.substring(i + 1);
   i = contents.indexOf('\n');
   line = contents.substring(0, i);
   expected = String("04/27/2021 14:24:52,   0, 20.021, 20.000, 7.5000, 7.5000,    0, 100000.0,   0.0,   0.0");
   COUT("expectedSize = " << expected.length() << "; actualSize = " << line.length());
   assertEqual(expected, line);
   COUT(data);
   file.close();
 }
References COUT, TankControllerLib::loop(), pTC, sd, and DateTime_TC::setAsCurrent().
unittest_setup()
unittest_setup ()
Definition at line 24 of file TestTCLib.cpp.
                  {
   // set temperature
   tempProbe->setTemperature(20.0);
   tempProbe->setCorrection(0.0);
   for (int i = 0; i < 100; ++i) {
     tempProbe->getRunningAverage();
   }
   // set target temperature
   tempControl->setTargetTemperature(20.0);
   // set pH
   state->serialPort[1].dataIn = "7.5\r";  // the queue of data waiting to be read
   pTC->serialEvent1();                    // fake interrupt
   // set target pH
   pPHControl->enablePID(false);
   pPHControl->setTargetPh(7.5);
   // clear SD card
   SD_TC::instance()->removeAll();
 }
References PHControl::enablePID(), TempProbe_TC::getRunningAverage(), SD_TC::instance(), pPHControl, pTC, TankControllerLib::serialEvent1(), TempProbe_TC::setCorrection(), PHControl::setTargetPh(), TemperatureControl::setTargetTemperature(), state, tempControl, and tempProbe.
unittest_teardown()
unittest_teardown ()
Definition at line 47 of file TestTCLib.cpp.
                     {
   SD_TC::instance()->removeAll();
 }
References SD_TC::instance().
Variable Documentation
PH_PIN
const int PH_PIN = 49
Definition at line 14 of file TestTCLib.cpp.
Referenced by unittest().
pPHControl
PHControl* pPHControl = PHControl::instance()
Definition at line 21 of file TestTCLib.cpp.
Referenced by unittest(), and unittest_setup().
pPHProbe
PHProbe* pPHProbe = PHProbe::instance()
Definition at line 20 of file TestTCLib.cpp.
Referenced by unittest().
pTC
TankControllerLib* pTC = TankControllerLib::instance()
Definition at line 17 of file TestTCLib.cpp.
Referenced by unittest(), and unittest_setup().
sd
SD_TC* sd = SD_TC::instance()
Definition at line 22 of file TestTCLib.cpp.
Referenced by unittest().
state
GodmodeState* state = GODMODE()
Definition at line 16 of file TestTCLib.cpp.
Referenced by unittest(), and unittest_setup().
TEMP_PIN
const int TEMP_PIN = 47
Definition at line 13 of file TestTCLib.cpp.
Referenced by unittest().
tempControl
TemperatureControl* tempControl = TemperatureControl::instance()
Definition at line 19 of file TestTCLib.cpp.
Referenced by MainMenu::idle(), unittest(), and unittest_setup().
tempProbe
TempProbe_TC* tempProbe = TempProbe_TC::instance()
Definition at line 18 of file TestTCLib.cpp.
Referenced by getTemperature(), MainMenu::idle(), setTemperature(), unittest(), and unittest_setup().