Tank Controller Lib: test/TestNumberCollectorState.cpp File Reference
TestNumberCollectorState.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "NumberCollectorState.h"
#include "TankControllerLib.h"
Functions
unittest (Edge_Case)
unittest (A_Digit_NoDecimal)
unittest (A_Digit_WithDecimal)
unittest (A_Digit_MultipleDecimals)
unittest (backSpace)
unittest (clear)
unittest (accept)
unittest (printing)
unittest (integer)
Function Documentation
unittest() [1/9]
unittest (A_Digit_MultipleDecimals)
Definition at line 36 of file TestNumberCollectorState.cpp.
{
   TestNumCollectorState testDecimal(TankControllerLib::instance());
   testDecimal.handleKey('1');
   testDecimal.handleKey('2');
   testDecimal.handleKey('*');
   testDecimal.handleKey('*');
   testDecimal.handleKey('3');
   testDecimal.handleKey('*');
   testDecimal.handleKey('4');
   assertEqual(12.34, testDecimal.getValue());
 }
References TankControllerLib::instance().
unittest() [2/9]
unittest (A_Digit_NoDecimal)
Definition at line 18 of file TestNumberCollectorState.cpp.
{
   TestNumCollectorState testNoDecimal(TankControllerLib::instance());
   testNoDecimal.handleKey('1');
   testNoDecimal.handleKey('2');
   testNoDecimal.handleKey('3');
   assertEqual(123, testNoDecimal.getValue());
 }
References TankControllerLib::instance().
unittest() [3/9]
unittest (A_Digit_WithDecimal)
Definition at line 26 of file TestNumberCollectorState.cpp.
{
   TestNumCollectorState testDecimal(TankControllerLib::instance());
   testDecimal.handleKey('1');
   testDecimal.handleKey('2');
   testDecimal.handleKey('*');
   testDecimal.handleKey('3');
   testDecimal.handleKey('4');
   assertEqual(12.34, testDecimal.getValue());
 }
References TankControllerLib::instance().
unittest() [4/9]
unittest (accept)
Definition at line 75 of file TestNumberCollectorState.cpp.
                  {
   TestNumCollectorState testDecimal(TankControllerLib::instance());
   testDecimal.handleKey('1');
   testDecimal.handleKey('2');
   testDecimal.handleKey('3');
   assertEqual(0, testDecimal.getStoredValue());
   testDecimal.handleKey('A');
   assertEqual(123, testDecimal.getStoredValue());
 }
References TankControllerLib::instance().
unittest() [5/9]
unittest (backSpace)
Definition at line 48 of file TestNumberCollectorState.cpp.
                     {
   TestNumCollectorState testNoDecimal(TankControllerLib::instance());
   testNoDecimal.handleKey('1');
   testNoDecimal.handleKey('2');
   testNoDecimal.handleKey('B');
   assertEqual(1, testNoDecimal.getValue());
   TestNumCollectorState testDecimal(TankControllerLib::instance());
   testDecimal.handleKey('1');
   testDecimal.handleKey('*');
   testDecimal.handleKey('B');
   testDecimal.handleKey('2');
   testDecimal.handleKey('*');
   testDecimal.handleKey('5');
   testDecimal.handleKey('3');
   testDecimal.handleKey('B');
   assertEqual(12.5, testDecimal.getValue());
 }
References TankControllerLib::instance().
unittest() [6/9]
unittest (clear)
Definition at line 67 of file TestNumberCollectorState.cpp.
                 {
   TestNumCollectorState testDecimal(TankControllerLib::instance());
   testDecimal.handleKey('1');
   testDecimal.handleKey('2');
   testDecimal.handleKey('C');
   assertEqual(0, testDecimal.getValue());
 }
References TankControllerLib::instance().
unittest() [7/9]
unittest (Edge_Case)
Definition at line 8 of file TestNumberCollectorState.cpp.
                     {
   TestNumCollectorState test(TankControllerLib::instance());
   test.handleKey('9');
   test.handleKey('0');
   test.handleKey('*');
   test.handleKey('0');
   test.handleKey('9');
   assertEqual(90.09, test.getValue());
 }
References TankControllerLib::instance().
unittest() [8/9]
unittest (integer)
Definition at line 122 of file TestNumberCollectorState.cpp.
                   {
   TestIntNumCollectorState testDecimal(TankControllerLib::instance());
   testDecimal.handleKey('1');
   testDecimal.handleKey('2');
   testDecimal.handleKey('*');
   testDecimal.handleKey('3');
   testDecimal.handleKey('4');
   assertEqual(1234, testDecimal.getValue());
 }
References TankControllerLib::instance().
unittest() [9/9]
unittest (printing)
Definition at line 85 of file TestNumberCollectorState.cpp.
                    {
   LiquidCrystal_TC* testLcd = LiquidCrystal_TC::instance();
   std::vector<String> lines;
   TestNumCollectorState test(TankControllerLib::instance());
   test.start();
   lines = testLcd->getLines();
   assertEqual("      0->     0 ", lines.at(1));
   test.setPriorValue(34.125);
   test.setPriorValuePrecision(1);
   test.handleKey('2');
   lines = testLcd->getLines();
   assertEqual("   34.1->     2 ", lines.at(1));
   test.handleKey('1');
   lines = testLcd->getLines();
   assertEqual("   34.1->    21 ", lines.at(1));
   test.handleKey('*');
   lines = testLcd->getLines();
   assertEqual("   34.1->    21.", lines.at(1));
   test.handleKey('3');
   lines = testLcd->getLines();
   assertEqual("   34.1->   21.3", lines.at(1));
   test.setPriorValuePrecision(2);
   test.handleKey('4');
   lines = testLcd->getLines();
   assertEqual("  34.12->  21.34", lines.at(1));
   test.setPriorValuePrecision(3);
   test.handleKey('1');
   lines = testLcd->getLines();
   assertEqual(" 34.125-> 21.341", lines.at(1));
 }
References LiquidCrystal_TC::instance(), and TankControllerLib::instance().