Tank Controller Lib: test/TestSetKI.cpp File Reference
TestSetKI.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "EEPROM_TC.h"
#include "Keypad_TC.h"
#include "SetKI.h"
#include "TankControllerLib.h"
Functions
unittest (test)
Function Documentation
unittest()
unittest (test)
Definition at line 10 of file TestSetKI.cpp.
                {
   TankControllerLib* tc = TankControllerLib::instance();
   SetKI* test = new SetKI(tc);
   tc->setNextState(test, true);
   // setValue
   test->setValue(12345.5);
   assertEqual(12345.5, EEPROM_TC::instance()->getKI());
   // during the delay we showed the new value
   std::vector<String> lines = LiquidCrystal_TC::instance()->getLines();
   assertEqual("New KI=12345.5  ", lines[1]);
   assertEqual("SetKI", tc->stateName());
   // Return to mainMenu
   Keypad_TC::instance()->_getPuppet()->push_back('D');
   tc->loop();
   assertEqual("MainMenu", tc->stateName());
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), EEPROM_TC::instance(), TankControllerLib::loop(), TankControllerLib::setNextState(), TankControllerLib::stateName(), and tc.