Tank Controller Lib: test/TestSD.cpp File Reference
TestSD.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "DateTime_TC.h"
#include "SD_TC.h"
#include "TC_util.h"
Functions
unittest_setup ()
unittest_teardown ()
unittest (singleton)
unittest (appendData)
unittest (appendToLog)
unittest (printRootDirectory)
Function Documentation
unittest() [1/4]
unittest (appendData)
Definition at line 23 of file TestSD.cpp.
                      {
   char data[80];
   DateTime_TC d1(2021, 4, 15), d2(2021, 4, 16);
   SD_TC* sd = SD_TC::instance();
   assertFalse(SD.exists("20210415.csv"));
   assertFalse(SD.exists("20210416.csv"));
   // write data for day 15
   d1.setAsCurrent();
   sd->appendData("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd", "line 1");
   sd->appendData("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd", "line 2");
   assertTrue(SD.exists("20210415.csv"));
   assertFalse(SD.exists("20210416.csv"));
   // write data for day 16
   d2.setAsCurrent();
   sd->appendData("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd", "line 3");
   assertTrue(SD.exists("20210415.csv"));
   assertTrue(SD.exists("20210416.csv"));
   // verify contents of 15.csv
   File file = SD.open("20210415.csv");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd\nline 1\nline 2\n", data);
   file.close();
   // verify contents of 16.csv
   file = SD.open("20210416.csv");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("time,tankid,temp,temp setpoint,pH,pH setpoint,onTime,Kp,Ki,Kd\nline 3\n", data);
   file.close();
 }
References SD_TC::appendData(), SD_TC::instance(), sd, and DateTime_TC::setAsCurrent().
unittest() [2/4]
unittest (appendToLog)
Definition at line 59 of file TestSD.cpp.
                       {
   char data[80];
   DateTime_TC d1(2021, 4, 15), d2(2021, 4, 16);
   SD_TC* sd = SD_TC::instance();
   assertFalse(SD.exists("20210415.log"));
   assertFalse(SD.exists("20210416.log"));
   // write data for day 15
   d1.setAsCurrent();
   sd->appendToLog("line 1");
   sd->appendToLog("line 2");
   assertTrue(SD.exists("20210415.log"));
   assertFalse(SD.exists("20210416.log"));
   // write data for day 16
   d2.setAsCurrent();
   sd->appendToLog("line 3");
   assertTrue(SD.exists("20210415.log"));
   assertTrue(SD.exists("20210416.log"));
   // verify contents of 15.log
   File file = SD.open("20210415.log");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("line 1\nline 2\n", data);
   file.close();
   // verify contents of 16.log
   file = SD.open("20210416.log");
   file.read(data, file.size());
   data[file.size()] = '\0';
   assertEqual("line 3\n", data);
   file.close();
 }
References SD_TC::appendToLog(), SD_TC::instance(), sd, and DateTime_TC::setAsCurrent().
unittest() [3/4]
unittest (printRootDirectory)
Definition at line 95 of file TestSD.cpp.
{
   GodmodeState* state = GODMODE();
   SD_TC* sd = SD_TC::instance();
   state->serialPort[0].dataOut = "";
   assertEqual("", state->serialPort[0].dataOut);
   SD.open("c", FILE_WRITE).close();
   SD.open("e", FILE_WRITE).close();
   SD.mkdir("d");
   SD.open("d/d1", FILE_WRITE).close();
   SD.open("d/d2", FILE_WRITE).close();
   state->serialPort[0].dataOut = "";
   sd->printRootDirectory();
   String output = String(state->serialPort[0].dataOut);
   int index;
   index = output.indexOf("           c (     0)\r\n");
   assertNotEqual(-1, index);
   index = output.indexOf("           d/\r\n");
   assertNotEqual(-1, index);
   index = output.indexOf("-           d1 (     0)\r\n");
   assertNotEqual(-1, index);
   index = output.indexOf("-           d2 (     0)\r\n");
   assertNotEqual(-1, index);
   index = output.indexOf("           e (     0)\r\n");
   assertNotEqual(-1, index);
 }
References SD_TC::instance(), SD_TC::printRootDirectory(), sd, and state.
unittest() [4/4]
unittest (singleton)
Definition at line 16 of file TestSD.cpp.
                     {
   SD_TC* thing1 = SD_TC::instance();
   SD_TC* thing2 = SD_TC::instance();
   assertTrue(thing1 != nullptr);
   assertEqual(thing1, thing2);
 }
References SD_TC::instance().
unittest_setup()
unittest_setup ()
Definition at line 8 of file TestSD.cpp.
                  {
   SD.removeAll();
 }
unittest_teardown()
unittest_teardown ()
Definition at line 12 of file TestSD.cpp.
                     {
   SD.removeAll();
 }