Tank Controller Lib: test/TestSetPHSetPoint.cpp File Reference
TestSetPHSetPoint.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "Devices/PHControl.h"
#include "EEPROM_TC.h"
#include "SetPHSetPoint.h"
#include "TankControllerLib.h"
Functions
unittest (test)
Function Documentation
unittest()
unittest (test)
Definition at line 10 of file TestSetPHSetPoint.cpp.
                {
   TankControllerLib* tc = TankControllerLib::instance();
   EEPROM_TC::instance()->setPH(8.100);
   SetPHSetPoint* test = new SetPHSetPoint(tc);
   assertEqual(8.100, PHControl::instance()->getTargetPh());
   tc->setNextState(test, true);
   // setValue
   test->setValue(7.1234);
   assertEqual(7.1234, PHControl::instance()->getTargetPh());
   assertEqual(7.1234, EEPROM_TC::instance()->getPH());
   // during the delay we showed the new value
   std::vector<String> lines = LiquidCrystal_TC::instance()->getLines();
   assertEqual("New pH=7.1234   ", lines[1]);
   assertEqual("SetPHSetPoint", tc->stateName());
   tc->loop();  // transition to Wait
   assertEqual("Wait", tc->stateName());
   delay(1000);
   tc->loop();  // queue MainMenu to be next
   tc->loop();  // transition to MainMenu
   // now we should be back to the main menu
   assertEqual("MainMenu", tc->stateName());
 }
References LiquidCrystal_TC::instance(), PHControl::instance(), TankControllerLib::instance(), EEPROM_TC::instance(), TankControllerLib::loop(), TankControllerLib::setNextState(), EEPROM_TC::setPH(), TankControllerLib::stateName(), and tc.