Tank Controller Lib: test/TestEnablePID.cpp File Reference
TestEnablePID.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "Devices/PHControl.h"
#include "EnablePID.h"
#include "TankControllerLib.h"
Functions
unittest (EnablePID)
Function Documentation
unittest()
unittest (EnablePID)
Definition at line 9 of file TestEnablePID.cpp.
                     {
   TankControllerLib* tc = TankControllerLib::instance();
   EnablePID* test = new EnablePID(tc);
   tc->setNextState(test, true);
   assertTrue(PHControl::instance()->getUsePID());
   test->setValue(2.0);
   assertTrue(PHControl::instance()->getUsePID());
   test->setValue(9.0);
   assertFalse(PHControl::instance()->getUsePID());
   test->setValue(2.0);
   assertFalse(PHControl::instance()->getUsePID());
   test->setValue(1.0);
   assertTrue(PHControl::instance()->getUsePID());
 }
References PHControl::instance(), TankControllerLib::instance(), TankControllerLib::setNextState(), and tc.