Tank Controller Lib: test/TestEEPROM2.cpp File Reference
TestEEPROM2.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "EEPROM_TC.h"
Functions
unittest_setup ()
unittest (version2)
unittest (singleton)
unittest (eeprom_Read_and_Write_Double)
unittest (PH)
unittest (Temp)
unittest (writing_PH_should_not_corrupt_Temp)
unittest (TankID)
unittest (CorrectedTemp)
unittest (KP)
unittest (KI)
unittest (KD)
unittest (Mac)
unittest (Heat)
unittest (Amplitude)
unittest (Frequency)
unittest (Granularity)
unittest (MaxDataAge)
unittest (PHSeriesSize)
unittest (PHSeriesPointer)
unittest (TempSeriesSize)
unittest (TempSeriesPointer)
unittest (PHInterval)
unittest (PHDelay)
unittest (TempInterval)
unittest (TempDelay)
unittest (GoogleSheetIntervalMinutes)
Function Documentation
unittest() [1/26]
unittest (Amplitude)
Definition at line 113 of file TestEEPROM2.cpp.
                     {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getAmplitude());
   singleton->setAmplitude(12);
   assertEqual(12, singleton->getAmplitude());
 }
References EEPROM_TC::getAmplitude(), EEPROM_TC::instance(), and EEPROM_TC::setAmplitude().
unittest() [2/26]
unittest (CorrectedTemp)
Definition at line 69 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getCorrectedTemp());
   singleton->setCorrectedTemp(6);
   assertEqual(6, singleton->getCorrectedTemp());
 }
References EEPROM_TC::getCorrectedTemp(), EEPROM_TC::instance(), and EEPROM_TC::setCorrectedTemp().
unittest() [3/26]
unittest (eeprom_Read_and_Write_Double)
Definition at line 27 of file TestEEPROM2.cpp.
{
   EEPROM_TC* test = EEPROM_TC::instance(2);
   const int TEST_ADDRESS = 4000;  // beyond the end of our use
   // integer
   test->eepromWriteFloat(TEST_ADDRESS, 10);
   assertEqual(10, test->eepromReadFloat(TEST_ADDRESS));
   // float
   test->eepromWriteFloat(TEST_ADDRESS, 12.25);
   assertEqual(12.25, test->eepromReadFloat(TEST_ADDRESS));
 }
References EEPROM_TC::instance().
unittest() [4/26]
unittest (Frequency)
Definition at line 120 of file TestEEPROM2.cpp.
                     {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getFrequency());
   singleton->setFrequency(13);
   assertEqual(13, singleton->getFrequency());
 }
References EEPROM_TC::getFrequency(), EEPROM_TC::instance(), and EEPROM_TC::setFrequency().
unittest() [5/26]
unittest (GoogleSheetIntervalMinutes)
Definition at line 197 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertEqual(-1, singleton->getGoogleSheetInterval());
   singleton->setGoogleSheetInterval(20);
   assertEqual(20, singleton->getGoogleSheetInterval());
 }
References EEPROM_TC::getGoogleSheetInterval(), EEPROM_TC::instance(), and EEPROM_TC::setGoogleSheetInterval().
unittest() [6/26]
unittest (Granularity)
Definition at line 127 of file TestEEPROM2.cpp.
                       {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getGranularity());
   singleton->setGranularity(14);
   assertEqual(14, singleton->getGranularity());
 }
References EEPROM_TC::getGranularity(), EEPROM_TC::instance(), and EEPROM_TC::setGranularity().
unittest() [7/26]
unittest (Heat)
Definition at line 104 of file TestEEPROM2.cpp.
                {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertTrue(singleton->getHeat());  // (bool)(-1)
   singleton->setHeat(false);
   assertFalse(singleton->getHeat());
   singleton->setHeat(true);
   assertTrue(singleton->getHeat());
 }
References EEPROM_TC::getHeat(), EEPROM_TC::instance(), and EEPROM_TC::setHeat().
unittest() [8/26]
unittest (KD)
Definition at line 90 of file TestEEPROM2.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getKD());
   singleton->setKD(9);
   assertEqual(9, singleton->getKD());
 }
References EEPROM_TC::getKD(), EEPROM_TC::instance(), and EEPROM_TC::setKD().
unittest() [9/26]
unittest (KI)
Definition at line 83 of file TestEEPROM2.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getKI());
   singleton->setKI(8);
   assertEqual(8, singleton->getKI());
 }
References EEPROM_TC::getKI(), EEPROM_TC::instance(), and EEPROM_TC::setKI().
unittest() [10/26]
unittest (KP)
Definition at line 76 of file TestEEPROM2.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getKP());
   singleton->setKP(7);
   assertEqual(7, singleton->getKP());
 }
References EEPROM_TC::getKP(), EEPROM_TC::instance(), and EEPROM_TC::setKP().
unittest() [11/26]
unittest (Mac)
Definition at line 97 of file TestEEPROM2.cpp.
               {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getMac());
   singleton->setMac(10);
   assertEqual(10, singleton->getMac());
 }
References EEPROM_TC::getMac(), EEPROM_TC::instance(), and EEPROM_TC::setMac().
unittest() [12/26]
unittest (MaxDataAge)
Definition at line 134 of file TestEEPROM2.cpp.
                      {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getMaxDataAge());
   singleton->setMaxDataAge(15);
   assertEqual(15, singleton->getMaxDataAge());
 }
References EEPROM_TC::getMaxDataAge(), EEPROM_TC::instance(), and EEPROM_TC::setMaxDataAge().
unittest() [13/26]
unittest (PH)
Definition at line 40 of file TestEEPROM2.cpp.
              {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getPH());
   singleton->setPH(3.125);
   assertEqual(3.125, singleton->getPH());
 }
References EEPROM_TC::getPH(), EEPROM_TC::instance(), and EEPROM_TC::setPH().
unittest() [14/26]
unittest (PHDelay)
Definition at line 176 of file TestEEPROM2.cpp.
                   {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getPHDelay());
   singleton->setPHDelay(21);
   assertEqual(21, singleton->getPHDelay());
 }
References EEPROM_TC::getPHDelay(), EEPROM_TC::instance(), and EEPROM_TC::setPHDelay().
unittest() [15/26]
unittest (PHInterval)
Definition at line 169 of file TestEEPROM2.cpp.
                      {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getPHInterval());
   singleton->setPHInterval(20);
   assertEqual(20, singleton->getPHInterval());
 }
References EEPROM_TC::getPHInterval(), EEPROM_TC::instance(), and EEPROM_TC::setPHInterval().
unittest() [16/26]
unittest (PHSeriesPointer)
Definition at line 148 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getPHSeriesPointer());
   singleton->setPHSeriesPointer(17);
   assertEqual(17, singleton->getPHSeriesPointer());
 }
References EEPROM_TC::getPHSeriesPointer(), EEPROM_TC::instance(), and EEPROM_TC::setPHSeriesPointer().
unittest() [17/26]
unittest (PHSeriesSize)
Definition at line 141 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getPHSeriesSize());
   singleton->setPHSeriesSize(16);
   assertEqual(16, singleton->getPHSeriesSize());
 }
References EEPROM_TC::getPHSeriesSize(), EEPROM_TC::instance(), and EEPROM_TC::setPHSeriesSize().
unittest() [18/26]
unittest (singleton)
Definition at line 16 of file TestEEPROM2.cpp.
                     {
   // Test singleton
   EEPROM_TC* singleton1 = nullptr;
   singleton1 = EEPROM_TC::instance(2);
   assertNotNull(singleton1);
   EEPROM_TC* singleton2 = nullptr;
   singleton2 = EEPROM_TC::instance(2);
   assertNotNull(singleton2);
   assertEqual(singleton1, singleton2);
 }
References EEPROM_TC::instance().
unittest() [19/26]
unittest (TankID)
Definition at line 62 of file TestEEPROM2.cpp.
                  {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   // Because the temperature (above) overwrites this field we can't check its default
   singleton->setTankID(5);
   assertEqual(5, singleton->getTankID());
 }
References EEPROM_TC::getTankID(), EEPROM_TC::instance(), and EEPROM_TC::setTankID().
unittest() [20/26]
unittest (Temp)
Definition at line 47 of file TestEEPROM2.cpp.
                {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getTemp());
   singleton->setTemp(4);
   assertEqual(4, singleton->getTemp());
 }
References EEPROM_TC::getTemp(), EEPROM_TC::instance(), and EEPROM_TC::setTemp().
unittest() [21/26]
unittest (TempDelay)
Definition at line 190 of file TestEEPROM2.cpp.
                     {
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getTempDelay());
   singleton->setTempDelay(23);
   assertEqual(23, singleton->getTempDelay());
 }
References EEPROM_TC::getTempDelay(), EEPROM_TC::instance(), and EEPROM_TC::setTempDelay().
unittest() [22/26]
unittest (TempInterval)
Definition at line 183 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getTempInterval());
   singleton->setTempInterval(22);
   assertEqual(22, singleton->getTempInterval());
 }
References EEPROM_TC::getTempInterval(), EEPROM_TC::instance(), and EEPROM_TC::setTempInterval().
unittest() [23/26]
unittest (TempSeriesPointer)
Definition at line 162 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getTempSeriesPointer());
   singleton->setTempSeriesPointer(19);
   assertEqual(19, singleton->getTempSeriesPointer());
 }
References EEPROM_TC::getTempSeriesPointer(), EEPROM_TC::instance(), and EEPROM_TC::setTempSeriesPointer().
unittest() [24/26]
unittest (TempSeriesSize)
Definition at line 155 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   assertNAN(singleton->getTempSeriesSize());
   singleton->setTempSeriesSize(18);
   assertEqual(18, singleton->getTempSeriesSize());
 }
References EEPROM_TC::getTempSeriesSize(), EEPROM_TC::instance(), and EEPROM_TC::setTempSeriesSize().
unittest() [25/26]
unittest (version2)
Definition at line 10 of file TestEEPROM2.cpp.
                    {
   // Test singleton
   EEPROM_TC* eeprom = EEPROM_TC::instance(2);
   assertEqual(2, eeprom->getVersion());
 }
References eeprom(), and EEPROM_TC::instance().
unittest() [26/26]
unittest (writing_PH_should_not_corrupt_Temp)
Definition at line 54 of file TestEEPROM2.cpp.
{
   EEPROM_TC* singleton = EEPROM_TC::instance(2);
   singleton->setTemp(4);
   assertEqual(4, singleton->getTemp());
   singleton->setPH(3.05);
   assertEqual(4, singleton->getTemp());  // Not a bug with 32-bit floats
 }
References EEPROM_TC::getTemp(), EEPROM_TC::instance(), EEPROM_TC::setPH(), and EEPROM_TC::setTemp().
unittest_setup()
unittest_setup ()
Definition at line 6 of file TestEEPROM2.cpp.
                  {
   GODMODE()->resetEEPROM();
 }