Tank Controller Lib: test/TestPID.cpp File Reference
TestPID.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <PID_v1.h>
#include "Devices/DateTime_TC.h"
#include "Devices/PID_TC.h"
#include "Devices/Serial_TC.h"
#include "PHCalibrationHigh.h"
#include "TC_util.h"
#include "TankControllerLib.h"
Functions
unittest_setup ()
unittest (singleton)
unittest (constructor)
unittest (logToSerial)
unittest (compute)
unittest (computeDuringCalibration)
unittest (setTunings)
unittest (setKp)
unittest (setKi)
unittest (setKd)
Function Documentation
unittest() [1/9]
unittest (compute)
Definition at line 40 of file TestPID.cpp.
                   {
   PID_TC *pPID = PID_TC::instance();
   pPID->setTunings(2, 5, 1);
   // initialize the variables we're linked to
   double input = 50;
   double setpoint = 100;
   double output;
   output = pPID->computeOutput(setpoint, input);
   assertEqual(0.0, output);
   // turn the PID on
   for (int i = 0; i < 1000; i++) {
     delay(200);
     output = pPID->computeOutput(setpoint, input);
     double delta = output - input;
     input = input - (delta / 25.6);
   }
   assertEqual(setpoint, round(input));
 }
References PID_TC::computeOutput(), PID_TC::instance(), and PID_TC::setTunings().
unittest() [2/9]
unittest (computeDuringCalibration)
Definition at line 60 of file TestPID.cpp.
{
   // set UI to one of the calibration states
   TankControllerLib *tc = TankControllerLib::instance();
   tc->setNextState(new PHCalibrationHigh(tc), true);
   PID_TC *pPID = PID_TC::instance();
   pPID->setTunings(2, 5, 1);
   // initialize the variables we're linked to
   double input = 50;
   double setpoint = 100;
   double output;
   output = pPID->computeOutput(setpoint, input);
   assertEqual(0.0, output);
   // turn the PID on
   for (int i = 0; i < 1000; i++) {
     delay(200);
     output = pPID->computeOutput(setpoint, input);
     double delta = output - input;
     input = input - (delta / 25.6);
   }
   assertEqual(0.0, output);
 }
References PID_TC::computeOutput(), PID_TC::instance(), TankControllerLib::instance(), TankControllerLib::setNextState(), PID_TC::setTunings(), and tc.
unittest() [3/9]
unittest (constructor)
Definition at line 22 of file TestPID.cpp.
                       {
   PID_TC *singleton = PID_TC::instance();
   assertEqual(100000.0, singleton->getKp());
   assertEqual(0.0, singleton->getKi());
   assertEqual(0.0, singleton->getKd());
   assertEqual(AUTOMATIC, singleton->getMode());
 }
References PID_TC::getKd(), PID_TC::getKi(), PID_TC::getKp(), PID_TC::getMode(), and PID_TC::instance().
unittest() [4/9]
unittest (logToSerial)
Definition at line 30 of file TestPID.cpp.
                       {
   GodmodeState *state = GODMODE();
   DateTime_TC::now();                 // this puts stuff on the serial port that we want to ignore
   serial("foo");                      // this should get the directory creation error (if any)
   state->serialPort[0].dataOut = "";  // so here we ignore it!
   PID_TC *singleton = PID_TC::instance();
   singleton->logToSerial();
   assertEqual("Kp: 100000.0 Ki:    0.0 Kd:    0.0\r\nPID output (s): 0.0\r\n", state->serialPort[0].dataOut);
 }
References PID_TC::instance(), PID_TC::logToSerial(), DateTime_TC::now(), serial(), and state.
unittest() [5/9]
unittest (setKd)
Definition at line 114 of file TestPID.cpp.
                 {
   PID_TC *singleton = PID_TC::instance();
   singleton->setTunings(2, 5, 10);
   singleton->setKd(1);
   assertEqual(1, singleton->getKd());
   assertEqual(2, singleton->getKp());
   assertEqual(5, singleton->getKi());
 }
References PID_TC::getKd(), PID_TC::getKi(), PID_TC::getKp(), PID_TC::instance(), PID_TC::setKd(), and PID_TC::setTunings().
unittest() [6/9]
unittest (setKi)
Definition at line 105 of file TestPID.cpp.
                 {
   PID_TC *singleton = PID_TC::instance();
   singleton->setTunings(2, 50, 10);
   singleton->setKi(5);
   assertEqual(5, singleton->getKi());
   assertEqual(2, singleton->getKp());
   assertEqual(10, singleton->getKd());
 }
References PID_TC::getKd(), PID_TC::getKi(), PID_TC::getKp(), PID_TC::instance(), PID_TC::setKi(), and PID_TC::setTunings().
unittest() [7/9]
unittest (setKp)
Definition at line 96 of file TestPID.cpp.
                 {
   PID_TC *singleton = PID_TC::instance();
   singleton->setTunings(20, 50, 10);
   singleton->setKp(2);
   assertEqual(2, singleton->getKp());
   assertEqual(50, singleton->getKi());
   assertEqual(10, singleton->getKd());
 }
References PID_TC::getKd(), PID_TC::getKi(), PID_TC::getKp(), PID_TC::instance(), PID_TC::setKp(), and PID_TC::setTunings().
unittest() [8/9]
unittest (setTunings)
Definition at line 84 of file TestPID.cpp.
                      {
   PID_TC *singleton = PID_TC::instance();
   singleton->setTunings(2, 5, 1);
   assertEqual(2, singleton->getKp());
   assertEqual(5, singleton->getKi());
   assertEqual(1, singleton->getKd());
   singleton->setTunings(20, 50, 10);
   assertEqual(20, singleton->getKp());
   assertEqual(50, singleton->getKi());
   assertEqual(10, singleton->getKd());
 }
References PID_TC::getKd(), PID_TC::getKi(), PID_TC::getKp(), PID_TC::instance(), and PID_TC::setTunings().
unittest() [9/9]
unittest (singleton)
Definition at line 16 of file TestPID.cpp.
                     {
   PID_TC *singleton1 = PID_TC::instance();
   PID_TC *singleton2 = PID_TC::instance();
   assertEqual(singleton1, singleton2);
 }
References PID_TC::instance().
unittest_setup()
unittest_setup ()
Definition at line 12 of file TestPID.cpp.
                  {
   PID_TC::reset();
 }
References PID_TC::reset().