Tank Controller Lib: test/TestSetTankID.cpp File Reference
TestSetTankID.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/LiquidCrystal_TC.h"
#include "EEPROM_TC.h"
#include "SetTankID.h"
#include "TankControllerLib.h"
Functions
unittest (test)
Function Documentation
unittest()
unittest (test)
Definition at line 9 of file TestSetTankID.cpp.
                {
   TankControllerLib* tc = TankControllerLib::instance();
   SetTankID* test = new SetTankID(tc);
   tc->setNextState(test, true);
   // setValue
   test->setValue(12);
   assertEqual(12, EEPROM_TC::instance()->getTankID());
   // during the delay we showed the new value
   std::vector<String> lines = LiquidCrystal_TC::instance()->getLines();
   assertEqual("Tank ID = 12    ", lines[1]);
   assertEqual("SetTankID", tc->stateName());
   tc->loop();  // transition to Wait
   assertEqual("Wait", tc->stateName());
   delay(1000);
   tc->loop();  // queue MainMenu to be next
   tc->loop();  // transition to MainMenu
   // now we should be back to the main menu
   assertEqual("MainMenu", tc->stateName());
 }
References LiquidCrystal_TC::instance(), TankControllerLib::instance(), EEPROM_TC::instance(), TankControllerLib::loop(), TankControllerLib::setNextState(), TankControllerLib::stateName(), and tc.