Tank Controller Lib: test/TestTemperatureControl.cpp File Reference
TestTemperatureControl.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <ci/ObservableDataStream.h>
#include "MainMenu.h"
#include "PHCalibrationMid.h"
#include "TankControllerLib.h"
#include "TemperatureControl.h"
Functions
unittest_setup ()
unittest_teardown ()
unittest (BeforeIntervalAndWithinDelta)
unittest (BeforeIntervalAndOutsideDelta)
unittest (AfterIntervalAndWithinDelta)
unittest (AfterIntervalAndOutsideDelta)
unittest (disableChillerDuringCalibration)
unittest (WithinDelta)
unittest (OutsideDelta)
unittest (disableHeaterDuringCalibration)
Variables
const int PIN = 47
Function Documentation
unittest() [1/8]
unittest (AfterIntervalAndOutsideDelta)
Test that is turned on when needed
See also
unittest(disableChillerDuringCalibration)
Definition at line 66 of file TestTemperatureControl.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   // chiller is initially off and goes on when needed
   assertEqual(HIGH, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   delay(31000);
   chiller.updateControl(20.05);
   assertEqual(LOW, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, and Chiller::updateControl().
unittest() [2/8]
unittest (AfterIntervalAndWithinDelta)
Definition at line 51 of file TestTemperatureControl.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   assertEqual(HIGH, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   delay(31000);
   chiller.updateControl(20.04);
   assertEqual(HIGH, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, and Chiller::updateControl().
unittest() [3/8]
unittest (BeforeIntervalAndOutsideDelta)
Definition at line 40 of file TestTemperatureControl.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   assertEqual(HIGH, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   chiller.updateControl(20.05);
   assertEqual(HIGH, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, and Chiller::updateControl().
unittest() [4/8]
unittest (BeforeIntervalAndWithinDelta)
Definition at line 29 of file TestTemperatureControl.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   assertEqual(HIGH, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   chiller.updateControl(20.04);
   assertEqual(HIGH, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, and Chiller::updateControl().
unittest() [5/8]
unittest (disableChillerDuringCalibration)
Test that chiller is not turned on during calibration
See also
unittest(AfterIntervalAndOutsideDelta)
Definition at line 82 of file TestTemperatureControl.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   assertFalse(tc->isInCalibration());
   PHCalibrationMid* test = new PHCalibrationMid(tc);
   tc->setNextState(test, true);
   assertTrue(tc->isInCalibration());
   GodmodeState* state = GODMODE();
   state->reset();
   Chiller chiller;
   // chiller is initially off and stays off during calibration
   // (test is same as above)
   assertEqual(HIGH, state->digitalPin[PIN]);
   chiller.setTargetTemperature(20);
   delay(31000);
   chiller.updateControl(20.05);
   assertEqual(HIGH, state->digitalPin[PIN]);
 }
References TankControllerLib::instance(), TankControllerLib::isInCalibration(), PIN, TankControllerLib::setNextState(), TemperatureControl::setTargetTemperature(), state, tc, and Chiller::updateControl().
unittest() [6/8]
unittest (disableHeaterDuringCalibration)
Test that heater is not turned on during calibration
See also
unittest(OutsideDelta)
Definition at line 130 of file TestTemperatureControl.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   assertFalse(tc->isInCalibration());
   PHCalibrationMid* test = new PHCalibrationMid(tc);
   tc->setNextState(test, true);
   assertTrue(tc->isInCalibration());
   GodmodeState* state = GODMODE();
   state->reset();
   Heater heater;
   // heater is initially off, and stays off due to calibration
   // (test is same as above)
   assertEqual(HIGH, state->digitalPin[PIN]);
   heater.setTargetTemperature(20);
   heater.updateControl(19.95);
   assertEqual(HIGH, state->digitalPin[PIN]);
 }
References TankControllerLib::instance(), TankControllerLib::isInCalibration(), PIN, TankControllerLib::setNextState(), TemperatureControl::setTargetTemperature(), state, tc, and Heater::updateControl().
unittest() [7/8]
unittest (OutsideDelta)
Test that heater is turned on when needed
See also
unittest(disableHeaterDuringCalibration)
Definition at line 115 of file TestTemperatureControl.cpp.
{
   GodmodeState* state = GODMODE();
   state->reset();
   Heater heater;
   // heater is initially off, then turns on
   assertEqual(HIGH, state->digitalPin[PIN]);
   heater.setTargetTemperature(20);
   heater.updateControl(19.95);
   assertEqual(LOW, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, and Heater::updateControl().
unittest() [8/8]
unittest (WithinDelta)
Definition at line 101 of file TestTemperatureControl.cpp.
                       {
   GodmodeState* state = GODMODE();
   state->reset();
   Heater heater;
   assertEqual(HIGH, state->digitalPin[PIN]);
   heater.setTargetTemperature(20);
   heater.updateControl(19.96);
   assertEqual(HIGH, state->digitalPin[PIN]);
 }
References PIN, TemperatureControl::setTargetTemperature(), state, and Heater::updateControl().
unittest_setup()
unittest_setup ()
Definition at line 18 of file TestTemperatureControl.cpp.
                  {
   TankControllerLib* tc = TankControllerLib::instance();
   tc->setNextState(new MainMenu(tc), true);
 }
References TankControllerLib::instance(), TankControllerLib::setNextState(), and tc.
unittest_teardown()
unittest_teardown ()
Definition at line 23 of file TestTemperatureControl.cpp.
                     {
   TankControllerLib* tc = TankControllerLib::instance();
   tc->setNextState(new MainMenu(tc), true);
 }
References TankControllerLib::instance(), TankControllerLib::setNextState(), and tc.
Variable Documentation
PIN
const int PIN = 47
These tests test the UpdateControl virtual function for the heater and chiller subclass and checks to see whether the heater or chiller should be in an on state or an off state. The following command lets you skip all the other tests and only run these tests bundle exec arduino_ci.rb –skip-examples-compilation –testfile-select=TemperatureControlTest.cpp
Definition at line 16 of file TestTemperatureControl.cpp.
Referenced by unittest().