Tank Controller Lib: test/TestPHControl.cpp File Reference
TestPHControl.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include <ci/ObservableDataStream.h>
#include "Devices/DateTime_TC.h"
#include "MainMenu.h"
#include "PHCalibrationMid.h"
#include "PHControl.h"
#include "TankControllerLib.h"
Functions
void reset ()
unittest_setup ()
unittest_teardown ()
unittest (beforeTenSeconds)
unittest (afterTenSecondsButPhStillHigher)
unittest (afterTenSecondsAndPhIsLower)
unittest (beforeTenSecondsButPhIsLower)
unittest (PhEvenWithTarget)
unittest (disableDuringCalibration)
Variables
const int PIN = 49
Function Documentation
reset()
void reset ()
cycle the control through to a point of being off
Definition at line 16 of file TestPHControl.cpp.
              {
   PHControl* singleton = PHControl::instance();
   singleton->enablePID(false);
   singleton->setTargetPh(7.00);
   singleton->updateControl(7.00);
   delay(10000);
   singleton->updateControl(7.00);
   TankControllerLib* tc = TankControllerLib::instance();
   tc->setNextState(new MainMenu(tc), true);
 }
References PHControl::enablePID(), PHControl::instance(), TankControllerLib::instance(), TankControllerLib::setNextState(), PHControl::setTargetPh(), tc, and PHControl::updateControl().
Referenced by unittest_setup(), and unittest_teardown().
unittest() [1/6]
unittest (afterTenSecondsAndPhIsLower)
Definition at line 67 of file TestPHControl.cpp.
{
   GodmodeState* state = GODMODE();
   PHControl* controlSolenoid = PHControl::instance();
   state->serialPort[0].dataOut = "";  // the history of data written
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   controlSolenoid->setTargetPh(7.00);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   assertEqual("2021-01-15 01:49:24\r\nCO2 bubbler turned on after 20014 ms\r\n", state->serialPort[0].dataOut);
   state->serialPort[0].dataOut = "";  // the history of data written
   delay(9500);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   delay(1000);
   controlSolenoid->updateControl(6.75);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   assertEqual("2021-01-15 01:49:34\r\nCO2 bubbler turned off after 10500 ms\r\n", state->serialPort[0].dataOut);
 }
References PHControl::instance(), PIN, PHControl::setTargetPh(), state, TURN_SOLENOID_OFF, TURN_SOLENOID_ON, and PHControl::updateControl().
unittest() [2/6]
unittest (afterTenSecondsButPhStillHigher)
Definition at line 52 of file TestPHControl.cpp.
{
   GodmodeState* state = GODMODE();
   PHControl* controlSolenoid = PHControl::instance();
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   controlSolenoid->setTargetPh(7.00);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   delay(9500);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   delay(1000);
   controlSolenoid->updateControl(7.25);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
 }
References PHControl::instance(), PIN, PHControl::setTargetPh(), state, TURN_SOLENOID_OFF, TURN_SOLENOID_ON, and PHControl::updateControl().
unittest() [3/6]
unittest (beforeTenSeconds)
Definition at line 36 of file TestPHControl.cpp.
{
   GodmodeState* state = GODMODE();
   PHControl* controlSolenoid = PHControl::instance();
   DateTime_TC january(2021, 1, 15, 1, 48, 24);
   january.setAsCurrent();
   state->serialPort[0].dataOut = "";  // the history of data written
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   controlSolenoid->setTargetPh(7.00);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   assertEqual("2021-01-15 01:48:24\r\nCO2 bubbler turned on after 10155 ms\r\n", state->serialPort[0].dataOut);
   delay(9500);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
 }
References PHControl::instance(), PIN, DateTime_TC::setAsCurrent(), PHControl::setTargetPh(), state, TURN_SOLENOID_OFF, TURN_SOLENOID_ON, and PHControl::updateControl().
unittest() [4/6]
unittest (beforeTenSecondsButPhIsLower)
Test that CO2 b is turned on when needed
See also
unittest(disableDuringCalibration)
Definition at line 90 of file TestPHControl.cpp.
{
   GodmodeState* state = GODMODE();
   PHControl* controlSolenoid = PHControl::instance();
   // device is initially off but turns on when needed
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   controlSolenoid->setTargetPh(7.00);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_ON, state->digitalPin[PIN]);
   delay(7500);
   controlSolenoid->updateControl(6.75);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References PHControl::instance(), PIN, PHControl::setTargetPh(), state, TURN_SOLENOID_OFF, TURN_SOLENOID_ON, and PHControl::updateControl().
unittest() [5/6]
unittest (disableDuringCalibration)
Test that CO2 bubbler is turned on when needed
See also
unittest(beforeTenSecondsButPhIsLower)
Definition at line 116 of file TestPHControl.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   assertFalse(tc->isInCalibration());
   PHCalibrationMid* test = new PHCalibrationMid(tc);
   tc->setNextState(test, true);
   assertTrue(tc->isInCalibration());
   GodmodeState* state = GODMODE();
   PHControl* controlSolenoid = PHControl::instance();
   // device is initially off and stays off due to calibration
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   controlSolenoid->setTargetPh(7.00);
   controlSolenoid->updateControl(8.00);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References PHControl::instance(), TankControllerLib::instance(), TankControllerLib::isInCalibration(), PIN, TankControllerLib::setNextState(), PHControl::setTargetPh(), state, tc, TURN_SOLENOID_OFF, and PHControl::updateControl().
unittest() [6/6]
unittest (PhEvenWithTarget)
Definition at line 103 of file TestPHControl.cpp.
{
   GodmodeState* state = GODMODE();
   PHControl* controlSolenoid = PHControl::instance();
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
   controlSolenoid->setTargetPh(7.00);
   controlSolenoid->updateControl(7.00);
   assertEqual(TURN_SOLENOID_OFF, state->digitalPin[PIN]);
 }
References PHControl::instance(), PIN, PHControl::setTargetPh(), state, TURN_SOLENOID_OFF, and PHControl::updateControl().
unittest_setup()
unittest_setup ()
Definition at line 27 of file TestPHControl.cpp.
                  {
   reset();
 }
References reset().
unittest_teardown()
unittest_teardown ()
Definition at line 31 of file TestPHControl.cpp.
                     {
   reset();
 }
References reset().
Variable Documentation
PIN
const int PIN = 49
Definition at line 11 of file TestPHControl.cpp.
Referenced by unittest().